import { Input, Select, T, today, useLabels } from './shared';

export type PurchaseInvestor = { user_id: string; name: string; email: string; default_profit_share_bps: number; default_loss_share_bps: number };
export type FundingDraft = { mode: 'store' | 'investor'; user_id: string; agreed_iqd: number | ''; received_iqd: number | ''; received_day: string; reference: string; profit_share_bps: number; loss_share_bps: number; save_default: boolean; incoming_indexes?: number[] };
export const newFunding = (): FundingDraft => ({ mode: 'store', user_id: '', agreed_iqd: '', received_iqd: '', received_day: today(), reference: '', profit_share_bps: 3500, loss_share_bps: 0, save_default: false });
export function fundingValid(f: FundingDraft) { return f.mode === 'store' || !!(f.user_id && Number(f.agreed_iqd) > 0 && Number.isSafeInteger(f.agreed_iqd) && (f.received_iqd === '' || (Number.isSafeInteger(f.received_iqd) && f.received_iqd >= 0)) && f.profit_share_bps >= 0 && f.profit_share_bps <= 10000 && Number.isSafeInteger(f.profit_share_bps) && Number.isSafeInteger(f.loss_share_bps) && f.loss_share_bps >= 0 && f.loss_share_bps <= 10000 && (!f.received_iqd || (f.reference.trim() && f.received_day))); }
export default function PurchaseFundingFields({ value, onChange, investors }: { value: FundingDraft; onChange: (f: FundingDraft) => void; investors: PurchaseInvestor[] }) {
  const { loc } = useLabels();
  const set = (v: Partial<FundingDraft>) => onChange({ ...value, ...v });
  return <div className="grid gap-4">
    <Select label={loc('مصدر تمويل الدفعة', 'Batch funding')} value={value.mode} onChange={(v) => set({ mode: v as FundingDraft['mode'] })} options={[{ id: 'store', name: loc('المتجر', 'Store') }, { id: 'investor', name: loc('مستثمر مسجل', 'Registered investor') }]} />
    {value.mode === 'investor' && <>
      <Select label={loc('المستثمر', 'Investor')} value={value.user_id} empty={loc('اختر حساب المستثمر', 'Select investor account')} options={investors.map((i) => ({ id: i.user_id, name: i.name || i.email }))} onChange={(id) => { const p = investors.find((i) => i.user_id === id); set({ user_id: id, profit_share_bps: p?.default_profit_share_bps ?? 3500, loss_share_bps: p?.default_loss_share_bps ?? 0 }); }} />
      {!investors.length && <p className={T.text3}>{loc('أضف المستثمر من المالية ← المستثمرون، ثم حدّث هذه الصفحة. تبقى المسودة محفوظة.', 'Add an investor in Finance → Investors, then refresh. Your draft is preserved.')}</p>}
      <div className="inventory-fields"><Input label={loc('الاستثمار المتفق عليه بالدينار', 'Agreed investment IQD')} type="number" decimals={0} min={1} value={value.agreed_iqd} onChange={(v) => set({ agreed_iqd: v === '' ? '' : Number(v) })} /><Input label={loc('نسبة ربح المستثمر %', 'Investor profit share %')} type="number" decimals={2} min={0} value={value.profit_share_bps / 100} onChange={(v) => set({ profit_share_bps: v === '' ? -1 : Math.round(Number(v) * 100) })} /></div>
      <p className={`text-sm ${T.text3}`}>{loc('النسبة من ربح القطع بعد تكاليف الطلب المباشرة. الترويج والمصاريف العامة الشهرية يتحملها المالك. الاتفاق وحده لا يسجل نقدًا.', 'The share applies to profit after direct order costs. Monthly promotion and overhead belong to the owner. An agreement alone records no cash.')}</p>
      <details><summary>{loc('هل استلمت التمويل؟', 'Have funds been received?')}</summary><div className="inventory-fields"><Input label={loc('المستلم فعليًا بالدينار', 'Actually received IQD')} type="number" decimals={0} min={0} value={value.received_iqd} onChange={(v) => set({ received_iqd: v === '' ? '' : Number(v) })} /><Input label={loc('تاريخ الاستلام', 'Receipt date')} type="date" value={value.received_day} onChange={(v) => set({ received_day: v })} /><Input label={loc('مرجع التحويل أو الوصل', 'Transfer or receipt reference')} value={value.reference} onChange={(v) => set({ reference: v })} /></div></details>
      <details><summary>{loc('الخسارة والإعداد الافتراضي', 'Loss and defaults')}</summary><Input label={loc('نسبة تحمّل الخسارة %', 'Loss share %')} type="number" decimals={2} min={0} value={value.loss_share_bps / 100} onChange={(v) => set({ loss_share_bps: v === '' ? -1 : Math.round(Number(v) * 100) })} /><label className="mt-3 flex items-start gap-2 text-sm"><input type="checkbox" checked={value.save_default} onChange={(e) => set({ save_default: e.target.checked })} />{loc('احفظ النسب افتراضيًا للدفعات المقبلة. العقود السابقة تبقى كما هي.', 'Save shares as defaults for future batches. Existing agreements stay unchanged.')}</label></details>
    </>}
  </div>;
}
