const fs = require('fs');
let content = fs.readFileSync('src/pages/Profile.tsx', 'utf8');

content = content.replace(/<div key=\{i\} className="flex flex-col items-center justify-center cursor-pointer group w-\[20%\]">/g, `<div key={i} onClick={() => navigate('/orders?status=' + item.label)} className="flex flex-col items-center justify-center cursor-pointer group w-[20%]">`);
content = content.replace(/<div className="flex flex-col items-center justify-center cursor-pointer group">\\s*<div className="w-\[24px\] h-\[24px\] sm:w-\[28px\] sm:h-\[28px\] md:w-\[32px\] md:h-\[32px\] mb-1\.5 sm:mb-2 text-\[#e6c687\] transition-transform group-hover:scale-105 drop-shadow-md">\\s*<svg viewBox="0 0 24 24" fill="currentColor" className="w-full h-full">\\s*<path fillRule="evenodd" clipRule="evenodd" d="M12 2\.25.*?" \/>\\s*<\/svg>\\s*<\/div>\\s*<span className="text-zinc-300 text-\[9px\] sm:text-\[10px\] md:text-\[11px\] font-medium mb-1 tracking-wide text-center">مركز الضمان<\/span>\\s*<span className="h-4 sm:h-5 md:h-6"><\/span> \{\/\* Spacer \*\/}\\s*<\/div>/g, `<div onClick={() => navigate('/warranty')} className="flex flex-col items-center justify-center cursor-pointer group">\n              <div className="w-[24px] h-[24px] sm:w-[28px] sm:h-[28px] md:w-[32px] md:h-[32px] mb-1.5 sm:mb-2 text-[#e6c687] transition-transform group-hover:scale-105 drop-shadow-md">\n                <svg viewBox="0 0 24 24" fill="currentColor" className="w-full h-full">\n                  <path fillRule="evenodd" clipRule="evenodd" d="M12 2.25C7.5 2.25 4 4.25 4 4.25V9.75C4 15.25 7.5 19.75 12 21.75C16.5 19.75 20 15.25 20 9.75V4.25S16.5 2.25 12 2.25ZM16.3 8.3L10.8 13.8L7.7 10.7L6.3 12.1L10.8 16.6L17.7 9.7L16.3 8.3Z" />\n                </svg>\n              </div>\n              <span className="text-zinc-300 text-[9px] sm:text-[10px] md:text-[11px] font-medium mb-1 tracking-wide text-center">مركز الضمان</span>\n              <span className="h-4 sm:h-5 md:h-6"></span> {/* Spacer */}\n            </div>`);
content = content.replace(/<div className="relative z-10 w-\[32%\] sm:w-\[28%\] md:w-\[23%\] flex justify-center sm:justify-end items-center pr-2 sm:pr-4 md:pr-6 text-black font-bold cursor-pointer hover:opacity-80 transition-opacity">/g, `<div onClick={() => navigate('/orders')} className="relative z-10 w-[32%] sm:w-[28%] md:w-[23%] flex justify-center sm:justify-end items-center pr-2 sm:pr-4 md:pr-6 text-black font-bold cursor-pointer hover:opacity-80 transition-opacity">`);
content = content.replace(/<div className="relative z-10 w-\[42%\] sm:w-\[38%\] md:w-\[33%\] flex justify-center sm:justify-end items-center pr-2 sm:pr-4 md:pr-6 text-black font-bold cursor-pointer hover:opacity-80 transition-opacity">/g, `<div onClick={() => navigate('/subscription')} className="relative z-10 w-[42%] sm:w-[38%] md:w-[33%] flex justify-center sm:justify-end items-center pr-2 sm:pr-4 md:pr-6 text-black font-bold cursor-pointer hover:opacity-80 transition-opacity">`);

// Tools Card
content = content.replace(/<div className="flex flex-col items-center gap-1.5 cursor-pointer group w-14">/g, `<div onClick={() => navigate('/tools')} className="flex flex-col items-center gap-1.5 cursor-pointer group w-14">`);

fs.writeFileSync('src/pages/Profile.tsx', content);
