/**
 * THE SPEC FIELDS IN SORANI (docs/DECISIONS.md row 212): one hand-written
 * Sorani label for every spec field id of worker/lib/templateFamilies.ts
 * (`FAMILIES` and `PRODUCT_TYPES`, 204 ids). The registry carries Arabic and
 * English only; the data file's comparison («تحديث البيانات») names a
 * `spec.<id>` line in the reader's language from here
 * (worker/routes/templateDataFile.ts `labelsOf`).
 *
 * Every entry is its own Sorani, never the Arabic pasted across (row 183),
 * and holds a Sorani-only letter (ڕ ڵ ێ ۆ ە ڤ). Units and abbreviations stay
 * Latin (AMS, RFID, HDT, XY). The vocabulary follows
 * packages/contracts/src/pricingFieldLabels.ts (ناردن, بەرهەم, تێچوو).
 * tests/productDataFileLabels.test.ts holds the table to exactly the
 * registry's ids.
 *
 * Pure data.
 */
export const SPEC_FIELD_LABEL_CKB: Readonly<Record<string, string>> = {
  technology: 'تەکنەلۆژیا',
  model: 'مۆدێل',
  release_year: 'ساڵی دەرچوون',
  skill_level: 'ئاستی شارەزایی پێویست',
  use_cases: 'گونجاوە بۆ',
  has_laser_module: 'هەڵبژاردەی یەکەی لەیزەر',
  build_volume: 'قەبارەی چاپکردن',
  print_speed: 'خێرایی چاپکردن',
  resolution: 'وردەکاریی چاپکردن',
  nozzle: 'تیرەی نۆزڵ',
  supported_materials: 'سیستەم و کەرەستە گونجاوەکان',
  power: 'وزە',
  dimensions: 'پێوانەکان',
  weight: 'کێش',
  connectivity: 'پەیوەندیکردن',
  compatibility: 'گونجاوی لەگەڵ ئامێرەکان',
  display: 'شاشە',
  camera: 'کامێرا',
  camera_resolution: 'وردیی کامێرا',
  camera_fps: 'خێرایی وێنەگرتنی کامێرا',
  noise_level: 'ئاستی دەنگەدەنگ',
  slicer_software: 'نەرمەکاڵا پشتگیریکراوەکانی پارچەکردن',
  companion_app: 'ئەپی هاوەڵ',
  assembly: 'دۆخ لە کاتی گەیاندندا',
  warranty: 'گەرەنتی',
  in_the_box: 'ناوەڕۆکی قوتووەکە',
  nozzle_temp_max: 'زۆرترین پلەی گەرمیی نۆزڵ',
  bed_temp_max: 'زۆرترین پلەی گەرمیی سەکۆ',
  heated_bed_power: 'وزەی سەکۆی گەرمکەرەوە',
  extruders: 'ژمارەی ئێکسترودەرەکان',
  enclosed: 'لاشەی داخراو',
  auto_leveling: 'ڕێکخستنی خۆکاری سەکۆ',
  multi_color: 'پشتگیریی چەند ڕەنگ',
  motion_system: 'سیستەمی جووڵە',
  filament_diameter: 'تیرەی فیلامێنت',
  max_flow_rate: 'زۆرترین ڕێژەی ڕۆیشتن',
  max_acceleration: 'زۆرترین خێراکردن',
  supported_nozzle_sizes: 'قەبارە پشتگیریکراوەکانی نۆزڵ',
  build_plate: 'ڕووی چاپکردن',
  filament_sensor: 'هەستەوەری فیلامێنت',
  power_loss_recovery: 'بەردەوامبوون دوای بڕانی کارەبا',
  input_shaping: 'ڕێکخستنی لەرە (Input shaping)',
  ams_compatibility: 'گونجان لەگەڵ AMS',
  chamber_temp_max: 'زۆرترین پلەی گەرمیی ژوورەکە',
  max_colors: 'زۆرترین ژمارەی ڕەنگ (لەگەڵ یەکەکانی AMS)',
  multicolor_method: 'ڕێگای چەند ڕەنگی',
  max_colors_native: 'ڕەنگەکان بێ گۆڕینی فیلامێنت',
  purge_waste: 'بەفیڕۆچوونی فیلامێنت لە گۆڕینی ڕەنگدا',
  multi_material: 'کەرەستەی جیاواز لە یەک چاپدا',
  colors_out_of_box: 'ڕەنگە ئامادەکان وەک دەفرۆشرێت',
  ams_units_included: 'یەکەکانی AMS لە ناو قوتووەکەدا',
  laser_module_power: 'یەکەی لەیزەری هاوپێچ',
  cutting_module: 'یەکەی بڕین و قەڵەم',
  variant_specs: 'تایبەتمەندییە جیاوازەکان بەپێی هەڵبژاردە',
  thermal_runaway_protection: 'پاراستن لە بەرزبوونەوەی بێکۆنترۆڵی گەرمی',
  supported_filaments: 'فیلامێنتە پشتگیریکراوەکان',
  lcd_size: 'قەبارەی شاشە',
  lcd_resolution: 'وردیی شاشە',
  xy_resolution: 'وردیی تەوەرەی XY',
  layer_height_range: 'مەودای بەرزیی چین',
  light_source: 'سەرچاوەی ڕووناکی',
  exposure_time: 'کاتی ڕووناکیپێدان',
  uv_power: 'وزەی ڕووناکیی UV',
  lcd_type: 'جۆری شاشە',
  lcd_lifespan: 'تەمەنی چاوەڕوانکراوی شاشە',
  release_film: 'پەردەی جیاکردنەوە',
  input_voltage: 'ڤۆڵتی کارەبای هاتوو',
  rated_power: 'زۆرترین وزە',
  typical_print_power: 'وزە لە کاتی چاپکردندا',
  standby_power: 'وزەی دۆخی چاوەڕوانی',
  input_frequency: 'لەرەلەری کارەبا',
  power_factor: 'هۆکاری وزە',
  air_filtration: 'پاڵاوتنی هەوا',
  ambient_temp_range: 'پلەی گەرمیی گونجاوی ژوور',
  extruder_drive: 'سیستەمی ئێکسترودەر',
  hotend_type: 'پێکهاتەی هۆتئێند',
  nozzle_material: 'کەرەستەی نۆزڵ',
  auxiliary_part_cooling: 'پانکەی ساردکەرەوەی زیادە',
  linear_guides: 'سیستەمی ڕێنمایی تەوەرەکان',
  leveling_sensor: 'جۆری هەستەوەری ڕێکخستن',
  min_layer_height: 'کەمترین بەرزیی چین',
  firmware: 'فێرموێر (نەرمەکاڵای جێگیر)',
  print_failure_detection: 'دۆزینەوەی شکستی چاپکردن',
  z_accuracy: 'وردیی تەوەرەی Z',
  max_print_speed_z: 'زۆرترین خێرایی چاپکردن (ستوونی)',
  release_mechanism: 'میکانیزمی جیاکردنەوەی چین',
  leveling_type: 'ڕێکخستنی سەکۆی چاپکردن',
  fits_models: 'گونجاوە بۆ ئەم مۆدێلانە',
  install_type: 'ڕێگای دامەزراندن',
  material: 'کەرەستە',
  use_case: 'بەکارهێنان',
  capacity: 'قەبارەی هەڵگرتن',
  ams_slots: 'ژمارەی شوێنەکان',
  ams_max_units: 'زۆرترین ژمارەی یەکەی پێکەوەبەستراو',
  filament_drying: 'وشککردنەوەی فیلامێنت',
  drying_temp_max: 'زۆرترین پلەی گەرمیی وشککردنەوە',
  humidity_sensor: 'هەستەوەری شێ',
  rfid_reading: 'خوێندنەوەی زانیاریی بەکرە (RFID)',
  ams_filaments: 'فیلامێنتە پشتگیریکراوەکانی AMS',
  ams_unsupported: 'فیلامێنتە پشتگیرینەکراوەکان',
  spool_sizes: 'قەبارە پشتگیریکراوەکانی بەکرە',
  nozzle_diameter: 'تیرەی نۆزڵ',
  hotend_nozzle_material: 'کەرەستەی نۆزڵی هۆتئێند',
  hotend_max_temp: 'زۆرترین پلەی گەرمی',
  flow_type: 'جۆری ڕۆیشتن',
  abrasive_ready: 'پشتگیریی فیلامێنتی خڕۆشێنەر',
  quick_swap: 'گۆڕینی خێرا',
  plate_size: 'قەبارەی تەختە',
  plate_surface: 'ڕووی تەختە',
  double_sided: 'دوو ڕوو',
  plate_max_temp: 'زۆرترین پلەی گەرمیی تەختە',
  usage_age: 'ماوەی بەکارهێنان',
  cosmetic_condition: 'دۆخی ڕووکەش',
  functional_check: 'پشکنینی کارکردنی ئامێرەکە',
  original_box: 'قوتووی ڕەسەن',
  replaced_parts: 'پارچە گۆڕدراوەکان',
  filament_used_kg: 'فیلامێنتی بەکارهاتوو',
  nozzle_condition: 'دۆخی نۆزڵ',
  calibrated: 'ڕێکخراوە دوای پشکنین',
  firmware_version: 'وەشانی فێرموێر',
  laser_source: 'جۆری سەرچاوەی لەیزەر',
  laser_power: 'وزەی لەیزەر',
  laser_wavelength: 'درێژیی شەپۆلی لەیزەر',
  work_area: 'ڕووبەری کار',
  max_material_thickness: 'زۆرترین ئەستووریی کەرەستە',
  engraving_speed: 'خێرایی هەڵکۆڵین',
  cutting_speed: 'خێرایی بڕین',
  positioning_accuracy: 'وردیی شوێندانان',
  auto_focus: 'فۆکەسی خۆکار',
  rotary_axis: 'تەوەرەی سووڕاو',
  laser_class: 'پۆلی سەلامەتیی لەیزەر',
  laser_enclosure: 'لاشەی لەیزەر',
  fume_extraction: 'ڕاکێشانی دووکەڵ',
  emergency_stop: 'دوگمەی وەستاندنی فریاکەوتن',
  flame_detection: 'دۆزینەوەی بڵێسە',
  tilt_detection: 'دۆزینەوەی لاربوونەوە',
  safety_interlock: 'قوفڵی سەلامەتیی سەرپۆش',
  laser_part_kind: 'جۆری پاشکۆی لەیزەر',
  focal_length: 'دووریی فۆکەس',
  filter_life: 'تەمەنی چاوەڕوانکراوی فلتەر',
  rotary_max_diameter: 'زۆرترین تیرەی تەوەرەی سووڕاو',
  work_surface_size: 'قەبارەی ڕووی کار',
  material_type: 'جۆری کەرەستە',
  diameter: 'تیرە',
  net_weight: 'کێشی سافی',
  color_name: 'ڕەنگ',
  color_hex: 'کۆدی ڕەنگ (HEX)',
  print_temp: 'پلەی گەرمیی چاپکردن',
  bed_temp: 'پلەی گەرمیی سەکۆ',
  processing_mode: 'شێوازی کارپێکردن',
  finish: 'ڕووکار',
  quantity_per_pack: 'بڕ لە ناو پاکێتدا',
  operating_temp: 'پلەی گەرمیی کارکردن',
  storage: 'مەرجەکانی هەڵگرتن',
  certifications: 'بڕوانامەکان',
  spool_type: 'جۆری بەکرە',
  drying: 'وشککردنەوە',
  tolerance: 'ڕێژەی جیاوازیی ڕێگەپێدراو',
  density: 'چڕی (density)',
  ams_compatible: 'گونجاوە لەگەڵ AMS',
  rfid_tag: 'نیشانەی RFID',
  spool_weight: 'کێشی بەکرەی بەتاڵ',
  filament_length: 'درێژیی فیلامێنت',
  max_print_speed: 'زۆرترین خێرایی چاپکردنی پێشنیارکراو',
  tensile_strength: 'بەرگەگرتنی ڕاکێشان',
  heat_deflection: 'بەرگەگرتنی گەرمی (HDT)',
  elongation: 'درێژبوونەوە لە کاتی شکاندندا',
  shore_hardness: 'ڕەقیی شۆر',
  enclosure_required: 'پێویستی بە ژووری داخراو هەیە',
  hardened_nozzle: 'پێویستی بە نۆزڵی بەهێزکراو هەیە',
  fan_speed: 'ساردکردنەوەی پارچە',
  volume: 'قەبارە',
  wavelength: 'درێژیی شەپۆل',
  hardness: 'ڕەقی',
  shelf_life: 'ماوەی بەسەرچوون',
  pieces: 'ژمارەی پارچەکان',
  assembly_time: 'کاتی کۆکردنەوە',
  age_rating: 'پۆلی تەمەن',
  battery: 'پاتری (باتەری)',
  control_range: 'مەودای کۆنترۆڵ',
  channels: 'ژمارەی کەناڵەکان',
  voltage: 'ڤۆڵت',
  current: 'تەزووی کارەبا',
  interface: 'ڕووکاری پەیوەندی',
  thread: 'پێچ (قلاووز)',
  length: 'درێژی',
  accessory_material: 'کەرەستەی پاشکۆ',
  substrate: 'کەرەستەی بنەڕەت',
  sheet_length: 'درێژیی تەختە',
  sheet_width: 'پانیی تەختە',
  sheet_thickness: 'ئەستووریی تەختە',
  sheet_weight: 'کێشی تەختە',
  coating: 'ڕووپۆش',
  engravable: 'دەکرێت هەڵبکۆڵرێت',
  cuttable: 'دەکرێت ببڕدرێت',
  sheets_per_pack: 'ژمارەی تەختەکان لە پاکێتدا',
  adhesive_backing: 'پشتی لکێنەر',
  media_format: 'شێوەی کەرەستە',
  media_width: 'پانیی کەرەستە',
  media_length: 'درێژیی کەرەستە',
  media_thickness: 'ئەستووریی کەرەستە',
  blade_depth: 'قووڵیی پێشنیارکراوی تیغ',
  backing_liner: 'کاغەزی جیاکەرەوەی پشتەوە',
  weeding_difficulty: 'قورسیی لابردنی زیادەکان',
};
