/**
 * Smart Fit — the engine's text fit (Programme C, C1 lane L3; docs/
 * LEVO_PROJECT_PROGRAMME.md §A C1.8, §C.1 row C1 «the Smart Fit table
 * generated from both faces … with positional forms and lam-alef, the joining
 * classes in fit.ts»).
 *
 * Pins: the committed advance table (checksum, shape, coverage of every code
 * point the text rule allows, sane values); the joining classes and the
 * positional forms Arabic and Sorani letters take, lam-alef as a ligature
 * (and not across ZWNJ); Arabic, Sorani and Latin names measured; each stage
 * of the fit reached by a fixture (one line → balanced two lines → bolder →
 * size up → too long); the minimum cap height and the printable stroke
 * respected; determinism; and «browser and Worker agree» — fit.ts is the only
 * implementation, the table its only data, no DOM or canvas anywhere in it.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { CAIRO, CAIRO_SUM } from '../packages/catalog/src/personalize/cairoAdvances';
import {
  FITTED_BELOW, MIN_STROKE_MM, WRAP_GAIN, fitText, fontMm, formCount, glyphRun, inTable, joiningClass, lineMetrics, lineTracking, measureEm, minCapFor, sizeSteps, stemEm,
} from '../packages/catalog/src/personalize/fit';
import { STYLE_LADDER, STYLE_PRESETS, styleBox, stylesFor } from '../packages/catalog/src/personalize/styles';
import { textRuleAllows } from '../packages/catalog/src/personalize/config';
import { STYLES } from '../packages/catalog/src/personalize/vocab';
import { FIXTURES } from './fixtures/personalizeBlueprints';
import { ARABIC_NAMES, FIT_SIZES, FIT_STAGES, LATIN_NAMES, SORANI_NAMES, textArea } from './fixtures/personalizeTaste';

const ROOT = join(import.meta.dirname, '..');
const DIR = join(ROOT, 'packages/catalog/src/personalize');
const WEIGHTS = [300, 400, 500, 600, 700, 800, 900];
const fnv = (s: string): number => {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 0x01000193) >>> 0;
  return h >>> 0;
};

// ---------------------------------------------------------------- the table

test('the committed table is the generated one: checksum, shape and header', () => {
  assert.equal(fnv(`${CAIRO.cps}|${CAIRO.lig}|${JSON.stringify(CAIRO.kern)}|${CAIRO.data}`), CAIRO_SUM, 'cairoAdvances.ts was edited by hand — re-run scripts/cairo-advances.mjs');
  let entries = 0;
  for (const part of CAIRO.cps.split(',')) {
    const [a, b = a] = part.split('-').map((h) => parseInt(h, 16));
    assert.ok(a <= b, part);
    for (let cp = a; cp <= b; cp++) entries += formCount(cp);
  }
  entries += CAIRO.lig.length * 4 * 2;
  assert.equal(CAIRO.data.length, entries * (CAIRO.w.length + 1), 'one base (two characters) and one step per further weight, per entry');
  assert.ok([...CAIRO.data].every((ch) => ch.charCodeAt(0) >= 48 && ch.charCodeAt(0) < 112), 'data characters are 0–63 from «0»');
  assert.deepEqual([...CAIRO.w], [400, 900]);
  assert.ok(CAIRO.cap > 0.6 && CAIRO.cap < 0.75, `cap ratio ${CAIRO.cap}`);
  assert.equal(CAIRO.stem.length, 7);
  for (let i = 1; i < 7; i++) assert.ok(CAIRO.stem[i] >= CAIRO.stem[i - 1], 'strokes thicken with weight');
  assert.ok(CAIRO.asc[1] > CAIRO.asc[0] && CAIRO.desc[1] > CAIRO.desc[0], 'Arabic reaches higher and lower than Latin');
  const file = readFileSync(join(DIR, 'cairoAdvances.ts'), 'utf8');
  assert.match(file, /GENERATED by scripts\/cairo-advances\.mjs/);
  assert.doesNotMatch(file, /\bfunction\b|=>|\bimport\b/, 'the table is data only');
});

test('every code point the text rule allows is measured — itself, folded to its base, or zero-width', () => {
  const missing: string[] = [];
  let allowed = 0;
  for (let cp = 0; cp < 0x3000; cp++) {
    if (!textRuleAllows(cp)) continue;
    allowed++;
    if (!inTable(cp)) missing.push(`U+${cp.toString(16)}`);
  }
  assert.deepEqual(missing, []);
  assert.ok(allowed > 300, `the rule allows ${allowed} code points`);
  for (const ch of 'ەۆێڕڵڤړپچژکگیھ') assert.ok(inTable(ch.codePointAt(0)!), ch);
});

test('advances are positive, below 1.5 em, and read the same at every weight between the table weights', () => {
  for (let cp = 0; cp < 0x3000; cp++) {
    if (!textRuleAllows(cp) || cp === 0x200c || cp === 0x200d) continue;
    const ch = String.fromCodePoint(cp);
    for (const w of WEIGHTS) {
      const em = measureEm(ch, w);
      assert.ok(em > 0 && em < 1.5, `U+${cp.toString(16)} @${w}: ${em}`);
    }
  }
  assert.equal(measureEm('\u200c\u200d', 700), 0, 'ZWNJ and ZWJ take no width');
  assert.equal(measureEm('A', 300), measureEm('A', 400), 'a weight below the table reads its first weight');
  const mid = measureEm('محمد', 650);
  assert.ok(Math.abs(mid - (measureEm('محمد', 400) + measureEm('محمد', 900)) / 2) < 1e-9, 'linear between 400 and 900');
});

// ------------------------------------------------------------------ joining

test('joining classes: dual, right, non-joining, join-causing, transparent — Arabic and Sorani', () => {
  const cls = (s: string) => [...s].map((c) => joiningClass(c.codePointAt(0)!)).join('');
  assert.equal(cls('بتثجحخسشصضطظعغفقكلمنهيىئ'), 'D'.repeat(24));
  assert.equal(cls('آأؤإاةدذرزو'), 'R'.repeat(11));
  assert.equal(cls('پچڤکگڵھیێ'), 'D'.repeat(9), 'Sorani letters that join both ways');
  assert.equal(cls('ړڕژۆە'), 'R'.repeat(5), 'Sorani letters that join only to the right');
  assert.equal(cls('ء٠۴؟ A1'), 'UUUUUUU');
  assert.equal(cls('ـ\u200d'), 'CC');
  assert.equal(cls('\u200c'), 'U');
  assert.equal(cls('\u064e\u0651\u0670'), 'TTT');
});

test('positional forms: initial, medial, final and isolated come from the neighbours', () => {
  const forms = (s: string) => glyphRun(s).map(([, f]) => f);
  assert.deepEqual(forms('بب'), [1, 3]);
  assert.deepEqual(forms('ببب'), [1, 2, 3]);
  assert.deepEqual(forms('با'), [1, 3], 'alef joins the letter before it');
  assert.deepEqual(forms('اب'), [0, 0], 'alef never joins the letter after it');
  assert.deepEqual(forms('ب\u200cب'), [0, 0], 'ZWNJ breaks the join');
  assert.deepEqual(forms('ب\u200dب'), [1, 3], 'ZWJ keeps it');
  assert.deepEqual(forms('بـ'), [1, 0], 'tatweel causes a join (and has one form)');
  assert.deepEqual(forms('ب\u064eب'), [1, 3], 'a mark is transparent');
  assert.deepEqual(forms('هێڵ'), [1, 2, 3], 'the patch letters join like any other');
  assert.deepEqual(forms('ڕۆژ'), [0, 0, 0], 'right-joining letters stand alone after one another');
  assert.deepEqual(forms('ئەڤ'), [1, 3, 0]);
});

test('lam-alef is one ligature glyph (isolated or final), not across ZWNJ; ZWJ keeps it', () => {
  assert.equal(glyphRun('لا').length, 1);
  assert.deepEqual(glyphRun('لا')[0], [0x644 * 0x10000 + 0x627, 0]);
  for (const alef of 'آأإا') assert.equal(glyphRun(`ل${alef}`).length, 1, alef);
  assert.deepEqual(glyphRun('بلا').map(([, f]) => f), [1, 3], 'a joined lam-alef is final');
  assert.equal(glyphRun('ل\u200cا').length, 2);
  assert.equal(glyphRun('ل\u200dا').length, 1);
  assert.equal(glyphRun('ڵا').length, 2, 'the Sorani lam does not ligate in these faces');
  for (const w of WEIGHTS) {
    assert.notEqual(measureEm('لا', w), measureEm('ل', w) + measureEm('ا', w), `@${w}`);
    assert.equal(measureEm('ل\u200cا', w), measureEm('ل', w) + measureEm('ا', w), `ZWNJ @${w}`);
  }
});

test('names: joined letters take their positional widths; every script measures and grows with weight', () => {
  assert.ok(measureEm('ببب', 700) < 3 * measureEm('ب', 700) * 0.7, 'initial and medial beh are far narrower than isolated');
  assert.ok(measureEm('ـسـ', 700) - 2 * measureEm('ـ', 700) < measureEm('س', 700), 'medial seen drops its tail');
  let differ = 0;
  for (const n of [...ARABIC_NAMES, ...SORANI_NAMES]) {
    const apart = [...n].reduce((s, ch) => s + measureEm(ch, 700), 0);
    if (Math.abs(measureEm(n, 700) - apart) > 1e-6) differ++;
  }
  assert.ok(differ >= ARABIC_NAMES.length + SORANI_NAMES.length - 2, 'a name is not the sum of its isolated letters');
  for (const n of [...ARABIC_NAMES, ...SORANI_NAMES, ...LATIN_NAMES]) {
    assert.ok(measureEm(n, 300) > 0, n);
    assert.ok(measureEm(n, 900) >= measureEm(n, 300) * 0.98, `${n} bolder is not narrower`);
    assert.equal(measureEm(n, 700), measureEm(n, 700), 'deterministic');
  }
  assert.ok(measureEm('Zoë', 700) === measureEm('Zoe', 700), 'ë folds to e');
  assert.ok(measureEm('ريم', 700) > measureEm('ر', 700) + measureEm('يم', 700) - 1e-9, 'the reh–yeh pair rule widens the pair');
});

// ------------------------------------------------------------------ fitting

test('each stage of Smart Fit is reached: ok → fitted → two lines → bolder → size up → too long', () => {
  const at = (k: keyof typeof FIT_STAGES, sizes?: typeof FIT_SIZES) => {
    const s = FIT_STAGES[k];
    return fitText(s.value, s.area, { style: s.style, scale: 1, sizes });
  };
  const ok = at('ok');
  assert.equal(ok.code, 'TEXT_OK');
  assert.deepEqual(ok.lines, ['ALI']);
  assert.ok(ok.fits);
  const fitted = at('fitted');
  assert.equal(fitted.code, 'TEXT_FITTED');
  assert.ok(fitted.fits && fitted.cap_mm < ok.cap_mm);
  const two = at('twoLines');
  assert.equal(two.code, 'TEXT_TWO_LINES');
  assert.deepEqual(two.lines, ['Abdul Rahman', 'Mustafa'], 'a balanced wrap at a space');
  const bolder = at('bolder');
  assert.equal(bolder.code, 'TEXT_STYLE_BOLDER');
  assert.equal(bolder.style, 'minimal', 'the lightest heavier style the area offers');
  assert.ok(bolder.fits);
  const up = at('sizeUp', FIT_SIZES);
  assert.equal(up.code, 'SIZE_UP_FOR_TEXT');
  assert.equal(up.size_value, 'ov_l', 'M is too small, L fits');
  assert.equal(up.fits, false);
  assert.ok(up.cap_mm > 0 && up.lines.length === 1);
  const long = at('tooLong');
  assert.equal(long.code, 'TEXT_TOO_LONG');
  assert.equal(long.fits, false);
  assert.equal(long.size_value, undefined);
  assert.equal(at('tooLong', [{ value: 'ov_m', scale: 1.2, iqd_delta: 2000 }]).code, 'TEXT_TOO_LONG', 'no size that fits: blocked');
});

test('the minimum cap height and the printable stroke are respected by every fitting answer', () => {
  for (const s of STYLES) {
    const min = minCapFor(s, { min_cap_mm: 0 });
    assert.ok(Math.abs(fontMm(min) * stemEm(STYLE_PRESETS[s].weight) - MIN_STROKE_MM) < 0.01, `${s}: strokes at the minimum are ${MIN_STROKE_MM} mm`);
    assert.equal(minCapFor(s, { min_cap_mm: 20 }), 20);
  }
  const names = [...ARABIC_NAMES, ...SORANI_NAMES, ...LATIN_NAMES, 'MOHAMMED ABDULLAH', 'عبد الرحمن مصطفى'];
  const areas = [textArea(60, 20), textArea(40, 10, { min_cap_mm: 3 }), textArea(90, 16, { lines: 2, min_cap_mm: 5 }), textArea(30, 30, { lines: 3 })];
  for (const a of areas) {
    for (const n of names) {
      for (const style of stylesFor(a)) {
        const r = fitText([n], a, { style, scale: 1 });
        if (r.fits) assert.ok(r.cap_mm >= minCapFor(r.style, a.text!) - 1e-9, `${n} ${style}: ${r.cap_mm} ≥ ${minCapFor(r.style, a.text!)}`);
        else assert.ok(r.cap_mm < minCapFor(style, a.text!) + 1e-9);
        assert.ok(r.lines.length <= a.text!.lines);
        assert.equal(r.lines.join(' ').replace(/ & | و /g, ' '), n, 'the words are never changed, only placed');
      }
    }
  }
});

test('TEXT_FITTED only when the text is drawn below FITTED_BELOW of what the height allows', () => {
  const a = textArea(40, 10, { styles: ['bold'] });
  const full = fitText(['Omar'], a, { style: 'bold', scale: 1 }).cap_mm;
  const slightly = fitText(['Christopher'], a, { style: 'bold', scale: 1 });
  assert.equal(slightly.code, 'TEXT_OK', `made a little smaller (${slightly.cap_mm} of ${full}) reads as it is`);
  assert.ok(slightly.cap_mm < full && slightly.cap_mm >= FITTED_BELOW * full);
  const much = fitText(['Abdulrahman'], a, { style: 'bold', scale: 1 });
  assert.equal(much.code, 'TEXT_FITTED');
  assert.ok(much.cap_mm < FITTED_BELOW * full);
});

test('the typed layout stays unless it is too small or a wrap is WRAP_GAIN larger', () => {
  const a = textArea(60, 24, { lines: 2 });
  const one = fitText(['Omar Ali'], a, { style: 'bold', scale: 1 });
  assert.deepEqual(one.lines, ['Omar Ali']);
  const explicit = fitText(['Omar', 'Ali'], a, { style: 'bold', scale: 1 });
  assert.deepEqual(explicit.lines, ['Omar', 'Ali'], 'typed lines stay lines');
  assert.notEqual(explicit.code, 'TEXT_TWO_LINES');
  assert.ok(WRAP_GAIN > 1);
});

test('names (count > 1) stay whole and join with « و » or « & »', () => {
  const a = textArea(60, 24, { lines: 2, count: 2 });
  assert.deepEqual(fitText(['ALI', 'SARA'], a, { style: 'bold', scale: 1 }).lines, ['ALI & SARA']);
  assert.deepEqual(fitText(['علي', 'سارة'], a, { style: 'bold', scale: 1 }).lines, ['علي و سارة']);
  const two = fitText(['Mohammed', 'Fatima'], a, { style: 'bold', scale: 1 });
  assert.deepEqual(two.lines, ['Mohammed', 'Fatima']);
  assert.equal(two.code, 'TEXT_TWO_LINES');
});

test('scale and photo-only areas: millimetres from the frame × scale, or the quad × the face', () => {
  const a = textArea(40, 10, { styles: ['bold'] });
  const small = fitText(['Mohammed'], a, { style: 'bold', scale: 1 });
  const big = fitText(['Mohammed'], a, { style: 'bold', scale: 2 });
  assert.ok(Math.abs(big.cap_mm - 2 * small.cap_mm) < 0.02, `${big.cap_mm} ≈ 2 × ${small.cap_mm}`);
  const sign = FIXTURES.photoOnlySign.spec;
  const area = sign.areas[0];
  const unmeasured = fitText(['متجر الأمل'], area, { style: 'elegant', scale: 1 });
  assert.equal(unmeasured.code, 'TEXT_OK', 'no dims: not measured');
  const r = fitText(['متجر الأمل'], area, { style: 'elegant', scale: 1, dims_mm: [300, 100, 5] });
  assert.ok(r.fits && r.cap_mm >= 8, `a 180 × 20 mm box: ${JSON.stringify(r)}`);
});

test('sizeSteps: the other in-stock sizes of the same look, with their price difference', () => {
  const pub = FIXTURES.nameStand.pub;
  const st = sizeSteps(pub, 'pv_m_classic');
  assert.equal(st.scale, 1);
  assert.deepEqual(st.sizes.map((z) => [z.value, z.scale, z.variant, z.iqd_delta]).sort(), [['ov_l', 1.25, 'pv_l_classic', 3000], ['ov_s', 0.8, 'pv_s_classic', -3000]]);
  assert.deepEqual(sizeSteps(pub, 'pv_m_silk').sizes.map((z) => z.value), ['ov_s'], 'L silk is sold out');
  assert.deepEqual(sizeSteps(pub, null), { scale: 1, dims_mm: undefined, sizes: [] });
  const r = fitText(['MOHAMMED ABDULLAH'], pub.areas[0], { style: 'bold', ...sizeSteps(pub, 'pv_m_classic') });
  assert.equal(r.code, 'SIZE_UP_FOR_TEXT');
  assert.equal(r.size_value, 'ov_l');
});

test('deterministic: the same entries give the same answer, every time and in every order of calls', () => {
  const s = FIT_STAGES.twoLines;
  const a = fitText(s.value, s.area, { style: 'bold', scale: 1 });
  fitText(['x'], s.area, { style: 'elegant', scale: 3 });
  assert.deepEqual(fitText(s.value, s.area, { style: 'bold', scale: 1 }), a);
});

test('styles: six presets on the ladder, the box they add, tracking only on lines without Arabic', () => {
  assert.deepEqual([...STYLE_LADDER].sort(), [...STYLES].sort());
  for (let i = 1; i < STYLE_LADDER.length; i++) assert.ok(STYLE_PRESETS[STYLE_LADDER[i]].weight >= STYLE_PRESETS[STYLE_LADDER[i - 1]].weight);
  for (const s of STYLES) {
    const p = STYLE_PRESETS[s];
    assert.ok(p.weight >= 300 && p.weight <= 900 && p.tracking >= 0 && p.outline >= 0 && p.shadow >= 0 && p.jitter >= 0, s);
    const b = styleBox(s, 1.2);
    assert.ok(b.x >= 0 && b.y >= 0);
  }
  assert.deepEqual(stylesFor(textArea(10, 10, { styles: ['bold', 'elegant'] })), ['elegant', 'bold']);
  assert.deepEqual(stylesFor({ text: undefined }), []);
  assert.equal(lineTracking('علي', 'elegant'), 0);
  assert.equal(lineTracking('ALI', 'elegant'), STYLE_PRESETS.elegant.tracking);
  const m = lineMetrics(['ALI', 'علي']);
  assert.ok(m.asc >= CAIRO.asc[1] && m.desc >= CAIRO.desc[1]);
});

test('browser and Worker agree: fit.ts is the only implementation and the table its only data — no DOM, canvas or clock', () => {
  const src = readFileSync(join(DIR, 'fit.ts'), 'utf8').replace(/\/\*[\s\S]*?\*\/|\/\/.*$/gm, '');
  for (const word of ['document', 'window', 'canvas', 'Canvas', 'measureText', 'FontFace', 'navigator', 'Date', 'Math.random', 'fetch', 'performance']) {
    assert.ok(!src.includes(word), `fit.ts uses ${word}`);
  }
  const imports = [...src.matchAll(/from '([^']+)'/g)].map((m) => m[1]).sort();
  assert.deepEqual(imports, ['./cairoAdvances', './styles', './types']);
  const others: string[] = [];
  const walk = (dir: string): void => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      if (e.name === 'node_modules' || e.name.startsWith('.')) continue;
      const p = join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (/\.(ts|tsx|mjs)$/.test(e.name) && !p.endsWith('personalize/fit.ts') && !p.endsWith('personalize/index.ts') && !p.includes(`${join('tests', 'personalizeFit')}`)) {
        const s = readFileSync(p, 'utf8');
        if (/function fitText\b|from '[^']*cairoAdvances'/.test(s) && !p.endsWith(join('scripts', 'cairo-advances.mjs'))) others.push(p);
      }
    }
  };
  for (const d of ['packages', 'src', 'worker']) walk(join(ROOT, d));
  assert.deepEqual(others, [], 'no second fit and no other reader of the table');
});
