/**
 * «الثيم المطبق حاليا هو ليس ابيض ولا اسود … تغيير الثيم طبقه في جميع الصفحات
 *  ويمكن تغييره في الاعدادات من المظهر.»
 *
 * The owner photographed an app that was neither light nor dark: homepage v2
 * had made the home page's lower half a warm ivory sheet while every card and
 * every other page stayed black. This replaces tests/darkOnlyTheme.test.ts,
 * which pinned the opposite rule («THIS APP HAS NO LIGHT THEME»).
 *
 * THE RULE NOW. There are two complete themes, light (the default) and dark,
 * switched by `data-theme` on <html> (src/index.css, THE TWO THEMES; values
 * generated by scripts/theme-tokens.mjs). Every page follows the one chosen in
 * Settings → «المظهر». That only holds if no page paints a colour that belongs
 * to ONE theme — so this file forbids exactly those:
 *
 *  - an arbitrary NEUTRAL or near-black / near-white hex in a colour utility
 *    (`bg-[#0a0a0a]`, `text-[#f2f2f2]`, `border-[#27272a]`): a grey written
 *    as hex cannot flip. Use the role (`bg-black`, `bg-surface`, `zinc-800`).
 *  - a CHROMATIC hex as text, border, ring … (`text-[#2CE59B]`): a colour tuned
 *    to read on black does not read on ivory. Use its named tone (`text-mint`)
 *    whose light value is contrast-checked. A chromatic hex as a FILL
 *    (`bg-[#B03142]` with `text-snow` on it) is fine — it is the same fill in
 *    both themes.
 *  - the `dark:` variant: it compiles to the OS query, not to this app's
 *    theme, so it would follow the phone instead of the user's choice.
 *
 * Out of scope, by the owner's brief: the merchant storefront (its themes are
 * the merchant's, dark by design, and `[data-store-theme]` keeps them dark),
 * the 3D viewer's canvas, and the printer-farm game's room scene.
 *
 * Run: npm run test:unit
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildBlock, currentBlock, contrast, parseColor, rgbToOklch, SEMANTIC, TONES, IVORY, PAPER } from '../scripts/theme-tokens.mjs';
import { THEME_BOOT_SCRIPT, THEME_BOOT_SCRIPT_HASH, spaCsp } from '../worker/lib/securityPolicy';
import { THEME_STORAGE_KEY, THEME_COLOR, DEFAULT_THEME_PREFERENCE, resolveTheme } from '../src/lib/theme';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p: string) => readFileSync(join(ROOT, p), 'utf8');

/** Out of scope: the merchant's storefront themes and two drawn scenes. */
const EXEMPT = [/^src\/components\/storefront\//, /^src\/pages\/farm\/room\//];

function walk(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(join(ROOT, dir))) {
    const rel = `${dir}/${name}`;
    if (statSync(join(ROOT, rel)).isDirectory()) walk(rel, out);
    else if (/\.(tsx|ts)$/.test(name)) out.push(rel);
  }
  return out;
}
const stripComments = (s: string) => s.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:'"`])\/\/[^\n]*/g, '$1');

const COLOR_UTIL = /(?:^|[\s"'`{])((?:[a-z0-9-]+:)*!?(bg|text|border(?:-[a-z]+)?|ring(?:-offset)?|outline|divide|from|via|to|fill|stroke|placeholder|caret|accent|decoration|shadow)-\[#([0-9a-fA-F]{3,8})\](?:\/[\d.]+)?)/g;
const FILL_PREFIX = new Set(['bg', 'from', 'via', 'to', 'shadow']);

/** Theme-specific: a grey, or a colour so dark or so light it is a ground, not a hue. */
function isThemeSpecific(hex: string): boolean {
  const [L, C] = rgbToOklch(parseColor(`#${hex}`));
  return C < 0.03 || L < 0.3 || L > 0.93;
}

test('no page paints a colour that belongs to one theme', () => {
  const offenders: string[] = [];
  for (const file of walk('src')) {
    if (EXEMPT.some((re) => re.test(file))) continue;
    const src = stripComments(read(file));
    for (const m of src.matchAll(COLOR_UTIL)) {
      const [, cls, prefix, hex] = m;
      const base = prefix.replace(/-.*/, '');
      if (isThemeSpecific(hex)) offenders.push(`${file}: ${cls}  (a ground colour written as hex — use its role)`);
      else if (!FILL_PREFIX.has(base)) offenders.push(`${file}: ${cls}  (a chromatic hex as ${prefix} — use its named tone)`);
    }
    for (const m of src.matchAll(/(?:^|[\s"'`{])((?:[a-z-]+:)*dark:[a-z-]+[^\s"'`]*)/g)) {
      offenders.push(`${file}: ${m[1]}  (the dark: variant follows the phone, not the chosen theme)`);
    }
  }
  assert.deepEqual(offenders, [], `theme-specific colours:\n${offenders.join('\n')}`);
});

test('both themes are defined, and the generated block is current', () => {
  const css = read('src/index.css');
  const block = currentBlock();
  assert.ok(block, 'the THEME TOKENS markers are missing from src/index.css');
  assert.equal(block, buildBlock(), 'src/index.css is stale — run: node scripts/theme-tokens.mjs --write');
  assert.match(block!, /\[data-theme='light'\]\{color-scheme:light;/);
  assert.match(block!, /\[data-theme='dark'\],\[data-store-theme\]\{color-scheme:dark;/);
  // The dark values in @theme are the ones the generator restores for a dark island.
  for (const [name, [dark]] of Object.entries(SEMANTIC as Record<string, [string, string]>)) {
    if (['accent', 'accent-contrast'].includes(name)) continue; // declared by reference in @theme
    assert.match(css, new RegExp(`--color-${name}:\\s*${dark}\\b`, 'i'), `@theme --color-${name} drifted from the generator's dark value`);
  }
  for (const [name, hex] of Object.entries(TONES as Record<string, string>)) {
    assert.match(css, new RegExp(`--color-${name}:\\s*${hex}\\b`, 'i'), `the tone ${name} is not declared in @theme`);
  }
  // No second, forced light island left over from homepage v2.
  assert.doesNotMatch(css, /body:has\(\[data-home-v2\]\)/, 'the home page forces its own ground again');
});

test('every light text colour reads on the ivory ground', () => {
  const block = buildBlock();
  const light = block.slice(block.indexOf("[data-theme='light']"), block.indexOf("[data-theme='dark']"));
  const value = (name: string) => light.match(new RegExp(`--color-${name}:([^;}]+)`))?.[1];
  const ivory = parseColor(IVORY);
  const paper = parseColor(PAPER);
  const TEXT = ['white', 'text-primary', 'text-secondary', 'text-muted', 'success', 'warning', 'danger', 'info', 'gold', 'accent', 'zinc-500', 'zinc-400', 'zinc-300', 'red-400', 'emerald-400', 'amber-400', 'sky-400', 'red-500', 'amber-300', 'emerald-300', ...Object.keys(TONES)];
  for (const name of TEXT) {
    const v = value(name);
    if (!v) continue; // a shade nobody uses is not emitted
    const c = Math.min(contrast(parseColor(v), ivory), contrast(parseColor(v), paper));
    assert.ok(c >= 4.5, `${name} (${v}) reads at ${c.toFixed(2)}:1 on the light ground, under 4.5`);
  }
  // The accent pair: text on a gold fill, in both themes.
  const pair = (fill: string, ink: string) => contrast(parseColor(fill), parseColor(ink));
  assert.ok(pair(value('accent')!, value('accent-contrast')!) >= 4.5, 'light: accent-contrast on accent');
  const [darkAccent, darkInk] = [(SEMANTIC as Record<string, string[]>).accent[0], (SEMANTIC as Record<string, string[]>)['accent-contrast'][0]];
  assert.ok(pair(darkAccent, darkInk) >= 4.5, 'dark: accent-contrast on accent');
});

test('the theme is set before the first paint, by the one inline script the CSP allows', () => {
  const html = read('index.html');
  assert.ok(html.includes(`<script>${THEME_BOOT_SCRIPT}</script>`), 'index.html does not carry the pinned theme script');
  assert.equal(html.match(/<script>/g)?.length, 1, 'one inline script, no other');
  // It runs in the head, after both metas it rewrites and before the stylesheet paints.
  const at = html.indexOf(`<script>${THEME_BOOT_SCRIPT}`);
  assert.ok(at > html.indexOf('name="theme-color"') && at > html.indexOf('apple-mobile-web-app-status-bar-style'));
  assert.ok(at < html.indexOf('</head>'));
  const expected = `sha256-${createHash('sha256').update(THEME_BOOT_SCRIPT, 'utf8').digest('base64')}`;
  assert.equal(THEME_BOOT_SCRIPT_HASH, expected, 'the CSP hash no longer matches the script');
  assert.ok(spaCsp().includes(`'${THEME_BOOT_SCRIPT_HASH}'`), 'the SPA policy does not allow the theme script');
  // The script and src/lib/theme.ts agree on the key, the default and the colours.
  assert.ok(THEME_BOOT_SCRIPT.includes(`'${THEME_STORAGE_KEY}'`));
  assert.ok(THEME_BOOT_SCRIPT.includes(THEME_COLOR.dark) && THEME_BOOT_SCRIPT.includes(THEME_COLOR.light));
  assert.equal(DEFAULT_THEME_PREFERENCE, 'light', 'no choice means the owner’s light design');
  assert.equal(resolveTheme('system', true), 'dark');
  assert.equal(resolveTheme('system', false), 'light');
  assert.equal(resolveTheme('dark', false), 'dark');
  // The shell's own ground before index.css arrives follows the theme too.
  assert.match(html, /html\[data-theme="dark"\], html\[data-theme="dark"\] body \{ background-color: #0b0c0f; \}/);
  assert.doesNotMatch(html, /<html[^>]*style="color-scheme: dark"/, 'the document is pinned dark again');
});

test('the built document carries the same script byte for byte (when a build exists)', (t) => {
  const built = join(ROOT, 'dist/index.html');
  if (!existsSync(built)) return t.skip('no dist/ — run npm run build');
  const html = readFileSync(built, 'utf8');
  if (!html.includes('data-theme')) return t.skip('dist/ predates the theme system — rebuild');
  assert.ok(html.includes(`<script>${THEME_BOOT_SCRIPT}</script>`), 'the build rewrote the inline script, so its hash no longer matches');
});

test('Settings offers the appearance, and it is wired to the theme store', () => {
  const settings = read('src/pages/Settings.tsx');
  assert.match(settings, /from '\.\.\/lib\/theme'/);
  assert.match(settings, /setThemePreference\(/);
  for (const v of ["'light'", "'dark'", "'system'"]) assert.ok(settings.includes(v), `the ${v} option is missing`);
  assert.ok(settings.includes('المظهر') && settings.includes('فاتح') && settings.includes('داكن') && settings.includes('حسب الجهاز'));
  const main = read('src/main.tsx');
  assert.match(main, /initTheme\(\)/, 'nothing follows the device or other tabs after the first paint');
});

test('a merchant storefront keeps its own theme inside a light app', () => {
  const block = currentBlock()!;
  assert.match(block, /\[data-store-theme\]\{color-scheme:dark;/, 'the storefront is not restored to its dark values');
  const sf = read('src/components/storefront/theme.css');
  assert.match(sf, /\[data-store-theme\]\s*\{/);
});
