-- ---------------------------------------------------------------------------
-- 0057 — the core's transactional outbox, its delivery ledger and the pump lock.
-- Owner: core (the legacy monolith, as a producer). 02-MIGRATION-PLAN.md slice
-- 1.6; the DDL is 03-EVENTS.md §2.1 verbatim, generated by the platform kit's
-- `outboxSchemaSql('core')` / `auditDetailsSchemaSql('core')` — tests/coreOutbox.test.ts
-- compares this file against those generators so the two can never drift.
-- ---------------------------------------------------------------------------
-- Numbering: the plan reserved `0056_core_outbox`; every reserved number moved
-- up one when `0055_option_color_names` was merged first (see the renumbering
-- note at the top of 02-MIGRATION-PLAN.md).
--
-- WHAT THIS IS FOR. An event that matters must be published if and only if the
-- business write that produced it committed. The only way to promise that on
-- one database is to write the event as a row IN THE SAME TRANSACTION as the
-- business rows — `bus.publishStatement()` returns exactly one statement, the
-- caller appends it to its own `db.batch()`, and a dispatcher (the cron pump,
-- plus a `waitUntil` pump for the ids a request just committed) delivers it
-- afterwards and records what each consumer acknowledged.
--
-- NOTHING HAPPENS UNTIL SOMEBODY TURNS IT ON. These tables are inert on
-- arrival: the emitters append no statement while `EVENT_BUS_ENABLED` is not
-- `on` (the default), and the pump delivers to nothing while no consumer
-- binding exists. The tables therefore ship, as the two-PR rule requires, well
-- before the code that fills them.
--
-- ADDITIVE. Four new tables, four indexes, `CREATE ... IF NOT EXISTS`
-- throughout: no existing table, column, row or index is touched. There is
-- deliberately NO seed row for `pump_lock` here — a migration that inserted
-- one would be the only non-CREATE statement in the file, and the lock row is
-- created idempotently by the pump itself on first use (worker/lib/eventBus.ts
-- `ensurePumpLock`), which also covers a database restored without it.

-- The outbox itself. `envelope` is the full signed JSON envelope
-- (03-EVENTS.md §1); `dispatched_at` is set once every subscriber has settled.
-- UNIQUE (aggregate_type, aggregate_id, aggregate_seq) is what lets a
-- projection apply "last sequence wins" and ignore a stale redelivery.
CREATE TABLE IF NOT EXISTS core_outbox_events (
  seq            INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id       TEXT NOT NULL UNIQUE,
  event_type     TEXT NOT NULL,
  version        INTEGER NOT NULL,
  aggregate_type TEXT NOT NULL,
  aggregate_id   TEXT NOT NULL,
  aggregate_seq  INTEGER NOT NULL,
  envelope       TEXT NOT NULL,
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  dispatched_at  TEXT,
  UNIQUE (aggregate_type, aggregate_id, aggregate_seq)
);
CREATE INDEX IF NOT EXISTS idx_core_outbox_pending ON core_outbox_events(dispatched_at) WHERE dispatched_at IS NULL;

-- One row per (event, consumer) in RPC mode: the dispatcher's memory of who
-- has acknowledged what, with the backoff schedule and the dead-letter state.
-- The DLQ is this table filtered by state, replayable through `redeliver`.
CREATE TABLE IF NOT EXISTS core_outbox_deliveries (
  event_id        TEXT NOT NULL,
  consumer        TEXT NOT NULL,
  attempts        INTEGER NOT NULL DEFAULT 0,
  state           TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending','acked','dead')),
  last_error      TEXT NOT NULL DEFAULT '',
  next_attempt_at TEXT NOT NULL,
  acked_at        TEXT,
  PRIMARY KEY (event_id, consumer)
);
CREATE INDEX IF NOT EXISTS idx_core_outbox_deliveries_due ON core_outbox_deliveries(state, next_attempt_at);

-- The cron sweep is the only lock holder, so two overlapping scheduled runs
-- cannot deliver the same event twice at the same moment. `locked_until` is a
-- lease, not a mutex: a run that dies without releasing it blocks nothing for
-- longer than the lease.
CREATE TABLE IF NOT EXISTS pump_lock (
  name         TEXT PRIMARY KEY,
  locked_until TEXT NOT NULL DEFAULT '1970-01-01T00:00:00.000Z',
  holder       TEXT NOT NULL DEFAULT ''
);

-- The audit body never travels in an envelope (03-EVENTS.md §4, D24): the
-- `audit()` facade writes it here, the pump hands it to Audit in the same
-- `deliver()` call, and acked rows are pruned within 24 h. `audit_log` itself
-- is untouched and keeps being written — this is a dual-write, not a move.
CREATE TABLE IF NOT EXISTS core_audit_details (
  id         TEXT PRIMARY KEY,
  event_id   TEXT NOT NULL UNIQUE,
  detail     TEXT NOT NULL,
  created_at TEXT NOT NULL
);
