-- ---------------------------------------------------------------------------
-- 0064 — the checkout idempotency key becomes unique PER USER.
-- Owner decision 11 (docs/BUNDLES_MYSTERY.md §17). Applied by workflow 7
-- BEFORE the code that writes the new column (two-PR rule, 02-MIGRATION-PLAN).
-- ---------------------------------------------------------------------------
-- THE DEFECT. `orders.idempotency_key` is globally UNIQUE (0001_init.sql:156)
-- while every lookup that reads it is scoped by user — `WHERE idempotency_key
-- = ? AND user_id = ?` at both checkout replay sites. So a key already spent
-- by ANOTHER account makes the INSERT fail, makes the replay lookup find
-- nothing, and drops the request into a generic "Order could not be placed",
-- for ever, for a key the attacker chooses. The client mints the key
-- (src/lib/api.ts newIdempotencyKey), so it is attacker-controlled input in a
-- globally-unique column: one account can permanently deny another's checkout.
--
-- WHY A NEW COLUMN AND NOT A REBUILT CONSTRAINT. The UNIQUE is declared inline
-- in `CREATE TABLE orders`, so SQLite materialises it as `sqlite_autoindex_
-- orders_2`, and an autoindex behind a UNIQUE constraint CANNOT be dropped
-- (`DROP INDEX` on it is refused by name). Removing it means rebuilding
-- `orders` — and `orders` is the root of a 38-table foreign-key closure whose
-- children cascade-delete on DROP, inside a migration D1 runs in ONE
-- transaction where `PRAGMA foreign_keys = OFF` is a documented no-op. 0018
-- refused to rebuild `users` for exactly this reason (0018:18-27). A rebuild
-- here is not a small migration; it is surgery on every order the store has
-- ever taken, to change one index. So the guarantee is delivered the way 0056
-- delivered the ledger keys: a new column plus its own unique index.
--
-- ADDITIVE AND UNUSED ON ARRIVAL. `client_idempotency_key` is NULLABLE, so
-- every existing order keeps NULL ("written before the column existed") and no
-- row is read, rewritten or deleted. The legacy column and its global UNIQUE
-- stay exactly as they are, holding every historical value; the new writers
-- bind NULL there, and SQLite permits unlimited NULLs in a UNIQUE column.
--
-- NULLABLE RATHER THAN NOT NULL DEFAULT '' — AND THAT IS A READ-PATH
-- DECISION, NOT A STYLE ONE. The first draft of this migration used `NOT NULL
-- DEFAULT ''` with a PARTIAL unique index (`WHERE client_idempotency_key <>
-- ''`) so that today's rows, all '', would not collide. It is a correct
-- constraint and a useless index: SQLite only uses a partial index when the
-- query's WHERE provably implies the index's WHERE, and `client_idempotency_key
-- = ?` cannot imply `<> ''` for a bound parameter. EXPLAIN QUERY PLAN on this
-- exact schema confirms it — the replay lookup fell back to
-- `SEARCH orders USING INDEX idx_orders_user_created (user_id=?)`, i.e. a walk
-- of every order that customer has ever placed, on every checkout, twice.
-- NULL solves both halves at once: SQLite treats NULLs as DISTINCT in a unique
-- index, so unlimited legacy rows per user are fine WITHOUT a partial
-- predicate, and the plain index is then usable — the same query plans as
-- `MULTI-INDEX OR / SEARCH orders USING INDEX idx_orders_user_idempotency
-- (user_id=? AND client_idempotency_key=?)`, a seek.
--
-- WHAT THE INDEX GUARANTEES. (user_id, client_idempotency_key) unique: the
-- same user retrying with the same key still collides and still replays their
-- own order; a different user carrying the identical key inserts cleanly.
ALTER TABLE orders ADD COLUMN client_idempotency_key TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_user_idempotency
  ON orders(user_id, client_idempotency_key);
