/**
 * Export manager (slice S7 — mandate §9).
 *
 * Owns the honest output model of LEVO Studio:
 *
 * 1. The MANDATORY distinction between the three output kinds — an editable
 *    3MF project, a MakerWorld/Bambu Studio print profile, and sliced G-code
 *    (or a `.gcode.3mf` printer package). Nothing is ever mislabeled:
 *    - the editable 3MF is real (the engine's own save path produces it and
 *      it is structurally verified here before being called "ready");
 *    - a print profile is DECLARED UNAVAILABLE: MakerWorld's profile check
 *      rejects files not generated by Bambu Studio (gap table §8), so the
 *      prepared file is offered as a model/project upload only;
 *    - `.gcode.3mf` packaging stays gated (studio/BAMBU_PRINT_PIPELINE.md);
 *    - raw G-code remains available as a SECONDARY/advanced action.
 *
 * 2. The four-step "تجهيز لـ MakerWorld" state machine (preflight → real 3MF
 *    preparation via the engine save path → transfers summary → official-path
 *    handoff). The machine has NO "uploaded" state on purpose: there is no
 *    sanctioned third-party MakerWorld upload API (verified secondarily; the
 *    three official references remained unreachable from the build network —
 *    see BAMBU_PRINT_PIPELINE.md), so the flow can only ever report
 *    "الملف جاهز" (file ready) and "فتح MakerWorld" (page opened) — never
 *    "تم الرفع".
 *
 * This module is dependency-free (type-only imports) so Node tests can load
 * it in isolation (tests/makerworld-flow.test.mjs). Browser wiring — the S4
 * engine adapter, anchor downloads, window.open — lives in
 * app/makerworld/prepare.tsx.
 *
 * Integration contract for the shell/orchestrator:
 * - wire `deps.engine.requestSave` to the S4 adapter's
 *   `runPrepareAction("save-project")`;
 * - forward the engine's `onExport(file, filename)` to
 *   `manager.handleViewportExport(file, filename)` BEFORE any autosave
 *   interception, and treat a `true` return as "consumed" (suppress the
 *   engine's own download);
 * - call `manager.invalidate("scene-edited")` from the adapter's onSceneEdit,
 *   `invalidate("settings-changed")` alongside
 *   useSlicingState.notifySettingsChanged, and
 *   `invalidate("profile-changed" | "project-switched" | "signed-out")` from
 *   the corresponding shell events, so a prepared file never survives edits
 *   it does not contain.
 */

import type { PreflightInput, PreflightReport } from "./makerworld/preflight";
import { runPreflight } from "./makerworld/preflight";

// ---------------------------------------------------------------------------
// Output kinds — the mandatory, honest classification
// ---------------------------------------------------------------------------

export type ExportKind = "editable-3mf" | "print-profile" | "gcode" | "gcode-3mf-package";

export interface ExportKindInfo {
  kind: ExportKind;
  /** Whether LEVO Studio can actually produce/use this kind today. */
  available: boolean;
  /** True only for the primary user-facing output action. */
  primary: boolean;
  /** Machine-readable reason for unavailability or demotion. */
  reason?:
    | "makerworld-rejects-non-bambu-studio-profiles"
    | "gated-until-golden-fixtures-pass"
    | "secondary-advanced-action";
}

/**
 * The single source of truth the UI must render output labels from. Honesty
 * invariants (tested):
 * - `editable-3mf` is the only primary kind;
 * - `print-profile` is unavailable with the MakerWorld/Bambu Studio reason;
 * - `gcode-3mf-package` stays gated per BAMBU_PRINT_PIPELINE.md;
 * - `gcode` is available but explicitly secondary.
 */
export const EXPORT_KINDS: readonly ExportKindInfo[] = [
  { kind: "editable-3mf", available: true, primary: true },
  { kind: "print-profile", available: false, primary: false, reason: "makerworld-rejects-non-bambu-studio-profiles" },
  { kind: "gcode", available: true, primary: false, reason: "secondary-advanced-action" },
  { kind: "gcode-3mf-package", available: false, primary: false, reason: "gated-until-golden-fixtures-pass" },
];

export function exportKindInfo(kind: ExportKind): ExportKindInfo {
  const info = EXPORT_KINDS.find((entry) => entry.kind === kind);
  // The table above is exhaustive over ExportKind.
  return info as ExportKindInfo;
}

/** Filename-based classification. `.gcode.3mf` is checked before `.3mf`. */
export function classifyExportFilename(filename: string): ExportKind | "unknown" {
  const name = filename.toLowerCase();
  if (name.endsWith(".gcode.3mf")) return "gcode-3mf-package";
  if (name.endsWith(".3mf")) return "editable-3mf";
  if (name.endsWith(".gcode")) return "gcode";
  return "unknown";
}

// ---------------------------------------------------------------------------
// Filenames
// ---------------------------------------------------------------------------

/** Keeps letters/digits/._- (any script), collapses the rest to "-". */
function sanitizeFileStem(stem: string): string {
  return stem
    .replace(/[^\p{L}\p{N}._-]+/gu, "-")
    .replace(/^-+|-+$/g, "");
}

/** Clear, honest name for the prepared MakerWorld project file. */
export function makerWorld3mfFilename(projectName: string, profileShortName: string): string {
  const safeProject = sanitizeFileStem(projectName.trim()) || "Project";
  const safeProfile = sanitizeFileStem(profileShortName.trim()) || "Printer";
  return `LEVO-${safeProject}-${safeProfile}.3mf`;
}

/** Secondary/advanced G-code download name (per plate). */
export function gcodeFilename(profileShortName: string, plateIndex: number): string {
  const safeProfile = sanitizeFileStem(profileShortName.trim()) || "Printer";
  return `LEVO-${safeProfile}-plate-${plateIndex + 1}.gcode`;
}

// ---------------------------------------------------------------------------
// Structural 3MF verification (ZIP central directory, no decompression)
// ---------------------------------------------------------------------------

export interface Editable3mfInspection {
  ok: boolean;
  reason?: "not-zip" | "truncated" | "no-content-types" | "no-model-part";
  entryCount: number;
  entryNames: string[];
  hasContentTypes: boolean;
  /** OPC part names matching 3D/*.model. */
  modelParts: string[];
  /** Orca/Bambu-style plate + per-object metadata (incl. extruder assignment). */
  hasModelSettings: boolean;
  /** Orca/Bambu-style global settings JSON. */
  hasProjectSettings: boolean;
  /** Any Metadata/*.png (the installed engine writes none — stays false). */
  hasThumbnail: boolean;
}

function readU16(bytes: Uint8Array, offset: number): number {
  return bytes[offset] | (bytes[offset + 1] << 8);
}

function readU32(bytes: Uint8Array, offset: number): number {
  return (bytes[offset] | (bytes[offset + 1] << 8) | (bytes[offset + 2] << 16)) + bytes[offset + 3] * 0x1000000;
}

const failedInspection = (
  reason: NonNullable<Editable3mfInspection["reason"]>,
  entryNames: string[] = [],
): Editable3mfInspection => ({
  ok: false,
  reason,
  entryCount: entryNames.length,
  entryNames,
  hasContentTypes: false,
  modelParts: [],
  hasModelSettings: false,
  hasProjectSettings: false,
  hasThumbnail: false,
});

/**
 * Verifies that `bytes` are a structurally valid 3MF package: a real ZIP whose
 * central directory lists `[Content_Types].xml` and at least one `3D/*.model`
 * part. This runs on every engine-saved file BEFORE it is labeled ready, so a
 * truncated or non-3MF blob is never handed to the user as a project file.
 *
 * Reads only the central directory (entry names/sizes) — entries stay
 * compressed, which keeps the check cheap and deterministic.
 */
export function inspectEditable3mf(bytes: Uint8Array): Editable3mfInspection {
  if (bytes.length < 22) return failedInspection("not-zip");
  // 3MF packages always contain entries, so they start with a local header.
  if (!(bytes[0] === 0x50 && bytes[1] === 0x4b && bytes[2] === 0x03 && bytes[3] === 0x04)) {
    return failedInspection("not-zip");
  }

  // End-of-central-directory: signature 0x06054b50 within the final 65557
  // bytes (max comment length + fixed EOCD size).
  let eocd = -1;
  const scanFloor = Math.max(0, bytes.length - 65557);
  for (let index = bytes.length - 22; index >= scanFloor; index -= 1) {
    if (bytes[index] === 0x50 && bytes[index + 1] === 0x4b && bytes[index + 2] === 0x05 && bytes[index + 3] === 0x06) {
      eocd = index;
      break;
    }
  }
  if (eocd < 0) return failedInspection("truncated");

  const declaredEntryCount = readU16(bytes, eocd + 10);
  const centralDirOffset = readU32(bytes, eocd + 16);
  if (centralDirOffset >= bytes.length) return failedInspection("truncated");

  const decoder = new TextDecoder();
  const entryNames: string[] = [];
  let position = centralDirOffset;
  for (let entry = 0; entry < declaredEntryCount; entry += 1) {
    if (position + 46 > bytes.length) return failedInspection("truncated", entryNames);
    if (!(bytes[position] === 0x50 && bytes[position + 1] === 0x4b && bytes[position + 2] === 0x01 && bytes[position + 3] === 0x02)) {
      return failedInspection("truncated", entryNames);
    }
    const nameLength = readU16(bytes, position + 28);
    const extraLength = readU16(bytes, position + 30);
    const commentLength = readU16(bytes, position + 32);
    if (position + 46 + nameLength > bytes.length) return failedInspection("truncated", entryNames);
    entryNames.push(decoder.decode(bytes.subarray(position + 46, position + 46 + nameLength)));
    position += 46 + nameLength + extraLength + commentLength;
  }

  const hasContentTypes = entryNames.includes("[Content_Types].xml");
  const modelParts = entryNames.filter((name) => /^3D\/[^/]+\.model$/i.test(name));
  const inspection: Editable3mfInspection = {
    ok: hasContentTypes && modelParts.length > 0,
    entryCount: entryNames.length,
    entryNames,
    hasContentTypes,
    modelParts,
    hasModelSettings: entryNames.includes("Metadata/model_settings.config"),
    hasProjectSettings: entryNames.includes("Metadata/project_settings.config"),
    hasThumbnail: entryNames.some((name) => /^Metadata\/.*\.png$/i.test(name)),
  };
  if (!inspection.ok) {
    inspection.reason = hasContentTypes ? "no-model-part" : "no-content-types";
  }
  return inspection;
}

// ---------------------------------------------------------------------------
// MakerWorld prepare state machine
// ---------------------------------------------------------------------------

export const MAKERWORLD_UPLOAD_URL = "https://makerworld.com/en/upload";

export const DEFAULT_SAVE_TIMEOUT_MS = 30_000;

/**
 * Every phase the machine can be in. There is intentionally NO "uploaded"
 * phase: opening the MakerWorld page is a handoff, not an upload, and no
 * sanctioned third-party upload API exists to confirm one.
 */
export const EXPORT_PHASES = [
  "idle",
  "blocked",
  "checked",
  "preparing",
  "failed",
  "file-ready",
  "handoff-opened",
] as const;

export type ExportPhase = (typeof EXPORT_PHASES)[number];

export type ExportFailureReason = "engine-unavailable" | "save-timeout" | "invalid-3mf";

export type InvalidationReason =
  | "scene-edited"
  | "settings-changed"
  | "profile-changed"
  | "project-switched"
  | "signed-out";

export interface PreparedFileSummary {
  filename: string;
  sizeBytes: number;
  inspection: Editable3mfInspection;
  preparedAt: number;
}

export interface ExportManagerState {
  phase: ExportPhase;
  /** Current step of the four-step flow (1 preflight, 2 prepare, 3 summary, 4 handoff). */
  step: 1 | 2 | 3 | 4;
  report: PreflightReport | null;
  failure: ExportFailureReason | null;
  /** Failed structural inspection details, when failure === "invalid-3mf". */
  failedInspection: Editable3mfInspection | null;
  file: PreparedFileSummary | null;
  handoffOpenedAt: number | null;
  invalidatedBy: InvalidationReason | null;
  /**
   * Always `false`. The manager cannot confirm an upload — MakerWorld offers
   * no sanctioned third-party upload API — and the type forbids ever claiming
   * one.
   */
  uploadConfirmed: false;
}

export function stepForPhase(phase: ExportPhase): 1 | 2 | 3 | 4 {
  switch (phase) {
    case "idle":
    case "blocked":
      return 1;
    case "checked":
    case "preparing":
    case "failed":
      return 2;
    case "file-ready":
      return 3;
    case "handoff-opened":
      return 4;
  }
}

export interface EngineSavePort {
  /**
   * Asks the engine to save the current project as a 3MF (the S4 adapter's
   * save-project action). Returns false (or resolves false) when the engine
   * is unavailable. The resulting file arrives asynchronously through
   * `handleViewportExport`.
   */
  requestSave(): boolean | Promise<boolean>;
}

export interface ExportManagerDeps {
  engine: EngineSavePort;
  /** Hands the verified, renamed 3MF to the user (browser: anchor download). */
  download: (file: File) => void;
  /** Opens the official MakerWorld upload page (browser: window.open). */
  openExternal: (url: string) => void;
  saveTimeoutMs?: number;
  now?: () => number;
}

export class MakerWorldExportManager {
  private readonly deps: ExportManagerDeps;
  private readonly listeners = new Set<() => void>();
  private state: ExportManagerState;
  private prepareToken = 0;
  private saveTimer: ReturnType<typeof setTimeout> | null = null;
  private projectName = "Project";
  private profileShortName = "Printer";

  constructor(deps: ExportManagerDeps) {
    this.deps = deps;
    this.state = this.freeze({
      phase: "idle",
      step: 1,
      report: null,
      failure: null,
      failedInspection: null,
      file: null,
      handoffOpenedAt: null,
      invalidatedBy: null,
      uploadConfirmed: false,
    });
  }

  // -- subscription (useSyncExternalStore-compatible) -----------------------

  subscribe = (listener: () => void): (() => void) => {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  };

  getState = (): ExportManagerState => this.state;

  // -- step 1: preflight ----------------------------------------------------

  /**
   * Runs the preflight and moves to `checked` or `blocked`. Discards any
   * previously prepared file — a new check starts a new flow.
   */
  runCheck(input: PreflightInput): PreflightReport {
    this.cancelPendingSave();
    this.profileShortName = input.profile.shortName || "Printer";
    const report = runPreflight(input);
    this.update({
      phase: report.ok ? "checked" : "blocked",
      report,
      failure: null,
      failedInspection: null,
      file: null,
      handoffOpenedAt: null,
      invalidatedBy: null,
    });
    return report;
  }

  // -- step 2: real 3MF preparation via the engine save path ----------------

  /**
   * Starts the engine's save-project path. Allowed only after a passing
   * preflight (`checked`), after a failure (retry), or from `file-ready`
   * (re-prepare). Returns false when refused.
   */
  prepare(naming?: { projectName?: string }): boolean {
    const { phase, report } = this.state;
    if (phase !== "checked" && phase !== "failed" && phase !== "file-ready") return false;
    if (!report?.ok) return false;
    if (naming?.projectName !== undefined) this.projectName = naming.projectName;

    const token = ++this.prepareToken;
    this.cancelSaveTimerOnly();
    this.update({
      phase: "preparing",
      failure: null,
      failedInspection: null,
      file: null,
      handoffOpenedAt: null,
    });

    let requested: boolean | Promise<boolean>;
    try {
      requested = this.deps.engine.requestSave();
    } catch {
      requested = false;
    }
    void Promise.resolve(requested).then((ok) => {
      if (token !== this.prepareToken || this.state.phase !== "preparing") return;
      if (!ok) {
        this.cancelSaveTimerOnly();
        this.update({ phase: "failed", failure: "engine-unavailable" });
      }
    }).catch(() => {
      if (token !== this.prepareToken || this.state.phase !== "preparing") return;
      this.cancelSaveTimerOnly();
      this.update({ phase: "failed", failure: "engine-unavailable" });
    });

    this.saveTimer = setTimeout(() => {
      this.saveTimer = null;
      if (token !== this.prepareToken || this.state.phase !== "preparing") return;
      this.update({ phase: "failed", failure: "save-timeout" });
    }, this.deps.saveTimeoutMs ?? DEFAULT_SAVE_TIMEOUT_MS);

    return true;
  }

  /**
   * The shell forwards every engine `onExport(file, filename)` here first.
   * Returns true when this manager consumed the file (a prepare is pending
   * and the file is a plain `.3mf` project — a `.gcode.3mf` package or a
   * G-code file is never mistaken for the editable project). The file is
   * verified structurally and only then downloaded and labeled ready.
   */
  handleViewportExport(file: Blob, filename: string): boolean {
    if (this.state.phase !== "preparing") return false;
    if (classifyExportFilename(filename) !== "editable-3mf") return false;

    const token = this.prepareToken;
    this.cancelSaveTimerOnly();

    void file.arrayBuffer().then((buffer) => {
      if (token !== this.prepareToken || this.state.phase !== "preparing") return;
      const bytes = new Uint8Array(buffer);
      const inspection = inspectEditable3mf(bytes);
      if (!inspection.ok) {
        this.update({ phase: "failed", failure: "invalid-3mf", failedInspection: inspection });
        return;
      }
      const outName = makerWorld3mfFilename(this.projectName, this.profileShortName);
      const outFile = new File([buffer], outName, { type: "model/3mf", lastModified: this.now() });
      this.deps.download(outFile);
      this.update({
        phase: "file-ready",
        failure: null,
        failedInspection: null,
        file: {
          filename: outName,
          sizeBytes: bytes.length,
          inspection,
          preparedAt: this.now(),
        },
      });
    }).catch(() => {
      if (token !== this.prepareToken || this.state.phase !== "preparing") return;
      this.update({ phase: "failed", failure: "invalid-3mf" });
    });

    return true;
  }

  // -- step 4: official-path handoff ----------------------------------------

  /**
   * Opens the official MakerWorld upload page via deps.openExternal, then
   * records the handoff. Only meaningful once the file is ready. NEVER
   * reports an upload — see `uploadConfirmed`.
   */
  openMakerWorld(): boolean {
    if (this.state.phase !== "file-ready" && this.state.phase !== "handoff-opened") return false;
    this.deps.openExternal(MAKERWORLD_UPLOAD_URL);
    this.markHandoffOpened();
    return true;
  }

  /**
   * Records that the upload page was opened without opening it (used when an
   * `<a target="_blank">` performed the navigation itself).
   */
  markHandoffOpened(): boolean {
    if (this.state.phase !== "file-ready" && this.state.phase !== "handoff-opened") return false;
    this.update({ phase: "handoff-opened", handoffOpenedAt: this.now() });
    return true;
  }

  // -- invalidation ----------------------------------------------------------

  /**
   * Any scene/settings/profile/account change after a check or prepare makes
   * the flow's outputs unrepresentative — drop them and return to idle. A
   * prepared file never survives edits it does not contain.
   */
  invalidate(reason: InvalidationReason): void {
    if (this.state.phase === "idle" && !this.state.report && !this.state.file) return;
    this.cancelPendingSave();
    this.update({
      phase: "idle",
      report: null,
      failure: null,
      failedInspection: null,
      file: null,
      handoffOpenedAt: null,
      invalidatedBy: reason,
    });
  }

  reset(): void {
    this.cancelPendingSave();
    this.update({
      phase: "idle",
      report: null,
      failure: null,
      failedInspection: null,
      file: null,
      handoffOpenedAt: null,
      invalidatedBy: null,
    });
  }

  // -- internals -------------------------------------------------------------

  private now(): number {
    return this.deps.now ? this.deps.now() : Date.now();
  }

  private cancelSaveTimerOnly(): void {
    if (this.saveTimer !== null) {
      clearTimeout(this.saveTimer);
      this.saveTimer = null;
    }
  }

  private cancelPendingSave(): void {
    this.prepareToken += 1;
    this.cancelSaveTimerOnly();
  }

  private freeze(state: Omit<ExportManagerState, "step"> & { step?: 1 | 2 | 3 | 4 }): ExportManagerState {
    return Object.freeze({ ...state, step: stepForPhase(state.phase) }) as ExportManagerState;
  }

  private update(patch: Partial<Omit<ExportManagerState, "step" | "uploadConfirmed">>): void {
    this.state = this.freeze({ ...this.state, ...patch, uploadConfirmed: false });
    for (const listener of [...this.listeners]) {
      try {
        listener();
      } catch {
        // A faulty subscriber must not break the state machine.
      }
    }
  }
}

export function createMakerWorldExportManager(deps: ExportManagerDeps): MakerWorldExportManager {
  return new MakerWorldExportManager(deps);
}
