/**
 * THE REQUEST PAGE'S WORDS — Arabic, English and Sorani, every key in all
 * three (docs/COMMUNITY_ECOSYSTEM.md D6: no Arabic standing in for Sorani).
 *
 * One table for /requests/:id (src/pages/community/Request.tsx), the offers
 * (OfferCompare, OfferComposer) and the discussion (Discussion.tsx). Figures
 * travel as `{n}`, `{name}`, `{price}` placeholders and are filled with `fill`
 * so a sentence is never assembled from fragments in one language's order.
 */
import { useLanguage } from '../../../LanguageContext';
import { createElement, Fragment, type ReactNode } from 'react';
import { dateLocale } from '../../orders/format';

export type RequestLang = 'ar' | 'en' | 'ckb';

const ar = {
  // ---- the page
  back: 'رجوع',
  kicker: 'طلب طباعة',
  by: 'من {name}',
  chosenMerchant: 'التاجر المختار: {name}',
  notFoundTitle: 'هذا الطلب لم يعد متاحًا',
  notFoundBody: 'ربما أُغلق، أو اختار صاحبه عرضًا، أو أن الرابط لا يخصك.',
  toBoard: 'إلى لوحة الطلبات',
  // ---- section headings
  files: 'الملفات',
  details: 'تفاصيل الطلب',
  discussion: 'النقاش',
  offers: 'العروض المقدّمة',
  yourOffer: 'عرضك',
  compare: 'مقارنة سريعة',
  chat: 'المحادثة',
  accepted: 'العرض المقبول',
  timeline: 'سير التنفيذ',
  escrow: 'المبلغ',
  delivery: 'التسليم والتواصل',
  review: 'قيّم الورشة',
  // ---- the status strip
  steps: {
    published: 'نُشر',
    offers: 'العروض',
    chosen: 'اختيار عرض',
    in_progress: 'التنفيذ',
    delivered: 'التسليم',
    completed: 'مكتمل',
  },
  statusDraft: 'مسودة — لا يراها التجار بعد',
  statusClosed: 'أُغلق الطلب ولا يقبل عروضًا',
  statusExpired: 'انتهت مهلة الطلب دون اختيار عرض',
  statusDisputed: 'نزاع مفتوح — المبلغ مجمّد حتى تفصل إدارة Levonis',
  // ---- the details
  budget: 'الميزانية',
  quantity: 'الكمية',
  material: 'المادة',
  colour: 'اللون',
  dimensions: 'الأبعاد',
  deadline: 'الموعد',
  governorate: 'المحافظة',
  publishedOn: 'نُشر',
  offersClose: 'آخر موعد للعروض',
  notesForMerchants: 'ملاحظات للتجار',
  editRequest: 'عدّل الطلب',
  closeRequest: 'أغلق الطلب',
  closeQ: 'إغلاق هذا الطلب؟',
  closeBody: 'يختفي من لوحة الطلبات ولا يُقبل عليه عرض بعد الآن، والعروض القائمة تُرفض. يبقى في «طلباتي» ملغى، مع ملفاته.',
  closing: 'جارٍ الإغلاق…',
  // ---- the draft card
  draftTitle: 'هذا الطلب مسودة',
  draftBody: 'لا يراه أي تاجر بعد. انشره ليصل إلى التجار الذين يستطيعون تنفيذه وتبدأ العروض بالوصول.',
  continueEditing: 'أكمل التعديل',
  discardDraft: 'إلغاء المسودة',
  discardQ: 'إلغاء هذه المسودة؟',
  discardBody: 'لن يُنشر هذا الطلب. يبقى في «طلباتي» ملغى، مع ملفاته.',
  discarding: 'جارٍ الإلغاء…',
  publish: 'نشر',
  couldNot: 'تعذّر إتمام العملية',
  // ---- the onlooker
  wantLikeThis: 'تريد شيئًا مثل هذا؟',
  askYourself: 'اطلبه أنت، وتصلك عروض التجار الذين يستطيعون صنعه.',
  askLikeIt: 'اطلب مثله',
  signInAndAsk: 'سجّل الدخول واطلب',
  printForOthers: 'تطبع لغيرك؟ العروض تُقدَّم من متجر على Levonis.',
  openYourStore: 'افتح متجرك',
  aboutPlus: 'اعرف عن PLUS والمتاجر',
  // ---- the customer's offers
  noOffersYet: 'لا عروض بعد. نُعلمك حين يصل أول عرض.',
  sortOffers: 'ترتيب العروض',
  sortPrice: 'الأقل إجمالًا',
  sortTime: 'الأسرع',
  sortRating: 'الأعلى تقييمًا',
  price: 'السعر',
  noFee: 'بلا رسوم',
  total: 'الإجمالي',
  completion: 'التنفيذ',
  handover: 'التسليم',
  materials: 'المواد',
  included: 'يشمل',
  warranty: 'الضمان',
  terms: 'الشروط',
  validUntil: 'صالح حتى',
  openEnded: 'مفتوح',
  offerFiles: 'ملفات العرض',
  revised: 'عرض معدّل',
  was: 'كان {price}',
  history: 'سجل التعديلات',
  version: 'النسخة {n}',
  staleNote: 'عدّلتَ الطلب بعد هذا العرض، فهو بانتظار أن يؤكده التاجر من جديد.',
  unableNote: 'هذه الورشة لم تعد قادرة على تنفيذ الطلب',
  acceptOffer: 'اقبل العرض',
  decline: 'اعتذر',
  askMerchant: 'اسأل التاجر',
  viewStore: 'زيارة المتجر',
  declineQ: 'الاعتذار عن هذا العرض؟',
  declineBody: 'سيُبلَّغ {name} أنك لم تختر عرضه.',
  theMerchant: 'التاجر',
  couldNotDecline: 'تعذّر الاعتذار عن العرض',
  couldNotOpenChat: 'تعذّر فتح المحادثة',
  verified: 'موثّق',
  // ---- the acceptance sheet
  acceptQ: 'قبول هذا العرض؟',
  acceptAndHold: 'اقبل واحجز المبلغ',
  acceptNewTerms: 'اقبل الشروط الجديدة',
  notNow: 'ليس الآن',
  holding: 'جارٍ حجز المبلغ…',
  refresh: 'حدّث',
  heldExplain: 'يُحجز الإجمالي من رصيدك الآن، ولا يُدفع للتاجر إلا بعد تأكيدك للاستلام.',
  deliveryAddress: 'عنوان التسليم',
  noAddress: 'لا عنوان محفوظ — سيصل للتاجر اسمك ورقمك، ويتفق معك على التسليم.',
  addAddress: 'أضف عنوانًا',
  contactConsent: 'عند القبول يصل إلى {name} اسمك ورقمك{address}، ويصلك رقم متجره. لا يصل شيء منها لأي تاجر آخر.',
  andAddress: ' وعنوان التسليم',
  topUp: 'اشحن المحفظة',
  couldNotAccept: 'تعذّر قبول العرض',
  unableAccept: 'هذه الورشة لم تعد قادرة على تنفيذ الطلب — اختر عرضًا آخر.',
  inDays: 'خلال {days}',
  // ---- the quick comparison
  cheapest: 'الأقل إجمالًا',
  fastest: 'الأسرع',
  topRated: 'الأعلى تقييمًا',
  noRatingYet: 'بلا تقييم بعد',
  // ---- the merchant's side
  makeOffer: 'قدّم عرضًا',
  cannotOfferNow: 'لا يمكنك تقديم عرض على هذا الطلب الآن.',
  previousOffer: 'عرضك السابق:',
  yourOfferVersion: 'عرضك — النسخة {n}',
  draftSaved: 'مسودة محفوظة',
  draftHint: 'لا يراها العميل حتى ترسلها.',
  continueDraft: 'أكمل المسودة',
  sendDraft: 'أرسل العرض',
  sending: 'جارٍ الإرسال…',
  reconfirm: 'أؤكد عرضي كما هو',
  editOffer: 'عدّل العرض',
  messageCustomer: 'راسل الزبون',
  withdraw: 'اسحب',
  withdrawQ: 'سحب عرضك؟',
  withdrawBody: 'لن يستطيع الزبون قبوله. يمكنك تقديم عرض جديد ما دام الطلب يستقبل العروض.',
  withdrawLabel: 'اسحب العرض',
  couldNotWithdraw: 'تعذّر سحب العرض',
  reconfirmed: 'أكّدت عرضك للطلب بصيغته الحالية.',
  couldNotReconfirm: 'تعذّر تأكيد العرض',
  staleMerchantNote: 'عدّل الزبون الطلب بعد عرضك، فلا يمكن قبوله حتى تؤكده أو تعدّله.',
  whatChanged: 'ما الذي تغيّر: ',
  offerSent: 'أُرسل عرضك.',
  offerUpdated: 'حُدّث عرضك — يراه الزبون كنسخة جديدة.',
  draftKept: 'حُفظت المسودة.',
  acceptedByCustomer: 'قبِل العميل عرضك — التنفيذ بدأ من هنا.',
  youChose: 'اخترت عرض {name}.',
  // ---- the composer
  composeTitle: 'قدّم عرضك',
  editTitle: 'تعديل عرضك',
  draftComposeTitle: 'مسودة عرضك',
  editHint: 'يرى الزبون التعديل نسخةً جديدة، ويبقى السعر السابق في السجل.',
  priceRequired: 'اكتب سعرك بالدينار.',
  daysRequired: 'كم يومًا يحتاج التنفيذ؟',
  feeLabel: 'رسوم التوصيل',
  feeHint: 'تُضاف إلى السعر، ويراها العميل ضمن الإجمالي.',
  quantityLabel: 'الكمية',
  quantityHint: 'ما يشمله هذا السعر.',
  upToFive: '— حتى 5',
  colourLabel: 'اللون',
  colourPh: 'مثل: أسود مطفي',
  notesLabel: 'رسالة للزبون',
  includedLabel: 'يشمل العرض',
  includedHint: 'مثل: صنفرة، طلاء أساس، تغليف.',
  warrantyLabel: 'الضمان',
  warrantyHint: 'مثل: إعادة الطباعة إن انكسرت خلال 30 يومًا.',
  termsLabel: 'الشروط',
  termsHint: 'ما يجب أن يعرفه العميل قبل القبول: دفعة، تعديلات، حدود.',
  validityLabel: 'يبقى العرض قائمًا',
  filesLabel: 'ملفات العرض',
  // Review 2026-09-30: an offer's model has no viewer yet — the requester downloads it as it is, before accepting; say so.
  filesHint: 'صور أو PDF أو مجسم — حتى 6 ملفات، لا يراها إلا صاحب الطلب، ويستطيع تنزيلها كما هي قبل أن يقبل العرض.',
  addFile: 'أضف ملفًا',
  removeFile: 'إزالة {name}',
  fileTooMany: 'الحد الأقصى 6 ملفات.',
  fileKindBad: 'صورة أو PDF أو ملف مجسم فقط.',
  totalLine: 'الإجمالي الذي يراه العميل',
  saveDraft: 'احفظ مسودة',
  sendOffer: 'أرسل العرض',
  saveNewVersion: 'احفظ النسخة الجديدة',
  fixedNote: 'بعد قبول الزبون لا يتغير السعر ولا المدة. يُحجز المبلغ لدى Levonis ويُحرَّر لك بعد تأكيد الاستلام.',
  couldNotSend: 'تعذّر الإرسال',
  couldNotSave: 'تعذّر الحفظ',
  deliverMyself: 'أوصله',
  courier: 'شركة توصيل',
  pickup: 'استلام',
  // ---- the discussion
  noComments: 'لا نقاش بعد',
  noCommentsHint: 'اسأل، أو اكتب ملاحظة يراها الجميع.',
  writeComment: 'اكتب تعليقًا',
  askCustomer: 'اسأل صاحب الطلب',
  kindComment: 'تعليق',
  kindQuestion: 'سؤال للعميل',
  question: 'سؤال',
  answer: 'أجب',
  answerLabel: 'جواب صاحب الطلب',
  reply: 'ردّ',
  send: 'إرسال',
  signInToComment: 'سجّل الدخول لتشارك في النقاش.',
  signIn: 'تسجيل الدخول',
  remove: 'حذف',
  removeQ: 'حذف هذا التعليق؟',
  removeBody: 'يختفي من النقاش ولا يمكن استرجاعه.',
  report: 'إبلاغ',
  reportTitle: 'الإبلاغ عن التعليق',
  reportSend: 'أرسل البلاغ',
  reported: 'وصل بلاغك. شكرًا.',
  reasons: {
    spam: 'إزعاج أو إعلان',
    abuse: 'إساءة',
    nudity: 'محتوى غير لائق',
    fraud: 'احتيال',
    copyright: 'انتهاك حقوق',
    offtopic: 'خارج الموضوع',
    other: 'سبب آخر',
  },
  roleCustomer: 'صاحب الطلب',
  roleMerchant: 'ورشة',
  cancel: 'إلغاء',
  replyingTo: 'ردّ على {name}',
  answering: 'جواب على سؤال {name}',
  closedForComments: 'أُغلق النقاش مع الطلب.',
  system: {
    revised: 'عُدّل الطلب — النسخة {n}',
    accepted: 'اختار صاحب الطلب عرضًا',
    cancelled: 'أُغلق الطلب',
    completed: 'اكتمل التنفيذ',
    expired: 'انتهت مهلة الطلب',
    disputed: 'فُتح نزاع على التنفيذ',
    republished: 'أُعيد نشر الطلب',
  },
  tooLong: 'التعليق أطول من المسموح.',
  commentPosted: 'نُشرت رسالتك في النقاش.',
  actionFailed: 'تعذّر تنفيذ الإجراء.',
  options: 'خيارات',
  moreComments: 'المزيد من النقاش',
  // ---- the chat door
  openConversation: 'افتح المحادثة',
  chatWithMerchant: 'تحدّث مع التاجر عن التفاصيل قبل القبول أو بعده.',
  chatWithCustomer: 'تحدّث مع الزبون عن التفاصيل.',
  // ---- the timeline peek
  lastUpdate: 'آخر تحديث',
  noUpdatesYet: 'لا تحديثات بعد — تظهر هنا خطوات التنفيذ أولًا بأول.',
  updatesFailed: 'تعذّر تحميل التحديثات.',
  updatesRetry: 'أعد المحاولة',
  openTimeline: 'سير التنفيذ كاملًا',
  // ---- the money
  escrowPending: 'بانتظار حجز المبلغ.',
  escrowHeld: 'محجوز لدى Levonis حتى تأكيد الاستلام.',
  escrowReleased: 'حُوّل المبلغ إلى التاجر.',
  escrowRefunded: 'أُعيد المبلغ إلى رصيد العميل.',
  escrowDisputed: 'المبلغ مجمّد حتى تفصل إدارة Levonis في النزاع.',
  escrowCancelled: 'أُلغي الحجز.',
  youReceive: 'يصلك بعد العمولة: {amount}',
  autoConfirms: 'يتأكد تلقائيًا في {date}',
  // ---- the delivery
  contactCustomer: 'الزبون — للتواصل والتسليم',
  contactMerchant: 'التاجر — للتواصل',
  noPhone: 'لا رقم مسجّل — تواصل عبر المحادثة.',
  collectsFromWorkshop: 'يستلمه بنفسه من ورشتك',
  noAddressAsk: 'لا عنوان محفوظ — اسأله في المحادثة.',
  talkInChat: 'تواصلا عبر محادثة الطلب.',
  // ---- the customer's own controls after acceptance
  changes: {
    quantity: 'الكمية',
    source_type: 'مصدر الطلب',
    process: 'طريقة الطباعة',
    material_id: 'المادة',
    color_hex: 'اللون',
    color_name: 'اللون',
    quality: 'الدقة',
    infill_percent: 'الحشوة',
    supports: 'الدعامات',
    colors_count: 'عدد الألوان',
    post_processing_minutes: 'التشطيب',
    primary_file_id: 'الملف',
    source_url: 'الرابط',
    stated_dims: 'المقاس',
    governorate: 'المحافظة',
    delivery_pref: 'الاستلام',
    deadline: 'الموعد',
    customer_notes: 'الملاحظات',
    file_ids: 'المرفقات',
  },
  // ---- Phase 5c, the page's second pass (Request.tsx, Discussion.tsx)
  status: 'الحالة',
  saving: 'جارٍ الحفظ…',
  publishing: 'جارٍ النشر…',
  daysUnit: 'يوم',
  yourDraft: 'مسودة عرضك',
  feeShort: 'توصيل',
  stateOpen: 'قائم',
  stateAwaiting: 'بانتظار التاجر',
  stateExpired: 'منتهي الصلاحية',
  stateNotChosen: 'لم يُختر',
  stateWithdrawn: 'مسحوب',
  stateAccepted: 'مقبول',
  stateDraft: 'مسودة',
  commentKindLabel: 'نوع المشاركة',
  reportReason: 'سبب البلاغ',
  systemRevisedPlain: 'عُدّل الطلب',
  escrowPartial: 'أُعيد جزء من المبلغ إلى رصيد العميل.',
  view3dOf: 'عرض {name} ثلاثي الأبعاد',
  couldNotOpenViewer: 'تعذّر فتح العرض ثلاثي الأبعاد',
  orderStates: {
    accepted: 'مقبول',
    funded: 'بانتظار بدء العمل',
    in_progress: 'قيد التنفيذ',
    merchant_marked_delivered: 'سلّم التاجر — بانتظار التأكيد',
    customer_confirmed: 'أكّد العميل الاستلام',
    completed: 'مكتمل',
    disputed: 'نزاع مفتوح',
    cancelled: 'ملغى',
    refunded: 'مسترجع',
  },
  confirmFromOrders: 'حين يصلك العمل، أكّد الاستلام من «تنفيذ طلباتي».',
  loadingRequest: 'جارٍ تحميل الطلب…',
  reviewThanks: 'شكرًا — تقييمك يظهر في صفحة المتجر.',
  handoverMerchant: 'يوصله التاجر',
  handoverCourier: 'عبر شركة توصيل',
  handoverPickup: 'استلام من الورشة',
  stepOf: 'الخطوة {n} من {total}: {label}',
  myCustomOrders: 'تنفيذ طلباتي',
  merchantOrders: 'طلبات التنفيذ',
};

const en: typeof ar = {
  back: 'Back',
  kicker: 'Print request',
  by: 'From {name}',
  chosenMerchant: 'Chosen merchant: {name}',
  notFoundTitle: 'That request is no longer available',
  notFoundBody: 'It may have closed, an offer may have been accepted, or the link is not yours.',
  toBoard: 'To the request board',
  files: 'Files',
  details: 'Request details',
  discussion: 'Discussion',
  offers: 'Offers received',
  yourOffer: 'Your offer',
  compare: 'Quick comparison',
  chat: 'Conversation',
  accepted: 'Accepted offer',
  timeline: 'Progress',
  escrow: 'The money',
  delivery: 'Handover and contact',
  review: 'Rate the workshop',
  steps: {
    published: 'Published',
    offers: 'Offers',
    chosen: 'Offer chosen',
    in_progress: 'In progress',
    delivered: 'Delivered',
    completed: 'Completed',
  },
  statusDraft: 'Draft — no merchant can see it yet',
  statusClosed: 'The request is closed and takes no offers',
  statusExpired: 'The request expired without a chosen offer',
  statusDisputed: 'A dispute is open — the money is frozen until Levonis decides',
  budget: 'Budget',
  quantity: 'Quantity',
  material: 'Material',
  colour: 'Colour',
  dimensions: 'Dimensions',
  deadline: 'Deadline',
  governorate: 'Governorate',
  publishedOn: 'Published',
  offersClose: 'Offers close',
  notesForMerchants: 'Notes for merchants',
  editRequest: 'Edit request',
  closeRequest: 'Close the request',
  closeQ: 'Close this request?',
  closeBody: 'It leaves the request board and takes no more offers; the standing offers are declined. It stays in “My requests” as cancelled, with its files.',
  closing: 'Closing…',
  draftTitle: 'This request is a draft',
  draftBody: 'No merchant can see it yet. Publish it to reach the merchants who can make it and start receiving offers.',
  continueEditing: 'Continue editing',
  discardDraft: 'Discard draft',
  discardQ: 'Discard this draft?',
  discardBody: 'This request will not be published. It stays in “My requests” as cancelled, with its files.',
  discarding: 'Discarding…',
  publish: 'Publish',
  couldNot: 'Could not complete that',
  wantLikeThis: 'Want something like this?',
  askYourself: 'Ask for it yourself, and get offers from the merchants who can make it.',
  askLikeIt: 'Ask for one like it',
  signInAndAsk: 'Sign in and ask',
  printForOthers: 'You print for others? Offers are made from a store on Levonis.',
  openYourStore: 'Open your store',
  aboutPlus: 'About PLUS and stores',
  noOffersYet: 'No offers yet. We will tell you when the first one arrives.',
  sortOffers: 'Sort offers',
  sortPrice: 'Lowest total',
  sortTime: 'Fastest',
  sortRating: 'Top rated',
  price: 'Price',
  noFee: 'No fee',
  total: 'Total',
  completion: 'Completion',
  handover: 'Handover',
  materials: 'Materials',
  included: 'Included',
  warranty: 'Warranty',
  terms: 'Terms',
  validUntil: 'Valid until',
  openEnded: 'Open-ended',
  offerFiles: 'Offer files',
  revised: 'Revised offer',
  was: 'Was {price}',
  history: 'Revision history',
  version: 'Version {n}',
  staleNote: 'You changed the request after this offer, so it waits for the merchant to re-confirm it.',
  unableNote: 'This workshop can no longer make this request',
  acceptOffer: 'Accept offer',
  decline: 'Decline',
  askMerchant: 'Ask the merchant',
  viewStore: 'View store',
  declineQ: 'Decline this offer?',
  declineBody: '{name} will be told you did not choose it.',
  theMerchant: 'The merchant',
  couldNotDecline: 'Could not decline the offer',
  couldNotOpenChat: 'Could not open the conversation',
  verified: 'Verified',
  acceptQ: 'Accept this offer?',
  acceptAndHold: 'Accept and hold the money',
  acceptNewTerms: 'Accept the new terms',
  notNow: 'Not now',
  holding: 'Holding the money…',
  refresh: 'Refresh',
  heldExplain: 'The total is held from your balance now; the merchant is paid only after you confirm delivery.',
  deliveryAddress: 'Delivery address',
  noAddress: 'No saved address — the merchant receives your name and phone and arranges the handover with you.',
  addAddress: 'Add an address',
  contactConsent: 'On acceptance {name} receives your name and phone{address}, and you receive the store’s phone. No other merchant receives any of it.',
  andAddress: ' and the delivery address',
  topUp: 'Top up the wallet',
  couldNotAccept: 'Could not accept the offer',
  unableAccept: 'This workshop can no longer make this request — choose another offer.',
  inDays: 'In {days}',
  cheapest: 'Lowest total',
  fastest: 'Fastest',
  topRated: 'Top rated',
  noRatingYet: 'No rating yet',
  makeOffer: 'Make an offer',
  cannotOfferNow: 'You cannot make an offer on this request now.',
  previousOffer: 'Your previous offer:',
  yourOfferVersion: 'Your offer — version {n}',
  draftSaved: 'Draft saved',
  draftHint: 'The customer cannot see it until you send it.',
  continueDraft: 'Continue the draft',
  sendDraft: 'Send the offer',
  sending: 'Sending…',
  reconfirm: 'Re-confirm as is',
  editOffer: 'Edit offer',
  messageCustomer: 'Message the customer',
  withdraw: 'Withdraw',
  withdrawQ: 'Withdraw your offer?',
  withdrawBody: 'The customer can no longer accept it. You can make a new offer while the request takes offers.',
  withdrawLabel: 'Withdraw offer',
  couldNotWithdraw: 'Could not withdraw the offer',
  reconfirmed: 'You re-confirmed your offer for the request as it is now.',
  couldNotReconfirm: 'Could not re-confirm the offer',
  staleMerchantNote: 'The customer changed the request after your offer; it cannot be accepted until you re-confirm or edit it.',
  whatChanged: 'What changed: ',
  offerSent: 'Your offer was sent.',
  offerUpdated: 'Offer updated — the customer sees it as a new version.',
  draftKept: 'Draft saved.',
  acceptedByCustomer: 'The customer accepted your offer — the work starts here.',
  youChose: 'You chose the offer from {name}.',
  composeTitle: 'Make your offer',
  editTitle: 'Edit your offer',
  draftComposeTitle: 'Your draft offer',
  editHint: 'The customer sees the edit as a new version; the old price stays in its history.',
  priceRequired: 'Enter your price in dinars.',
  daysRequired: 'How many days will it take?',
  feeLabel: 'Delivery fee',
  feeHint: 'Added to the price; the customer sees it inside the total.',
  quantityLabel: 'Quantity',
  quantityHint: 'What this price covers.',
  upToFive: '— up to 5',
  colourLabel: 'Colour',
  colourPh: 'e.g. matte black',
  notesLabel: 'Message to the customer',
  includedLabel: 'Included',
  includedHint: 'e.g. sanding, primer, packaging.',
  warrantyLabel: 'Warranty',
  warrantyHint: 'e.g. a reprint if it cracks within 30 days.',
  termsLabel: 'Terms',
  termsHint: 'What the customer should know before accepting: deposit, changes, limits.',
  validityLabel: 'Offer stands for',
  filesLabel: 'Offer files',
  filesHint: 'Pictures, a PDF or a model — up to 6, seen only by the requester, who can download them as they are before accepting.',
  addFile: 'Add a file',
  removeFile: 'Remove {name}',
  fileTooMany: 'At most 6 files.',
  fileKindBad: 'A picture, a PDF or a model file only.',
  totalLine: 'Total the customer sees',
  saveDraft: 'Save draft',
  sendOffer: 'Send offer',
  saveNewVersion: 'Save the new version',
  fixedNote: 'Once the customer accepts, the price and timeline are fixed. Levonis holds the money and releases it to you when delivery is confirmed.',
  couldNotSend: 'Could not send',
  couldNotSave: 'Could not save',
  deliverMyself: 'I deliver',
  courier: 'Courier',
  pickup: 'Pickup',
  noComments: 'No discussion yet',
  noCommentsHint: 'Ask a question, or leave a note everyone can read.',
  writeComment: 'Write a comment',
  askCustomer: 'Ask the requester',
  kindComment: 'Comment',
  kindQuestion: 'Question for the customer',
  question: 'Question',
  answer: 'Answer',
  answerLabel: 'The requester’s answer',
  reply: 'Reply',
  send: 'Send',
  signInToComment: 'Sign in to join the discussion.',
  signIn: 'Sign in',
  remove: 'Remove',
  removeQ: 'Remove this comment?',
  removeBody: 'It leaves the discussion and cannot be restored.',
  report: 'Report',
  reportTitle: 'Report this comment',
  reportSend: 'Send report',
  reported: 'Your report was received. Thank you.',
  reasons: {
    spam: 'Spam or advertising',
    abuse: 'Abuse',
    nudity: 'Inappropriate content',
    fraud: 'Fraud',
    copyright: 'Copyright violation',
    offtopic: 'Off topic',
    other: 'Something else',
  },
  roleCustomer: 'Requester',
  roleMerchant: 'Workshop',
  cancel: 'Cancel',
  replyingTo: 'Replying to {name}',
  answering: 'Answering {name}’s question',
  closedForComments: 'The discussion closed with the request.',
  system: {
    revised: 'The request was edited — version {n}',
    accepted: 'The requester chose an offer',
    cancelled: 'The request was closed',
    completed: 'The work was completed',
    expired: 'The request expired',
    disputed: 'A dispute was opened on the work',
    republished: 'The request was republished',
  },
  tooLong: 'The comment is longer than allowed.',
  commentPosted: 'Your message is in the discussion.',
  actionFailed: 'Could not do that.',
  options: 'Options',
  moreComments: 'More of the discussion',
  openConversation: 'Open conversation',
  chatWithMerchant: 'Talk to the merchant about the details, before or after accepting.',
  chatWithCustomer: 'Talk to the customer about the details.',
  lastUpdate: 'Last update',
  noUpdatesYet: 'No updates yet — the steps of the work appear here as they happen.',
  updatesFailed: 'The updates could not be loaded.',
  updatesRetry: 'Try again',
  openTimeline: 'Full progress',
  escrowPending: 'Waiting for the money to be held.',
  escrowHeld: 'Held by Levonis until receipt is confirmed.',
  escrowReleased: 'The money was released to the merchant.',
  escrowRefunded: 'The money was returned to the customer’s balance.',
  escrowDisputed: 'The money is frozen until Levonis decides the dispute.',
  escrowCancelled: 'The hold was cancelled.',
  youReceive: 'You receive after the fee: {amount}',
  autoConfirms: 'Auto-confirms on {date}',
  contactCustomer: 'The customer — contact and delivery',
  contactMerchant: 'The merchant — contact',
  noPhone: 'No phone on file — use the conversation.',
  collectsFromWorkshop: 'Collects it from your workshop',
  noAddressAsk: 'No saved address — ask in the conversation.',
  talkInChat: 'Talk through the request conversation.',
  changes: {
    quantity: 'quantity',
    source_type: 'source',
    process: 'process',
    material_id: 'material',
    color_hex: 'colour',
    color_name: 'colour',
    quality: 'detail',
    infill_percent: 'infill',
    supports: 'supports',
    colors_count: 'colours',
    post_processing_minutes: 'finishing',
    primary_file_id: 'model file',
    source_url: 'link',
    stated_dims: 'size',
    governorate: 'governorate',
    delivery_pref: 'handover',
    deadline: 'deadline',
    customer_notes: 'notes',
    file_ids: 'attachments',
  },
  // ---- Phase 5c, the page's second pass (Request.tsx, Discussion.tsx)
  status: 'Status',
  saving: 'Saving…',
  publishing: 'Publishing…',
  daysUnit: 'days',
  yourDraft: 'Your draft offer',
  feeShort: 'delivery',
  stateOpen: 'Open',
  stateAwaiting: 'Awaiting the merchant',
  stateExpired: 'Expired',
  stateNotChosen: 'Not chosen',
  stateWithdrawn: 'Withdrawn',
  stateAccepted: 'Accepted',
  stateDraft: 'Draft',
  commentKindLabel: 'What you are writing',
  reportReason: 'Reason',
  systemRevisedPlain: 'The request was edited',
  escrowPartial: 'Part of the money was returned to the customer’s balance.',
  view3dOf: 'View {name} in 3D',
  couldNotOpenViewer: 'Could not open the 3D view',
  orderStates: {
    accepted: 'Accepted',
    funded: 'Waiting for the work to start',
    in_progress: 'In progress',
    merchant_marked_delivered: 'Delivered — awaiting confirmation',
    customer_confirmed: 'Receipt confirmed',
    completed: 'Completed',
    disputed: 'Disputed',
    cancelled: 'Cancelled',
    refunded: 'Refunded',
  },
  confirmFromOrders: 'When the work reaches you, confirm receipt from “My custom orders”.',
  loadingRequest: 'Loading the request…',
  reviewThanks: 'Thank you — your rating shows on the store’s page.',
  handoverMerchant: 'The merchant delivers',
  handoverCourier: 'By courier',
  handoverPickup: 'Collected from the workshop',
  stepOf: 'Step {n} of {total}: {label}',
  myCustomOrders: 'My custom orders',
  merchantOrders: 'Custom orders',
};

const ckb: typeof ar = {
  back: 'گەڕانەوە',
  kicker: 'داواکاری چاپکردن',
  by: 'لە {name}',
  chosenMerchant: 'بازرگانی هەڵبژێردراو: {name}',
  notFoundTitle: 'ئەم داواکاریە ئیتر بەردەست نییە',
  notFoundBody: 'لەوانەیە داخرابێت، یان خاوەنەکەی ئۆفەرێکی هەڵبژاردبێت، یان لینکەکە هی تۆ نەبێت.',
  toBoard: 'بۆ بۆردی داواکاریەکان',
  files: 'فایلەکان',
  details: 'وردەکاریەکانی داواکاری',
  discussion: 'گفتوگۆ',
  offers: 'ئۆفەرە وەرگیراوەکان',
  yourOffer: 'ئۆفەرەکەت',
  compare: 'بەراوردی خێرا',
  chat: 'گفتوگۆی تایبەت',
  accepted: 'ئۆفەری قبوڵکراو',
  timeline: 'ڕەوتی جێبەجێکردن',
  escrow: 'پارەکە',
  delivery: 'گەیاندن و پەیوەندی',
  review: 'وۆرکشۆپەکە هەڵسەنگێنە',
  steps: {
    published: 'بڵاوکرایەوە',
    offers: 'ئۆفەرەکان',
    chosen: 'هەڵبژاردنی ئۆفەر',
    in_progress: 'جێبەجێکردن',
    delivered: 'گەیاندن',
    completed: 'تەواو',
  },
  statusDraft: 'ڕەشنووس — هێشتا هیچ بازرگانێک نایبینێت',
  statusClosed: 'داواکاریەکە داخرا و ئۆفەر وەرناگرێت',
  statusExpired: 'ماوەی داواکاریەکە تەواو بوو بەبێ هەڵبژاردنی ئۆفەر',
  statusDisputed: 'ناکۆکی کراوەیە — پارەکە بەستراوە تا بەڕێوەبەرایەتی Levonis بڕیار دەدات',
  budget: 'بودجە',
  quantity: 'بڕ',
  material: 'ماددە',
  colour: 'ڕەنگ',
  dimensions: 'ڕەهەندەکان',
  deadline: 'کاتی کۆتایی',
  governorate: 'پارێزگا',
  publishedOn: 'بڵاوکرایەوە',
  offersClose: 'دوا وادە بۆ ئۆفەرەکان',
  notesForMerchants: 'تێبینی بۆ بازرگانەکان',
  editRequest: 'داواکاریەکە دەستکاری بکە',
  closeRequest: 'داواکاریەکە دابخە',
  closeQ: 'ئەم داواکاریە دابخرێت؟',
  closeBody: 'لە بۆردی داواکاریەکان نامێنێت و ئیتر ئۆفەر وەرناگرێت، ئۆفەرە بەردەستەکانیش ڕەت دەکرێنەوە. لە «داواکاریەکانم» وەک هەڵوەشێنراوە دەمێنێتەوە، لەگەڵ فایلەکانی.',
  closing: 'دادەخرێت…',
  draftTitle: 'ئەم داواکاریە ڕەشنووسە',
  draftBody: 'هێشتا هیچ بازرگانێک نایبینێت. بڵاوی بکەرەوە تا بگاتە ئەو بازرگانانەی دەتوانن جێبەجێی بکەن و ئۆفەرەکان دەست بکەن بە گەیشتن.',
  continueEditing: 'دەستکاریکردن تەواو بکە',
  discardDraft: 'ڕەشنووسەکە هەڵبوەشێنەوە',
  discardQ: 'ئەم ڕەشنووسە هەڵبوەشێنرێتەوە؟',
  discardBody: 'ئەم داواکاریە بڵاو ناکرێتەوە. لە «داواکاریەکانم» وەک هەڵوەشێنراوە دەمێنێتەوە، لەگەڵ فایلەکانی.',
  discarding: 'هەڵدەوەشێنرێتەوە…',
  publish: 'بڵاوکردنەوە',
  couldNot: 'نەتوانرا تەواو بکرێت',
  wantLikeThis: 'شتێکی وەک ئەمەت دەوێت؟',
  askYourself: 'خۆت داوای بکە، و ئۆفەر لەو بازرگانانەوە وەربگرە کە دەتوانن دروستی بکەن.',
  askLikeIt: 'داوای وەک ئەمە بکە',
  signInAndAsk: 'بچۆ ژوورەوە و داوا بکە',
  printForOthers: 'بۆ خەڵک چاپ دەکەیت؟ ئۆفەرەکان لە فرۆشگایەکی سەر Levonis پێشکەش دەکرێن.',
  openYourStore: 'فرۆشگاکەت بکەرەوە',
  aboutPlus: 'دەربارەی PLUS و فرۆشگاکان',
  noOffersYet: 'هێشتا هیچ ئۆفەرێک نییە. کاتێک یەکەم ئۆفەر گەیشت ئاگادارت دەکەینەوە.',
  sortOffers: 'ڕیزکردنی ئۆفەرەکان',
  // Short enough for a 360 px segment (review 2026-09-30: «کەمترین کۆی…» was cut).
  sortPrice: 'هەرزانترین',
  sortTime: 'خێراترین',
  sortRating: 'باشترین',
  price: 'نرخ',
  noFee: 'بەبێ کرێ',
  total: 'کۆی گشتی',
  completion: 'جێبەجێکردن',
  handover: 'ڕادەستکردن',
  materials: 'ماددەکان',
  included: 'دەگرێتەوە',
  warranty: 'گەرەنتی',
  terms: 'مەرجەکان',
  validUntil: 'کارا هەتا',
  openEnded: 'کراوە',
  offerFiles: 'فایلەکانی ئۆفەر',
  revised: 'ئۆفەری دەستکاریکراو',
  was: 'پێشتر {price} بوو',
  history: 'مێژووی دەستکاریەکان',
  version: 'وەشانی {n}',
  staleNote: 'دوای ئەم ئۆفەرە داواکاریەکەت دەستکاری کرد، بۆیە چاوەڕوانی ئەوەیە بازرگانەکە دووبارە پشتڕاستی بکاتەوە.',
  unableNote: 'ئەم وۆرکشۆپە ئیتر ناتوانێت ئەم داواکاریە جێبەجێ بکات',
  acceptOffer: 'ئۆفەرەکە قبوڵ بکە',
  decline: 'ڕەتکردنەوە',
  askMerchant: 'لە بازرگانەکە بپرسە',
  viewStore: 'بینینی فرۆشگا',
  declineQ: 'ئەم ئۆفەرە ڕەت بکرێتەوە؟',
  declineBody: '{name} ئاگادار دەکرێتەوە کە ئۆفەرەکەیت هەڵنەبژارد.',
  theMerchant: 'بازرگانەکە',
  couldNotDecline: 'نەتوانرا ئۆفەرەکە ڕەت بکرێتەوە',
  couldNotOpenChat: 'نەتوانرا گفتوگۆکە بکرێتەوە',
  verified: 'پشتڕاستکراوە',
  acceptQ: 'ئەم ئۆفەرە قبوڵ دەکەیت؟',
  acceptAndHold: 'قبوڵی بکە و پارەکە ڕابگرە',
  acceptNewTerms: 'مەرجە نوێیەکان قبوڵ بکە',
  notNow: 'ئێستا نا',
  holding: 'پارەکە ڕادەگیرێت…',
  refresh: 'نوێکردنەوە',
  heldExplain: 'کۆی گشتی ئێستا لە باڵانسەکەت ڕادەگیرێت، و تەنها دوای پشتڕاستکردنەوەی وەرگرتن دەدرێتە بازرگانەکە.',
  deliveryAddress: 'ناونیشانی گەیاندن',
  noAddress: 'هیچ ناونیشانێکی پاشەکەوتکراو نییە — ناو و ژمارەکەت دەگاتە بازرگانەکە، و لەگەڵت ڕێک دەکەوێت بۆ ڕادەستکردن.',
  addAddress: 'ناونیشانێک زیاد بکە',
  contactConsent: 'کاتی قبوڵکردن ناو و ژمارەکەت{address} دەگاتە {name}، و ژمارەی فرۆشگاکەی دەگاتە تۆ. هیچ لەمانە ناگاتە هیچ بازرگانێکی تر.',
  andAddress: ' و ناونیشانی گەیاندن',
  topUp: 'جزدانەکە پڕ بکەرەوە',
  couldNotAccept: 'نەتوانرا ئۆفەرەکە قبوڵ بکرێت',
  unableAccept: 'ئەم وۆرکشۆپە ئیتر ناتوانێت ئەم داواکاریە جێبەجێ بکات — ئۆفەرێکی تر هەڵبژێرە.',
  inDays: 'لە ماوەی {days}دا',
  cheapest: 'کەمترین کۆی گشتی',
  fastest: 'خێراترین',
  topRated: 'بەرزترین هەڵسەنگاندن',
  noRatingYet: 'هێشتا هەڵسەنگاندنی نییە',
  makeOffer: 'ئۆفەرێک پێشکەش بکە',
  cannotOfferNow: 'ئێستا ناتوانیت ئۆفەر بۆ ئەم داواکاریە پێشکەش بکەیت.',
  previousOffer: 'ئۆفەری پێشووت:',
  yourOfferVersion: 'ئۆفەرەکەت — وەشانی {n}',
  draftSaved: 'ڕەشنووس پاشەکەوت کرا',
  draftHint: 'کڕیارەکە نایبینێت تا نەینێریت.',
  continueDraft: 'ڕەشنووسەکە تەواو بکە',
  sendDraft: 'ئۆفەرەکە بنێرە',
  sending: 'دەنێردرێت…',
  reconfirm: 'ئۆفەرەکەم وەک خۆی پشتڕاست دەکەمەوە',
  editOffer: 'ئۆفەرەکە دەستکاری بکە',
  messageCustomer: 'نامە بۆ کڕیارەکە',
  withdraw: 'کشانەوە',
  withdrawQ: 'ئۆفەرەکەت بکشێنیتەوە؟',
  withdrawBody: 'کڕیارەکە ئیتر ناتوانێت قبوڵی بکات. دەتوانیت ئۆفەرێکی نوێ پێشکەش بکەیت هەتا داواکاریەکە ئۆفەر وەردەگرێت.',
  withdrawLabel: 'ئۆفەرەکە بکشێنەوە',
  couldNotWithdraw: 'نەتوانرا ئۆفەرەکە بکشێنرێتەوە',
  reconfirmed: 'ئۆفەرەکەت بۆ داواکاریەکە بە شێوەی ئێستای پشتڕاست کردەوە.',
  couldNotReconfirm: 'نەتوانرا ئۆفەرەکە پشتڕاست بکرێتەوە',
  staleMerchantNote: 'کڕیارەکە داواکاریەکەی دوای ئۆفەرەکەت گۆڕی، بۆیە قبوڵ ناکرێت تا پشتڕاستی دەکەیتەوە یان دەستکاری دەکەیت.',
  whatChanged: 'چی گۆڕا: ',
  offerSent: 'ئۆفەرەکەت نێردرا.',
  offerUpdated: 'ئۆفەرەکەت نوێ کرایەوە — کڕیارەکە وەک وەشانێکی نوێ دەیبینێت.',
  draftKept: 'ڕەشنووسەکە پاشەکەوت کرا.',
  acceptedByCustomer: 'کڕیارەکە ئۆفەرەکەتی قبوڵ کرد — کارەکە لێرەوە دەست پێدەکات.',
  youChose: 'ئۆفەری {name}ت هەڵبژارد.',
  composeTitle: 'ئۆفەرەکەت پێشکەش بکە',
  editTitle: 'دەستکاریکردنی ئۆفەرەکەت',
  draftComposeTitle: 'ڕەشنووسی ئۆفەرەکەت',
  editHint: 'کڕیارەکە دەستکاریەکە وەک وەشانێکی نوێ دەبینێت، و نرخی پێشوو لە مێژووەکەدا دەمێنێتەوە.',
  priceRequired: 'نرخەکەت بە دینار بنووسە.',
  daysRequired: 'جێبەجێکردنەکە چەند ڕۆژی دەوێت؟',
  feeLabel: 'کرێی گەیاندن',
  feeHint: 'بۆ سەر نرخەکە زیاد دەکرێت، و کڕیارەکە لە کۆی گشتیدا دەیبینێت.',
  quantityLabel: 'بڕ',
  quantityHint: 'ئەوەی ئەم نرخە دەیگرێتەوە.',
  upToFive: '— هەتا ٥',
  colourLabel: 'ڕەنگ',
  colourPh: 'وەک: ڕەشی مات',
  notesLabel: 'نامە بۆ کڕیارەکە',
  includedLabel: 'ئۆفەرەکە دەگرێتەوە',
  includedHint: 'وەک: سافکردن، بۆیەی بنەڕەتی، پێچانەوە.',
  warrantyLabel: 'گەرەنتی',
  warrantyHint: 'وەک: دووبارە چاپکردن ئەگەر لە ماوەی ٣٠ ڕۆژدا شکا.',
  termsLabel: 'مەرجەکان',
  termsHint: 'ئەوەی کڕیارەکە پێویستە پێش قبوڵکردن بیزانێت: پێشەکی، گۆڕانکاری، سنوورەکان.',
  validityLabel: 'ئۆفەرەکە بەردەوام دەبێت بۆ',
  filesLabel: 'فایلەکانی ئۆفەر',
  filesHint: 'وێنە یان PDF یان مۆدێل — هەتا ٦ فایل، تەنها خاوەنی داواکاریەکە دەیانبینێت و دەتوانێت پێش قبوڵکردنی ئۆفەرەکە وەک خۆیان دایانبگرێت.',
  addFile: 'فایلێک زیاد بکە',
  removeFile: 'لابردنی {name}',
  fileTooMany: 'زۆرترین ٦ فایل.',
  fileKindBad: 'تەنها وێنە یان PDF یان فایلی مۆدێل.',
  totalLine: 'ئەو کۆی گشتیەی کڕیارەکە دەیبینێت',
  saveDraft: 'وەک ڕەشنووس پاشەکەوت بکە',
  sendOffer: 'ئۆفەرەکە بنێرە',
  saveNewVersion: 'وەشانە نوێیەکە پاشەکەوت بکە',
  fixedNote: 'دوای قبوڵکردنی کڕیارەکە نرخ و ماوە ناگۆڕێن. پارەکە لای Levonis ڕادەگیرێت و دوای پشتڕاستکردنەوەی وەرگرتن دەدرێتە تۆ.',
  couldNotSend: 'نەتوانرا بنێردرێت',
  couldNotSave: 'نەتوانرا پاشەکەوت بکرێت',
  deliverMyself: 'خۆم دەیگەیەنم',
  courier: 'گەیەنەر',
  pickup: 'وەرگرتن',
  noComments: 'هێشتا گفتوگۆ نییە',
  noCommentsHint: 'پرسیار بکە، یان تێبینیەک بنووسە کە هەمووان بیبینن.',
  writeComment: 'کۆمێنتێک بنووسە',
  askCustomer: 'لە خاوەنی داواکاریەکە بپرسە',
  kindComment: 'کۆمێنت',
  kindQuestion: 'پرسیار بۆ کڕیارەکە',
  question: 'پرسیار',
  answer: 'وەڵام بدەرەوە',
  answerLabel: 'وەڵامی خاوەنی داواکاری',
  reply: 'وەڵام',
  send: 'ناردن',
  signInToComment: 'بچۆ ژوورەوە بۆ بەشداریکردن لە گفتوگۆکە.',
  signIn: 'چوونە ژوورەوە',
  remove: 'سڕینەوە',
  removeQ: 'ئەم کۆمێنتە بسڕدرێتەوە؟',
  removeBody: 'لە گفتوگۆکە نامێنێت و ناگەڕێندرێتەوە.',
  report: 'ڕاپۆرتکردن',
  reportTitle: 'ڕاپۆرتکردنی ئەم کۆمێنتە',
  reportSend: 'ڕاپۆرتەکە بنێرە',
  reported: 'ڕاپۆرتەکەت گەیشت. سوپاس.',
  reasons: {
    spam: 'سپام یان ڕیکلام',
    abuse: 'سووکایەتی',
    nudity: 'ناوەڕۆکی نەشیاو',
    fraud: 'فێڵ',
    copyright: 'پێشێلکردنی مافی چاپ',
    offtopic: 'دەرەوەی بابەت',
    other: 'هۆکارێکی تر',
  },
  roleCustomer: 'خاوەنی داواکاری',
  roleMerchant: 'وۆرکشۆپ',
  cancel: 'هەڵوەشاندنەوە',
  replyingTo: 'وەڵام بۆ {name}',
  answering: 'وەڵامی پرسیاری {name}',
  closedForComments: 'گفتوگۆکە لەگەڵ داواکاریەکە داخرا.',
  system: {
    revised: 'داواکاریەکە دەستکاری کرا — وەشانی {n}',
    accepted: 'خاوەنی داواکاریەکە ئۆفەرێکی هەڵبژارد',
    cancelled: 'داواکاریەکە داخرا',
    completed: 'جێبەجێکردنەکە تەواو بوو',
    expired: 'ماوەی داواکاریەکە تەواو بوو',
    disputed: 'ناکۆکی لەسەر جێبەجێکردنەکە کرایەوە',
    republished: 'داواکاریەکە دووبارە بڵاوکرایەوە',
  },
  tooLong: 'کۆمێنتەکە لە ڕێگەپێدراو درێژترە.',
  commentPosted: 'نامەکەت لە گفتوگۆکەدا بڵاوکرایەوە.',
  actionFailed: 'نەتوانرا ئەنجام بدرێت.',
  options: 'هەڵبژاردەکان',
  moreComments: 'زیاتر لە گفتوگۆکە',
  openConversation: 'گفتوگۆکە بکەرەوە',
  chatWithMerchant: 'لەگەڵ بازرگانەکە لەسەر وردەکاریەکان قسە بکە، پێش قبوڵکردن یان دوای.',
  chatWithCustomer: 'لەگەڵ کڕیارەکە لەسەر وردەکاریەکان قسە بکە.',
  lastUpdate: 'دوایین نوێکردنەوە',
  noUpdatesYet: 'هێشتا نوێکردنەوە نییە — هەنگاوەکانی کارەکە لێرە دەردەکەون کاتێک ڕوودەدەن.',
  updatesFailed: 'نەتوانرا نوێکردنەوەکان باربکرێن.',
  updatesRetry: 'دووبارە هەوڵ بدەرەوە',
  openTimeline: 'ڕەوتی جێبەجێکردن بە تەواوی',
  escrowPending: 'چاوەڕوانی ڕاگرتنی پارەکە.',
  escrowHeld: 'لای Levonis ڕاگیراوە تا وەرگرتن پشتڕاست دەکرێتەوە.',
  escrowReleased: 'پارەکە درایە بازرگانەکە.',
  escrowRefunded: 'پارەکە گەڕێندرایەوە بۆ باڵانسی کڕیارەکە.',
  escrowDisputed: 'پارەکە بەستراوە تا بەڕێوەبەرایەتی Levonis بڕیار لە ناکۆکیەکە دەدات.',
  escrowCancelled: 'ڕاگرتنەکە هەڵوەشێنرایەوە.',
  youReceive: 'دوای کۆمیسیۆن دەگاتە تۆ: {amount}',
  autoConfirms: 'خۆکارانە پشتڕاست دەکرێتەوە لە {date}',
  contactCustomer: 'کڕیارەکە — بۆ پەیوەندی و گەیاندن',
  contactMerchant: 'بازرگانەکە — بۆ پەیوەندی',
  noPhone: 'ژمارە تۆمار نەکراوە — لە ڕێگەی گفتوگۆکەوە پەیوەندی بکە.',
  collectsFromWorkshop: 'خۆی لە وۆرکشۆپەکەتەوە وەریدەگرێت',
  noAddressAsk: 'ناونیشانی پاشەکەوتکراو نییە — لە گفتوگۆکەدا لێی بپرسە.',
  talkInChat: 'لە ڕێگەی گفتوگۆی داواکاریەکەوە قسە بکەن.',
  changes: {
    quantity: 'بڕ',
    source_type: 'سەرچاوەی داواکاری',
    process: 'شێوازی چاپکردن',
    material_id: 'ماددە',
    color_hex: 'ڕەنگ',
    color_name: 'ڕەنگ',
    quality: 'وردی',
    infill_percent: 'پڕکردنەوە',
    supports: 'پاڵپشتەکان',
    colors_count: 'ژمارەی ڕەنگەکان',
    post_processing_minutes: 'تەواوکاری',
    primary_file_id: 'فایلەکە',
    source_url: 'لینکەکە',
    stated_dims: 'قەبارە',
    governorate: 'پارێزگا',
    delivery_pref: 'وەرگرتن',
    deadline: 'کاتی کۆتایی',
    customer_notes: 'تێبینیەکان',
    file_ids: 'هاوپێچەکان',
  },
  // ---- Phase 5c, the page's second pass (Request.tsx, Discussion.tsx)
  status: 'دۆخ',
  saving: 'پاشەکەوت دەکرێت…',
  publishing: 'بڵاو دەکرێتەوە…',
  daysUnit: 'ڕۆژ',
  yourDraft: 'ڕەشنووسی ئۆفەرەکەت',
  feeShort: 'گەیاندن',
  stateOpen: 'کراوە',
  stateAwaiting: 'چاوەڕوانی بازرگانەکە',
  stateExpired: 'بەسەرچووە',
  stateNotChosen: 'هەڵنەبژێردرا',
  stateWithdrawn: 'کشێنرایەوە',
  stateAccepted: 'قبوڵکراو',
  stateDraft: 'ڕەشنووس',
  commentKindLabel: 'جۆری بەشداریکردن',
  reportReason: 'هۆکاری ڕاپۆرت',
  systemRevisedPlain: 'داواکاریەکە دەستکاری کرا',
  escrowPartial: 'بەشێک لە پارەکە گەڕێندرایەوە بۆ باڵانسی کڕیارەکە.',
  view3dOf: 'بینینی {name} بە سێ ڕەهەند',
  couldNotOpenViewer: 'نەتوانرا بینینی سێ ڕەهەندی بکرێتەوە',
  orderStates: {
    accepted: 'قبوڵکراو',
    funded: 'چاوەڕوانی دەستپێکردنی کارەکە',
    in_progress: 'لە جێبەجێکردندا',
    merchant_marked_delivered: 'بازرگانەکە ڕادەستی کرد — چاوەڕوانی پشتڕاستکردنەوە',
    customer_confirmed: 'کڕیارەکە وەرگرتنی پشتڕاست کردەوە',
    completed: 'تەواو',
    disputed: 'ناکۆکی کراوە',
    cancelled: 'هەڵوەشێنراوە',
    refunded: 'گەڕێندرایەوە',
  },
  confirmFromOrders: 'کاتێک کارەکە گەیشت، لە «داواکاریە تایبەتەکانم» وەرگرتن پشتڕاست بکەرەوە.',
  loadingRequest: 'داواکاریەکە بار دەکرێت…',
  reviewThanks: 'سوپاس — هەڵسەنگاندنەکەت لە پەڕەی فرۆشگاکەدا دەردەکەوێت.',
  handoverMerchant: 'بازرگانەکە دەیگەیەنێت',
  handoverCourier: 'بە کۆمپانیای گەیاندن',
  handoverPickup: 'لە وۆرکشۆپەکە وەردەگیرێت',
  stepOf: 'هەنگاوی {n} لە {total}: {label}',
  myCustomOrders: 'داواکاریە تایبەتەکانم',
  merchantOrders: 'داواکاریەکانی جێبەجێکردن',
};

export type RequestStrings = typeof ar;

export const REQUEST_STRINGS: Record<RequestLang, RequestStrings> = { ar, en, ckb };

export function requestLang(lang: string): RequestLang {
  return lang === 'en' || lang === 'ckb' ? lang : 'ar';
}

export function requestStrings(lang: string): RequestStrings {
  return REQUEST_STRINGS[requestLang(lang)];
}

export function useRequestStrings(): RequestStrings {
  const { lang } = useLanguage();
  return requestStrings(lang);
}

/** «{n} يوم» → «3 يوم»; every placeholder the sentence names, in the sentence's own order. */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (m, k: string) => (k in values ? String(values[k]) : m));
}

/** The reader's word for how an offer is handed over (a closed list; a free-text method from before offers v2 is shown as written). */
export function handoverLabel(method: string, s: RequestStrings): string {
  switch (method) {
    case 'pickup':
      return s.handoverPickup;
    case 'merchant_delivery':
      return s.handoverMerchant;
    case 'courier':
      return s.handoverCourier;
    case '':
      return '—';
    default:
      return method;
  }
}

/** The composer's choices, in the merchant's own voice: «أوصله» · «شركة توصيل» · «استلام». */
export function composerHandover(method: 'pickup' | 'merchant_delivery' | 'courier', s: RequestStrings): string {
  return method === 'pickup' ? s.pickup : method === 'courier' ? s.courier : s.deliverMyself;
}

/** A server-written discussion row, by its code and meta. */
export function systemUpdateLabel(code: string, meta: Record<string, unknown> | null | undefined, s: RequestStrings): string {
  const table = s.system as Record<string, string>;
  const t = table[code];
  if (!t) return code;
  const n = meta && typeof meta.revision === 'number' ? meta.revision : meta && typeof meta.revision === 'string' ? meta.revision : '';
  if (code === 'revised' && n === '') return s.systemRevisedPlain;
  return fill(t, { n });
}

// ---- the order timeline (Client 5d): its words live in ./timelineStrings.ts,
// a small module the /requests chunk and the merchant's custom-order screen
// can import without this whole table; re-exported here so the request page
// reads every word from one door.
export { TIMELINE_STRINGS, soraniAgo, timelineLang, timelineStrings, useTimelineStrings, type TimelineStrings } from './timelineStrings';

// ---------------------------------------------------------------- Phase 5c
// COUNTED WORDS, DATES AND STATES FOR THE REQUEST PAGE — pure, so
// tests/requestPageUi.test.ts reads them without a browser.

/**
 * «يوم واحد», «يومان», «3 أيام», «14 يومًا», «100 يوم» — the Arabic noun
 * agrees with its number (the rule of src/components/community/hub/copy.ts:
 * 1, 2, 3–10, 11–99, hundreds); Sorani keeps the singular after a number
 * («٣ ڕۆژ»), English its plural.
 */
export function daysLabel(n: number, lang: RequestLang): string {
  const count = Math.max(0, Math.floor(Number(n) || 0));
  if (lang === 'en') return `${count} ${count === 1 ? 'day' : 'days'}`;
  if (lang === 'ckb') return `${count} ڕۆژ`;
  if (count === 1) return 'يوم واحد';
  if (count === 2) return 'يومان';
  const r = count % 100;
  if (r >= 3 && r <= 10) return `${count} أيام`;
  if (r >= 11 && r <= 99) return `${count} يومًا`;
  return `${count} يوم`;
}

/** «عمل منجز واحد», «عملان منجزان», «5 أعمال منجزة», «12 عملًا منجزًا» — a workshop's finished jobs. */
export function jobsLabel(n: number, lang: RequestLang): string {
  const count = Math.max(0, Math.floor(Number(n) || 0));
  if (lang === 'en') return `${count} ${count === 1 ? 'job done' : 'jobs done'}`;
  if (lang === 'ckb') return `${count} کاری تەواوکراو`;
  if (count === 1) return 'عمل منجز واحد';
  if (count === 2) return 'عملان منجزان';
  const r = count % 100;
  if (r >= 3 && r <= 10) return `${count} أعمال منجزة`;
  if (r >= 11 && r <= 99) return `${count} عملًا منجزًا`;
  return `${count} عمل منجز`;
}

/** «٣ أكتوبر» in the reader's calendar (the app's one date locale rule), or '' for no date. */
export function shortDay(iso: string | null | undefined, lang: RequestLang): string {
  const t = iso ? Date.parse(iso) : NaN;
  if (!Number.isFinite(t)) return '';
  return new Intl.DateTimeFormat(dateLocale(lang), { day: 'numeric', month: 'short' }).format(t);
}

export type OfferTone = 'neutral' | 'success' | 'warning' | 'danger' | 'info';

/** An offer's state in the reader's words and a tone — every state, in all three languages. */
export function offerStateWords(o: { state: string; stale?: boolean; expired?: boolean; draft?: boolean }, s: RequestStrings): { text: string; tone: OfferTone } {
  if (o.draft || o.state === 'draft') return { text: s.stateDraft, tone: 'neutral' };
  if (o.state === 'accepted') return { text: s.stateAccepted, tone: 'success' };
  if (o.state === 'superseded' || (o.state === 'pending' && o.stale)) return { text: s.stateAwaiting, tone: 'warning' };
  if (o.state === 'expired' || o.expired) return { text: s.stateExpired, tone: 'neutral' };
  if (o.state === 'rejected') return { text: s.stateNotChosen, tone: 'neutral' };
  if (o.state === 'withdrawn') return { text: s.stateWithdrawn, tone: 'neutral' };
  return { text: s.stateOpen, tone: 'info' };
}

/** A community order's state as a word (the server's machine word never reaches a reader). */
export function orderStateWord(state: string, s: RequestStrings): string {
  const table = s.orderStates as Record<string, string>;
  return table[state] ?? s.orderStates.in_progress;
}

/** The escrow's state as the sentence the money line says — held, released, returned; never a key or an id. */
export function escrowSentence(state: string | null | undefined, s: RequestStrings): string {
  switch (state) {
    case 'held':
      return s.escrowHeld;
    case 'released':
      return s.escrowReleased;
    case 'refunded':
      return s.escrowRefunded;
    case 'partially_refunded':
      return s.escrowPartial;
    case 'disputed':
      return s.escrowDisputed;
    case 'cancelled':
      return s.escrowCancelled;
    default:
      return s.escrowPending;
  }
}

/**
 * `fill` for a sentence that carries an ELEMENT — «كان {price}» with the
 * price drawn as <Money>: the template is split on its placeholders and each
 * is replaced by its node, in the sentence's own order, so no language's word
 * order is assembled from fragments.
 */
export function fillNodes(template: string, values: Record<string, ReactNode>): ReactNode[] {
  return template.split(/(\{\w+\})/).map((part, i) => {
    const m = /^\{(\w+)\}$/.exec(part);
    return createElement(Fragment, { key: i }, m && m[1] in values ? values[m[1]] : part);
  });
}
