/**
 * THE ANNOUNCEMENT SHEET'S WORDS (P5, docs/MERCHANT_PLATFORM_V2.md §3.2 / §4.6)
 * — the notice line of the store page (header.notice / notice_link /
 * notice_from / notice_until), written through PUT /draft + POST /publish
 * (AnnouncementSheet.tsx).
 *
 * Its own module, imported only by the lazy sheet: in the Counter's table
 * (strings.ts) this sentence table rode in the Today chunk on every workspace
 * open (tests/bundleBudget.test.ts TODAY_SCREEN_BUDGET — «room for a line,
 * not for a sheet or a sentence table»). The dock's one word stays there.
 * Arabic, English and Sorani, every key in all three (D6).
 */
import { useLanguage } from '../../../LanguageContext';
import { counterLang, type CounterLang } from './strings';

const ANNOUNCE = {
  ar: {
    title: 'شريط الإعلان',
    lead: 'سطر قصير أعلى صفحة متجرك: عرض، موعد، تنبيه.',
    textLabel: 'نص الإعلان',
    textHint: 'اكتبه بلغات زبائنك؛ اللغة الفارغة تُعرض بنص لغة كتبتها.',
    langLabel: 'لغة النص',
    lang: { ar: 'العربية', en: 'الإنجليزية', ckb: 'الكردية' },
    left: 'بقي {n} حرفًا',
    linkLabel: 'عند الضغط عليه',
    link: { none: 'بلا رابط', route: 'صفحة في متجري', external: 'عنوان https خارجي' },
    linkKept: 'يفتح منتجًا أو مجموعة اخترتها من «تصميم المتجر».',
    pageLabel: 'الصفحة',
    routes: {
      home: 'أعلى صفحة المتجر',
      products: 'كل المنتجات',
      deals: 'التخفيضات',
      collections: 'المجموعات',
      services: 'الخدمات',
      showcase: 'المعرض',
      about: 'عن المتجر',
      reviews: 'التقييمات',
      cart: 'السلة',
    } as Record<string, string>,
    urlLabel: 'العنوان',
    urlBad: 'يقبل الشريط عناوين تبدأ بـ https:// فقط.',
    fromLabel: 'يظهر من',
    untilLabel: 'حتى',
    windowHint: 'اتركهما فارغين ليبقى الشريط ظاهرًا.',
    windowOrder: 'موعد النهاية يجب أن يأتي بعد موعد البداية.',
    windowRange: 'اختر تاريخًا بين 2020 و2099.',
    state: {
      none: 'لا شريط إعلان الآن',
      live: 'الشريط ظاهر لزبائنك الآن',
      waiting: 'مجدول — يظهر في موعده',
      ended: 'انتهى موعده — لا يظهر',
    },
    preview: 'هكذا يظهر',
    publishNow: 'سيُنشر فورًا — يراه زبائنك الآن.',
    draftToo: 'في مسودة صفحتك تعديلات أخرى لم تُنشر بعد، وستُنشر معه.',
    publish: 'انشر الشريط',
    confirm: 'نعم، انشر الآن',
    back: 'رجوع',
    remove: 'أزل الشريط',
    saveDraft: 'احفظ في المسودة فقط',
    savedDraft: 'حُفظ في مسودة صفحتك — انشره من «تصميم المتجر».',
    published: 'نُشر الشريط',
    removed: 'أُزيل الشريط',
    failed: 'تعذّر نشر الشريط. حاول مجددًا.',
    changed: 'تغيّرت صفحتك من مكان آخر — أُعيد تحميلها؛ راجع الشريط وانشره.',
    loading: 'جارٍ تحميل صفحتك…',
    loadFailed: 'تعذّر تحميل صفحتك.',
    retry: 'أعد المحاولة',
    historyNote: 'شريط الإعلان',
  },
  en: {
    title: 'Announcement bar',
    lead: 'One short line at the top of your store page: an offer, a date, a heads-up.',
    textLabel: 'Announcement text',
    textHint: 'Write it in your customers’ languages; an empty language shows one you wrote.',
    langLabel: 'Text language',
    lang: { ar: 'Arabic', en: 'English', ckb: 'Kurdish' },
    left: '{n} characters left',
    linkLabel: 'When tapped',
    link: { none: 'No link', route: 'A page of my store', external: 'An https address' },
    linkKept: 'Opens a product or collection you chose in «Store design».',
    pageLabel: 'Page',
    routes: {
      home: 'Top of the store page',
      products: 'All products',
      deals: 'Deals',
      collections: 'Collections',
      services: 'Services',
      showcase: 'Showcase',
      about: 'About',
      reviews: 'Reviews',
      cart: 'Cart',
    } as Record<string, string>,
    urlLabel: 'Address',
    urlBad: 'The bar accepts addresses starting with https:// only.',
    fromLabel: 'Shows from',
    untilLabel: 'Until',
    windowHint: 'Leave both empty to keep the bar showing.',
    windowOrder: 'The end must come after the start.',
    windowRange: 'Pick a date between 2020 and 2099.',
    state: {
      none: 'No announcement bar right now',
      live: 'The bar is showing to customers now',
      waiting: 'Scheduled — it shows at its time',
      ended: 'Its time is over — not showing',
    },
    preview: 'How it shows',
    publishNow: 'It goes live right away — customers see it now.',
    draftToo: 'Your page’s draft has other unpublished changes; they will be published with it.',
    publish: 'Publish the bar',
    confirm: 'Yes, publish now',
    back: 'Back',
    remove: 'Remove the bar',
    saveDraft: 'Save to the draft only',
    savedDraft: 'Saved to your page’s draft — publish it from «Store design».',
    published: 'The bar is live',
    removed: 'The bar was removed',
    failed: 'The bar could not be published. Try again.',
    changed: 'Your page changed somewhere else — it was reloaded; check the bar and publish.',
    loading: 'Loading your page…',
    loadFailed: 'Your page could not be loaded.',
    retry: 'Try again',
    historyNote: 'Announcement bar',
  },
  ckb: {
    title: 'شریتی ڕاگەیاندن',
    lead: 'دێڕێکی کورت لە سەرەوەی پەڕەی فرۆشگاکەت: ئۆفەرێک، کاتێک، ئاگادارییەک.',
    textLabel: 'دەقی ڕاگەیاندن',
    textHint: 'بە زمانەکانی کڕیارەکانت بینووسە؛ زمانی بەتاڵ بە دەقی زمانێک پیشان دەدرێت کە نووسیوتە.',
    langLabel: 'زمانی دەق',
    lang: { ar: 'عەرەبی', en: 'ئینگلیزی', ckb: 'کوردی' },
    left: '{n} پیت ماوە',
    linkLabel: 'کاتێک دەستی لێدەدرێت',
    link: { none: 'بەبێ بەستەر', route: 'پەڕەیەک لە فرۆشگاکەم', external: 'ناونیشانێکی دەرەکی https' },
    linkKept: 'بەرهەمێک یان کۆمەڵەیەک دەکاتەوە کە لە «دیزاینی فرۆشگا» هەڵتبژاردووە.',
    pageLabel: 'پەڕە',
    routes: {
      home: 'سەرەوەی پەڕەی فرۆشگا',
      products: 'هەموو بەرهەمەکان',
      deals: 'داشکاندنەکان',
      collections: 'کۆمەڵەکان',
      services: 'خزمەتگوزارییەکان',
      showcase: 'پیشانگا',
      about: 'دەربارەی فرۆشگا',
      reviews: 'هەڵسەنگاندنەکان',
      cart: 'سەبەتە',
    } as Record<string, string>,
    urlLabel: 'ناونیشان',
    urlBad: 'شریتەکە تەنها ئەو ناونیشانانە وەردەگرێت کە بە https:// دەست پێدەکەن.',
    fromLabel: 'پیشان دەدرێت لە',
    untilLabel: 'تا',
    windowHint: 'هەردووکیان بەتاڵ بهێڵەوە تا شریتەکە هەمیشە دیار بێت.',
    windowOrder: 'کاتی کۆتایی دەبێت دوای کاتی دەستپێکردن بێت.',
    windowRange: 'بەروارێک لە نێوان 2020 و 2099 هەڵبژێرە.',
    state: {
      none: 'ئێستا هیچ شریتی ڕاگەیاندنێک نییە',
      live: 'شریتەکە ئێستا بۆ کڕیارەکانت دیارە',
      waiting: 'خشتەکراوە — لە کاتی خۆیدا دەردەکەوێت',
      ended: 'کاتەکەی تەواو بووە — دەرناکەوێت',
    },
    preview: 'بەم شێوەیە دەردەکەوێت',
    publishNow: 'یەکسەر بڵاو دەکرێتەوە — کڕیارەکانت ئێستا دەیبینن.',
    draftToo: 'لە ڕەشنووسی پەڕەکەتدا گۆڕانکاری تری بڵاونەکراوە هەیە، و لەگەڵیدا بڵاو دەکرێنەوە.',
    publish: 'شریتەکە بڵاو بکەرەوە',
    confirm: 'بەڵێ، ئێستا بڵاوی بکەرەوە',
    back: 'گەڕانەوە',
    remove: 'شریتەکە لاببە',
    saveDraft: 'تەنها لە ڕەشنووسدا پاشەکەوتی بکە',
    savedDraft: 'لە ڕەشنووسی پەڕەکەتدا پاشەکەوت کرا — لە «دیزاینی فرۆشگا»وە بڵاوی بکەرەوە.',
    published: 'شریتەکە بڵاوکرایەوە',
    removed: 'شریتەکە لابرا',
    failed: 'شریتەکە بڵاو نەکرایەوە. دووبارە هەوڵ بدە.',
    changed: 'پەڕەکەت لە شوێنێکی ترەوە گۆڕدرا — دووبارە بار کرایەوە؛ شریتەکە ببینەوە و بڵاوی بکەرەوە.',
    loading: 'پەڕەکەت بار دەکرێت…',
    loadFailed: 'پەڕەکەت بار نەکرا.',
    retry: 'دووبارە هەوڵ بدەوە',
    historyNote: 'شریتی ڕاگەیاندن',
  },
} as const;

export type AnnounceStrings = (typeof ANNOUNCE)['ar'];
export const ANNOUNCE_STRINGS: Record<CounterLang, AnnounceStrings> = ANNOUNCE as unknown as Record<CounterLang, AnnounceStrings>;

/** The sheet's words for the current language. */
export function useAnnounceStrings(): AnnounceStrings {
  const { lang } = useLanguage();
  return ANNOUNCE_STRINGS[counterLang(lang)];
}
