/**
 * THE COUNTER'S WORDS — Today (the workspace home), its status strip, pulse,
 * queue, restock sheet and dock (docs/MERCHANT_PLATFORM_V2.md §2 «The
 * Counter», §7 localisation).
 *
 * Arabic, English and Sorani, every key in all three, hand-written here under
 * the rule docs/DECISIONS.md rows 166–168 (D6) set for the community: real
 * Sorani in the feature's own table, never the Arabic standing in. The shell
 * (src/components/merchant/shell/**) copies a phrase from here VERBATIM when it
 * needs one — its test forbids Sorani that exists nowhere else in `src`.
 *
 * Counted nouns follow src/components/community/hub/copy.ts: the numeral
 * leads the sentence it counts and stays an LTR island (`<bdi>`); Sorani
 * counts with the bare noun. Clock words are formatted from the server's
 * `next_change_at` in Baghdad time (StatusStrip.tsx), never typed here.
 */
import { useLanguage } from '../../../LanguageContext';

export type CounterLang = 'ar' | 'en' | 'ckb';

const STRINGS = {
  ar: {
    generic: {
      error: 'حدث خطأ. حاول مجددًا.',
      cancel: 'إلغاء',
      save: 'حفظ',
      open: 'فتح',
    },
    mode: {
      label: 'وضع العمل',
      operate: 'تشغيل',
      design: 'تصميم',
    },
    today: {
      title: 'ما الذي يحتاج انتباهك الآن',
      subtitle: 'كل رقم هنا من سجلات متجرك الآن، وكل سطر يفتح المكان الذي تُنجزه فيه.',
      loading: 'جارٍ عدّ ما ينتظرك…',
      empty: 'لا شيء ينتظرك الآن. الطلبات والرسائل والمخزون كلها في حالها.',
      emptyPartial: 'لا شيء مما أمكن عدّه ينتظرك الآن.',
      error: 'تعذّر عدّ ما ينتظرك.',
      rowDone: 'تم — خرج من القائمة',
      waiting: 'بانتظارك',
      problems: 'ما يمنع متجرك الآن',
    },
    pulse: {
      title: 'نبض المتجر',
      unpublished: 'تعديلات محفوظة لم تُنشر',
    },
    status: {
      openNow: 'مفتوح الآن · يغلق {time}',
      openNowNoEnd: 'مفتوح الآن',
      closedNow: 'مغلق الآن · يفتح {day} {time}',
      closedNowNoNext: 'مغلق الآن',
      byArrangement: 'ساعات العمل حسب الاتفاق',
      away: 'في إجازة حتى {date}',
      today: 'اليوم',
      tomorrow: 'غدًا',
      switchLabel: 'المتجر يستقبل الطلبات',
      switchOn: 'مفتوح — الزبائن يطلبون الآن',
      switchOff: 'متوقّف — لا طلبات جديدة حتى تعيد فتحه',
      switchSuspended: 'موقوف من Levonis — لا يُفتح من هنا',
      opened: 'فُتح المتجر',
      pausedToast: 'أُوقف المتجر مؤقتًا',
      hours: 'ساعات العمل',
    },
    tickets: {
      ordersPending: 'طلبات جديدة تنتظر تأكيدك',
      ordersConfirmed: 'طلبات مؤكدة تنتظر التجهيز',
      ordersProcessing: 'طلبات قيد التجهيز تنتظر الشحن',
      customStart: 'طلبات مخصصة مدفوعة تنتظر أن تبدأ',
      customProgress: 'طلبات مخصصة قيد التنفيذ',
      inbox: 'محادثات فيها رسائل لم تقرأها',
      inboxMessages: '{n} رسالة',
      requests: 'طلبات زبائن تطابق ورشتك ولم تقدّم عليها عرضًا',
      stockOut: 'منتجات معروضة نفد مخزونها',
      stockLow: 'منتجات قارب مخزونها على النفاد',
      reviewsNew: 'تقييمات جديدة لم تطّلع عليها',
      reviewsUnanswered: 'تقييمات بلا رد منك',
      money: 'أرباح متاحة يمكنك طلب تحويلها',
      payouts: 'طلبات تحويل أرباح قيد المعالجة',
      coupons: 'كوبونات تنتهي خلال {n} أيام',
      returns: 'طلبات إرجاع — القرار عند Levonis',
    },
    rows: {
      confirm: 'تأكيد',
      confirmed: 'تم تأكيد الطلب #{id}',
      reply: 'رد',
      restock: 'مخزون',
      orderLabel: 'طلب #{id} لـ{name}',
      attachment: 'مرفق',
      units: '{n} قطعة',
    },
    returns: {
      adminDecides: 'القرار في المرتجعات عند Levonis؛ هنا ترى الحالة.',
      state: {
        requested: 'بانتظار المراجعة',
        assessment: 'قيد التقييم',
        approved: 'مقبول',
        collection: 'قيد الاستلام',
        received: 'استُلم',
        inspected: 'فُحص',
      } as Record<string, string>,
    },
    problems: {
      layoutUnpublished: 'في صفحة متجرك تعديلات محفوظة لم تُنشر بعد — الزبائن يرون النسخة السابقة.',
      reviewAndPublish: 'راجع وانشر',
      renew: 'جدّد الاشتراك',
      contactSupport: 'تواصل مع الدعم',
      storeSetup: 'إعداد المتجر',
    },
    setup: {
      title: 'جهّز متجرك',
      each: 'كل خطوة تجعل صفحتك أوضح لزبائنك.',
      hide: 'إخفاء',
      progress: 'ما أنجزته من تجهيز المتجر',
      done: 'تم',
      logo: 'أضف شعار متجرك',
      banner: 'أضف صورة الغلاف',
      about: 'اكتب «عن المتجر»',
      phone: 'أضف رقم التواصل',
      delivery: 'حدّد أين توصل وبكم',
      products: 'انشر أول منتج',
      design: 'اختر شكل صفحتك وانشره',
    },
    week: {
      title: 'اليوم وآخر 7 أيام',
      all: 'كل التحليلات',
      locked: 'الأرقام جزء من LEVO PLUS. طلباتك وأرباحك كلها محفوظة وتراها في صفحاتها — جدّد الاشتراك لتعود الأرقام.',
      ordersToday: 'طلبات اليوم',
      salesToday: 'مبيعات اليوم',
      orders7: 'طلبات آخر 7 أيام',
      sales7: 'مبيعات آخر 7 أيام',
      vsLastWeek: 'مقارنة بالأسبوع السابق',
      visitors: '{n} زائر',
    },
    restock: {
      title: 'إضافة مخزون',
      label: 'الكمية المتوفرة الآن',
      hint: 'يظهر المنتج للزبائن فور أن يكون المخزون أكبر من صفر.',
      saved: 'حُدّث المخزون',
      failed: 'تعذّر تحديث المخزون.',
    },
    dock: {
      title: 'افعل الآن',
      newProduct: 'منتج جديد',
      reel: 'ريل',
      cover: 'الغلاف',
      design: 'التصميم',
      // P5: the announcement door opens the lazy AnnouncementSheet (its words: announceStrings.ts).
      announce: 'إعلان',
    },
    weekdays: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'],
  },
  en: {
    generic: {
      error: 'Something went wrong. Try again.',
      cancel: 'Cancel',
      save: 'Save',
      open: 'Open',
    },
    mode: {
      label: 'Mode',
      operate: 'Operate',
      design: 'Design',
    },
    today: {
      title: 'What needs your attention now',
      subtitle: 'Every number here is counted from your store right now; every line opens where you act on it.',
      loading: 'Counting what is waiting…',
      empty: 'Nothing is waiting for you right now. Orders, messages and stock are all in hand.',
      emptyPartial: 'Nothing that could be counted is waiting for you right now.',
      error: 'What is waiting could not be counted.',
      rowDone: 'Done — off the list',
      waiting: 'Waiting for you',
      problems: 'What is holding your store back',
    },
    pulse: {
      title: 'Store pulse',
      unpublished: 'Saved changes not yet published',
    },
    status: {
      openNow: 'Open now · closes {time}',
      openNowNoEnd: 'Open now',
      closedNow: 'Closed now · opens {day} {time}',
      closedNowNoNext: 'Closed now',
      byArrangement: 'Hours by arrangement',
      away: 'Away until {date}',
      today: 'today',
      tomorrow: 'tomorrow',
      switchLabel: 'The store takes orders',
      switchOn: 'Open — customers are ordering now',
      switchOff: 'Paused — no new orders until you reopen',
      switchSuspended: 'Suspended by Levonis — cannot be opened from here',
      opened: 'Store opened',
      pausedToast: 'Store paused',
      hours: 'Opening hours',
    },
    tickets: {
      ordersPending: 'New orders waiting for you to confirm',
      ordersConfirmed: 'Confirmed orders to prepare',
      ordersProcessing: 'Orders being prepared, waiting to ship',
      customStart: 'Paid custom orders waiting for you to start',
      customProgress: 'Custom orders in progress',
      inbox: 'Conversations with messages you have not read',
      inboxMessages: '{n} messages',
      requests: 'Customer requests that match your workshop, not yet answered',
      stockOut: 'Listed products that are sold out',
      stockLow: 'Products running low',
      reviewsNew: 'New reviews you have not seen',
      reviewsUnanswered: 'Reviews you have not replied to',
      money: 'Earnings available to request',
      payouts: 'Payout requests being processed',
      coupons: 'Coupons ending within {n} days',
      returns: 'Return requests — Levonis decides',
    },
    rows: {
      confirm: 'Confirm',
      confirmed: 'Order #{id} confirmed',
      reply: 'Reply',
      restock: 'Restock',
      orderLabel: 'Order #{id} for {name}',
      attachment: 'Attachment',
      units: '{n} units',
    },
    returns: {
      adminDecides: 'Levonis decides returns; here you see the state.',
      state: {
        requested: 'Awaiting review',
        assessment: 'Being assessed',
        approved: 'Approved',
        collection: 'Being collected',
        received: 'Received',
        inspected: 'Inspected',
      } as Record<string, string>,
    },
    problems: {
      layoutUnpublished: 'Your store page has saved changes that are not published — customers see the previous version.',
      reviewAndPublish: 'Review and publish',
      renew: 'Renew',
      contactSupport: 'Contact support',
      storeSetup: 'Store setup',
    },
    setup: {
      title: 'Set up your store',
      each: 'each step makes your page clearer to customers.',
      hide: 'Hide',
      progress: 'Store setup done so far',
      done: 'Done',
      logo: 'Add your store’s logo',
      banner: 'Add a banner picture',
      about: 'Write «About»',
      phone: 'Add a contact phone',
      delivery: 'Set where you deliver, and for how much',
      products: 'Publish your first product',
      design: 'Choose your page’s look and publish it',
    },
    week: {
      title: 'Today and the last 7 days',
      all: 'All analytics',
      locked: 'The figures are part of LEVO PLUS. Your orders and earnings are all kept and visible on their screens — renew to see the figures again.',
      ordersToday: 'Orders today',
      salesToday: 'Sales today',
      orders7: 'Orders, last 7 days',
      sales7: 'Sales, last 7 days',
      vsLastWeek: 'vs the week before',
      visitors: '{n} visitors',
    },
    restock: {
      title: 'Add stock',
      label: 'Quantity available now',
      hint: 'The product shows to customers as soon as the stock is above zero.',
      saved: 'Stock updated',
      failed: 'The stock could not be updated.',
    },
    dock: {
      title: 'Do now',
      newProduct: 'New product',
      reel: 'Reel',
      cover: 'Cover',
      design: 'Design',
      announce: 'Announcement',
    },
    weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  ckb: {
    generic: {
      error: 'هەڵەیەک ڕوویدا. دووبارە هەوڵ بدە.',
      cancel: 'هەڵوەشاندنەوە',
      save: 'پاشەکەوتکردن',
      open: 'کردنەوە',
    },
    mode: {
      label: 'دۆخی کار',
      operate: 'کارپێکردن',
      design: 'دیزاین',
    },
    today: {
      title: 'ئێستا چی پێویستی بە سەرنجی تۆیە',
      subtitle: 'هەموو ژمارەیەک لێرە ئێستا لە تۆمارەکانی فرۆشگاکەتەوەیە، و هەر دێڕێک ئەو شوێنە دەکاتەوە کە کارەکەی تێدا ئەنجام دەدەیت.',
      loading: 'ئەوەی چاوەڕوانتە دەژمێردرێت…',
      empty: 'ئێستا هیچ شتێک چاوەڕوانت نییە. داواکاری و نامە و کۆگا هەموو لە جێی خۆیاندان.',
      emptyPartial: 'لەوەی توانرا بژمێردرێت، ئێستا هیچ شتێک چاوەڕوانت نییە.',
      error: 'نەتوانرا ئەوەی چاوەڕوانتە بژمێردرێت.',
      rowDone: 'تەواو — لە لیستەکە دەرچوو',
      waiting: 'چاوەڕوانی تۆیە',
      problems: 'ئەوەی ئێستا ڕێگرە لە فرۆشگاکەت',
    },
    pulse: {
      title: 'لێدانی فرۆشگا',
      unpublished: 'گۆڕانکاری پاشەکەوتکراو بڵاونەکراوەتەوە',
    },
    status: {
      openNow: 'ئێستا کراوەیە · {time} دادەخرێت',
      openNowNoEnd: 'ئێستا کراوەیە',
      closedNow: 'ئێستا داخراوە · {day} {time} دەکرێتەوە',
      closedNowNoNext: 'ئێستا داخراوە',
      byArrangement: 'کاتژمێرەکانی کار بە ڕێککەوتن',
      away: 'لە پشوودایە تا {date}',
      today: 'ئەمڕۆ',
      tomorrow: 'سبەینێ',
      switchLabel: 'فرۆشگا داواکاری وەردەگرێت',
      switchOn: 'کراوەیە — کڕیاران ئێستا داوا دەکەن',
      switchOff: 'ڕاگیراوە — هیچ داواکارییەکی نوێ نییە تا دەیکەیتەوە',
      switchSuspended: 'لەلایەن Levonis ڕاگیراوە — لێرەوە ناکرێتەوە',
      opened: 'فرۆشگاکە کرایەوە',
      pausedToast: 'فرۆشگاکە کاتی ڕاگیرا',
      hours: 'کاتژمێرەکانی کار',
    },
    tickets: {
      ordersPending: 'داواکاری نوێ چاوەڕوانی پشتڕاستکردنەوەی تۆن',
      ordersConfirmed: 'داواکاری پشتڕاستکراو چاوەڕوانی ئامادەکردنن',
      ordersProcessing: 'داواکاری لە ئامادەکردندان و چاوەڕوانی ناردنن',
      customStart: 'داواکاری تایبەتی پارەدراو چاوەڕوانن دەست پێ بکەیت',
      customProgress: 'داواکاری تایبەت لە جێبەجێکردندان',
      inbox: 'گفتوگۆ کە نامەی نەخوێندراوەیان تێدایە',
      inboxMessages: '{n} نامە',
      requests: 'داواکاری کڕیاران کە لەگەڵ وۆرکشۆپەکەت دەگونجێن و هێشتا ئۆفەرت بۆیان نەناردووە',
      stockOut: 'بەرهەمی پیشاندراو کە کۆگایان تەواو بووە',
      stockLow: 'بەرهەم کە کۆگایان خەریکە تەواو دەبێت',
      reviewsNew: 'هەڵسەنگاندنی نوێ کە هێشتا نەتبینیوە',
      reviewsUnanswered: 'هەڵسەنگاندن بەبێ وەڵامی تۆ',
      money: 'قازانجی بەردەست کە دەتوانیت داوای گواستنەوەی بکەیت',
      payouts: 'داواکاری گواستنەوەی قازانج لە پرۆسەدان',
      coupons: 'کۆبۆن کە لە ماوەی {n} ڕۆژدا کۆتاییان دێت',
      returns: 'داواکاری گەڕاندنەوە — بڕیارەکە لای Levonis‌ـە',
    },
    rows: {
      confirm: 'پشتڕاستکردنەوە',
      confirmed: 'داواکاری #{id} پشتڕاستکرایەوە',
      reply: 'وەڵام',
      restock: 'کۆگا',
      orderLabel: 'داواکاری #{id} بۆ {name}',
      attachment: 'هاوپێچ',
      units: '{n} دانە',
    },
    returns: {
      adminDecides: 'بڕیاری گەڕاندنەوە لای Levonis‌ـە؛ لێرە دۆخەکە دەبینیت.',
      state: {
        requested: 'چاوەڕوانی پێداچوونەوە',
        assessment: 'لە هەڵسەنگاندندایە',
        approved: 'پەسەندکراوە',
        collection: 'لە کۆکردنەوەدایە',
        received: 'وەرگیرا',
        inspected: 'پشکنرا',
      } as Record<string, string>,
    },
    problems: {
      layoutUnpublished: 'لە پەڕەی فرۆشگاکەتدا گۆڕانکاری پاشەکەوتکراو هەیە کە هێشتا بڵاونەکراوەتەوە — کڕیاران وەشانی پێشوو دەبینن.',
      reviewAndPublish: 'پێداچوونەوە بکە و بڵاوی بکەرەوە',
      renew: 'ئەندامێتی نوێ بکەرەوە',
      contactSupport: 'پەیوەندی بە پشتیوانییەوە بکە',
      storeSetup: 'ڕێکخستنی فرۆشگا',
    },
    setup: {
      title: 'فرۆشگاکەت ئامادە بکە',
      each: 'هەر هەنگاوێک پەڕەکەت بۆ کڕیارانت ڕوونتر دەکات.',
      hide: 'شاردنەوە',
      progress: 'ئەوەی لە ئامادەکردنی فرۆشگا تەواوت کردووە',
      done: 'تەواو',
      logo: 'لۆگۆی فرۆشگاکەت زیاد بکە',
      banner: 'وێنەی بەرگ زیاد بکە',
      about: '«دەربارەی فرۆشگا» بنووسە',
      phone: 'ژمارەی پەیوەندی زیاد بکە',
      delivery: 'دیاری بکە بۆ کوێ و بە چەند دەگەیەنیت',
      products: 'یەکەم بەرهەمت بڵاو بکەرەوە',
      design: 'شێوەی پەڕەکەت هەڵبژێرە و بڵاوی بکەرەوە',
    },
    week: {
      title: 'ئەمڕۆ و ٧ ڕۆژی ڕابردوو',
      all: 'هەموو شیکارییەکان',
      locked: 'ژمارەکان بەشێکن لە LEVO PLUS. داواکاری و قازانجەکانت هەموو پارێزراون و لە پەڕەکانیاندا دەیانبینیت — ئەندامێتی نوێ بکەرەوە بۆ ئەوەی ژمارەکان بگەڕێنەوە.',
      ordersToday: 'داواکارییەکانی ئەمڕۆ',
      salesToday: 'فرۆشی ئەمڕۆ',
      orders7: 'داواکاری ٧ ڕۆژی ڕابردوو',
      sales7: 'فرۆشی ٧ ڕۆژی ڕابردوو',
      vsLastWeek: 'بەراورد بە هەفتەی پێشوو',
      visitors: '{n} سەردانکەر',
    },
    restock: {
      title: 'زیادکردنی کۆگا',
      label: 'بڕی بەردەست ئێستا',
      hint: 'بەرهەمەکە بۆ کڕیاران دەردەکەوێت هەر کە کۆگا لە سفر زیاتر بوو.',
      saved: 'کۆگا نوێکرایەوە',
      failed: 'کۆگا نوێ نەکرایەوە.',
    },
    dock: {
      title: 'ئێستا بیکە',
      newProduct: 'بەرهەمی نوێ',
      reel: 'ڕیل',
      cover: 'بەرگ',
      design: 'دیزاین',
      announce: 'ڕاگەیاندن',
    },
    weekdays: ['یەکشەممە', 'دووشەممە', 'سێشەممە', 'چوارشەممە', 'پێنجشەممە', 'هەینی', 'شەممە'],
  },
} as const;

export type CounterStrings = (typeof STRINGS)['ar'];
export const COUNTER_STRINGS: Record<CounterLang, CounterStrings> = STRINGS as unknown as Record<CounterLang, CounterStrings>;

export function counterLang(lang: string): CounterLang {
  return lang === 'en' || lang === 'ckb' ? lang : 'ar';
}

/** The table for the current language. */
export function useCounterStrings(): CounterStrings {
  const { lang } = useLanguage();
  return COUNTER_STRINGS[counterLang(lang)];
}

/** «{n} رسالة» → «3 رسالة»: every `{name}` replaced; a missing value leaves nothing behind. */
export function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_m, k: string) => (k in vars ? String(vars[k]) : '')).replace(/\s{2,}/g, ' ').trim();
}
