/**
 * EVERY WORD OF THE REVIEW FORM AND THE REVIEW GALLERY, IN AR / EN / CKB
 * (docs/REVIEWS_GIFTS.md §8 C1).
 *
 * One module for ReviewSheet (the only review form), the media picker, the
 * star control, the gallery and its viewer, the product page's review section
 * and the profile's «my reviews» list — so the same thing is called the same
 * thing on every screen of the feature.
 *
 * Sorani is written, never an Arabic stand-in: tests/reviewStringsUi.test.ts
 * fails on a ckb value that equals the Arabic, carries Arabic-only letters
 * (ة ي ك, harakat) or has no Kurdish letter at all. «review» is
 * هەڵسەنگاندن everywhere in this feature, the word the refusal sentences of
 * §9 use. The brand is always «Levonis» in Latin letters.
 *
 * REFUSALS ARE NOT HERE. A server refusal (and the client's own pre-check of
 * the same rule) is a code mapped through src/lib/refusalStrings.ts; the
 * sentences below only name counts and states that no code carries.
 */

export type ReviewLang = 'ar' | 'en' | 'ckb';

const AR = {
  // ------------------------------------------------------------ the sheet
  sheetTitle: 'تقييم المنتجات المستلمة',
  pickItem: 'منتجات هذا الطلب',
  loading: 'جارٍ تحميل منتجات الطلب…',
  loadFailed: 'تعذّر تحميل منتجات هذا الطلب.',
  retry: 'إعادة المحاولة',
  progress: (done: number, total: number) => `قيّمت ${done} من ${total}`,
  reviewedOn: (date: string) => `قيّمت هذا المنتج في ${date}.`,
  reviewStatus: { pending: 'قيد المراجعة', published: 'منشورة', rejected: 'مرفوضة' } as Record<string, string>,
  chipReviewed: 'مُقيَّم',
  chipTodo: 'بانتظار التقييم',
  edit: 'تعديل',
  editing: (name: string) => `تعديل مراجعتك لـ «${name}»`,
  cancelEdit: 'إلغاء التعديل',
  starsLabel: 'التقييم',
  star: (n: number) => (n === 1 ? 'نجمة واحدة' : n === 2 ? 'نجمتان' : `${n} نجوم`),
  starsOf: (n: number) => `${n} من 5 نجوم`,
  bodyLabel: 'مراجعتك',
  bodyPlaceholder: 'ما الذي أعجبك؟ ما الذي كان يمكن أن يكون أفضل؟',
  realChars: (n: number) => `${n}/30 حرفًا فعليًا`,
  needMore: (n: number) => `بقي ${n} حرفًا على الأقل`,
  textReady: 'النص جاهز',
  moderation: 'تُنشر المراجعة فورًا. اعتماد المكافأة قرار منفصل.',
  submit: 'نشر المراجعة',
  submitting: 'جارٍ النشر…',
  save: 'حفظ التعديل',
  saving: 'جارٍ الحفظ…',
  close: 'إغلاق',
  published: (name: string) => `شكرًا — نُشرت مراجعتك لـ «${name}».`,
  saved: (name: string) => `حُفظ تعديل مراجعتك لـ «${name}».`,
  nextUp: 'المنتج التالي بالأسفل.',
  failed: 'تعذّر إرسال المراجعة. حاول مرة أخرى.',
  noItems: 'لا توجد منتجات قابلة للتقييم في هذا الطلب.',
  allReviewed: 'قيّمت كل منتجات هذا الطلب. شكرًا لك.',
  notDelivered: 'يمكنك تقييم المنتجات بعد استلام الطلب.',
  pointsHint: (n: number) => `تُنشر فورًا؛ وإن لم تتأهل لهدية تحصل على ${(n * 2).toLocaleString('en-US')} نقطة وفق إعداد الأساس.`,
  // Why «نشر» is not available yet — one sentence, in the footer.
  needStars: 'اختر عدد النجوم.',
  waitUploads: (n: number) => (n === 1 ? 'انتظر اكتمال رفع ملف واحد…' : `انتظر اكتمال رفع ${n} ملفات…`),
  fixFailed: (n: number) => (n === 1 ? 'ملف واحد لم يُرفع. أعد رفعه أو احذفه.' : `${n} ملفات لم تُرفع. أعد رفعها أو احذفها.`),
  overLimit: 'عدد الصور أو الفيديو أكبر من الحد. احذف بعضها.',

  // ------------------------------------------------- the printer gift hint
  giftProgram: '5 نجوم مع مراجعة حقيقية تُدخل مراجعة هذه الطابعة قائمة فحص هدية التقييم، والإدارة تقرر الهدية.',
  giftNeedsLink: 'لتدخل برنامج الهدية، اربط هذه الطابعة بحسابك في مركز الضمان.',
  giftLinkCta: 'مركز الضمان',
  giftLinkedElsewhere: 'هذه الطابعة مربوطة بحساب آخر في مركز الضمان، لذلك لا تدخل برنامج الهدية.',
  giftUnitRewarded: 'حصلت هذه الطابعة على هدية تقييم من قبل.',
  giftQueued: 'مراجعتك قيد اعتماد الهدية',
  giftFiveStarsOnly: 'هدية الطابعة لمراجعات الخمس نجوم فقط، ومراجعتك منشورة كما هي.',
  giftNotQueued: 'نُشرت مراجعتك، لكن شروط برنامج الهدية لا تنطبق عليها الآن.',
  giftRevision: 'طُلب تعديل مراجعتك قبل قرار الهدية.',
  giftApproved: 'تم اعتماد مراجعتك للحصول على هدية',
  giftRejected: 'لم تُعتمد هدية لهذه المراجعة، وتبقى مراجعتك منشورة.',
  giftsCta: 'هداياي',
  pointsAwarded: (n: number) => `+${n.toLocaleString('en-US')} نقطة`,

  // ---------------------------------------------------- the media picker
  mediaTitle: 'الصور والفيديو (اختياري)',
  photosCount: (n: number) => `الصور ${n}/10`,
  videosCount: (n: number) => `الفيديو ${n}/2`,
  addPhotos: 'إضافة صور',
  addVideo: 'إضافة فيديو',
  takePhoto: 'التقاط صورة',
  photoN: (i: number, n: number) => `صورة ${i} من ${n}`,
  videoN: (i: number, n: number) => `فيديو ${i} من ${n}`,
  remove: (label: string) => `حذف ${label}`,
  replace: (label: string) => `استبدال ${label}`,
  preview: (label: string) => `معاينة ${label}`,
  retryFile: (label: string) => `إعادة رفع ${label}`,
  queued: 'في الانتظار',
  preparing: 'جارٍ التجهيز…',
  uploadingPct: (p: number) => `جارٍ الرفع ${p}%`,
  uploaded: 'تم الرفع',
  uploadFailed: 'فشل الرفع',
  retryShort: 'إعادة',
  skippedImages: (n: number) => `لم تُضف ${n} من الصور: الحد 10 صور لكل مراجعة.`,
  skippedVideos: (n: number) => `لم يُضف ${n} من الفيديو: الحد فيديوهان لكل مراجعة.`,
  duplicateFile: (name: string) => `«${name}» مضاف من قبل.`,
  fileRefused: (name: string, reason: string) => `«${name}»: ${reason}`,
  fileFallback: 'تعذّرت إضافة هذا الملف.',
  limitsNote: 'الصورة حتى 8 ميغابايت، والفيديو حتى 40 ميغابايت.',

  // ------------------------------------------------ gallery and viewer
  galleryLabel: 'صور المراجعة وفيديوهاتها',
  openPhoto: (i: number, n: number) => `فتح الصورة ${i} من ${n}`,
  playVideo: (i: number, n: number) => `تشغيل الفيديو ${i} من ${n}`,
  showMore: (n: number) => `عرض ${n} أخرى`,
  viewerLabel: 'عارض صور المراجعة وفيديوهاتها',
  prev: 'السابق',
  next: 'التالي',
  imageFailed: 'تعذّر تحميل الصورة',

  // ------------------------------------------ the product page section
  sectionTitle: 'التقييمات والمراجعات',
  empty: 'لا توجد مراجعات منشورة بعد.',
  loadError: 'تعذّر تحميل المراجعات.',
  loadMore: 'عرض المزيد',
  listLoading: 'جارٍ التحميل…',
  write: 'اكتب مراجعتك',
  editMine: 'عدّل مراجعتك',
  incentivized: 'مراجعة ضمن برنامج المكافآت',
  systemGenerated: 'تم التقييم تلقائيًا بواسطة النظام',
  verified: 'شراء مؤكد',
  notEligible: 'المراجعات متاحة لمن استلم المنتج ضمن طلب مُسلَّم.',
  signInToReview: 'سجّل الدخول لكتابة مراجعة بعد استلام طلبك.',
  myReview: 'مراجعتك',
  moderationNote: 'ملاحظة الإدارة',
  rewardReason: 'سبب القرار',
  reviewsCount: (n: number) => `${n.toLocaleString('en-US')} مراجعة`,
  disclosure: 'قد يحصل أصحاب المراجعات المؤهلة على مكافآت (هدايا أو نقاط) — يُفصح عن ذلك في المراجعات المنشورة.',
  publishedImmediately: 'تُنشر مراجعتك فورًا، ثم تُراجع المكافأة بشكل منفصل.',
};

export type ReviewStrings = typeof AR;

const EN: ReviewStrings = {
  sheetTitle: 'Rate the products you received',
  pickItem: 'Products in this order',
  loading: 'Loading the products of this order…',
  loadFailed: 'The products of this order could not be loaded.',
  retry: 'Try again',
  progress: (done, total) => `${done} of ${total} rated`,
  reviewedOn: (date) => `You reviewed this product on ${date}.`,
  reviewStatus: { pending: 'under review', published: 'published', rejected: 'rejected' },
  chipReviewed: 'Rated',
  chipTodo: 'Not rated yet',
  edit: 'Edit',
  editing: (name) => `Editing your review of “${name}”`,
  cancelEdit: 'Cancel editing',
  starsLabel: 'Rating',
  star: (n) => (n === 1 ? '1 star' : `${n} stars`),
  starsOf: (n) => `${n} out of 5 stars`,
  bodyLabel: 'Your review',
  bodyPlaceholder: 'What did you like? What could be better?',
  realChars: (n) => `${n}/30 real characters`,
  needMore: (n) => `At least ${n} more characters`,
  textReady: 'Text ready',
  moderation: 'The review publishes immediately. Reward approval is separate.',
  submit: 'Publish review',
  submitting: 'Publishing…',
  save: 'Save changes',
  saving: 'Saving…',
  close: 'Close',
  published: (name) => `Thank you — your review of “${name}” is published.`,
  saved: (name) => `Your changes to the review of “${name}” are saved.`,
  nextUp: 'The next product is below.',
  failed: 'The review could not be sent. Please try again.',
  noItems: 'No reviewable products in this order.',
  allReviewed: 'You have rated every product in this order. Thank you.',
  notDelivered: 'You can rate the products once the order has been delivered.',
  pointsHint: (n) => `Published immediately; outside a gift it earns ${(n * 2).toLocaleString('en-US')} configured fallback points.`,
  needStars: 'Choose a star rating.',
  waitUploads: (n) => (n === 1 ? 'Wait for 1 upload to finish…' : `Wait for ${n} uploads to finish…`),
  fixFailed: (n) => (n === 1 ? '1 file failed to upload. Retry or remove it.' : `${n} files failed to upload. Retry or remove them.`),
  overLimit: 'Too many photos or videos. Remove some.',

  giftProgram: '5 stars with a real review put this printer’s review on the review-gift checklist; the team decides the gift.',
  giftNeedsLink: 'To join the gift program, link this printer to your account in the warranty centre.',
  giftLinkCta: 'Warranty centre',
  giftLinkedElsewhere: 'This printer is linked to another account in the warranty centre, so it cannot join the gift program.',
  giftUnitRewarded: 'This printer has already received a review gift.',
  giftQueued: 'Your review is being considered for a gift',
  giftFiveStarsOnly: 'The printer gift is for five-star reviews only; your review is published as it is.',
  giftNotQueued: 'Your review is published, but the gift program’s conditions do not apply to it now.',
  giftRevision: 'Changes to your review were requested before the gift decision.',
  giftApproved: 'Your review was approved for a gift',
  giftRejected: 'No gift was approved for this review; your review stays published.',
  giftsCta: 'My gifts',
  pointsAwarded: (n) => `+${n.toLocaleString('en-US')} points`,

  mediaTitle: 'Photos and video (optional)',
  photosCount: (n) => `Photos ${n}/10`,
  videosCount: (n) => `Videos ${n}/2`,
  addPhotos: 'Add photos',
  addVideo: 'Add video',
  takePhoto: 'Take a photo',
  photoN: (i, n) => `Photo ${i} of ${n}`,
  videoN: (i, n) => `Video ${i} of ${n}`,
  remove: (label) => `Remove ${label}`,
  replace: (label) => `Replace ${label}`,
  preview: (label) => `Preview ${label}`,
  retryFile: (label) => `Upload ${label} again`,
  queued: 'Waiting',
  preparing: 'Preparing…',
  uploadingPct: (p) => `Uploading ${p}%`,
  uploaded: 'Uploaded',
  uploadFailed: 'Upload failed',
  retryShort: 'Retry',
  skippedImages: (n) => `${n} photo(s) not added: a review can have up to 10 photos.`,
  skippedVideos: (n) => `${n} video(s) not added: a review can have up to 2 videos.`,
  duplicateFile: (name) => `“${name}” is already added.`,
  fileRefused: (name, reason) => `“${name}”: ${reason}`,
  fileFallback: 'This file could not be added.',
  limitsNote: 'Photos up to 8 MB, videos up to 40 MB.',

  galleryLabel: 'Review photos and videos',
  openPhoto: (i, n) => `Open photo ${i} of ${n}`,
  playVideo: (i, n) => `Play video ${i} of ${n}`,
  showMore: (n) => `Show ${n} more`,
  viewerLabel: 'Review photo and video viewer',
  prev: 'Previous',
  next: 'Next',
  imageFailed: 'The image could not be loaded',

  sectionTitle: 'Ratings & Reviews',
  empty: 'No published reviews yet.',
  loadError: 'Could not load reviews.',
  loadMore: 'Load more',
  listLoading: 'Loading…',
  write: 'Write your review',
  editMine: 'Edit your review',
  incentivized: 'Rewards-program review',
  systemGenerated: 'Automatically rated by the system',
  verified: 'Verified purchase',
  notEligible: 'Reviews are open to customers with a delivered order containing this product.',
  signInToReview: 'Sign in to review after your order is delivered.',
  myReview: 'Your review',
  moderationNote: 'Moderation note',
  rewardReason: 'Decision reason',
  reviewsCount: (n) => `${n.toLocaleString('en-US')} reviews`,
  disclosure: 'Eligible reviews may receive rewards (gifts or points) — published reviews disclose this.',
  publishedImmediately: 'Your review is published immediately; the reward is reviewed separately.',
};

const CKB: ReviewStrings = {
  sheetTitle: 'هەڵسەنگاندنی ئەو بەرهەمانەی وەرتگرتوون',
  pickItem: 'بەرهەمەکانی ئەم داواکارییە',
  loading: 'بەرهەمەکانی داواکارییەکە بار دەکرێن…',
  loadFailed: 'بەرهەمەکانی ئەم داواکارییە بار نەکران.',
  retry: 'دووبارە هەوڵ بدەرەوە',
  progress: (done, total) => `${done} لە ${total} هەڵسەنگێنران`,
  reviewedOn: (date) => `لە ${date} ئەم بەرهەمەت هەڵسەنگاندووە.`,
  reviewStatus: { pending: 'لە پێداچوونەوەدایە', published: 'بڵاوکراوەتەوە', rejected: 'ڕەتکراوەتەوە' },
  chipReviewed: 'هەڵسەنگێنراوە',
  chipTodo: 'چاوەڕێی هەڵسەنگاندنە',
  edit: 'دەستکاری',
  editing: (name) => `دەستکاریکردنی هەڵسەنگاندنەکەت بۆ «${name}»`,
  cancelEdit: 'وازهێنان لە دەستکاری',
  starsLabel: 'هەڵسەنگاندن',
  star: (n) => `${n} ئەستێرە`,
  starsOf: (n) => `${n} لە 5 ئەستێرە`,
  bodyLabel: 'هەڵسەنگاندنەکەت',
  bodyPlaceholder: 'چیت پێ باش بوو؟ چی دەکرا باشتر بێت؟',
  realChars: (n) => `${n}/30 پیتی ڕاستەقینە`,
  needMore: (n) => `لانیکەم ${n} پیتی تر ماوە`,
  textReady: 'دەقەکە ئامادەیە',
  moderation: 'هەڵسەنگاندنەکە دەستبەجێ بڵاو دەکرێتەوە؛ پەسەندکردنی خەڵات بڕیارێکی جیاوازە.',
  submit: 'بڵاوکردنەوەی هەڵسەنگاندن',
  submitting: 'بڵاو دەکرێتەوە…',
  save: 'پاشەکەوتکردنی گۆڕانکارییەکان',
  saving: 'پاشەکەوت دەکرێت…',
  close: 'داخستن',
  published: (name) => `سوپاس — هەڵسەنگاندنەکەت بۆ «${name}» بڵاوکرایەوە.`,
  saved: (name) => `گۆڕانکارییەکانی هەڵسەنگاندنەکەت بۆ «${name}» پاشەکەوت کران.`,
  nextUp: 'بەرهەمی داهاتوو لە خوارەوەیە.',
  failed: 'هەڵسەنگاندنەکە نەنێردرا. تکایە دووبارە هەوڵ بدەرەوە.',
  noItems: 'هیچ بەرهەمێکی شیاوی هەڵسەنگاندن لەم داواکارییەدا نییە.',
  allReviewed: 'هەموو بەرهەمەکانی ئەم داواکارییەت هەڵسەنگاندووە. سوپاس.',
  notDelivered: 'دوای وەرگرتنی داواکارییەکە دەتوانیت بەرهەمەکان هەڵبسەنگێنیت.',
  pointsHint: (n) => `دەستبەجێ بڵاو دەکرێتەوە؛ ئەگەر دیاری وەرنەگرێت ${(n * 2).toLocaleString('en-US')} خاڵی بنەڕەت وەردەگریت.`,
  needStars: 'ژمارەی ئەستێرەکان هەڵبژێرە.',
  waitUploads: (n) => `چاوەڕێ بکە تا بارکردنی ${n} فایل تەواو دەبێت…`,
  fixFailed: (n) => `${n} فایل بار نەکران. دووبارە باریان بکەرەوە یان لایان ببە.`,
  overLimit: 'ژمارەی وێنە یان ڤیدیۆکان لە سنوور زیاترە. هەندێکیان لابە.',

  giftProgram: '5 ئەستێرە لەگەڵ هەڵسەنگاندنێکی ڕاستەقینە، هەڵسەنگاندنی ئەم چاپکەرە دەخاتە لیستی پشکنینی دیاری؛ بڕیاری دیارییەکە لای بەڕێوەبەرایەتییە.',
  giftNeedsLink: 'بۆ بەشداریکردن لە بەرنامەی دیاری، ئەم چاپکەرە لە ناوەندی گەرەنتی بە هەژمارەکەتەوە ببەستەوە.',
  giftLinkCta: 'ناوەندی گەرەنتی',
  giftLinkedElsewhere: 'ئەم چاپکەرە لە ناوەندی گەرەنتی بە هەژمارێکی ترەوە بەستراوە، بۆیە ناچێتە بەرنامەی دیاری.',
  giftUnitRewarded: 'ئەم چاپکەرە پێشتر دیاری هەڵسەنگاندنی وەرگرتووە.',
  giftQueued: 'هەڵسەنگاندنەکەت لە ژێر پێداچوونەوەدایە بۆ دیاری',
  giftFiveStarsOnly: 'دیاری چاپکەر تەنها بۆ هەڵسەنگاندنی پێنج ئەستێرەیە؛ هەڵسەنگاندنەکەت وەک خۆی بڵاوکراوەتەوە.',
  giftNotQueued: 'هەڵسەنگاندنەکەت بڵاوکرایەوە، بەڵام مەرجەکانی بەرنامەی دیاری ئێستا لەسەری جێبەجێ نابن.',
  giftRevision: 'پێش بڕیاری دیاری، داوای گۆڕانکاری لە هەڵسەنگاندنەکەت کراوە.',
  giftApproved: 'هەڵسەنگاندنەکەت بۆ وەرگرتنی دیاری پەسەند کرا',
  giftRejected: 'دیاری بۆ ئەم هەڵسەنگاندنە پەسەند نەکرا؛ هەڵسەنگاندنەکەت بڵاوکراوە دەمێنێتەوە.',
  giftsCta: 'دیارییەکانم',
  pointsAwarded: (n) => `+${n.toLocaleString('en-US')} خاڵ`,

  mediaTitle: 'وێنە و ڤیدیۆ (ئارەزوومەندانە)',
  photosCount: (n) => `وێنەکان ${n}/10`,
  videosCount: (n) => `ڤیدیۆکان ${n}/2`,
  addPhotos: 'زیادکردنی وێنە',
  addVideo: 'زیادکردنی ڤیدیۆ',
  takePhoto: 'وێنەگرتن',
  photoN: (i, n) => `وێنەی ${i} لە ${n}`,
  videoN: (i, n) => `ڤیدیۆی ${i} لە ${n}`,
  remove: (label) => `لابردنی ${label}`,
  replace: (label) => `گۆڕینی ${label}`,
  preview: (label) => `پێشبینینی ${label}`,
  retryFile: (label) => `دووبارە بارکردنەوەی ${label}`,
  queued: 'لە ڕیزدایە',
  preparing: 'ئامادە دەکرێت…',
  uploadingPct: (p) => `بار دەکرێت ${p}%`,
  uploaded: 'بارکرا',
  uploadFailed: 'بارکردن سەرنەکەوت',
  retryShort: 'دووبارە',
  skippedImages: (n) => `${n} وێنە زیاد نەکران: هەر هەڵسەنگاندنێک تا 10 وێنەی دەبێت.`,
  skippedVideos: (n) => `${n} ڤیدیۆ زیاد نەکران: هەر هەڵسەنگاندنێک تا 2 ڤیدیۆی دەبێت.`,
  duplicateFile: (name) => `«${name}» پێشتر زیاد کراوە.`,
  fileRefused: (name, reason) => `«${name}»: ${reason}`,
  fileFallback: 'ئەم فایلە زیاد نەکرا.',
  limitsNote: 'وێنە تا 8 مێگابایت، ڤیدیۆ تا 40 مێگابایت.',

  galleryLabel: 'وێنە و ڤیدیۆکانی هەڵسەنگاندن',
  openPhoto: (i, n) => `کردنەوەی وێنەی ${i} لە ${n}`,
  playVideo: (i, n) => `لێدانی ڤیدیۆی ${i} لە ${n}`,
  showMore: (n) => `پیشاندانی ${n} دانەی تر`,
  viewerLabel: 'پیشاندەری وێنە و ڤیدیۆی هەڵسەنگاندن',
  prev: 'پێشوو',
  next: 'دواتر',
  imageFailed: 'وێنەکە بار نەبوو',

  sectionTitle: 'هەڵسەنگاندن و پێداچوونەوەکان',
  empty: 'هێشتا هیچ هەڵسەنگاندنێکی بڵاوکراوە نییە.',
  loadError: 'هەڵسەنگاندنەکان بار نەبوون.',
  loadMore: 'زیاتر ببینە',
  listLoading: 'بار دەکرێت…',
  write: 'هەڵسەنگاندنەکەت بنووسە',
  editMine: 'دەستکاری هەڵسەنگاندنەکەت بکە',
  incentivized: 'هەڵسەنگاندنی بەرنامەی خەڵات',
  systemGenerated: 'خۆکارانە لەلایەن سیستەمەوە هەڵسەنگێنراوە',
  verified: 'کڕینی پشتڕاستکراو',
  notEligible: 'هەڵسەنگاندن بۆ ئەو کڕیارانەیە کە داواکارییەکی گەیشتوویان هەیە و ئەم بەرهەمەی تێدایە.',
  signInToReview: 'بچۆ ژوورەوە بۆ نووسینی هەڵسەنگاندن دوای گەیشتنی داواکارییەکەت.',
  myReview: 'هەڵسەنگاندنەکەت',
  moderationNote: 'تێبینی بەڕێوەبەرایەتی',
  rewardReason: 'هۆکاری بڕیار',
  reviewsCount: (n) => `${n.toLocaleString('en-US')} هەڵسەنگاندن`,
  disclosure: 'هەڵسەنگاندنە شیاوەکان لەوانەیە خەڵات وەربگرن (دیاری یان خاڵ) — لە هەڵسەنگاندنە بڵاوکراوەکاندا ئەمە ڕوون دەکرێتەوە.',
  publishedImmediately: 'هەڵسەنگاندنەکەت دەستبەجێ بڵاو دەکرێتەوە؛ خەڵاتەکە بە جیا پێداچوونەوەی بۆ دەکرێت.',
};

export const REVIEW_STRINGS: Record<ReviewLang, ReviewStrings> = { ar: AR, en: EN, ckb: CKB };

export function asReviewLang(lang: string): ReviewLang {
  return lang === 'en' || lang === 'ckb' ? lang : 'ar';
}

/** The strings for the language the app is rendering in. */
export function reviewStrings(lang: string): ReviewStrings {
  return REVIEW_STRINGS[asReviewLang(lang)];
}
