/**
 * «التخصيص · Customization · خۆگونجاندن» — THE MERCHANT'S WORDS, IN ARABIC
 * (Programme C, phase C1). One table per language, each its own lazy chunk:
 * a merchant downloads only the language they read (./strings.ts `useWords`
 * — the door asks for it with the builder's state, so it has arrived by the
 * time the builder opens). Merchant vocabulary: plain workshop words (a model,
 * a file, its parts) are fine here; the customer never reads this table.
 * `{placeholders}` are filled at render time and are the same in every
 * language (tests/blueprintBuilderUi.test.ts). The engine's closed words —
 * roles, looks, tiers, kinds, part kinds, colours, families, licences — come
 * from packages/catalog, so a word is the same on the merchant's screen and in
 * the customer's summary.
 */
const AR = {
  doorTitle: 'التخصيص',
  doorOff: 'غير مفعّل',
  doorDraft: 'مسودة',
  doorLive: 'منشور · النسخة {rev}',
  doorPaused: 'متوقف',
  doorOffHint: 'اجعل الزبون يكتب اسمه ويختار الألوان والمقاس قبل أن يطلب.',
  doorDraftHint: 'لم يُنشر بعد — الزبائن لا يرونه.',
  doorLiveHint: 'يخصّص الزبائن هذا المنتج الآن.',
  doorPausedHint: 'متوقف — الزبائن لا يرونه، وإعداداتك محفوظة.',
  doorStart: 'ابدأ التخصيص',
  doorEdit: 'تعديل',
  doorPause: 'إيقاف',
  doorPauseTitle: 'إيقاف التخصيص؟',
  doorPauseBody: 'يتوقف الزبائن عن تخصيص هذا المنتج. تبقى النسخة المنشورة محفوظة وتعيد تفعيلها متى شئت.',
  doorPausedToast: 'أُوقف التخصيص',
  doorSaveFirst: 'احفظ المنتج أولًا، ثم افتح التخصيص.',
  doorPrivate: 'منتج خاص بزبون واحد — لا يُخصَّص.',
  doorArchived: 'منتج مؤرشف — لا يُخصَّص.',
  doorLegacy: 'حوّل الخيارات القديمة إلى متغيرات أولًا.',
  doorFailed: 'تعذّر تحميل التخصيص.',
  doorRetry: 'أعد المحاولة',
  title: 'التخصيص · {name}',
  close: 'إغلاق',
  back: 'السابق',
  next: 'التالي',
  steps: 'خطوات التخصيص',
  saving: 'يُحفظ…',
  saved: 'محفوظ',
  unsaved: 'لم يُحفظ — {n} يحتاج تصحيحًا',
  saveFailed: 'تعذّر الحفظ',
  nextDraft: 'النسخة {rev} منشورة ولا تُعدّل — تعديلك يفتح مسودة جديدة، والزبائن يرون المنشورة حتى تنشر.',
  freshStart: 'النسخة المتوقفة محفوظة كما هي — «أعد التفعيل» يعيدها، وما تبنيه هنا مسودة جديدة.',
  stepSource: 'المصدر',
  stepParts: 'الأجزاء',
  stepAreas: 'الكتابة والشعار',
  stepSizes: 'المقاسات والمظهر',
  stepAddons: 'الإضافات',
  stepRules: 'القواعد',
  stepPublish: 'المعاينة والنشر',
  toFix: 'يحتاج تصحيحًا',
  code_REQUIRED: 'مطلوب',
  code_TYPE: 'غير صحيح',
  code_RANGE: 'خارج الحدود المسموحة',
  code_TOO_MANY: 'أكثر من المسموح',
  code_TOO_LONG: 'أطول من المسموح',
  code_TOO_LARGE: 'أكبر من المسموح',
  code_UNKNOWN_KEY: 'غير معروف',
  code_UNKNOWN_REF: 'يشير إلى شيء لم يعد موجودًا',
  code_DUPLICATE: 'مكرر',
  code_INVALID: 'غير صالح',
  code_NOT_ALLOWED: 'غير مسموح هنا',
  code_PRICE: 'سعر غير صحيح',
  whereParts: 'الأجزاء',
  whereArea: 'المساحة {n}',
  whereSizes: 'المقاسات والمظهر',
  whereAddon: 'الإضافة {n}',
  whereRule: 'القاعدة {n}',
  wherePhotos: 'الصور',
  whereColours: 'الألوان',
  whereSell: 'طريقة البيع',
  whereOther: 'الإعدادات',
  stage: 'المجسّم — اضغط جزءًا لتختاره',
  loadingModel: 'نحمّل المجسّم…',
  noModelView: 'لا يستطيع هذا المتصفح عرض المجسّم — القائمة تكفي لكل شيء.',
  mm: 'مم',
  cancel: 'إلغاء',
  remove: 'احذف',
  add: 'أضف',
  srcLead: 'كيف يرى الزبون منتجك؟',
  srcModel: 'بمجسّم ثلاثي الأبعاد',
  srcModelHint: 'يدوّره الزبون ويرى ألوانه واسمه عليه.',
  srcPhotos: 'بالصور فقط',
  srcPhotosHint: 'بلا مجسّم: صور منتجك لكل لون ومقاس، والكتابة تُرسم على صورة.',
  pickFiles: 'اختر ملفات النموذج',
  replaceFiles: 'استبدل النموذج',
  filesHint: 'ملف 3MF أو OBJ أو GLB واحد، أو حتى ١٢ ملف STL — قطعة لكل ملف.',
  reading: 'نقرأ ملفك ونقسّمه إلى أجزاء…',
  fileParts: 'ملفك فيه {n} أجزاء · {dims}',
  tooManyFiles: 'حتى ١٢ ملفًا في المرة.',
  notModel: 'هذا ليس ملف نموذج.',
  unreadable: 'تعذّرت قراءة ملفك.',
  tooHeavy: 'النموذج فيه {triangles} مثلثًا والحد {max} — صدّر ملفًا أخف.',
  wayOut: 'انشر بالصور فقط',
  hint_export_mesh: 'صدّره شبكةَ مثلثات: 3MF أو STL أو OBJ أو GLB.',
  hint_damaged: 'يبدو الملف تالفًا — صدّره من جديد.',
  hint_empty: 'الملف لا يحوي شكلًا.',
  hint_compressed_gltf: 'ملف GLB مضغوط — صدّره دون ضغط.',
  hint_external_buffers: 'ملف glTF يعتمد ملفات أخرى — صدّره GLB واحدًا.',
  hint_too_heavy: 'الملف أكبر من أن يُقرأ — صدّر نسخة أخف.',
  hint_mixed_files: 'لا تخلط STL مع أنواع أخرى — ملف واحد، أو ملفات STL فقط.',
  hint_too_many_files: 'حتى ١٢ ملف STL.',
  warn_UNIT_GUESSED: 'قدّرنا الوحدة بالملّيمتر — راجع المقاسات.',
  warn_PARTS_MERGED: 'جمعنا الأجزاء الصغيرة لتبقى ٦٤ جزءًا على الأكثر.',
  warn_BBOX_MISMATCH: 'أحد ملفات STL لا يطابق مكانه المحفوظ — راجع ترتيب القطع.',
  warn_PAINT_IGNORED: 'ألوان الطلاء داخل الملف لا تُقرأ — حدّد الألوان هنا.',
  warn_skipped: 'تجاهلنا أجزاءً لا تُطبع (دعامات أو معدِّلات).',
  photosLead: 'اختر صور المنتج التي يراها الزبون، ولكل صورة لونها أو مقاسها.',
  noPhotos: 'أضف صور المنتج أولًا من أعلى المحرّر، ثم احفظه.',
  photoColour: 'اللون',
  photoValue: 'الخيار',
  anyValue: 'أي',
  useModelInstead: 'ارفع نموذجًا بدل الصور',
  partsLead: 'اضغط جزءًا على المجسّم أو في القائمة، ثم قل ما هو.',
  suggested: 'اقترحنا دور كل جزء من أسماء أجزاء ملفك — غيّر ما لا يناسب.',
  noParts: 'ارفع النموذج أولًا في خطوة «المصدر».',
  roleLabel: 'ما هذا الجزء؟',
  roleHidden: 'مخفي',
  hiddenHint: 'يُحذف من المجسّم الذي يراه الزبون.',
  colours: 'الألوان التي يختار منها الزبون',
  paintStocked: 'من رفّي',
  paintAll: 'كل الألوان',
  paintList: 'أختارها',
  startsAs: 'اللون الأول',
  fixedHint: 'قطعة ثابتة: لونها لا يتغيّر.',
  areasLead: 'حتى ٤ مساحات: اختر نوعًا ثم اضغط على المجسّم حيث يوضع.',
  areasLeadPhoto: 'حتى ٤ مساحات: اختر نوعًا ثم اسحب زواياه على الصورة.',
  addName: 'اسم',
  placing: 'اضغط على المجسّم حيث تريد {kind}.',
  areasFull: 'أربع مساحات هي الحد.',
  onRegion: 'على {region}',
  drawnOn: 'تُرسم على',
  nameOrText: 'نوع الكتابة',
  width: 'العرض',
  depth: 'العمق',
  height: 'الارتفاع',
  lines: 'الأسطر',
  names: 'عدد الأسماء',
  maxChars: 'أقصى الحروف',
  maxHint: 'مقترح: {n} حرفًا بارتفاع {mm} مم',
  minCap: 'أصغر ارتفاع للحرف',
  textColours: 'ألوان الكتابة',
  sample: 'مثال يظهر للزبون قبل أن يكتب',
  inAr: 'بالعربية',
  inEn: 'بالإنجليزية',
  inCkb: 'بالكردية',
  required: 'على الزبون أن يملأها',
  fee: 'سعر إضافي إن مُلئت',
  modes: 'الطرق المتاحة',
  logoColours: 'أقصى ألوان الشعار',
  qrKinds: 'ما يفتحه الرمز',
  move: 'انقلها',
  sizesLead: 'المقاس والمظهر والجودة هي خيارات منتجك نفسه — قل ما يمثّله كل خيار.',
  noGroups: 'لا خيارات لهذا المنتج بعد.',
  groupIs: 'هذا الخيار هو',
  axisNone: 'شيء آخر',
  axisSize: 'المقاس',
  axisLook: 'المظهر',
  axisTier: 'الجودة',
  addSizes: 'أضف مقاسات: صغير · وسط · كبير',
  addSizesHint: 'تُضاف إلى خيارات المنتج بسعر ×٠٫٨ و×١ و×١٫٣٥ — الجديدة تبدأ بكمية صفر، فعدّلها في «الخيارات والمتغيرات».',
  sizesAdded: 'أُضيفت المقاسات إلى المنتج.',
  saveProductFirst: 'احفظ تعديلات المنتج أولًا.',
  recommended: 'الموصى به',
  longest: 'أطول ضلع',
  fits: 'تطبعه طابعتك',
  tooBig: 'أكبر من طابعتك',
  material: 'الخامة',
  pickMaterial: 'اختر الخامة',
  privateNote: 'ملاحظة لك وحدك',
  addonsLead: 'قطع من متجرك تدخل المنتج: مغناطيس، إضاءة، محرّك…',
  noStoreParts: 'لا قطع في متجرك بعد — فعّل «يُستخدم داخل منتجات مطبوعة» على منتج ليظهر هنا.',
  addAddon: 'أضف إضافة',
  pickPart: 'اختر قطعة من متجرك',
  qty: 'العدد في كل منتج',
  mustHave: 'إلزامية',
  choiceCustomer: 'يختار الزبون',
  choiceFixed: 'أحدّدها أنا',
  pricingAdd: 'يدفع سعرها',
  pricingIncluded: 'مشمولة بالسعر',
  includedHint: 'يدفع الزبون الفرق فقط إن اختار أغلى منها.',
  isDefault: 'الافتراضية',
  addOption: 'أضف قطعة أخرى',
  showOn: 'تظهر على المجسّم',
  effect_: 'لا',
  effect_glow: 'توهّج',
  effect_ring: 'حلقة',
  effect_badge: 'شارة',
  effect_marker: 'علامة',
  effect_visible: 'جزء من ملفك',
  tapAnchor: 'اضغط على المجسّم حيث توضع.',
  anchorSet: 'موضعها محدد — اضغط مرة أخرى لنقله.',
  whichPart: 'أي جزء من ملفك؟',
  otherKind: 'هذه القطعة «{kind}» والإضافة «{slot}» — اختر قطعة من النوع نفسه.',
  removeAddon: 'احذف الإضافة',
  rulesLead: 'ما يحدث تلقائيًا، وقواعدك أنت.',
  auto1: 'الاسم الطويل يصغر ليتّسع، ثم يُقترح مقاس أكبر.',
  auto2: 'المقاسات الأكبر من طابعتك لا تُعرض.',
  auto3: 'اللون غير المتوفر يُستبدل بأقرب لون على رفّك.',
  yours: 'قواعدك',
  noRules: 'لا قواعد بعد.',
  addRule: 'أضف قاعدة',
  when: 'إذا',
  then: 'فإن',
  if_text: 'كان النص أطول من',
  if_slot: 'اختار الزبون',
  if_qr: 'أضاف الزبون رمز QR',
  if_value: 'اختار الزبون',
  then_size_at_least: 'يلزم مقاس لا يقل عن',
  then_requires: 'تلزم معه',
  then_excludes: 'لا تجتمع مع',
  then_only_colors: 'تكون ألوان',
  then_max_colors: 'لا تزيد الألوان عن',
  letters: '{n} حرفًا',
  onlyKeys: 'من هذه فقط',
  fixAuto: 'تُطبّق تلقائيًا',
  fixSuggest: 'تُقترح على الزبون',
  autoNote: 'التطبيق التلقائي لا يغيّر السعر أبدًا؛ ما يغيّره يصبح اقتراحًا.',
  sellTitle: 'كيف يشتري الزبون؟',
  sellCart: 'مباشرة',
  sellRequest: 'بطلب',
  sellBoth: 'الاثنان',
  sellHintCart: 'يضيفه الزبون إلى السلة ويدفع السعر الظاهر.',
  sellHintRequest: 'يرسل الزبون طلبًا، وتؤكّد أنت السعر.',
  sellHintBoth: 'السلة لما هو جاهز، والطلب لما يحتاج مراجعتك.',
  coloursTitle: 'سعر الألوان',
  included: 'ألوان مشمولة',
  maxColours: 'أقصى عدد',
  perExtra: 'كل لون إضافي',
  warranty: 'الضمان بالأيام',
  licence: 'إعادة التصميم',
  family: 'نوع المنتج',
  notes: 'ملاحظات لك وحدك',
  preparing: 'نحفظ ونجهّز صورة المنتج…',
  captureFailed: 'تعذّر رسم المجسّم في هذا المتصفح — افتح المحرّر في متصفح آخر لتنشر.',
  previewTitle: 'كما يراه الزبون',
  previewAfterSave: 'تظهر المعاينة بعد أن يُحفظ ما فوق.',
  v_ready: 'جاهز للطلب',
  v_adjusted: 'جاهز بعد تعديل تلقائي',
  v_review: 'تراجعه أنت عند الطلب',
  v_blocked: 'يكمله الزبون قبل الطلب',
  from: 'يبدأ من {price}',
  publish: 'انشر',
  republish: 'أعد التفعيل',
  published: 'منشور — يراه الزبائن الآن.',
  liveRev: 'منشور · النسخة {rev}',
  missing: 'ينقص قبل النشر:',
  m_spec: 'الإعدادات',
  m_mesh: 'النموذج',
  m_look: 'صورة المنتج',
  pause: 'إيقاف',
  pausedNow: 'أُوقف التخصيص.',
  done: 'تم',
};

export type BuilderStrings = typeof AR;
export default AR;
