/**
 * «التخصيص · Customization · خۆگونجاندن» — THE MERCHANT'S WORDS, IN ENGLISH
 * (Programme C, phase C1). One table per language, each its own lazy chunk:
 * a merchant downloads only the language they read (./strings.ts `useWords`
 * — the door asks for it with the builder's state, so it has arrived by the
 * time the builder opens). Merchant vocabulary: plain workshop words (a model,
 * a file, its parts) are fine here; the customer never reads this table.
 * `{placeholders}` are filled at render time and are the same in every
 * language (tests/blueprintBuilderUi.test.ts). The engine's closed words —
 * roles, looks, tiers, kinds, part kinds, colours, families, licences — come
 * from packages/catalog, so a word is the same on the merchant's screen and in
 * the customer's summary.
 */
import type { BuilderStrings } from './strings.ar';

const EN: BuilderStrings = {
  doorTitle: 'Customization',
  doorOff: 'Off',
  doorDraft: 'Draft',
  doorLive: 'Live · version {rev}',
  doorPaused: 'Paused',
  doorOffHint: 'Let customers type their name and choose colours and size before they order.',
  doorDraftHint: 'Not published yet — customers do not see it.',
  doorLiveHint: 'Customers are personalizing this product now.',
  doorPausedHint: 'Paused — customers do not see it, and your settings are kept.',
  doorStart: 'Start customization',
  doorEdit: 'Edit',
  doorPause: 'Pause',
  doorPauseTitle: 'Pause customization?',
  doorPauseBody: 'Customers stop personalizing this product. The published version is kept and you can turn it back on any time.',
  doorPausedToast: 'Customization paused',
  doorSaveFirst: 'Save the product first, then open customization.',
  doorPrivate: 'A private product for one customer — it cannot be customized.',
  doorArchived: 'An archived product — it cannot be customized.',
  doorLegacy: 'Convert the old choices to variants first.',
  doorFailed: 'Customization could not be loaded.',
  doorRetry: 'Try again',
  title: 'Customization · {name}',
  close: 'Close',
  back: 'Back',
  next: 'Next',
  steps: 'Customization steps',
  saving: 'Saving…',
  saved: 'Saved',
  unsaved: 'Not saved — {n} to fix',
  saveFailed: 'Could not save',
  nextDraft: 'Version {rev} is live and is never edited — your changes open a new draft, and customers keep the live one until you publish.',
  freshStart: 'The paused version is kept as it was — «Turn back on» restores it, and what you build here is a new draft.',
  stepSource: 'Source',
  stepParts: 'Parts',
  stepAreas: 'Text & logo',
  stepSizes: 'Sizes & looks',
  stepAddons: 'Add-ons',
  stepRules: 'Rules',
  stepPublish: 'Preview & publish',
  toFix: 'To fix',
  code_REQUIRED: 'required',
  code_TYPE: 'not valid',
  code_RANGE: 'out of range',
  code_TOO_MANY: 'too many',
  code_TOO_LONG: 'too long',
  code_TOO_LARGE: 'too large',
  code_UNKNOWN_KEY: 'not known',
  code_UNKNOWN_REF: 'points to something that is gone',
  code_DUPLICATE: 'repeated',
  code_INVALID: 'not valid',
  code_NOT_ALLOWED: 'not allowed here',
  code_PRICE: 'not a valid price',
  whereParts: 'Parts',
  whereArea: 'Area {n}',
  whereSizes: 'Sizes & looks',
  whereAddon: 'Add-on {n}',
  whereRule: 'Rule {n}',
  wherePhotos: 'Photos',
  whereColours: 'Colours',
  whereSell: 'How it sells',
  whereOther: 'Settings',
  stage: 'The model — tap a part to choose it',
  loadingModel: 'Loading the model…',
  noModelView: 'This browser cannot show the model — the list does everything.',
  mm: 'mm',
  cancel: 'Cancel',
  remove: 'Remove',
  add: 'Add',
  srcLead: 'How will customers see your product?',
  srcModel: 'With a 3D model',
  srcModelHint: 'Customers turn it and see their colours and name on it.',
  srcPhotos: 'Photos only',
  srcPhotosHint: 'No model: your product photos for each colour and size; the text is drawn on a photo.',
  pickFiles: 'Choose the model files',
  replaceFiles: 'Replace the model',
  filesHint: 'One 3MF, OBJ or GLB file, or up to 12 STL files — one piece each.',
  reading: 'Reading your file and splitting it into parts…',
  fileParts: 'Your file has {n} parts · {dims}',
  tooManyFiles: 'Up to 12 files at a time.',
  notModel: 'That is not a model file.',
  unreadable: 'Your file could not be read.',
  tooHeavy: 'The model has {triangles} triangles and the limit is {max} — export a lighter file.',
  wayOut: 'Publish with photos only',
  hint_export_mesh: 'Export it as a mesh: 3MF, STL, OBJ or GLB.',
  hint_damaged: 'The file looks damaged — export it again.',
  hint_empty: 'The file holds no shape.',
  hint_compressed_gltf: 'A compressed GLB — export it without compression.',
  hint_external_buffers: 'A glTF that needs other files — export one GLB.',
  hint_too_heavy: 'The file is too big to read — export a lighter one.',
  hint_mixed_files: 'Do not mix STL with other kinds — one file, or STL files only.',
  hint_too_many_files: 'Up to 12 STL files.',
  warn_UNIT_GUESSED: 'We took the units as millimetres — check the sizes.',
  warn_PARTS_MERGED: 'Small parts were joined to keep at most 64.',
  warn_BBOX_MISMATCH: 'One STL file does not match its saved place — check how the pieces sit.',
  warn_PAINT_IGNORED: 'Paint inside the file is not read — set the colours here.',
  warn_skipped: 'Parts that are not printed (supports or modifiers) were left out.',
  photosLead: 'Choose the product photos customers see, and each photo\'s colour or option.',
  noPhotos: 'Add product photos first, at the top of the editor, and save.',
  photoColour: 'Colour',
  photoValue: 'Option',
  anyValue: 'Any',
  useModelInstead: 'Upload a model instead',
  partsLead: 'Tap a part on the model or in the list, then say what it is.',
  suggested: 'We suggested each part\'s role from the names in your file — change what does not fit.',
  noParts: 'Upload the model first, in «Source».',
  roleLabel: 'What is this part?',
  roleHidden: 'Hidden',
  hiddenHint: 'Left out of the model customers see.',
  colours: 'Colours the customer chooses from',
  paintStocked: 'My shelf',
  paintAll: 'All colours',
  paintList: 'I pick them',
  startsAs: 'First colour',
  fixedHint: 'A fixed part: its colour never changes.',
  areasLead: 'Up to 4 areas: pick a kind, then tap the model where it goes.',
  areasLeadPhoto: 'Up to 4 areas: pick a kind, then drag its corners on the photo.',
  addName: 'Name',
  placing: 'Tap the model where the {kind} goes.',
  areasFull: 'Four areas is the limit.',
  onRegion: 'On {region}',
  drawnOn: 'Drawn on',
  nameOrText: 'Kind of text',
  width: 'Width',
  depth: 'Depth',
  height: 'Height',
  lines: 'Lines',
  names: 'Names',
  maxChars: 'Most letters',
  maxHint: 'Suggested: {n} letters at {mm} mm tall',
  minCap: 'Smallest letter height',
  textColours: 'Text colours',
  sample: 'Sample shown before the customer types',
  inAr: 'In Arabic',
  inEn: 'In English',
  inCkb: 'In Kurdish',
  required: 'The customer must fill it',
  fee: 'Extra price when filled',
  modes: 'Ways offered',
  logoColours: 'Most logo colours',
  qrKinds: 'What the code opens',
  move: 'Move it',
  sizesLead: 'Size, look and quality are your product\'s own options — say what each option stands for.',
  noGroups: 'This product has no options yet.',
  groupIs: 'This option is',
  axisNone: 'Other',
  axisSize: 'Size',
  axisLook: 'Look',
  axisTier: 'Quality',
  addSizes: 'Add sizes: Small · Medium · Large',
  addSizesHint: 'Added to the product\'s options at ×0.8, ×1 and ×1.35 of the price — the new ones start at quantity 0, so set them in «Options & variants».',
  sizesAdded: 'The sizes were added to the product.',
  saveProductFirst: 'Save the product\'s changes first.',
  recommended: 'Recommended',
  longest: 'Longest side',
  fits: 'Your printer makes it',
  tooBig: 'Bigger than your printer',
  material: 'Material',
  pickMaterial: 'Choose a material',
  privateNote: 'A note only you see',
  addonsLead: 'Parts from your store that go into the product: magnets, lights, a motor…',
  noStoreParts: 'Your store has no parts yet — turn on «Can be used inside printed products» on a product to see it here.',
  addAddon: 'Add an add-on',
  pickPart: 'Choose a part from your store',
  qty: 'How many in each product',
  mustHave: 'Required',
  choiceCustomer: 'Customer chooses',
  choiceFixed: 'I set it',
  pricingAdd: 'Customer pays its price',
  pricingIncluded: 'Included in the price',
  includedHint: 'The customer pays only the difference if they pick a dearer one.',
  isDefault: 'Default',
  addOption: 'Add another part',
  showOn: 'Shows on the model',
  effect_: 'No',
  effect_glow: 'Glow',
  effect_ring: 'Ring',
  effect_badge: 'Badge',
  effect_marker: 'Marker',
  effect_visible: 'A part of your file',
  tapAnchor: 'Tap the model where it sits.',
  anchorSet: 'Its place is set — tap again to move it.',
  whichPart: 'Which part of your file?',
  otherKind: 'This part is «{kind}» and the add-on is «{slot}» — choose a part of the same kind.',
  removeAddon: 'Remove the add-on',
  rulesLead: 'What happens by itself, and your own rules.',
  auto1: 'A long name shrinks to fit, then a bigger size is suggested.',
  auto2: 'Sizes bigger than your printer are not offered.',
  auto3: 'A colour you are out of is swapped for the nearest one on your shelf.',
  yours: 'Your rules',
  noRules: 'No rules yet.',
  addRule: 'Add a rule',
  when: 'When',
  then: 'then',
  if_text: 'the text is longer than',
  if_slot: 'the customer picks',
  if_qr: 'the customer adds a QR code',
  if_value: 'the customer picks',
  then_size_at_least: 'a size of at least',
  then_requires: 'it needs',
  then_excludes: 'it cannot go with',
  then_only_colors: 'the colours of',
  then_max_colors: 'no more colours than',
  letters: '{n} letters',
  onlyKeys: 'only from these',
  fixAuto: 'Automatic',
  fixSuggest: 'Suggested',
  autoNote: 'An automatic rule never changes the price; one that would becomes a suggestion.',
  sellTitle: 'How does the customer buy?',
  sellCart: 'Directly',
  sellRequest: 'By request',
  sellBoth: 'Both',
  sellHintCart: 'The customer adds it to the cart and pays the price shown.',
  sellHintRequest: 'The customer sends a request, and you confirm the price.',
  sellHintBoth: 'The cart for what is ready, a request for what needs your review.',
  coloursTitle: 'Colour pricing',
  included: 'Colours included',
  maxColours: 'Most colours',
  perExtra: 'Each extra colour',
  warranty: 'Warranty in days',
  licence: 'Remixing',
  family: 'Kind of product',
  notes: 'Notes only you see',
  preparing: 'Saving and preparing the product picture…',
  captureFailed: 'This browser cannot draw the model — open the editor in another browser to publish.',
  previewTitle: 'As the customer sees it',
  previewAfterSave: 'The preview appears once the settings above are saved.',
  v_ready: 'Ready to order',
  v_adjusted: 'Ready after an automatic fix',
  v_review: 'You review it when ordered',
  v_blocked: 'The customer completes it before ordering',
  from: 'From {price}',
  publish: 'Publish',
  republish: 'Turn back on',
  published: 'Live — customers see it now.',
  liveRev: 'Live · version {rev}',
  missing: 'Missing before publishing:',
  m_spec: 'The settings',
  m_mesh: 'The model',
  m_look: 'The product picture',
  pause: 'Pause',
  pausedNow: 'Customization paused.',
  done: 'Done',
};

export default EN;
