/**
 * EVERY WORD OF THE ADMIN «المراجعات والهدايا» SECTION — Arabic, English and
 * written Sorani (never an Arabic placeholder in ckb). `{hole}` placeholders
 * are identical in the three languages and filled by `fill()` (model.ts).
 * tests/adminReviewsStrings.test.ts holds the three tables to one key set,
 * real Sorani and identical holes.
 *
 * The admin-only refusal codes of docs/REVIEWS_GIFTS.md §9 live here (C2);
 * the customer-facing ones live in src/lib/refusalStrings.ts (C3) and are
 * loaded only when an admin door answers with one of them.
 *
 * The brand is «Levonis» in Latin letters in every language.
 */
import type { Lang } from './model';

const AR = {
  title: 'المراجعات والهدايا',
  subtitle: 'كل المراجعات المنشورة، وقرار هدايا الطابعات، ومستويات الهدايا الخمسة.',
  admin: 'الإدارة',
  sections: 'أقسام المراجعات والهدايا',
  tabs: {
    all: 'كل المراجعات',
    gifts: 'هدايا الطابعات',
    levels: 'مستويات الهدايا',
    granted: 'الهدايا الممنوحة',
  },
  pendingCount: '{n} بانتظار القرار',
  refresh: 'تحديث',
  loading: 'جارٍ التحميل…',
  loadFailed: 'تعذّر التحميل. حاول مرة أخرى.',
  retry: 'إعادة المحاولة',
  loadMore: 'تحميل المزيد',
  empty: 'لا توجد عناصر هنا.',
  showDetails: 'عرض التفاصيل',
  hideDetails: 'إخفاء التفاصيل',
  copy: 'نسخ',
  copied: 'نُسخ',
  close: 'إغلاق',
  cancel: 'إلغاء',
  back: 'رجوع',

  facts: {
    title: 'حقائق المراجعة',
    customer: 'العميل',
    product: 'المنتج',
    productType: 'نوع المنتج',
    order: 'رقم الطلب',
    openOrder: 'فتح الطلب',
    orderStatus: 'حالة الطلب',
    deliveredAt: 'تاريخ التسليم',
    orderItem: 'سطر الطلب',
    unit: 'الوحدة',
    unitIndex: 'القطعة رقم {n}',
    warrantyEnd: 'نهاية الضمان: {date}',
    replaced: 'استُبدلت هذه الوحدة بوحدة أخرى',
    serial: 'الرقم التسلسلي',
    noSerial: 'لا يوجد رقم تسلسلي',
    receipt: 'رقم الإيصال',
    registration: 'ربط الطابعة في مركز الضمان',
    registeredAt: 'رُبطت في {date}',
    priorReward: 'مكافأة سابقة لهذه الوحدة',
    priorNone: 'لا — لم تحصل هذه الوحدة على مكافأة من قبل',
    priorYes: 'نعم — مكافأة سابقة ({state})',
    reviewDate: 'تاريخ المراجعة',
    stars: 'النجوم',
    starsValue: '{n} من 5',
    text: 'نص المراجعة',
    noText: 'بدون نص (تقييم تلقائي)',
    media: 'الصور والفيديو',
    mediaCount: '{images} صور · {videos} فيديو',
    noMedia: 'لا توجد صور أو فيديو',
    galleryLabel: 'صور وفيديو المراجعة',
    rewardState: 'حالة الهدية',
  },
  families: {
    fdm: 'طابعة FDM (فلمنت)',
    resin: 'طابعة رزن',
    laser: 'جهاز ليزر',
    none: 'ليست طابعة ضمن برنامج الهدية',
  },
  registration: {
    reviewer: 'مربوطة بحساب صاحب المراجعة',
    other: 'مربوطة بحساب آخر',
    released: 'فُكّ ربطها',
    none: 'غير مربوطة',
  },
  reviewStatus: {
    published: 'منشورة',
    pending: 'غير منشورة',
    rejected: 'النشر مرفوض',
  },
  source: {
    user: 'كتبها العميل',
    system: 'تقييم تلقائي',
  },
  rewardStates: {
    submitted: 'بانتظار القرار',
    revision_needed: 'طُلب تعديل',
    approved: 'مُعتمدة',
    rejected: 'مرفوضة',
    all: 'الكل',
  },
  rewardKinds: {
    printer_gift: 'هدية طابعة',
    points: 'نقاط',
  },

  moderation: {
    title: 'النشر العام (منفصل عن قرار الهدية)',
    publish: 'نشر',
    unpublish: 'رفض النشر',
    requestChanges: 'طلب تعديل',
    reasonTitle: 'سبب القرار',
    reasonLabel: 'السبب (يظهر للعميل)',
    note: 'ملاحظة الإشراف: {note}',
    published: 'نُشرت المراجعة.',
    unpublished: 'رُفض نشر المراجعة.',
    changesRequested: 'طُلب من العميل تعديل المراجعة.',
  },
  reasonMin3: 'اكتب سببًا من 3 أحرف على الأقل.',
  reasonMin5: 'اكتب سببًا من 5 أحرف على الأقل.',

  list: {
    intro: 'كل المراجعات، منشورة أو لا، مع أو بدون هدية. النشر قرار منفصل عن الهدية.',
    statusAll: 'كل الحالات',
    printersOnly: 'الطابعات فقط',
    withMedia: 'مع صور أو فيديو',
    includeSystem: 'إظهار التقييمات التلقائية',
    starsAny: 'كل النجوم',
    starsN: '{n} نجوم',
    starsFilter: 'النجوم',
    search: 'بحث',
    searchPlaceholder: 'البريد أو اسم المستخدم أو رقم الطلب أو المنتج',
    clear: 'مسح',
    rewardChip: 'هدية طابعة: {state}',
    openInGifts: 'فتح في هدايا الطابعات',
  },

  queue: {
    intro: 'مراجعات الطابعات التي دخلت برنامج الهدية تلقائيًا: 5 نجوم، نص حقيقي، وطابعة مربوطة بحساب صاحبها في مركز الضمان. الأدمن وحده يختار المستوى ويُصدر الكود.',
    legacy: 'مراجعة قديمة دخلت قبل القواعد الجديدة ولم تُربط بوحدة، فلا يمكن إصدار كود لها.',
    instagram: 'دليل إنستغرام (قديم، خاص)',
    evidenceFile: 'الملف المرفوع',
  },

  checklist: {
    title: 'شروط دخول برنامج الهدية',
    condition: 'الشرط',
    atEntry: 'عند الدخول',
    now: 'الآن',
    met: 'متحقق',
    notMet: 'غير متحقق',
    unknown: 'غير معروف',
    excluded: 'استبعادات تمنع الهدية',
    liveFailing: 'بعض الشروط غير متحققة الآن، فلن يُصدر الكود.',
    noLive: 'تعذّر فحص الشروط الآن؛ يفحصها الخادم من جديد عند الإصدار.',
    checks: {
      buyer: 'صاحب المراجعة هو المشتري',
      delivered: 'الطلب مُسلَّم',
      printer: 'طابعة FDM أو رزن أو ليزر',
      unit: 'توجد وحدة فعلية للطابعة',
      unit_owned: 'الوحدة مملوكة لصاحب المراجعة',
      registered_to_reviewer: 'الطابعة مربوطة بحسابه في مركز الضمان',
      five_stars: 'التقييم 5 نجوم',
      text_ok: 'نص حقيقي من 30 حرفًا على الأقل',
      user_authored: 'كتبها العميل (ليست تقييمًا تلقائيًا)',
      unit_not_rewarded: 'لم تُمنح هذه الوحدة مكافأة من قبل',
    },
    exclusions: {
      gift_line: 'الوحدة جاءت من سطر هدية',
      refunded: 'استُرد مبلغ الوحدة',
      traded_in: 'الوحدة سُلّمت في استبدال (Trade-in)',
    },
  },

  quality: {
    title: 'جودة المراجعة (استرشادية فقط)',
    score: 'الدرجة: {score} من 100',
    reasons: 'الأسباب',
    signals: 'إشارات تستحق الفحص',
    note: 'هذه الدرجة لا تحدد المستوى؛ المستوى قرارك أنت.',
  },

  decision: {
    title: 'قرار الهدية',
    mode: 'طريقة الهدية',
    modeLevel: 'استخدام هدايا المستوى',
    modeManual: 'اختيار هدية يدويًا',
    level: 'مستوى الهدية (1–5)',
    levelHint: 'اختر المستوى حسب جودة النص والصور والفيديو. لا يوجد اختيار مسبق.',
    levelN: 'المستوى {n}',
    levelNone: 'لم يُختر مستوى بعد',
    levelItems: 'هدايا المستوى {n} ({count}) — يختار العميل واحدة منها:',
    levelItemsLoading: 'جارٍ تحميل هدايا المستويات…',
    manualPick: 'اختيار منتج…',
    manualChange: 'تغيير',
    manualNone: 'لم تُختر هدية بعد',
    manualFixed: 'هدية ثابتة: لا يستطيع العميل تغييرها.',
    note: 'ملاحظة داخلية (اختياري)',
    notePlaceholder: 'لماذا هذا المستوى؟ ملاحظات عن الصور والفيديو…',
    issue: 'تأكيد وإصدار الكود',
    issuing: 'جارٍ الإصدار…',
    confirmTitle: 'إصدار كود هدية المستوى {n}؟',
    confirmLevelBody: 'لـ {customer}، من هدايا المستوى {n}. يظهر الكود مرة واحدة فقط بعد التأكيد؛ انسخه وأرسله للعميل.',
    confirmManualBody: 'لـ {customer}: {gift}. يظهر الكود مرة واحدة فقط بعد التأكيد؛ انسخه وأرسله للعميل.',
    blocked: {
      decided: 'قُرّرت هذه الهدية من قبل.',
      system: 'التقييمات التلقائية لا تحصل على مكافأة.',
      legacy: 'مراجعة قديمة غير مربوطة بوحدة: لا يمكن إصدار كود لها.',
      notEligibleNow: 'بعض الشروط غير متحققة الآن، فلن يُصدر الكود.',
      needLevel: 'اختر المستوى أولًا.',
      levelEmpty: 'لا توجد هدايا فعّالة في هذا المستوى. أضف منتجًا أو اختر هدية يدويًا.',
      needManual: 'اختر الهدية أولًا.',
    },
    reject: 'رفض الهدية',
    rejectTitle: 'رفض هدية هذه المراجعة',
    rejectBody: 'تبقى المراجعة منشورة؛ الرفض يخص الهدية فقط.',
    requestChanges: 'طلب تعديل',
    requestChangesTitle: 'طلب تعديل من العميل',
    rejected: 'رُفضت الهدية.',
    changesRequested: 'طُلب من العميل تعديل مراجعته.',
    decidedReason: 'القرار: {reason}',
    decidedBy: 'بواسطة {who} في {date}',
    approvePoints: 'اعتماد ومنح {n} نقطة',
    pointsUnconfigured: 'قيمة نقاط المراجعة غير مُعدّة؛ لا يمكن اعتماد مكافأة نقاط قبل إعدادها.',
    pointsAwarded: 'مُنحت {n} نقطة.',
    approvePointsTitle: 'اعتماد مكافأة النقاط',
    reasonLabel: 'السبب (يُسجَّل)',
    replayed: 'صدر كود لهذه المراجعة ولا يُعرض مرة أخرى. استخدم «إلغاء وإصدار كود جديد».',
  },

  entitlement: {
    title: 'الهدية والكود',
    states: {
      available: 'قديمة — متاحة',
      selected: 'قديمة — قيد التجهيز',
      code_issued: 'الكود صادر — بانتظار الاسترداد',
      redeemed_ready_to_order: 'اُستردّت — جاهزة للطلب',
      in_cart: 'في سلة العميل',
      ordered: 'طُلبت',
      fulfilled: 'سُلِّمت',
      cancelled: 'أُلغيت',
    },
    code: 'الكود',
    codeStates: {
      none: 'لا يوجد كود',
      issued: 'صالح',
      redeemed: 'اُستخدم',
      revoked: 'مُلغى',
    },
    attempts: 'المحاولات الخاطئة: {n} من 5',
    locked: 'مقفل بعد 5 محاولات خاطئة — أصدر كودًا جديدًا.',
    issuedAt: 'صدر في {date} بواسطة {who}',
    redeemedAt: 'اُسترد في {date}',
    modes: {
      level: 'من هدايا المستوى',
      manual: 'هدية يدوية',
      legacy: 'هدية قديمة (صندوق)',
    },
    levelMode: 'المستوى {n} · {mode}',
    codeHidden: 'لا يُعرض الكود مرة أخرى بعد إغلاق نافذته.',
    reissue: 'إلغاء وإصدار كود جديد',
    reissueTitle: 'إلغاء الكود الحالي وإصدار كود جديد',
    reissueBody: 'يتوقف الكود القديم فورًا، ويظهر الكود الجديد مرة واحدة فقط. يُسجَّل السبب.',
    revoke: 'إلغاء الكود',
    revokeTitle: 'إلغاء الكود دون إصدار كود جديد',
    revokeBody: 'لن يعمل الكود الحالي. يمكنك إصدار كود جديد لاحقًا.',
    revoked: 'أُلغي الكود.',
    cancel: 'إلغاء الهدية',
    cancelTitle: 'إلغاء هذه الهدية',
    cancelBody: 'يُلغى الكود ويُحذف سطر الهدية من سلة العميل إن وُجد. لا يمكن التراجع.',
    cancelled: 'أُلغيت الهدية.',
    fulfil: 'تأكيد التسليم',
    fulfilled: 'سُجّل التسليم.',
    convert: 'إصدار كود لهذه الهدية القديمة',
    orderedHint: 'طُلبت الهدية: ألغِ الطلب بدل إلغاء الهدية.',
    order: 'الطلب {id}',
  },

  code: {
    title: 'صدر كود الهدية',
    once: 'يظهر هذا الكود مرة واحدة فقط. انسخه الآن وأرسله للعميل.',
    label: 'كود الهدية المكوّن من 6 أرقام',
    copy: 'نسخ الكود',
    copied: 'نُسخ الكود',
    copyFailed: 'تعذّر النسخ تلقائيًا. حدّد الأرقام وانسخها يدويًا.',
    facts: '{customer} · المستوى {level}',
    done: 'تم — إغلاق',
    closeTitle: 'إغلاق دون نسخ الكود؟',
    closeBody: 'لن يظهر هذا الكود مرة أخرى. إن فقدته فاستخدم «إلغاء وإصدار كود جديد».',
    closeAnyway: 'إغلاق دون نسخ',
  },

  levels: {
    intro: 'كل مستوى قائمة منتجات حقيقية من المتجر. بعد استرداد الكود يختار العميل منتجًا واحدًا من هدايا مستواه.',
    picker: 'المستوى',
    activeCount: '{n} فعّالة',
    header: 'المستوى {n} — هدايا فعّالة: {count}',
    add: 'إضافة منتج',
    empty: 'لا هدايا في هذا المستوى بعد.',
    active: 'فعّالة',
    activeHint: 'الهدية المعطّلة لا تدخل في الأكواد الجديدة.',
    disabled: 'معطّلة مؤقتًا',
    moveUp: 'تحريك لأعلى',
    moveDown: 'تحريك لأسفل',
    edit: 'تعديل',
    remove: 'حذف',
    removeTitle: 'حذف هذه الهدية من المستوى {n}؟',
    removeBody: 'الهدايا الممنوحة سابقًا تحتفظ بنسختها ولا تتأثر.',
    removed: 'حُذفت الهدية.',
    saved: 'حُفظت الهدية.',
    legacyItem: 'عنصر قديم بالاسم فقط (ليس منتجًا من المتجر)، لا يدخل في الهدايا الجديدة.',
    customerPicks: 'يختار العميل من: {list}',
    customerPicksCount: 'يختار العميل من {n} خيارات',
    warnings: {
      archived: 'المنتج مؤرشف أو غير فعّال',
      out_of_stock: 'نفد من المخزون الآن',
      selection_gone: 'الخيار أو اللون المحدد لم يعد موجودًا',
      sale_type_unavailable: 'نوع البيع المحدد غير متاح الآن',
      unknown: 'تنبيه: {code}',
    },
  },

  sheet: {
    addTitle: 'إضافة هدية — المستوى {n}',
    editTitle: 'تعديل هدية — المستوى {n}',
    manualTitle: 'هدية يدوية لهذه المراجعة',
    saveToLevel: 'حفظ في المستوى {n}',
    useGift: 'اعتماد هذه الهدية',
    saving: 'جارٍ الحفظ…',
    product: 'المنتج من المتجر',
    productHint: 'ابحث بالاسم أو الرمز. الحزم والعروض الغامضة لا تكون هدية.',
    optionsLoading: 'جارٍ تحميل خيارات المنتج…',
    saleType: 'نوع البيع',
    saleTypes: {
      direct_sale: 'بيع مباشر',
      pre_order: 'طلب مسبق',
    },
    saleTypeUnavailable: 'غير متاح لهذا المنتج',
    pinOne: 'قيمة واحدة ثابتة',
    customerChooses: 'يختار العميل من قائمة محددة',
    color: 'اللون',
    colorNotLinked: 'لا يناسب الخيار المحدد',
    transport: 'طريق الشحن (طلب مسبق)',
    transports: {
      air: 'جوي',
      sea: 'بحري',
      land: 'بري',
    },
    activeLabel: 'فعّالة في المستوى',
    preview: 'معاينة الهدية',
    previewing: 'جارٍ التحقق…',
    previewOk: 'الاختيار صالح',
    price: 'سعرها في المتجر: {price}',
    fixFirst: 'أكمل هذه قبل الحفظ:',
    problems: {
      needProduct: 'اختر منتجًا من المتجر.',
      composition: 'الحزم والعروض الغامضة لا يمكن أن تكون هدية.',
      needSaleType: 'اختر نوع البيع.',
      saleTypeNotOffered: 'نوع البيع المختار غير متاح لهذا المنتج.',
      needTransport: 'اختر طريق الشحن للطلب المسبق.',
      needGroup: 'حدّد قيمة لـ «{group}» أو اسمح للعميل بالاختيار من قائمة.',
      needGroupManual: 'اختر قيمة لـ «{group}».',
      allowedEmpty: 'اختر قيمة واحدة على الأقل في قائمة العميل لـ «{group}».',
      needColor: 'حدّد لونًا أو اسمح للعميل بالاختيار من قائمة الألوان.',
      needColorManual: 'اختر اللون.',
      allowedColorsEmpty: 'اختر لونًا واحدًا على الأقل في قائمة العميل.',
      colorMismatch: 'اللون المختار لا يناسب الخيار المحدد.',
    },
  },

  granted: {
    intro: 'كل هدية مُنحت، مع حالة كودها وطلبها.',
    filters: {
      all: 'الكل',
      code_issued: 'بانتظار الاسترداد',
      redeemed_ready_to_order: 'جاهزة للطلب',
      ordered: 'مطلوبة',
      fulfilled: 'مُسلَّمة',
      cancelled: 'ملغاة',
      legacy: 'قديمة',
    },
    gift: 'الهدية',
    chooseOne: 'يختار العميل واحدة من {n} هدايا',
    legacyContents: 'محتوى الصندوق القديم',
    printer: 'الطابعة',
    grantedAt: 'تاريخ المنح',
    noGift: 'لم تُحدد الهدية بعد',
  },

  errors: {
    generic: 'تعذّر تنفيذ العملية. حاول مرة أخرى.',
    conflict: 'تغيّرت الحالة في الأثناء. حدّث القائمة وحاول مرة أخرى.',
    network: 'تعذّر الاتصال بالخادم. تحقّق من الاتصال وحاول مرة أخرى؛ الإعادة لا تُصدر كودًا ثانيًا.',
    rateLimited: 'محاولات كثيرة. انتظر قليلًا ثم حاول مرة أخرى.',
  },
};

export type AdminReviewStrings = typeof AR;

const EN: AdminReviewStrings = {
  title: 'Reviews & gifts',
  subtitle: 'Every published review, the printer gift decisions, and the five gift levels.',
  admin: 'Admin',
  sections: 'Reviews and gifts sections',
  tabs: {
    all: 'All reviews',
    gifts: 'Printer gifts',
    levels: 'Gift levels',
    granted: 'Granted gifts',
  },
  pendingCount: '{n} awaiting a decision',
  refresh: 'Refresh',
  loading: 'Loading…',
  loadFailed: 'Could not load. Try again.',
  retry: 'Try again',
  loadMore: 'Load more',
  empty: 'Nothing here.',
  showDetails: 'Show details',
  hideDetails: 'Hide details',
  copy: 'Copy',
  copied: 'Copied',
  close: 'Close',
  cancel: 'Cancel',
  back: 'Back',

  facts: {
    title: 'Review facts',
    customer: 'Customer',
    product: 'Product',
    productType: 'Product type',
    order: 'Order number',
    openOrder: 'Open order',
    orderStatus: 'Order status',
    deliveredAt: 'Delivered',
    orderItem: 'Order line',
    unit: 'Unit',
    unitIndex: 'Piece #{n}',
    warrantyEnd: 'Warranty ends: {date}',
    replaced: 'This unit was replaced by another unit',
    serial: 'Serial number',
    noSerial: 'No serial number',
    receipt: 'Receipt number',
    registration: 'Printer link in the warranty centre',
    registeredAt: 'Linked on {date}',
    priorReward: 'Earlier reward on this unit',
    priorNone: 'No — this unit has never been rewarded',
    priorYes: 'Yes — an earlier reward ({state})',
    reviewDate: 'Review date',
    stars: 'Stars',
    starsValue: '{n} of 5',
    text: 'Review text',
    noText: 'No text (automatic rating)',
    media: 'Photos and video',
    mediaCount: '{images} photos · {videos} videos',
    noMedia: 'No photos or video',
    galleryLabel: 'Review photos and video',
    rewardState: 'Gift state',
  },
  families: {
    fdm: 'FDM printer (filament)',
    resin: 'Resin printer',
    laser: 'Laser machine',
    none: 'Not a printer of the gift program',
  },
  registration: {
    reviewer: "Linked to the reviewer's account",
    other: 'Linked to another account',
    released: 'Unlinked',
    none: 'Not linked',
  },
  reviewStatus: {
    published: 'Published',
    pending: 'Not published',
    rejected: 'Publication rejected',
  },
  source: {
    user: 'Written by the customer',
    system: 'Automatic rating',
  },
  rewardStates: {
    submitted: 'Awaiting decision',
    revision_needed: 'Changes requested',
    approved: 'Approved',
    rejected: 'Rejected',
    all: 'All',
  },
  rewardKinds: {
    printer_gift: 'Printer gift',
    points: 'Points',
  },

  moderation: {
    title: 'Public visibility (separate from the gift decision)',
    publish: 'Publish',
    unpublish: 'Reject publication',
    requestChanges: 'Request changes',
    reasonTitle: 'Reason for the decision',
    reasonLabel: 'Reason (shown to the customer)',
    note: 'Moderation note: {note}',
    published: 'Review published.',
    unpublished: 'Publication rejected.',
    changesRequested: 'The customer was asked to change the review.',
  },
  reasonMin3: 'Write a reason of at least 3 characters.',
  reasonMin5: 'Write a reason of at least 5 characters.',

  list: {
    intro: 'Every review, published or not, with or without a gift. Publication is a separate decision from the gift.',
    statusAll: 'Every status',
    printersOnly: 'Printers only',
    withMedia: 'With photos or video',
    includeSystem: 'Show automatic ratings',
    starsAny: 'Any stars',
    starsN: '{n} stars',
    starsFilter: 'Stars',
    search: 'Search',
    searchPlaceholder: 'Email, username, order number or product',
    clear: 'Clear',
    rewardChip: 'Printer gift: {state}',
    openInGifts: 'Open in printer gifts',
  },

  queue: {
    intro: 'Printer reviews that entered the gift program automatically: 5 stars, real text, and a printer linked to its owner in the warranty centre. Only an admin picks the level and issues the code.',
    legacy: 'A legacy review that entered before the new rules and is not tied to a unit, so no code can be issued for it.',
    instagram: 'Instagram evidence (legacy, private)',
    evidenceFile: 'Uploaded file',
  },

  checklist: {
    title: 'Gift program conditions',
    condition: 'Condition',
    atEntry: 'At entry',
    now: 'Now',
    met: 'Met',
    notMet: 'Not met',
    unknown: 'Unknown',
    excluded: 'Exclusions that stop the gift',
    liveFailing: 'Some conditions are not met now, so no code will be issued.',
    noLive: 'The conditions could not be checked now; the server checks them again on issue.',
    checks: {
      buyer: 'The reviewer is the buyer',
      delivered: 'The order was delivered',
      printer: 'An FDM, resin or laser printer',
      unit: 'A real unit of the printer exists',
      unit_owned: 'The unit belongs to the reviewer',
      registered_to_reviewer: 'The printer is linked to their account in the warranty centre',
      five_stars: 'Rated 5 stars',
      text_ok: 'Real text of at least 30 characters',
      user_authored: 'Written by the customer (not an automatic rating)',
      unit_not_rewarded: 'This unit was never rewarded before',
    },
    exclusions: {
      gift_line: 'The unit came from a gift line',
      refunded: 'The unit was refunded',
      traded_in: 'The unit was handed in for a trade-in',
    },
  },

  quality: {
    title: 'Review quality (advice only)',
    score: 'Score: {score} of 100',
    reasons: 'Reasons',
    signals: 'Signals worth checking',
    note: 'This score never sets the level; the level is your decision.',
  },

  decision: {
    title: 'Gift decision',
    mode: 'How the gift is chosen',
    modeLevel: "Use the level's gifts",
    modeManual: 'Choose a gift manually',
    level: 'Gift level (1–5)',
    levelHint: 'Pick the level from the quality of the text, photos and video. Nothing is preselected.',
    levelN: 'Level {n}',
    levelNone: 'No level chosen yet',
    levelItems: 'Level {n} gifts ({count}) — the customer picks one:',
    levelItemsLoading: 'Loading the level gifts…',
    manualPick: 'Choose a product…',
    manualChange: 'Change',
    manualNone: 'No gift chosen yet',
    manualFixed: 'A fixed gift: the customer cannot change it.',
    note: 'Internal note (optional)',
    notePlaceholder: 'Why this level? Notes on the photos and video…',
    issue: 'Confirm and issue code',
    issuing: 'Issuing…',
    confirmTitle: 'Issue a level {n} gift code?',
    confirmLevelBody: "For {customer}, from the level {n} gifts. The code appears only once after you confirm; copy it and send it to the customer.",
    confirmManualBody: 'For {customer}: {gift}. The code appears only once after you confirm; copy it and send it to the customer.',
    blocked: {
      decided: 'This gift was already decided.',
      system: 'Automatic ratings do not earn a reward.',
      legacy: 'A legacy review not tied to a unit: no code can be issued for it.',
      notEligibleNow: 'Some conditions are not met now, so no code will be issued.',
      needLevel: 'Choose the level first.',
      levelEmpty: 'This level has no active gifts. Add a product or choose a gift manually.',
      needManual: 'Choose the gift first.',
    },
    reject: 'Reject the gift',
    rejectTitle: "Reject this review's gift",
    rejectBody: 'The review stays published; only the gift is rejected.',
    requestChanges: 'Request changes',
    requestChangesTitle: 'Ask the customer for changes',
    rejected: 'The gift was rejected.',
    changesRequested: 'The customer was asked to change their review.',
    decidedReason: 'Decision: {reason}',
    decidedBy: 'By {who} on {date}',
    approvePoints: 'Approve and award {n} points',
    pointsUnconfigured: 'The review points value is not set; a points reward cannot be approved until it is.',
    pointsAwarded: '{n} points awarded.',
    approvePointsTitle: 'Approve the points reward',
    reasonLabel: 'Reason (recorded)',
    replayed: 'A code was already issued for this review and is never shown again. Use “Revoke and issue a new code”.',
  },

  entitlement: {
    title: 'Gift and code',
    states: {
      available: 'Legacy — available',
      selected: 'Legacy — being prepared',
      code_issued: 'Code issued — awaiting redemption',
      redeemed_ready_to_order: 'Redeemed — ready to order',
      in_cart: "In the customer's cart",
      ordered: 'Ordered',
      fulfilled: 'Delivered',
      cancelled: 'Cancelled',
    },
    code: 'Code',
    codeStates: {
      none: 'No code',
      issued: 'Valid',
      redeemed: 'Used',
      revoked: 'Revoked',
    },
    attempts: 'Wrong tries: {n} of 5',
    locked: 'Locked after 5 wrong tries — issue a new code.',
    issuedAt: 'Issued {date} by {who}',
    redeemedAt: 'Redeemed {date}',
    modes: {
      level: "From the level's gifts",
      manual: 'Manual gift',
      legacy: 'Legacy gift (box)',
    },
    levelMode: 'Level {n} · {mode}',
    codeHidden: 'The code is never shown again once its window is closed.',
    reissue: 'Revoke and issue a new code',
    reissueTitle: 'Revoke the current code and issue a new one',
    reissueBody: 'The old code stops working at once, and the new code appears only once. The reason is recorded.',
    revoke: 'Revoke code',
    revokeTitle: 'Revoke the code without issuing a new one',
    revokeBody: 'The current code will stop working. You can issue a new one later.',
    revoked: 'Code revoked.',
    cancel: 'Cancel the gift',
    cancelTitle: 'Cancel this gift',
    cancelBody: "The code is revoked and the gift line leaves the customer's cart if it is there. This cannot be undone.",
    cancelled: 'Gift cancelled.',
    fulfil: 'Mark delivered',
    fulfilled: 'Marked delivered.',
    convert: 'Issue a code for this legacy gift',
    orderedHint: 'The gift was ordered: cancel the order instead of the gift.',
    order: 'Order {id}',
  },

  code: {
    title: 'Gift code issued',
    once: 'This code is shown only once. Copy it now and send it to the customer.',
    label: 'The 6-digit gift code',
    copy: 'Copy code',
    copied: 'Code copied',
    copyFailed: 'Could not copy automatically. Select the digits and copy them by hand.',
    facts: '{customer} · level {level}',
    done: 'Done — close',
    closeTitle: 'Close without copying the code?',
    closeBody: 'This code will never be shown again. If you lose it, use “Revoke and issue a new code”.',
    closeAnyway: 'Close without copying',
  },

  levels: {
    intro: "Each level is a list of real store products. After redeeming the code, the customer picks one product from their level's gifts.",
    picker: 'Level',
    activeCount: '{n} active',
    header: 'Level {n} — active gifts: {count}',
    add: 'Add a product',
    empty: 'No gifts in this level yet.',
    active: 'Active',
    activeHint: 'A disabled gift is left out of new codes.',
    disabled: 'Temporarily disabled',
    moveUp: 'Move up',
    moveDown: 'Move down',
    edit: 'Edit',
    remove: 'Delete',
    removeTitle: 'Delete this gift from level {n}?',
    removeBody: 'Gifts already granted keep their own copy and are not affected.',
    removed: 'Gift deleted.',
    saved: 'Gift saved.',
    legacyItem: 'A legacy name-only item (not a store product); it is not used for new gifts.',
    customerPicks: 'The customer picks from: {list}',
    customerPicksCount: 'The customer picks from {n} choices',
    warnings: {
      archived: 'The product is archived or inactive',
      out_of_stock: 'Out of stock right now',
      selection_gone: 'The pinned option or colour no longer exists',
      sale_type_unavailable: 'The set sale type is not available now',
      unknown: 'Warning: {code}',
    },
  },

  sheet: {
    addTitle: 'Add a gift — level {n}',
    editTitle: 'Edit a gift — level {n}',
    manualTitle: 'A manual gift for this review',
    saveToLevel: 'Save to level {n}',
    useGift: 'Use this gift',
    saving: 'Saving…',
    product: 'Store product',
    productHint: 'Search by name or SKU. Bundles and mystery offers cannot be gifts.',
    optionsLoading: "Loading the product's choices…",
    saleType: 'Sale type',
    saleTypes: {
      direct_sale: 'Direct sale',
      pre_order: 'Pre-order',
    },
    saleTypeUnavailable: 'Not offered for this product',
    pinOne: 'One fixed value',
    customerChooses: 'The customer picks from a set list',
    color: 'Colour',
    colorNotLinked: 'Does not fit the chosen option',
    transport: 'Shipping route (pre-order)',
    transports: {
      air: 'Air',
      sea: 'Sea',
      land: 'Land',
    },
    activeLabel: 'Active in the level',
    preview: 'Gift preview',
    previewing: 'Checking…',
    previewOk: 'The selection is valid',
    price: 'Store price: {price}',
    fixFirst: 'Complete these before saving:',
    problems: {
      needProduct: 'Choose a store product.',
      composition: 'Bundles and mystery offers cannot be gifts.',
      needSaleType: 'Choose the sale type.',
      saleTypeNotOffered: 'The chosen sale type is not offered for this product.',
      needTransport: 'Choose the shipping route for the pre-order.',
      needGroup: 'Set a value for “{group}” or let the customer pick from a list.',
      needGroupManual: 'Choose a value for “{group}”.',
      allowedEmpty: 'Pick at least one value in the customer\'s list for “{group}”.',
      needColor: 'Set a colour or let the customer pick from a colour list.',
      needColorManual: 'Choose the colour.',
      allowedColorsEmpty: "Pick at least one colour in the customer's list.",
      colorMismatch: 'The chosen colour does not fit the chosen option.',
    },
  },

  granted: {
    intro: 'Every granted gift, with its code and order state.',
    filters: {
      all: 'All',
      code_issued: 'Awaiting redemption',
      redeemed_ready_to_order: 'Ready to order',
      ordered: 'Ordered',
      fulfilled: 'Delivered',
      cancelled: 'Cancelled',
      legacy: 'Legacy',
    },
    gift: 'Gift',
    chooseOne: 'The customer picks one of {n} gifts',
    legacyContents: 'Legacy box contents',
    printer: 'Printer',
    grantedAt: 'Granted on',
    noGift: 'The gift is not chosen yet',
  },

  errors: {
    generic: 'The action failed. Try again.',
    conflict: 'The state changed meanwhile. Refresh the list and try again.',
    network: 'Could not reach the server. Check the connection and try again; a retry never issues a second code.',
    rateLimited: 'Too many attempts. Wait a little and try again.',
  },
};

const CKB: AdminReviewStrings = {
  title: 'هەڵسەنگاندن و دیارییەکان',
  subtitle: 'هەموو هەڵسەنگاندنە بڵاوکراوەکان، بڕیاری دیاری چاپکەرەکان و پێنج ئاستی دیارییەکان.',
  admin: 'بەڕێوەبردن',
  sections: 'بەشەکانی هەڵسەنگاندن و دیاری',
  tabs: {
    all: 'هەموو هەڵسەنگاندنەکان',
    gifts: 'دیاری چاپکەرەکان',
    levels: 'ئاستەکانی دیاری',
    granted: 'دیارییە بەخشراوەکان',
  },
  pendingCount: '{n} چاوەڕێی بڕیارن',
  refresh: 'نوێکردنەوە',
  loading: 'باردەکرێت…',
  loadFailed: 'بارنەکرا. دووبارە هەوڵ بدەرەوە.',
  retry: 'دووبارە هەوڵدانەوە',
  loadMore: 'زیاتر باربکە',
  empty: 'هیچ شتێک لێرە نییە.',
  showDetails: 'پیشاندانی وردەکاری',
  hideDetails: 'شاردنەوەی وردەکاری',
  copy: 'کۆپی',
  copied: 'کۆپی کرا',
  close: 'داخستن',
  cancel: 'هەڵوەشاندنەوە',
  back: 'گەڕانەوە',

  facts: {
    title: 'ڕاستییەکانی هەڵسەنگاندن',
    customer: 'کڕیار',
    product: 'بەرهەم',
    productType: 'جۆری بەرهەم',
    order: 'ژمارەی داواکاری',
    openOrder: 'کردنەوەی داواکاری',
    orderStatus: 'دۆخی داواکاری',
    deliveredAt: 'بەرواری گەیاندن',
    orderItem: 'هێڵی داواکاری',
    unit: 'یەکە',
    unitIndex: 'پارچەی ژمارە {n}',
    warrantyEnd: 'کۆتایی گەرەنتی: {date}',
    replaced: 'ئەم یەکەیە بە یەکەیەکی تر گۆڕدراوە',
    serial: 'ژمارەی زنجیرەیی',
    noSerial: 'ژمارەی زنجیرەیی نییە',
    receipt: 'ژمارەی پسوولە',
    registration: 'بەستنی چاپکەر لە ناوەندی گەرەنتی',
    registeredAt: 'لە {date} بەسترا',
    priorReward: 'خەڵاتی پێشووی ئەم یەکەیە',
    priorNone: 'نەخێر — ئەم یەکەیە هەرگیز خەڵاتی وەرنەگرتووە',
    priorYes: 'بەڵێ — خەڵاتێکی پێشوو ({state})',
    reviewDate: 'بەرواری هەڵسەنگاندن',
    stars: 'ئەستێرەکان',
    starsValue: '{n} لە 5',
    text: 'دەقی هەڵسەنگاندن',
    noText: 'بێ دەق (هەڵسەنگاندنی خۆکار)',
    media: 'وێنە و ڤیدیۆ',
    mediaCount: '{images} وێنە · {videos} ڤیدیۆ',
    noMedia: 'هیچ وێنە و ڤیدیۆیەک نییە',
    galleryLabel: 'وێنە و ڤیدیۆی هەڵسەنگاندن',
    rewardState: 'دۆخی دیاری',
  },
  families: {
    fdm: 'چاپکەری FDM (فیلامێنت)',
    resin: 'چاپکەری ڕەزن',
    laser: 'ئامێری لەیزەر',
    none: 'چاپکەری بەرنامەی دیاری نییە',
  },
  registration: {
    reviewer: 'بە هەژماری خاوەنی هەڵسەنگاندنەکە بەستراوە',
    other: 'بە هەژمارێکی دیکە بەستراوە',
    released: 'بەستنەکەی لابراوە',
    none: 'نەبەستراوە',
  },
  reviewStatus: {
    published: 'بڵاوکراوەتەوە',
    pending: 'بڵاونەکراوەتەوە',
    rejected: 'بڵاوکردنەوە ڕەتکرایەوە',
  },
  source: {
    user: 'کڕیار نووسیویەتی',
    system: 'هەڵسەنگاندنی خۆکار',
  },
  rewardStates: {
    submitted: 'چاوەڕێی بڕیار',
    revision_needed: 'داوای گۆڕانکاری کراوە',
    approved: 'پەسەندکراو',
    rejected: 'ڕەتکراوە',
    all: 'هەموو',
  },
  rewardKinds: {
    printer_gift: 'دیاری چاپکەر',
    points: 'خاڵ',
  },

  moderation: {
    title: 'بڵاوکردنەوەی گشتی (جیا لە بڕیاری دیاری)',
    publish: 'بڵاوکردنەوە',
    unpublish: 'ڕەتکردنەوەی بڵاوکردنەوە',
    requestChanges: 'داواکردنی گۆڕانکاری',
    reasonTitle: 'هۆکاری بڕیارەکە',
    reasonLabel: 'هۆکار (بۆ کڕیار پیشان دەدرێت)',
    note: 'تێبینی چاودێری: {note}',
    published: 'هەڵسەنگاندنەکە بڵاوکرایەوە.',
    unpublished: 'بڵاوکردنەوەی هەڵسەنگاندنەکە ڕەتکرایەوە.',
    changesRequested: 'داوا لە کڕیار کرا هەڵسەنگاندنەکە بگۆڕێت.',
  },
  reasonMin3: 'هۆکارێک بنووسە کە لانیکەم 3 پیت بێت.',
  reasonMin5: 'هۆکارێک بنووسە کە لانیکەم 5 پیت بێت.',

  list: {
    intro: 'هەموو هەڵسەنگاندنەکان، بڵاوکراوە یان نا، لەگەڵ دیاری یان بێ دیاری. بڵاوکردنەوە بڕیارێکی جیایە لە دیاری.',
    statusAll: 'هەموو دۆخەکان',
    printersOnly: 'تەنها چاپکەرەکان',
    withMedia: 'لەگەڵ وێنە یان ڤیدیۆ',
    includeSystem: 'هەڵسەنگاندنە خۆکارەکان پیشان بدە',
    starsAny: 'هەموو ئەستێرەکان',
    starsN: '{n} ئەستێرە',
    starsFilter: 'ئەستێرەکان',
    search: 'گەڕان',
    searchPlaceholder: 'ئیمەیڵ، ناوی بەکارهێنەر، ژمارەی داواکاری یان بەرهەم',
    clear: 'سڕینەوە',
    rewardChip: 'دیاری چاپکەر: {state}',
    openInGifts: 'لە دیاری چاپکەرەکاندا بیکەرەوە',
  },

  queue: {
    intro: 'ئەو هەڵسەنگاندنانەی چاپکەر کە خۆکارانە چوونە ناو بەرنامەی دیاری: 5 ئەستێرە، دەقی ڕاستەقینە و چاپکەرێک کە لە ناوەندی گەرەنتی بە هەژماری خاوەنەکەی بەستراوە. تەنها بەڕێوەبەر ئاست هەڵدەبژێرێت و کۆد دەردەکات.',
    legacy: 'هەڵسەنگاندنێکی کۆنە کە پێش یاسا نوێیەکان هاتووە و بە هیچ یەکەیەک نەبەستراوە، بۆیە ناتوانرێت کۆدی بۆ دەربکرێت.',
    instagram: 'بەڵگەی ئینستاگرام (کۆن، تایبەت)',
    evidenceFile: 'فایلی بارکراو',
  },

  checklist: {
    title: 'مەرجەکانی چوونە ناو بەرنامەی دیاری',
    condition: 'مەرج',
    atEntry: 'لە کاتی چوونە ناو',
    now: 'ئێستا',
    met: 'جێبەجێ بووە',
    notMet: 'جێبەجێ نەبووە',
    unknown: 'نەزانراو',
    excluded: 'ئەو هۆکارانەی ڕێگری لە دیاری دەکەن',
    liveFailing: 'هەندێک مەرج ئێستا جێبەجێ نەبوون، بۆیە کۆد دەرناکرێت.',
    noLive: 'ئێستا نەتوانرا مەرجەکان بپشکنرێن؛ ڕاژەکار لە کاتی دەرکردن دووبارە دەیانپشکنێت.',
    checks: {
      buyer: 'خاوەنی هەڵسەنگاندنەکە کڕیارەکەیە',
      delivered: 'داواکارییەکە گەیەنراوە',
      printer: 'چاپکەری FDM، ڕەزن یان لەیزەر',
      unit: 'یەکەیەکی ڕاستەقینەی چاپکەرەکە هەیە',
      unit_owned: 'یەکەکە هی خاوەنی هەڵسەنگاندنەکەیە',
      registered_to_reviewer: 'چاپکەرەکە لە ناوەندی گەرەنتی بە هەژمارەکەیەوە بەستراوە',
      five_stars: 'هەڵسەنگاندنی 5 ئەستێرە',
      text_ok: 'دەقی ڕاستەقینە بە لانیکەم 30 پیت',
      user_authored: 'کڕیار نووسیویەتی (هەڵسەنگاندنی خۆکار نییە)',
      unit_not_rewarded: 'ئەم یەکەیە پێشتر هیچ خەڵاتێکی پێنەدراوە',
    },
    exclusions: {
      gift_line: 'یەکەکە لە هێڵێکی دیاری هاتووە',
      refunded: 'پارەی یەکەکە گەڕێنراوەتەوە',
      traded_in: 'یەکەکە لە گۆڕینەوەدا (Trade-in) ڕادەستکراوە',
    },
  },

  quality: {
    title: 'کوالیتی هەڵسەنگاندن (تەنها بۆ ڕێنمایی)',
    score: 'نمرە: {score} لە 100',
    reasons: 'هۆکارەکان',
    signals: 'ئەو نیشانانەی شایانی پشکنینن',
    note: 'ئەم نمرەیە ئاست دیاری ناکات؛ ئاست بڕیاری خۆتە.',
  },

  decision: {
    title: 'بڕیاری دیاری',
    mode: 'شێوازی دیاری',
    modeLevel: 'بەکارهێنانی دیارییەکانی ئاست',
    modeManual: 'هەڵبژاردنی دیاری بە دەست',
    level: 'ئاستی دیاری (1–5)',
    levelHint: 'ئاستەکە بەپێی کوالیتی دەق و وێنە و ڤیدیۆکە هەڵبژێرە. هیچ شتێک پێشوەختە هەڵنەبژێردراوە.',
    levelN: 'ئاستی {n}',
    levelNone: 'هێشتا هیچ ئاستێک هەڵنەبژێردراوە',
    levelItems: 'دیارییەکانی ئاستی {n} ({count}) — کڕیار یەکێکیان هەڵدەبژێرێت:',
    levelItemsLoading: 'دیارییەکانی ئاستەکان باردەکرێن…',
    manualPick: 'بەرهەمێک هەڵبژێرە…',
    manualChange: 'گۆڕین',
    manualNone: 'هێشتا هیچ دیارییەک هەڵنەبژێردراوە',
    manualFixed: 'دیارییەکی جێگیرە: کڕیار ناتوانێت بیگۆڕێت.',
    note: 'تێبینی ناوخۆیی (ئارەزوومەندانە)',
    notePlaceholder: 'بۆچی ئەم ئاستە؟ تێبینی لەسەر وێنە و ڤیدیۆکان…',
    issue: 'پشتڕاستکردنەوە و دەرکردنی کۆد',
    issuing: 'دەردەکرێت…',
    confirmTitle: 'کۆدی دیاری ئاستی {n} دەربکرێت؟',
    confirmLevelBody: 'بۆ {customer}، لە دیارییەکانی ئاستی {n}. کۆدەکە تەنها یەک جار دوای پشتڕاستکردنەوە دەردەکەوێت؛ کۆپی بکە و بۆ کڕیاری بنێرە.',
    confirmManualBody: 'بۆ {customer}: {gift}. کۆدەکە تەنها یەک جار دوای پشتڕاستکردنەوە دەردەکەوێت؛ کۆپی بکە و بۆ کڕیاری بنێرە.',
    blocked: {
      decided: 'پێشتر بڕیار لەسەر ئەم دیارییە دراوە.',
      system: 'هەڵسەنگاندنە خۆکارەکان خەڵات وەرناگرن.',
      legacy: 'هەڵسەنگاندنێکی کۆنە کە بە یەکەیەک نەبەستراوە: ناتوانرێت کۆدی بۆ دەربکرێت.',
      notEligibleNow: 'هەندێک مەرج ئێستا جێبەجێ نەبوون، بۆیە کۆد دەرناکرێت.',
      needLevel: 'سەرەتا ئاستەکە هەڵبژێرە.',
      levelEmpty: 'هیچ دیارییەکی چالاک لەم ئاستەدا نییە. بەرهەمێک زیاد بکە یان دیارییەک بە دەست هەڵبژێرە.',
      needManual: 'سەرەتا دیارییەکە هەڵبژێرە.',
    },
    reject: 'ڕەتکردنەوەی دیاری',
    rejectTitle: 'ڕەتکردنەوەی دیاری ئەم هەڵسەنگاندنە',
    rejectBody: 'هەڵسەنگاندنەکە بڵاوکراوە دەمێنێتەوە؛ تەنها دیارییەکە ڕەتدەکرێتەوە.',
    requestChanges: 'داواکردنی گۆڕانکاری',
    requestChangesTitle: 'داوای گۆڕانکاری لە کڕیار بکە',
    rejected: 'دیارییەکە ڕەتکرایەوە.',
    changesRequested: 'داوا لە کڕیار کرا هەڵسەنگاندنەکەی بگۆڕێت.',
    decidedReason: 'بڕیار: {reason}',
    decidedBy: 'لەلایەن {who} لە {date}',
    approvePoints: 'پەسەندکردن و بەخشینی {n} خاڵ',
    pointsUnconfigured: 'بەهای خاڵی هەڵسەنگاندن دیاری نەکراوە؛ تا دیاری نەکرێت خەڵاتی خاڵ پەسەند ناکرێت.',
    pointsAwarded: '{n} خاڵ بەخشرا.',
    approvePointsTitle: 'پەسەندکردنی خەڵاتی خاڵ',
    reasonLabel: 'هۆکار (تۆمار دەکرێت)',
    replayed: 'پێشتر کۆدێک بۆ ئەم هەڵسەنگاندنە دەرچووە و دووبارە پیشان نادرێتەوە. «هەڵوەشاندنەوە و دەرکردنی کۆدی نوێ» بەکاربهێنە.',
  },

  entitlement: {
    title: 'دیاری و کۆد',
    states: {
      available: 'کۆن — بەردەستە',
      selected: 'کۆن — ئامادە دەکرێت',
      code_issued: 'کۆد دەرچووە — چاوەڕێی وەرگرتنەوەیە',
      redeemed_ready_to_order: 'وەرگیرایەوە — ئامادەیە بۆ داواکردن',
      in_cart: 'لە سەبەتەی کڕیاردایە',
      ordered: 'داواکراوە',
      fulfilled: 'گەیەنرا',
      cancelled: 'هەڵوەشێنرایەوە',
    },
    code: 'کۆد',
    codeStates: {
      none: 'کۆد نییە',
      issued: 'کارایە',
      redeemed: 'بەکارهاتووە',
      revoked: 'هەڵوەشێنراوەتەوە',
    },
    attempts: 'هەوڵە هەڵەکان: {n} لە 5',
    locked: 'دوای 5 هەوڵی هەڵە داخراوە — کۆدێکی نوێ دەربکە.',
    issuedAt: 'لە {date} لەلایەن {who} دەرچووە',
    redeemedAt: 'لە {date} وەرگیرایەوە',
    modes: {
      level: 'لە دیارییەکانی ئاست',
      manual: 'دیاری بە دەست',
      legacy: 'دیاری کۆن (سندوق)',
    },
    levelMode: 'ئاستی {n} · {mode}',
    codeHidden: 'کۆدەکە دوای داخستنی پەنجەرەکەی هەرگیز دووبارە پیشان نادرێتەوە.',
    reissue: 'هەڵوەشاندنەوە و دەرکردنی کۆدی نوێ',
    reissueTitle: 'هەڵوەشاندنەوەی کۆدی ئێستا و دەرکردنی کۆدێکی نوێ',
    reissueBody: 'کۆدە کۆنەکە یەکسەر لە کار دەکەوێت و کۆدە نوێیەکە تەنها یەک جار دەردەکەوێت. هۆکارەکە تۆمار دەکرێت.',
    revoke: 'هەڵوەشاندنەوەی کۆد',
    revokeTitle: 'هەڵوەشاندنەوەی کۆد بێ دەرکردنی کۆدێکی نوێ',
    revokeBody: 'کۆدی ئێستا کار ناکات. دەتوانیت دواتر کۆدێکی نوێ دەربکەیت.',
    revoked: 'کۆدەکە هەڵوەشێنرایەوە.',
    cancel: 'هەڵوەشاندنەوەی دیاری',
    cancelTitle: 'هەڵوەشاندنەوەی ئەم دیارییە',
    cancelBody: 'کۆدەکە هەڵدەوەشێتەوە و هێڵی دیاری لە سەبەتەی کڕیار لادەبرێت ئەگەر لەوێ بێت. ناگەڕێتەوە.',
    cancelled: 'دیارییەکە هەڵوەشێنرایەوە.',
    fulfil: 'پشتڕاستکردنەوەی گەیاندن',
    fulfilled: 'گەیاندن تۆمار کرا.',
    convert: 'دەرکردنی کۆد بۆ ئەم دیارییە کۆنە',
    orderedHint: 'دیارییەکە داواکراوە: لە جیاتی دیارییەکە، داواکارییەکە هەڵبوەشێنەوە.',
    order: 'داواکاری {id}',
  },

  code: {
    title: 'کۆدی دیاری دەرچوو',
    once: 'ئەم کۆدە تەنها یەک جار پیشان دەدرێت. ئێستا کۆپی بکە و بۆ کڕیاری بنێرە.',
    label: 'کۆدی دیاریی 6 ژمارەیی',
    copy: 'کۆپیکردنی کۆد',
    copied: 'کۆدەکە کۆپی کرا',
    copyFailed: 'بە شێوەی خۆکار کۆپی نەکرا. ژمارەکان دیاری بکە و بە دەست کۆپییان بکە.',
    facts: '{customer} · ئاستی {level}',
    done: 'تەواو — داخستن',
    closeTitle: 'بێ کۆپیکردنی کۆدەکە دابخرێت؟',
    closeBody: 'ئەم کۆدە هەرگیز دووبارە پیشان نادرێتەوە. ئەگەر ونت کرد، «هەڵوەشاندنەوە و دەرکردنی کۆدی نوێ» بەکاربهێنە.',
    closeAnyway: 'داخستن بێ کۆپیکردن',
  },

  levels: {
    intro: 'هەر ئاستێک لیستێکی بەرهەمی ڕاستەقینەی فرۆشگایە. دوای وەرگرتنەوەی کۆد، کڕیار یەک بەرهەم لە دیارییەکانی ئاستەکەی هەڵدەبژێرێت.',
    picker: 'ئاست',
    activeCount: '{n} چالاک',
    header: 'ئاستی {n} — دیارییە چالاکەکان: {count}',
    add: 'زیادکردنی بەرهەم',
    empty: 'هێشتا هیچ دیارییەک لەم ئاستەدا نییە.',
    active: 'چالاک',
    activeHint: 'دیاریی ناچالاک ناچێتە ناو کۆدە نوێیەکانەوە.',
    disabled: 'بە کاتی ناچالاکە',
    moveUp: 'جوڵاندن بۆ سەرەوە',
    moveDown: 'جوڵاندن بۆ خوارەوە',
    edit: 'دەستکاری',
    remove: 'سڕینەوە',
    removeTitle: 'ئەم دیارییە لە ئاستی {n} بسڕدرێتەوە؟',
    removeBody: 'دیارییە بەخشراوەکانی پێشوو کۆپی خۆیان دەپارێزن و کاریگەر نابن.',
    removed: 'دیارییەکە سڕایەوە.',
    saved: 'دیارییەکە پاشەکەوت کرا.',
    legacyItem: 'دانەیەکی کۆنە تەنها بە ناو (بەرهەمی فرۆشگا نییە)، بۆ دیارییە نوێیەکان بەکارنایەت.',
    customerPicks: 'کڕیار هەڵدەبژێرێت لە: {list}',
    customerPicksCount: 'کڕیار لە {n} هەڵبژاردن هەڵدەبژێرێت',
    warnings: {
      archived: 'بەرهەمەکە ئەرشیف کراوە یان ناچالاکە',
      out_of_stock: 'ئێستا لە کۆگادا نەماوە',
      selection_gone: 'هەڵبژاردن یان ڕەنگی دیاریکراو ئیتر نەماوە',
      sale_type_unavailable: 'جۆری فرۆشتنی دیاریکراو ئێستا بەردەست نییە',
      unknown: 'ئاگاداری: {code}',
    },
  },

  sheet: {
    addTitle: 'زیادکردنی دیاری — ئاستی {n}',
    editTitle: 'دەستکاریکردنی دیاری — ئاستی {n}',
    manualTitle: 'دیارییەکی بە دەست بۆ ئەم هەڵسەنگاندنە',
    saveToLevel: 'پاشەکەوتکردن لە ئاستی {n}',
    useGift: 'ئەم دیارییە بەکاربهێنە',
    saving: 'پاشەکەوت دەکرێت…',
    product: 'بەرهەمی فرۆشگا',
    productHint: 'بە ناو یان کۆد بگەڕێ. کۆمەڵە و پێشکەشکراوە نادیارەکان نابنە دیاری.',
    optionsLoading: 'هەڵبژاردنەکانی بەرهەمەکە باردەکرێن…',
    saleType: 'جۆری فرۆشتن',
    saleTypes: {
      direct_sale: 'فرۆشتنی ڕاستەوخۆ',
      pre_order: 'پێش-داواکاری',
    },
    saleTypeUnavailable: 'بۆ ئەم بەرهەمە بەردەست نییە',
    pinOne: 'یەک بەهای جێگیر',
    customerChooses: 'کڕیار لە لیستێکی دیاریکراو هەڵدەبژێرێت',
    color: 'ڕەنگ',
    colorNotLinked: 'لەگەڵ هەڵبژاردنە دیاریکراوەکە ناگونجێت',
    transport: 'ڕێگای گواستنەوە (پێش-داواکاری)',
    transports: {
      air: 'ئاسمانی',
      sea: 'دەریایی',
      land: 'وشکانی',
    },
    activeLabel: 'لە ئاستەکەدا چالاکە',
    preview: 'پێشبینینی دیاری',
    previewing: 'دەپشکنرێت…',
    previewOk: 'هەڵبژاردنەکە دروستە',
    price: 'نرخی لە فرۆشگا: {price}',
    fixFirst: 'پێش پاشەکەوتکردن ئەمانە تەواو بکە:',
    problems: {
      needProduct: 'بەرهەمێک لە فرۆشگا هەڵبژێرە.',
      composition: 'کۆمەڵە و پێشکەشکراوە نادیارەکان ناتوانن ببنە دیاری.',
      needSaleType: 'جۆری فرۆشتن هەڵبژێرە.',
      saleTypeNotOffered: 'جۆری فرۆشتنی هەڵبژێردراو بۆ ئەم بەرهەمە بەردەست نییە.',
      needTransport: 'ڕێگای گواستنەوە بۆ پێش-داواکارییەکە هەڵبژێرە.',
      needGroup: 'بەهایەک بۆ «{group}» دیاری بکە یان ڕێگە بدە کڕیار لە لیستێک هەڵبژێرێت.',
      needGroupManual: 'بەهایەک بۆ «{group}» هەڵبژێرە.',
      allowedEmpty: 'لانیکەم یەک بەها لە لیستی کڕیار بۆ «{group}» هەڵبژێرە.',
      needColor: 'ڕەنگێک دیاری بکە یان ڕێگە بدە کڕیار لە لیستی ڕەنگەکان هەڵبژێرێت.',
      needColorManual: 'ڕەنگەکە هەڵبژێرە.',
      allowedColorsEmpty: 'لانیکەم یەک ڕەنگ لە لیستی کڕیار هەڵبژێرە.',
      colorMismatch: 'ڕەنگی هەڵبژێردراو لەگەڵ هەڵبژاردنە دیاریکراوەکە ناگونجێت.',
    },
  },

  granted: {
    intro: 'هەموو دیارییە بەخشراوەکان، لەگەڵ دۆخی کۆد و داواکارییەکەیان.',
    filters: {
      all: 'هەموو',
      code_issued: 'چاوەڕێی وەرگرتنەوە',
      redeemed_ready_to_order: 'ئامادەیە بۆ داواکردن',
      ordered: 'داواکراوە',
      fulfilled: 'گەیەنراوە',
      cancelled: 'هەڵوەشێنراوەتەوە',
      legacy: 'کۆن',
    },
    gift: 'دیاری',
    chooseOne: 'کڕیار یەکێک لە {n} دیاری هەڵدەبژێرێت',
    legacyContents: 'ناوەڕۆکی سندوقی کۆن',
    printer: 'چاپکەر',
    grantedAt: 'بەرواری بەخشین',
    noGift: 'هێشتا دیارییەکە هەڵنەبژێردراوە',
  },

  errors: {
    generic: 'کردارەکە سەرکەوتوو نەبوو. دووبارە هەوڵ بدەرەوە.',
    conflict: 'لەو ماوەیەدا دۆخەکە گۆڕا. لیستەکە نوێ بکەرەوە و دووبارە هەوڵ بدەرەوە.',
    network: 'نەتوانرا پەیوەندی بە ڕاژەکارەوە بکرێت. پەیوەندییەکە بپشکنە و دووبارە هەوڵ بدەرەوە؛ دووبارەکردنەوە هەرگیز کۆدی دووەم دەرناکات.',
    rateLimited: 'هەوڵی زۆر دراوە. کەمێک چاوەڕێ بکە و دووبارە هەوڵ بدەرەوە.',
  },
};

export const ADMIN_REVIEW_STRINGS: Record<Lang, AdminReviewStrings> = { ar: AR, en: EN, ckb: CKB };

export function adminStrings(lang: string): AdminReviewStrings {
  return lang === 'en' ? EN : lang === 'ckb' ? CKB : AR;
}

/**
 * THE ADMIN-ONLY REFUSAL CODES (docs/REVIEWS_GIFTS.md §9, «Admin-only codes»),
 * plus the admin codes the doc's tables lack (named in the C2 handoff) and the
 * store's own selection codes the configurator can receive in `errors`.
 */
export const ADMIN_REFUSALS: Record<string, Record<Lang, string>> = {
  GIFT_LEVEL_REQUIRED: {
    ar: 'اختر مستوى الهدية من 1 إلى 5.',
    en: 'Choose the gift level, 1 to 5.',
    ckb: 'ئاستی دیارییەکە لە 1 تا 5 هەڵبژێرە.',
  },
  GIFT_LEVEL_EMPTY: {
    ar: 'لا توجد هدايا فعّالة في هذا المستوى. أضف منتجًا أو اختر هدية يدويًا.',
    en: 'This level has no active gifts. Add a product or choose a gift manually.',
    ckb: 'هیچ دیارییەکی چالاک لەم ئاستەدا نییە. بەرهەمێک زیاد بکە یان دیارییەک بە دەست هەڵبژێرە.',
  },
  GIFT_ELIGIBILITY_CHANGED: {
    ar: 'لم تعد المراجعة مؤهلة (تغيّر ربط الطابعة أو النجوم أو الطلب).',
    en: 'The review is no longer eligible (printer link, stars or order changed).',
    ckb: 'هەڵسەنگاندنەکە ئیتر شایستە نییە (بەستنەوەی چاپکەر، ئەستێرەکان یان داواکارییەکە گۆڕاوە).',
  },
  GIFT_ALREADY_ISSUED: {
    ar: 'صدر كود لهذه المراجعة ولا يُعرض مرة أخرى. استخدم «إلغاء وإصدار كود جديد».',
    en: 'A code was already issued and is never shown again. Use “Revoke and issue a new code”.',
    ckb: 'پێشتر کۆدێک دەرچووە و دووبارە پیشان نادرێتەوە. «هەڵوەشاندنەوە و دەرکردنی کۆدی نوێ» بەکاربهێنە.',
  },
  GIFT_COMPOSITION_UNSUPPORTED: {
    ar: 'الحزم والعروض الغامضة لا يمكن أن تكون هدية.',
    en: 'Bundles and mystery offers cannot be gifts.',
    ckb: 'کۆمەڵە و پێشکەشکراوە نادیارەکان ناتوانن ببنە دیاری.',
  },
  GIFT_SELECTION_INVALID: {
    ar: 'الخيار أو اللون المختار لا يخص هذا المنتج أو غير متاح.',
    en: 'The chosen option or colour does not belong to this product or is unavailable.',
    ckb: 'هەڵبژاردن یان ڕەنگی هەڵبژێردراو سەر بەم بەرهەمە نییە یان بەردەست نییە.',
  },
  GIFT_TRANSPORT_REQUIRED: {
    ar: 'اختر طريق الشحن للطلب المسبق.',
    en: 'Choose the shipping route for the pre-order.',
    ckb: 'ڕێگای گواستنەوە بۆ پێش-داواکارییەکە هەڵبژێرە.',
  },
  GIFT_ORDER_REOPEN_REFUSED: {
    ar: 'لا يُعاد فتح طلب فيه هدية بعد إلغائه؛ عادت الهدية للزبون ليطلبها من جديد.',
    en: 'An order holding a gift cannot be re-opened; the gift went back to the customer to order again.',
    ckb: 'داواکارییەک کە دیاری تێدایە دووبارە ناکرێتەوە؛ دیارییەکە گەڕایەوە بۆ کڕیار تا دووبارە داوای بکات.',
  },
  // ---- admin codes the §9 tables lack (C2 handoff) --------------------
  GIFT_NOT_CONVERTIBLE: {
    ar: 'لا يمكن تحويل هذه الهدية القديمة إلى كود؛ فقط الهدية القديمة «المتاحة» تتحول.',
    en: 'This legacy gift cannot be converted to a code; only an “available” legacy gift can.',
    ckb: 'ئەم دیارییە کۆنە ناگۆڕدرێت بۆ کۆد؛ تەنها دیاریی کۆنی «بەردەست» دەگۆڕدرێت.',
  },
  GIFT_ITEM_CHOICES_INVALID: {
    ar: 'خيارات هذه الهدية غير مكتملة: لكل خيار قيمة ثابتة أو قائمة يختار منها العميل.',
    en: "This gift's choices are incomplete: every option needs a fixed value or a list the customer picks from.",
    ckb: 'هەڵبژاردنەکانی ئەم دیارییە تەواو نین: هەر هەڵبژاردنێک پێویستی بە بەهایەکی جێگیر یان لیستێکە کە کڕیار لێی هەڵبژێرێت.',
  },
  GIFT_PRODUCT_NOT_FOUND: {
    ar: 'المنتج غير موجود في المتجر.',
    en: 'The product is not in the store.',
    ckb: 'بەرهەمەکە لە فرۆشگادا نییە.',
  },
  GIFT_PRODUCT_INACTIVE: {
    ar: 'المنتج غير فعّال في المتجر. فعّله أو اختر منتجًا آخر.',
    en: 'The product is not active in the store. Activate it or choose another product.',
    ckb: 'بەرهەمەکە لە فرۆشگادا چالاک نییە. چالاکی بکە یان بەرهەمێکی تر هەڵبژێرە.',
  },
  SYSTEM_REVIEW_NO_REWARD: {
    ar: 'التقييمات التلقائية لا تحصل على مكافأة.',
    en: 'Automatic ratings do not earn a reward.',
    ckb: 'هەڵسەنگاندنە خۆکارەکان خەڵات وەرناگرن.',
  },
  REVIEW_POINTS_UNCONFIGURED: {
    ar: 'قيمة نقاط المراجعة غير مُعدّة؛ لا يمكن اعتماد مكافأة نقاط قبل إعدادها.',
    en: 'The review points value is not set; a points reward cannot be approved until it is.',
    ckb: 'بەهای خاڵی هەڵسەنگاندن دیاری نەکراوە؛ تا دیاری نەکرێت خەڵاتی خاڵ پەسەند ناکرێت.',
  },
  // ---- the store's own selection codes (validateSelection), in the configurator
  OPTION_VALUE_NOT_FOUND: {
    ar: 'أحد الخيارات لا يخص هذا المنتج.',
    en: 'One of the options does not belong to this product.',
    ckb: 'یەکێک لە هەڵبژاردنەکان سەر بەم بەرهەمە نییە.',
  },
  OPTION_VALUE_INACTIVE: {
    ar: 'أحد الخيارات معطّل في المتجر.',
    en: 'One of the options is disabled in the store.',
    ckb: 'یەکێک لە هەڵبژاردنەکان لە فرۆشگادا ناچالاکە.',
  },
  OPTION_GROUP_DUPLICATE_SELECTION: {
    ar: 'اختير أكثر من قيمة في الخيار نفسه.',
    en: 'More than one value was chosen in the same option.',
    ckb: 'لە هەمان هەڵبژاردندا زیاتر لە یەک بەها هەڵبژێردراوە.',
  },
  OPTION_GROUP_REQUIRED: {
    ar: 'خيار مطلوب لم يُحدَّد.',
    en: 'A required option is not set.',
    ckb: 'هەڵبژاردنێکی پێویست دیاری نەکراوە.',
  },
  COLOR_NOT_FOUND: {
    ar: 'اللون لا يخص هذا المنتج.',
    en: 'The colour does not belong to this product.',
    ckb: 'ڕەنگەکە سەر بەم بەرهەمە نییە.',
  },
  COLOR_INACTIVE: {
    ar: 'اللون معطّل في المتجر.',
    en: 'The colour is disabled in the store.',
    ckb: 'ڕەنگەکە لە فرۆشگادا ناچالاکە.',
  },
  COLOR_OPTION_MISMATCH: {
    ar: 'اللون المختار غير مرتبط بالخيار المحدد.',
    en: 'The chosen colour is not linked to the chosen option.',
    ckb: 'ڕەنگی هەڵبژێردراو بە هەڵبژاردنە دیاریکراوەکەوە نەبەستراوە.',
  },
  COLOR_REQUIRED: {
    ar: 'هذا المنتج يحتاج إلى لون.',
    en: 'This product needs a colour.',
    ckb: 'ئەم بەرهەمە پێویستی بە ڕەنگێکە.',
  },
};

/** The admin sentence for a refusal code, or null when the code is not an admin one. */
export function adminRefusal(code: string | null | undefined, lang: string): string | null {
  if (!code) return null;
  const entry = ADMIN_REFUSALS[code];
  if (!entry) return null;
  return entry[lang === 'en' ? 'en' : lang === 'ckb' ? 'ckb' : 'ar'];
}
