/**
 * THE STUDIO'S WORDS IN ARABIC — one language's file, loaded on its own
 * (./strings.ts `studioWords`): the studio carries only the language on
 * the screen. The shape, the rules and the customer vocabulary are
 * ./strings.ts; tests/personalizeUi.test.ts checks the three files key by key.
 */
import type { StudioWords } from './strings';

const AR: StudioWords = {
  close: 'إغلاق',
  options: 'خيارات أخرى',
  startOver: 'ابدأ من جديد',
  undo: 'تراجع',
  resetView: 'أعد العرض',
  preview: 'معاينة',
  previewChip: 'معاينة: هكذا يراها زبونك',
  stageLabel: 'معاينة {product}',
  partColour: '{part}: {colour}',
  textOn: '{label}: «{text}»',
  loading: 'نجهّز المعاينة…',
  noLive: 'المعاينة الحية غير متاحة على هذا الجهاز — اختياراتك محفوظة كما هي.',
  showLive: 'اعرض المعاينة الحية',
  saveData: 'وفّرنا بياناتك بصورة ثابتة.',
  unavailable: 'لا يمكن تصميم هذا المنتج الآن',
  unavailableHint: 'جرّب لاحقًا أو تواصل مع المتجر.',
  tiles: { name: 'الاسم', text: 'النص', photo: 'الصورة', logo: 'الشعار', qr: 'رمز QR', icon: 'الأيقونة', look: 'الألوان', size: 'المقاس', addons: 'الإضافات', more: 'المزيد' },
  controls: 'التصميم',
  add: 'أضف',
  added: 'مضاف',
  pages: '{n} خيارات',
  door: { add_to_cart: 'أضف إلى السلة', request: 'اطلب الطباعة', ask: 'اسأل المتجر' },
  doorBlocked: 'أكمل ما ينقص أولًا',
  doorPreview: 'هذا زر زبونك — لا يُرسل شيء في المعاينة.',
  price: 'السعر',
  ready: 'جاهز للطباعة',
  apply: 'طبّق',
  useSize: 'استخدم {size}',
  useOption: 'استخدم {option}',
  better: 'اجعله أجمل',
  fixIt: 'أصلحه',
  entry: '{label} {n}',
  left: 'المتبقي {n}',
  lettersOnly: 'حروف وأرقام فقط',
  style: 'الأسلوب',
  icon: 'أيقونة',
  none: 'بدون',
  themes: 'السمات',
  chooseForMe: 'اختر لي',
  tryAnother: 'جرّب غيره',
  surprise: 'فاجئني',
  parts: 'الأجزاء',
  colourOf: 'لون {name}',
  plate: { name: 'لوحة الاسم', text: 'لوحة النص' },
  addPiece: 'أضف {part}',
  matched: 'يُطبع بـ{name}',
  approx: 'الألوان على الشاشة تقريبية.',
  look: 'المظهر',
  tier: 'الجودة',
  sizes: ['صغير جدًا', 'صغير', 'متوسط', 'كبير', 'كبير جدًا'],
  recommended: 'المقترح',
  dims: '≈ {dims} سم',
  soldOut: 'نفد',
  samePrice: 'السعر نفسه',
  more: 'المزيد',
  back: 'المزيد',
  nfc: 'المس بهاتفك',
  notes: 'ملاحظة للمتجر',
  notesHint: 'اختياري — مثل «غلّفه كهدية».',
  ask: 'اطلب تعديلات من المتجر',
  askHint: 'تصلك الإجابة في محادثتك مع المتجر.',
  required: 'مطلوب',
  addPhoto: 'أضف صورتك',
  addLogo: 'أضف شعارك',
  change: 'غيّر',
  remove: 'إزالة',
  localOnly: 'في المعاينة تبقى الصورة على جهازك.',
  qrField: { handle: 'اسم الحساب', phone: 'رقم الهاتف', link: 'الرابط', text: 'ما يُكتب في الشريحة' },
  qrCheck: 'تحقّق مما كتبت.',
  scansWell: 'يُقرأ بسهولة',
  reorderLater: 'يُضاف رابط إعادة الطلب حين تطلب.',
  shopSees: 'يجهّزها المتجر وسيرى ما تكتبه.',
  check: {
    TEXT_FITTED: 'صغّرنا الكتابة قليلًا لتتّسع.',
    TEXT_TWO_LINES: 'كتبناها على سطرين لتبقى واضحة.',
    TEXT_STYLE_BOLDER: 'استخدمنا خطًا أعرض لتُطبع بوضوح.',
    COLOR_MATCHED: '{from} غير متوفر هنا، فاستخدمنا الأقرب: {to}.',
    COLORS_MERGED: 'دمجنا لونين متقاربين.',
    CONTRAST_FIXED: 'غيّرنا لون الخلفية ليُقرأ الرمز.',
    QR_ENLARGED: 'كبّرنا المقاس بالسعر نفسه ليُقرأ الرمز.',
    LOGO_SIMPLIFIED: 'بسّطنا ألوان الشعار لتُطبع بدقة.',
    RULE_ADJUSTED: 'عدّلنا اختيارًا ليناسب القطعة.',
    SIZE_UP_FOR_TEXT: 'الكتابة طويلة على هذا المقاس.',
    SIZE_UP_FOR_QR: 'الرمز صغير على هذا المقاس.',
    SIZE_UP_FOR_ADDON: 'هذه الإضافة تحتاج مقاسًا أكبر.',
    LOGO_DETAIL: 'شعارك مفصّل، سيراجعه المتجر أولًا.',
    PHOTO_LOW_RES: 'الصورة صغيرة قليلًا، سيراجعها المتجر.',
    PHOTO_NEEDS_CUTOUT: 'سيقصّ المتجر خلفية الصورة.',
    TOO_BIG_FOR_PRINTER: 'هذا المقاس كبير على المتجر، سيراجعه أولًا.',
    TEXT_TOO_LONG: 'الكتابة أطول من مكانها — اختصرها قليلًا.',
    COMPONENT_OUT: '{from} نفد من المتجر.',
    COLOR_OUT: '{from} غير متوفر لهذا الجزء — اختر لونًا آخر.',
    SIZE_OUT: 'هذا المقاس نفد.',
    QR_UNREADABLE: 'لن يُقرأ الرمز هكذا — جرّب رابطًا أقصر.',
    CONTENT_MISSING: 'ينقص شيء قبل المتابعة.',
    RULE_UNMET: 'هذا الاختيار يحتاج تعديلًا.',
  },
  checkAsk: {
    COLOR_MATCHED: '{from} غير متوفر هنا، والأقرب {to}.',
    COLORS_MERGED: 'ألوان كثيرة لهذه القطعة.',
    CONTRAST_FIXED: 'الرمز يحتاج خلفية أوضح ليُقرأ.',
    TEXT_STYLE_BOLDER: 'خط أعرض يُطبع بوضوح أكبر.',
    TEXT_FITTED: 'الكتابة تتّسع في مقاس آخر.',
    LOGO_SIMPLIFIED: 'الشعار يُطبع أدق بألوان أقل.',
    QR_ENLARGED: 'الرمز يُقرأ أفضل في مقاس أكبر.',
  },
  missing: {
    texts: 'اكتب {what} للمتابعة.',
    logo: 'أضف شعارك للمتابعة.',
    photo: 'أضف صورتك للمتابعة.',
    qr: 'أضف رابط الرمز للمتابعة.',
    icon: 'اختر أيقونة للمتابعة.',
    slots: 'اختر {what} للمتابعة.',
  },
  say: {
    text_needs_size: 'الكتابة الطويلة تحتاج مقاسًا أكبر.',
    addon_needs_size: 'هذه الإضافة تحتاج مقاسًا أكبر.',
    qr_needs_size: 'الرمز يحتاج مقاسًا أكبر ليُقرأ.',
    addon_needs_addon: 'هذه الإضافة تحتاج إضافة أخرى معها.',
    addons_conflict: 'هاتان الإضافتان لا تجتمعان.',
    look_limits_colors: 'هذا المظهر يأتي بألوان محددة.',
    fewer_colors: 'ألوان أقل تناسب هذه القطعة.',
  },
  betterSay: {
    CONTRAST_TEXT: 'الكتابة تُقرأ أوضح بلون آخر.',
    STOCKED_ONLY: 'استخدم ألوانًا متوفرة الآن.',
    FEWER_COLOURS: 'ألوان أقل تبدو أنظف.',
    STYLE_FOR_LENGTH: 'خط آخر يكبّر الكتابة.',
    BALANCE_ACCENT: 'لون مميّز للزخرفة يوازن الشكل.',
    LOGO_FIT: 'اعرض الشعار كاملًا.',
    THEME_MATCH: 'لون واحد يكمّل سمة متناسقة.',
  },
};

export default AR;
