/**
 * THE STUDIO'S WORDS IN ENGLISH — one language's file, loaded on its own
 * (./strings.ts `studioWords`): the studio carries only the language on
 * the screen. The shape, the rules and the customer vocabulary are
 * ./strings.ts; tests/personalizeUi.test.ts checks the three files key by key.
 */
import type { StudioWords } from './strings';

const EN: StudioWords = {
  close: 'Close',
  options: 'More options',
  startOver: 'Start over',
  undo: 'Undo',
  resetView: 'Reset the view',
  preview: 'Preview',
  previewChip: 'Preview: what your customer sees',
  stageLabel: 'Preview of {product}',
  partColour: '{part}: {colour}',
  textOn: '{label}: “{text}”',
  loading: 'Getting the preview ready…',
  noLive: 'The live preview isn’t available on this device — your choices are kept exactly.',
  showLive: 'Show the live preview',
  saveData: 'We saved your data with a still picture.',
  unavailable: 'This product can’t be personalized right now',
  unavailableHint: 'Try again later or contact the shop.',
  tiles: { name: 'Name', text: 'Text', photo: 'Photo', logo: 'Logo', qr: 'QR code', icon: 'Icon', look: 'Colours', size: 'Size', addons: 'Add-ons', more: 'More' },
  controls: 'Your design',
  add: 'Add',
  added: 'Added',
  pages: '{n} options',
  door: { add_to_cart: 'Add to cart', request: 'Request printing', ask: 'Ask the shop' },
  doorBlocked: 'Finish what’s missing first',
  doorPreview: 'This is your customer’s button — nothing is sent in the preview.',
  price: 'Price',
  ready: 'Ready to print',
  apply: 'Apply',
  useSize: 'Use {size}',
  useOption: 'Use {option}',
  better: 'Make it better',
  fixIt: 'Fix it',
  entry: '{label} {n}',
  left: '{n} left',
  lettersOnly: 'Letters and numbers only',
  style: 'Style',
  icon: 'Icon',
  none: 'None',
  themes: 'Themes',
  chooseForMe: 'Choose for me',
  tryAnother: 'Try another',
  surprise: 'Surprise me',
  parts: 'Parts',
  colourOf: '{name} colour',
  plate: { name: 'Name plate', text: 'Text plate' },
  addPiece: 'Add the {part}',
  matched: 'Printed in {name}',
  approx: 'Colours on screens are approximate.',
  look: 'Look',
  tier: 'Quality',
  sizes: ['Extra small', 'Small', 'Medium', 'Large', 'Extra large'],
  recommended: 'Recommended',
  dims: '≈ {dims} cm',
  soldOut: 'Sold out',
  samePrice: 'Same price',
  more: 'More',
  back: 'More',
  nfc: 'Tap with your phone',
  notes: 'Note for the maker',
  notesHint: 'Optional — like “wrap it as a gift”.',
  ask: 'Ask the shop for changes',
  askHint: 'The shop replies in your chat.',
  required: 'Required',
  addPhoto: 'Add your photo',
  addLogo: 'Add your logo',
  change: 'Change',
  remove: 'Remove',
  localOnly: 'In the preview the picture stays on your device.',
  qrField: { handle: 'Account name', phone: 'Phone number', link: 'Link', text: 'What the tag says' },
  qrCheck: 'Check what you typed.',
  scansWell: 'Scans easily',
  reorderLater: 'Your reorder link is added when you order.',
  shopSees: 'The shop sets it up and will see what you type.',
  check: {
    TEXT_FITTED: 'We made the writing a little smaller to fit.',
    TEXT_TWO_LINES: 'We put it on two lines so it stays clear.',
    TEXT_STYLE_BOLDER: 'We used a bolder style so it prints clearly.',
    COLOR_MATCHED: '{from} isn’t in stock here — we used the closest: {to}.',
    COLORS_MERGED: 'We merged two close colours.',
    CONTRAST_FIXED: 'We changed the background colour so the code scans.',
    QR_ENLARGED: 'We moved to a larger size at the same price so the code scans.',
    LOGO_SIMPLIFIED: 'We simplified the logo’s colours so it prints cleanly.',
    RULE_ADJUSTED: 'We adjusted a choice to suit the piece.',
    SIZE_UP_FOR_TEXT: 'The writing is long for this size.',
    SIZE_UP_FOR_QR: 'The code is small for this size.',
    SIZE_UP_FOR_ADDON: 'This add-on needs a larger size.',
    LOGO_DETAIL: 'Your logo is detailed — the shop will check it first.',
    PHOTO_LOW_RES: 'The photo is a little small — the shop will check it.',
    PHOTO_NEEDS_CUTOUT: 'The shop will cut out the photo’s background.',
    TOO_BIG_FOR_PRINTER: 'This size is big for the shop — they’ll check it first.',
    TEXT_TOO_LONG: 'The writing is longer than its space — shorten it a little.',
    COMPONENT_OUT: '{from} is sold out.',
    COLOR_OUT: '{from} isn’t available for this part — pick another colour.',
    SIZE_OUT: 'This size is sold out.',
    QR_UNREADABLE: 'The code won’t scan like this — try a shorter link.',
    CONTENT_MISSING: 'Something is missing before you continue.',
    RULE_UNMET: 'This choice needs a change.',
  },
  checkAsk: {
    COLOR_MATCHED: '{from} isn’t in stock here — the closest is {to}.',
    COLORS_MERGED: 'Too many colours for this piece.',
    CONTRAST_FIXED: 'The code needs a clearer background to scan.',
    TEXT_STYLE_BOLDER: 'A bolder style prints more clearly.',
    TEXT_FITTED: 'The writing fits in another size.',
    LOGO_SIMPLIFIED: 'The logo prints cleaner in fewer colours.',
    QR_ENLARGED: 'The code scans better in a larger size.',
  },
  missing: {
    texts: 'Type {what} to continue.',
    logo: 'Add your logo to continue.',
    photo: 'Add your photo to continue.',
    qr: 'Add the code’s link to continue.',
    icon: 'Pick an icon to continue.',
    slots: 'Choose {what} to continue.',
  },
  say: {
    text_needs_size: 'Longer writing needs a larger size.',
    addon_needs_size: 'This add-on needs a larger size.',
    qr_needs_size: 'The code needs a larger size to scan.',
    addon_needs_addon: 'This add-on needs another one with it.',
    addons_conflict: 'These two add-ons don’t go together.',
    look_limits_colors: 'This look comes in set colours.',
    fewer_colors: 'Fewer colours suit this piece.',
  },
  betterSay: {
    CONTRAST_TEXT: 'The writing reads better in another colour.',
    STOCKED_ONLY: 'Use colours the shop has now.',
    FEWER_COLOURS: 'Fewer colours look cleaner.',
    STYLE_FOR_LENGTH: 'Another style makes the writing larger.',
    BALANCE_ACCENT: 'An accent colour balances the look.',
    LOGO_FIT: 'Show the whole logo.',
    THEME_MATCH: 'One colour away from a matching theme.',
  },
};

export default EN;
