import LegacyInvestmentHistory from './LegacyInvestmentHistory';
import { useState } from 'react';
import { ChevronLeft, Plus, Pencil } from 'lucide-react';
import { NumberInput } from '../ui/NumberInput';
import { Select } from '../ui/Field';
import { api, Button, Dialog, Empty, Feedback, Field, Loading, Money, Surface, useLanguage, useMutation, useRemote, type Account, type PanelProps } from './shared';
import { investmentReturnStrings } from '../../lib/investmentReturn';

const API = '/api/admin/investment-finance';
type Profile = { user_id: string; name: string; email: string; state: string; version: number; default_profit_share_bps: number; default_capital_share_bps: number; default_loss_share_bps: number; capital: { agreed_iqd: number; received_iqd: number; used_iqd: number; allocated_iqd: number; unallocated_iqd: number; returned_surplus_iqd?: number; loss_iqd: number; recovered_iqd: number; paid_iqd: number; contracts_count: number }; balance: { investor_profit_iqd: number; investor_profit_available_iqd: number; earnings_paid_iqd: number; investor_profit_pending_iqd: number; investor_profit_debt_iqd: number }; period: { earned_iqd: number; paid_iqd: number; adjustments_iqd: number; recovered_capital_iqd: number } };
type Batch = { purchase_id: string; agreed_iqd: number; received_iqd: number; allocated_iqd: number; unallocated_iqd: number; returned_iqd?: number; funding_shortfall_iqd: number; profit_share_bps: number };
type Contract = { id: string; name: string; label: string; purchase_id: string; qty_ordered: number; qty_received: number; remaining_qty: number; delivered_qty: number; principal_iqd: number; profit_share_bps: number; state: string };
type List = { profiles: Profile[]; accounts: Account[]; totals: { agreed_iqd: number; received_iqd: number; available_profit_iqd: number; period_profit_iqd: number } };

export default function InvestorProfiles({ from, to, month, onChanged, openContract }: PanelProps & { openContract: (id: string) => void }) {
  const { loc, dir } = useLanguage();
  const query = new URLSearchParams(from || to ? { from: from || '', to: to || '' } : month ? { month } : {});
  const remote = useRemote<List>(`${API}/profiles?${query}`);
  const [editing, setEditing] = useState<Profile | 'new' | null>(null), [selected, setSelected] = useState<Profile | null>(null);
  const data = remote.data;
  const saved = async () => { setEditing(null); await remote.load(); onChanged?.(); };
  return <div className="ap fp fp-stack" dir={dir}>
    <Surface title={loc('حسابات المستثمرين', 'Investor accounts')} hint={loc('حساب واحد لكل مستثمر، وشروط مستقلة لكل دفعة. أرصدة الحساب تراكمية، ونتيجة الفترة حسب تاريخ التسليم.', 'One account per investor, with independent batch terms. Balances are cumulative; period earnings follow delivery dates.')} action={<Button variant="primary" icon={<Plus size={16} />} onClick={() => setEditing('new')}>{loc('إضافة مستثمر', 'Add investor')}</Button>}>
      {!data ? <Loading error={remote.error} retry={remote.load} /> : <><Feedback error={remote.error} /><div className="fp-stats">{[[loc('رأس المال المتفق عليه', 'Agreed capital'), data.totals.agreed_iqd], [loc('المستلم فعليًا', 'Actually received'), data.totals.received_iqd], [loc('أرباح الفترة', 'Period earnings'), data.totals.period_profit_iqd], [loc('متاح للسحب الآن', 'Available now'), data.totals.available_profit_iqd]].map(([title, n]) => <div className="fp-stat" key={String(title)}><span>{title}</span><Money value={Number(n)} /></div>)}</div>
      {!data.profiles.length ? <Empty>{loc('اختر حساب مساعد لإضافة مستثمر، ثم اختره في خطوة تمويل الشراء.', 'Choose an assistant account to register an investor, then select it when funding a purchase.')}</Empty> : <div className="fp-stack">{data.profiles.map((p) => <article className="fp-rule" key={p.user_id}><header className="fp-rule-heading fp-staff-heading"><button type="button" className="fp-account flex-1 text-start" onClick={() => setSelected(p)}><span className="fp-avatar">{(p.name || p.email).slice(0, 1)}</span><div><h3>{p.name || p.email}</h3><p>{p.state === 'archived' ? loc('مؤرشف · السجل محفوظ', 'Archived · history retained') : `${loc('نسبة الربح الافتراضية', 'Default profit share')} ${p.default_profit_share_bps / 100}%`} · {p.capital.contracts_count} {loc('اتفاق', 'agreements')}</p></div><ChevronLeft size={18} /></button><Button variant="ghost" size="sm" icon={<Pencil size={15} />} onClick={() => setEditing(p)}>{loc('تعديل', 'Edit')}</Button></header><div className="fp-stats">{[[loc('أرباح الفترة', 'Period earnings'), p.period.earned_iqd], [loc('المسدد في الفترة', 'Period payments'), p.period.paid_iqd], [loc('المتاح التراكمي', 'Cumulative available'), p.balance.investor_profit_available_iqd], [loc('رأس المال المتبقي في الحساب', 'Remaining account capital'), Math.max(0, p.capital.received_iqd - p.capital.paid_iqd - p.capital.loss_iqd)]].map(([title, n]) => <div className="fp-stat" key={String(title)}><span>{title}</span><Money value={Number(n)} /></div>)}</div><Button variant="ghost" onClick={() => setSelected(p)}>{loc('الدفعات ورأس المال والحركات', 'Batches, capital and activity')}</Button></article>)}</div>}</>}
    </Surface>
    <LegacyInvestmentHistory admin />
    {editing && data && <ProfileEditor profile={editing === 'new' ? undefined : editing} accounts={data.accounts.filter((a) => editing !== 'new' || !data.profiles.some((p) => p.user_id === a.id))} onClose={() => setEditing(null)} onSaved={saved} />}
    {selected && <ProfileDetail profile={selected} onClose={() => setSelected(null)} openContract={openContract} />}
  </div>;
}

function ProfileEditor({ profile, accounts, onClose, onSaved }: { profile?: Profile; accounts: Account[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const { loc } = useLanguage(), op = useMutation();
  const [user, setUser] = useState(profile?.user_id || ''), [profit, setProfit] = useState<number | null>(profile ? profile.default_profit_share_bps / 100 : 35), [capital, setCapital] = useState<number | null>(profile ? profile.default_capital_share_bps / 100 : 100), [loss, setLoss] = useState<number | null>(profile ? profile.default_loss_share_bps / 100 : 0), [state, setState] = useState(profile?.state || 'active');
  return <Dialog open onClose={onClose} busy={op.busy} title={profile ? loc('إعدادات المستثمر', 'Investor settings') : loc('إضافة مستثمر', 'Add investor')}><div className="fp-stack">
    {profile ? <h3>{profile.name || profile.email}</h3> : <Field label={loc('حساب المساعد', 'Assistant account')}><Select value={user} onChange={(e) => setUser(e.target.value)}><option value="">{loc('اختر الحساب', 'Choose account')}</option>{accounts.map((a) => <option value={a.id} key={a.id}>{a.name || a.email}</option>)}</Select></Field>}
    <Field label={loc('نسبة الربح الافتراضية', 'Default profit share')}><NumberInput value={profit} min={0} max={100} unit="%" onValueChange={(n, valid) => setProfit(valid ? n : null)} /></Field>
    <details className="fp-detail"><summary>{loc('التمويل والخسارة والحالة', 'Funding, loss and status')}</summary><div className="fp-stack"><Field label={loc('نسبة التمويل المقترحة', 'Suggested capital funding share')}><NumberInput value={capital} min={0.01} max={100} unit="%" onValueChange={(n, valid) => setCapital(valid ? n : null)} /></Field><Field label={loc('نسبة تحمّل الخسارة', 'Loss share')}><NumberInput value={loss} min={0} max={100} unit="%" onValueChange={(n, valid) => setLoss(valid ? n : null)} /></Field><Field label={loc('الحالة', 'State')}><Select value={state} onChange={(e) => setState(e.target.value)}><option value="active">{loc('نشط', 'Active')}</option><option value="archived">{loc('مؤرشف', 'Archived')}</option></Select></Field></div></details>
    <p className="fp-note">{loc('تطبق الإعدادات الافتراضية على الاتفاقات الجديدة فقط. رأس المال ونسبة الربح والخسارة ثلاث قيم مستقلة. الحساب يرى أرباحه فقط دون صلاحيات مالية عامة.', 'Defaults apply only to new agreements. Capital, profit share and loss share are independent. This role grants access only to the account’s own earnings.')}</p><Feedback error={op.error} />
  </div><footer className="fp-footer"><Button variant="ghost" onClick={onClose} disabled={op.busy}>{loc('رجوع', 'Back')}</Button><Button variant="primary" loading={op.busy} disabled={!user || profit == null || loss == null || capital == null} onClick={() => op.run(async () => { await api.post(`${API}/profiles`, { user_id: user, version: profile?.version, default_profit_share_bps: Math.round(profit! * 100), default_capital_share_bps: Math.round(capital! * 100), default_loss_share_bps: Math.round(loss! * 100), state }); await onSaved(); })}>{loc('حفظ', 'Save')}</Button></footer></Dialog>;
}

function ProfileDetail({ profile, onClose, openContract }: { profile: Profile; onClose: () => void; openContract: (id: string) => void }) {
  const { loc, lang } = useLanguage(), remote = useRemote<{ contracts: Contract[]; batches: Batch[] }>(`${API}/profiles/${profile.user_id}`);
  return <Dialog open onClose={onClose} title={profile.name || profile.email}><div className="fp-stack">
    <Surface title={loc('رأس المال · تراكمي', 'Capital · cumulative')}><div className="fp-stats">{[[loc('متفق عليه', 'Agreed'), profile.capital.agreed_iqd], [loc('مستلم', 'Received'), profile.capital.received_iqd], [loc('مخصص', 'Allocated'), profile.capital.allocated_iqd], [loc('مستخدم في المخزون', 'Used in inventory'), profile.capital.used_iqd], [investmentReturnStrings(lang).profilesReturned, profile.capital.returned_surplus_iqd ?? profile.capital.unallocated_iqd], [loc('مسترد من المبيعات', 'Recovered from sales'), profile.capital.recovered_iqd], [loc('مسحوب كرأس مال', 'Paid as capital'), profile.capital.paid_iqd], [loc('خسارة رأس المال', 'Capital loss'), profile.capital.loss_iqd]].map(([title, n]) => <div className="fp-stat" key={String(title)}><span>{title}</span><Money value={Number(n)} /></div>)}</div></Surface>
    <Surface title={loc('الأرباح · تراكمي', 'Profit · cumulative')}><div className="fp-stats">{[[loc('مستحقة', 'Accrued'), profile.balance.investor_profit_iqd], [loc('متاحة', 'Available'), profile.balance.investor_profit_available_iqd], [loc('معلقة', 'Pending'), profile.balance.investor_profit_pending_iqd], [loc('مسحوبة', 'Paid'), profile.balance.earnings_paid_iqd], [loc('دين أرباح متبقٍ', 'Remaining profit debt'), profile.balance.investor_profit_debt_iqd]].map(([title, n]) => <div className="fp-stat" key={String(title)}><span>{title}</span><Money value={Number(n)} /></div>)}</div></Surface>
    {!remote.data ? <Loading error={remote.error} retry={remote.load} /> : <>{remote.data.batches.map((b) => <Surface key={b.purchase_id} title={`${loc('دفعة', 'Batch')} ${b.purchase_id.slice(-8)}`} hint={`${loc('حصة الربح', 'Profit share')} ${b.profit_share_bps / 100}%`}><div className="fp-rows"><div className="fp-row"><span>{loc('التمويل المتفق / المستلم', 'Agreed / received funding')}</span><span><Money value={b.agreed_iqd} /> / <Money value={b.received_iqd} /></span></div>{b.funding_shortfall_iqd > 0 && <p className="fp-note">{loc('تمويل ينتظر الاستلام', 'Funding pending receipt')}: <Money value={b.funding_shortfall_iqd} /></p>}{(b.returned_iqd ?? b.unallocated_iqd) > 0 && <p className="fp-note">{investmentReturnStrings(lang).returned}: <Money value={b.returned_iqd ?? b.unallocated_iqd} /></p>}{remote.data!.contracts.filter((c) => c.purchase_id === b.purchase_id).map((c) => <ContractRow key={c.id} contract={c} onClick={() => openContract(c.id)} />)}</div></Surface>)}
    {remote.data.contracts.filter((c) => !remote.data!.batches.some((b) => b.purchase_id === c.purchase_id)).map((c) => <ContractRow key={c.id} contract={c} onClick={() => openContract(c.id)} />)}{!remote.data.contracts.length && <Empty>{loc('لا دفعات بعد. اختر هذا المستثمر أثناء إنشاء الشراء.', 'No batches yet. Select this investor when creating a purchase.')}</Empty>}</>}
    <p className="fp-note">{loc('رأس المال المسترد مستقل عن الربح. شروط التحصيل وتثبيت التكلفة تحدد ما يصبح متاحًا للسحب.', 'Recovered principal is separate from profit. Collection and verified costs determine withdrawal availability.')}</p>
  </div></Dialog>;
}
function ContractRow({ contract: c, onClick }: { contract: Contract; onClick: () => void }) {
  const { loc } = useLanguage();
  return <button type="button" className="fp-rule text-start" onClick={onClick}><div className="fp-rule-heading"><strong>{c.label || c.name}</strong><ChevronLeft size={17} /></div><p className="fp-muted">{loc('مستلم / مباع مسلّم / متبقٍ', 'Received / sold and delivered / remaining')}: {c.qty_received} / {c.delivered_qty} / {c.remaining_qty}</p><div className="fp-row"><span>{loc('رأس المال', 'Principal')}: <Money value={c.principal_iqd} /></span><span>{c.profit_share_bps / 100}% · {c.state === 'void' ? loc('مبطل', 'Voided') : loc('نشط', 'Active')}</span></div></button>;
}
