import { useRef, useState } from 'react';
import { ChevronLeft, HandCoins, Plus } from 'lucide-react';
import { Select } from '../ui/Field';
import { NumberInput } from '../ui/NumberInput';
import { api, Button, dateLabel, Dialog, Empty, Feedback, Field, Input, Loading, Money, Surface, useLanguage, useMutation, useRemote, type PanelProps } from './shared';

const INVESTMENT = '/api/admin/investment-finance';
export type IncomingLine = { id: string; purchase_id: string; label: string; product_id: string; qty_ordered: number; qty_received: number; total_cost_iqd: number };
export type InvestmentContract = { id: string; name: string; user_id: string; user_name?: string; investor_name?: string; incoming_id: string; incoming_label?: string; principal_iqd: number; capital_share_bps: number; profit_share_bps: number; loss_share_bps: number; created_at: string; state?: 'active' | 'void'; active?: number; funded_iqd?: number; accrued_profit_iqd?: number };
type InvestorUser = { id: string; name: string; email: string; admin_scope?: string };
type InvestmentConfig = { users: InvestorUser[]; incoming: IncomingLine[]; contracts: InvestmentContract[] };
type ContractDetail = {
  can_void: boolean;
  contract: InvestmentContract;
  summary: { funded_iqd: number; principal_iqd: number; inventory_capital_iqd: number | null; accrued_profit_iqd: number; available_profit_iqd: number; recovered_capital_iqd: number; loss_iqd: number };
  lots: Array<{ id: string; quantity?: number; qty_received?: number; qty_remaining?: number; unit_cost_iqd?: number; product_name?: string; label?: string; location_name?: string }>;
  events: Array<{ id: string; kind: string; amount_iqd: number; created_at: string; reference?: string; order_id?: string }>;
};

export default function InvestorPanel({ onChanged }: PanelProps = {}) {
  const { loc, dir } = useLanguage();
  const remote = useRemote<InvestmentConfig>(`${INVESTMENT}/config`);
  const [creating, setCreating] = useState(false), [selected, setSelected] = useState<string | null>(null);
  const config = remote.data;
  const refreshed = async () => { await remote.load(); onChanged?.(); };
  return <div className="ap fp fp-stack" dir={dir}><Surface title={loc('المستثمرون وتمويل الدفعات', 'Investors and batch funding')} hint={loc('اربط المستثمر بالدفعة. تُحسب حصته عند بيع قطعها وتسليمها.', 'Link investors to batches. Their share accrues when the batch units sell and are delivered.')} action={<Button variant="primary" icon={<Plus size={16} />} onClick={() => setCreating(true)}>{loc('إضافة استثمار', 'Add investment')}</Button>}>
    {!config ? <Loading error={remote.error} retry={remote.load} /> : <><Feedback error={remote.error} />{config.contracts.length === 0 ? <Empty><HandCoins size={28} className="mb-3" aria-hidden="true" />{loc('أضف اتفاق الاستثمار بعد إنشاء شحنة الشراء.', 'Add an investment agreement after creating the purchase shipment.')}</Empty> : <div className="fp-stack">{config.contracts.map((contract) => <button type="button" className="fp-rule text-start" key={contract.id} onClick={() => setSelected(contract.id)}><div className="fp-rule-heading"><div><h3>{contract.name || contract.user_name || contract.investor_name || loc('استثمار دفعة', 'Batch investment')}</h3><p className="fp-muted">{contract.user_name || contract.investor_name || config.users.find((u) => u.id === contract.user_id)?.name}</p></div><ChevronLeft size={19} className="shrink-0 rtl:rotate-0 ltr:rotate-180" aria-hidden="true" /></div><p className="fp-muted">{contract.incoming_label || config.incoming.find((i) => i.id === contract.incoming_id)?.label || loc('دفعة مخزون مرتبطة', 'Linked inventory batch')}</p><div className="flex items-center justify-between gap-3 flex-wrap"><span className="fp-status">{contract.state === 'void' ? loc('اتفاق مبطل', 'Voided agreement') : `${loc('حصة الربح', 'Profit share')} ${contract.profit_share_bps / 100}%`}</span><Money value={contract.principal_iqd} /></div></button>)}</div>}</>}
  </Surface>{creating && <InvestorContractForm incoming={config?.incoming} users={config?.users} onClose={() => setCreating(false)} onSaved={async () => { setCreating(false); await refreshed(); }} />}{selected && <ContractDetails id={selected} onClose={() => setSelected(null)} onChanged={refreshed} />}</div>;
}

export function InvestorContractForm({ incoming, users, initialIncomingId = '', onSaved, onClose }: { incoming?: IncomingLine[]; users?: InvestorUser[]; initialIncomingId?: string; onSaved: () => void | Promise<void>; onClose: () => void }) {
  const { loc } = useLanguage();
  return incoming && users ? <ContractForm incoming={incoming} users={users} initialIncomingId={initialIncomingId} onSaved={onSaved} onClose={onClose} /> : <LoadContractForm initialIncomingId={initialIncomingId} onSaved={onSaved} onClose={onClose} />;
  function LoadContractForm(props: { initialIncomingId: string; onSaved: () => void | Promise<void>; onClose: () => void }) {
    const config = useRemote<InvestmentConfig>(`${INVESTMENT}/config`);
    return config.data ? <ContractForm incoming={config.data.incoming} users={config.data.users} {...props} /> : <Dialog open onClose={onClose} title={loc('إضافة استثمار', 'Add investment')}><Loading error={config.error} retry={config.load} /></Dialog>;
  }
}

function ContractForm({ incoming, users, initialIncomingId, onSaved, onClose }: { incoming: IncomingLine[]; users: InvestorUser[]; initialIncomingId: string; onSaved: () => void | Promise<void>; onClose: () => void }) {
  const { loc } = useLanguage(), op = useMutation();
  const [lineId, setLineId] = useState(initialIncomingId), [userId, setUserId] = useState(''), [search, setSearch] = useState(''), [principal, setPrincipal] = useState<number | null>(null), [profit, setProfit] = useState<number | null>(null), [capital, setCapital] = useState<number | null>(100), [loss, setLoss] = useState<number | null>(0), [name, setName] = useState('');
  const operationId = useRef(crypto.randomUUID());
  const line = incoming.find((i) => i.id === lineId), user = users.find((u) => u.id === userId);
  const filtered = users.filter((u) => !search || `${u.name} ${u.email}`.toLowerCase().includes(search.toLowerCase()) || u.id === userId);
  const valid = lineId && userId && principal != null && principal > 0 && profit != null && profit > 0 && profit <= 100 && capital != null && capital > 0 && capital <= 100 && loss != null && loss >= 0 && loss <= 100;
  const save = () => op.run(async () => { if (!valid || !user || !line || capital == null || profit == null || loss == null) return; await api.post(`${INVESTMENT}/contracts`, { operation_id: operationId.current, incoming_id: lineId, user_id: userId, name: name.trim() || `${user.name} · ${line.label}`, principal_iqd: principal, capital_share_bps: Math.round(capital * 100), profit_share_bps: Math.round(profit * 100), loss_share_bps: Math.round(loss * 100) }); await onSaved(); });
  return <Dialog open onClose={onClose} busy={op.busy} dirty title={loc('إضافة استثمار', 'Add investment')}><div className="fp-stack">
    <Field label={loc('الدفعة المشمولة', 'Included batch')}><Select value={lineId} onChange={(e) => setLineId(e.target.value)}><option value="">{loc('اختر دفعة من المشتريات', 'Choose a purchase batch')}</option>{incoming.map((i) => <option key={i.id} value={i.id}>{i.label} · {i.qty_ordered} {loc('قطعة', 'units')}</option>)}</Select></Field>
    {line && <p className="fp-note">{loc('تكلفة الدفعة المرجعية: ', 'Reference batch cost: ')}<Money value={line.total_cost_iqd} /> · {loc(`المستلم ${line.qty_received} من ${line.qty_ordered}`, `${line.qty_received} of ${line.qty_ordered} received`)}</p>}
    <div className="fp-stack"><Field label={loc('ابحث عن المستثمر', 'Find investor')}><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder={loc('الاسم أو البريد', 'Name or email')} /></Field><Field label={loc('حساب المستثمر', 'Investor account')}><Select value={userId} onChange={(e) => setUserId(e.target.value)}><option value="">{loc('اختر الحساب', 'Choose account')}</option>{filtered.map((u) => <option key={u.id} value={u.id}>{u.name || u.email}{u.name && u.email ? ` · ${u.email}` : ''}</option>)}</Select></Field></div>
    <div className="fp-grid"><Field label={loc('رأس المال المتفق عليه', 'Agreed capital')}><NumberInput kind="money" min={1} value={principal} onValueChange={(n, ok) => setPrincipal(ok ? n : null)} /></Field><Field label={loc('حصة المستثمر من الربح', 'Investor profit share')}><NumberInput value={profit} min={0.01} max={100} unit="%" placeholder="35" onValueChange={(n, ok) => setProfit(ok ? n : null)} /></Field></div>
    <details className="fp-detail"><summary>{loc('شروط إضافية', 'Additional terms')}</summary><div className="fp-stack"><Field label={loc('نسبة ملكية رأس مال الدفعة', 'Share of batch capital')} hint={loc('منفصلة عن حصة الربح. تُستخدم لتتبّع رأس المال المسترد.', 'Separate from profit share; used to track recovered capital.')}><NumberInput value={capital} min={0.01} max={100} unit="%" onValueChange={(n, ok) => setCapital(ok ? n : null)} /></Field><Field label={loc('نسبة تحمّل الخسارة', 'Loss share')}><NumberInput value={loss} min={0} max={100} unit="%" onValueChange={(n, ok) => setLoss(ok ? n : null)} /></Field><Field label={loc('اسم الاتفاق', 'Agreement name')} optional><Input value={name} onChange={(e) => setName(e.target.value)} /></Field></div></details>
    <p className="fp-note">{loc('هذا اتفاق لتوزيع الأرباح ورأس المال. سجّل التمويل المستلم فعليًا من تفاصيل الاتفاق بعد الحفظ.', 'This agreement allocates profit and capital. Record funds actually received from the agreement details after saving.')}</p><Feedback error={op.error} />
  </div><footer className="fp-footer"><Button variant="ghost" disabled={op.busy} onClick={onClose}>{loc('رجوع', 'Back')}</Button><Button variant="primary" loading={op.busy} disabled={!valid} onClick={save}>{loc('حفظ الاستثمار', 'Save investment')}</Button></footer></Dialog>;
}

function ContractDetails({ id, onClose, onChanged }: { id: string; onClose: () => void; onChanged: () => Promise<void> }) {
  const { loc, lang } = useLanguage();
  const remote = useRemote<ContractDetail>(`${INVESTMENT}/contracts/${encodeURIComponent(id)}`), op = useMutation();
  const [funding, setFunding] = useState(false), [amount, setAmount] = useState<number | null>(null), [reference, setReference] = useState(''), [voiding, setVoiding] = useState(false), [replacement, setReplacement] = useState(false);
  const operationId = useRef('');
  const voidOperationId = useRef('');
  const d = remote.data;
  const isVoid = d?.contract.state === 'void';
  const canVoid = d && !isVoid && d.can_void === true;
  return <><Dialog open onClose={onClose} title={d?.contract.name || loc('تفاصيل الاستثمار', 'Investment details')} busy={op.busy}>{!d ? <Loading error={remote.error} retry={remote.load} /> : <div className="fp-stack"><Feedback error={op.error || remote.error} notice={op.notice} /><p className="fp-muted">{d.contract.user_name || d.contract.investor_name} · {loc('حصة الربح', 'Profit share')} {d.contract.profit_share_bps / 100}%</p><div className="fp-stats">{[[loc('التمويل المستلم', 'Funds received'), d.summary.funded_iqd], [loc('في المخزون', 'In inventory'), d.summary.inventory_capital_iqd], [loc('أرباح مستحقة', 'Accrued profits'), d.summary.accrued_profit_iqd], [loc('أرباح متاحة للسحب', 'Available profits'), d.summary.available_profit_iqd], [loc('رأس المال المسترد', 'Recovered capital'), d.summary.recovered_capital_iqd], [loc('الخسارة', 'Loss'), d.summary.loss_iqd]].map(([title, value]) => <div className="fp-stat" key={String(title)}><span>{title}</span><Money value={typeof value === 'number' ? value : null} /></div>)}</div>
    {isVoid ? <Surface title={loc('الاتفاق مبطل', 'Agreement voided')} hint={loc('يبقى الاتفاق في السجل. يمكنك إنشاء اتفاق صحيح لنفس المستثمر والدفعة.', 'The agreement stays in the record. You can create a corrected agreement for the same investor and batch.')}><Button variant="primary" onClick={() => setReplacement(true)}>{loc('إنشاء اتفاق بديل', 'Create replacement agreement')}</Button></Surface> : <>{!funding ? <Button icon={<Plus size={16} />} onClick={() => { operationId.current = crypto.randomUUID(); setAmount(null); setReference(''); setFunding(true); }}>{loc('تسجيل تمويل مستلم', 'Record received funding')}</Button> : <Surface title={loc('تمويل مستلم فعليًا', 'Funds actually received')}><div className="fp-stack"><Field label={loc('المبلغ المستلم', 'Amount received')}><NumberInput kind="money" min={1} value={amount} onValueChange={(n, ok) => setAmount(ok ? n : null)} /></Field><Field label={loc('مرجع الاستلام', 'Receipt reference')}><Input value={reference} onChange={(e) => setReference(e.target.value)} placeholder={loc('رقم التحويل أو الوصل', 'Transfer or receipt number')} /></Field><div className="flex gap-2"><Button variant="primary" loading={op.busy} disabled={!amount || !reference.trim()} onClick={() => op.run(async () => { await api.post(`${INVESTMENT}/contracts/${encodeURIComponent(id)}/funding`, { operation_id: operationId.current, amount_iqd: amount, payment_day: new Date(Date.now() + 3 * 3600000).toISOString().slice(0, 10), reference: reference.trim() }); setFunding(false); await remote.load(); await onChanged(); }, loc('تم تسجيل التمويل.', 'Funding recorded.'))}>{loc('تسجيل الاستلام', 'Record receipt')}</Button><Button variant="ghost" disabled={op.busy} onClick={() => setFunding(false)}>{loc('إلغاء', 'Cancel')}</Button></div></div></Surface>}{canVoid && <details className="fp-detail"><summary>{loc('تصحيح اتفاق لم يُموّل أو تُبع قطعه', 'Correct an unfunded, unsold agreement')}</summary>{!voiding ? <Button variant="ghost" disabled={op.busy} onClick={() => { voidOperationId.current = crypto.randomUUID(); setVoiding(true); }}>{loc('إبطال الاتفاق', 'Void agreement')}</Button> : <Surface title={loc('إبطال هذا الاتفاق؟', 'Void this agreement?')} hint={loc('يبقى السجل محفوظًا وتصبح حصصه متاحة لاتفاق جديد. لا يُسمح بالإبطال بعد التمويل أو استهلاك القطع.', 'The record is retained and its shares become available for a new agreement. Funding or consumed units prevent voiding.')}><div className="flex flex-wrap gap-2"><Button variant="primary" loading={op.busy} onClick={() => op.run(async () => { await api.post(`${INVESTMENT}/contracts/${encodeURIComponent(id)}/void`, { operation_id: voidOperationId.current }); setVoiding(false); await remote.load(); await onChanged(); }, loc('تم إبطال الاتفاق وحفظ السجل.', 'Agreement voided and record retained.'))}>{loc('تأكيد الإبطال', 'Confirm void')}</Button><Button variant="ghost" disabled={op.busy} onClick={() => setVoiding(false)}>{loc('رجوع', 'Back')}</Button></div></Surface>}</details>}</>}
    <details className="fp-detail"><summary>{loc('الدفعات والحركات', 'Lots and activity')}</summary><div className="fp-stack">{d.lots.length > 0 && <div className="fp-rows">{d.lots.map((lot) => <div className="fp-row" key={lot.id}><div><strong>{lot.label || lot.product_name || loc('دفعة مخزون', 'Inventory lot')}</strong><p className="fp-row-meta">{lot.location_name}</p></div><span>{lot.qty_remaining ?? lot.quantity ?? lot.qty_received ?? '—'} {loc('قطعة', 'units')}</span></div>)}</div>}{d.events.length ? <div className="fp-rows">{d.events.map((event) => <div className="fp-row" key={event.id}><div className="min-w-0"><div>{event.kind === 'funding' ? loc('تمويل', 'Funding') : event.kind === 'profit' ? loc('ربح', 'Profit') : event.kind === 'capital_recovery' ? loc('استرداد رأس المال', 'Capital recovery') : loc('حركة استثمار', 'Investment activity')}</div><p className="fp-row-meta">{dateLabel(event.created_at, lang)}{event.reference ? ` · ${event.reference}` : ''}{event.order_id ? ` · ${event.order_id}` : ''}</p></div><Money value={event.amount_iqd} /></div>)}</div> : <Empty>{loc('لا توجد حركات بعد.', 'No activity yet.')}</Empty>}</div></details><p className="fp-note">{loc('يشاهد المستثمر حصته في «أرباحي» ويطلب سحب المتاح. تصل طلباته إلى «طلبات السحب».', 'The investor sees their share in My earnings and requests withdrawals. Requests appear in Withdrawals.')}</p>
  </div>}</Dialog>{replacement && d && <InvestorContractForm initialIncomingId={d.contract.incoming_id} onClose={() => setReplacement(false)} onSaved={async () => { setReplacement(false); await remote.load(); await onChanged(); }} />}</>;
}
export { InvestorPanel };
