import { useState } from 'react';
import { Check, Pencil, Plus, Users, X } from 'lucide-react';
import ProductPicker from '../adminProducts/form/ProductPicker';
import { NumberInput } from '../ui/NumberInput';
import { Select } from '../ui/Field';
import { AccountPicker, api, Button, Dialog, Empty, Feedback, Field, Input, Loading, Money, PEOPLE, Surface, useLanguage, useMutation, useRemote, type Account, type PanelProps } from './shared';

type Named = { id: string; name?: string; name_ar?: string; name_en?: string; parent_id?: string | null };
type Scope = { catalog_ids: string[]; product_ids: string[]; excluded_product_ids: string[] };
type Staff = { id: string; name: string; role: string; active: number; user_id: string | null; account_name?: string; account_email?: string };
type Rule = { id: string; version: number; name: string; staff_id: string | null; amount: number; basis: string; milestone: string; requires_assignment: number; active: number; scope?: Scope; target_type?: string; target_id?: string; cap_iqd?: number | null; group_key?: string; category_id?: string; center_id?: string | null; priority?: number; effective_from?: string; effective_to?: string | null };
type Config = { staff: Staff[]; catalogs: Named[]; rules: Rule[]; scope_products: Named[] };
const label = (n: Named | undefined) => n?.name_ar || n?.name || n?.name_en || n?.id || '';
const emptyScope = (): Scope => ({ catalog_ids: [], product_ids: [], excluded_product_ids: [] });
function ruleScope(rule: Rule): Scope { return rule.scope ?? { catalog_ids: rule.target_type === 'catalog' && rule.target_id ? [rule.target_id] : [], product_ids: rule.target_type === 'product' && rule.target_id ? [rule.target_id] : [], excluded_product_ids: [] }; }

export default function PeoplePanel({ onChanged }: PanelProps = {}) {
  const { loc, dir } = useLanguage();
  const remote = useRemote<Config>(`${PEOPLE}/staff`);
  const [editor, setEditor] = useState<{ rule?: Rule; staff?: Staff } | null>(null), [linking, setLinking] = useState<Staff | null>(null), [linkAccount, setLinkAccount] = useState<Account | null>(null);
  const op = useMutation();
  const refresh = async () => { await remote.load(); onChanged?.(); };
  const config = remote.data;
  const describe = (rule: Rule) => rule.basis.endsWith('percent') ? `${rule.amount / 100}% ${rule.basis === 'profit_percent' ? loc('من الربح', 'of profit') : loc('من البيع', 'of sales')}` : `${rule.amount.toLocaleString('en-US')} ${loc('د.ع', 'IQD')} ${rule.basis === 'unit' ? loc('لكل قطعة', 'per unit') : loc('لكل طلب', 'per order')}`;
  return <div className="ap fp fp-stack" dir={dir}><Surface title={loc('الموظفون وقواعد الأجور', 'People and earning rules')} hint={loc('اختر الحساب، المنتجات المشمولة، والأجر. نحسب الباقي مع كل طلب.', 'Choose an account, eligible products and pay. Earnings are calculated for each order.')} action={<Button variant="primary" icon={<Plus size={16} />} onClick={() => setEditor({})}>{loc('إضافة موظف أو قاعدة', 'Add person or rule')}</Button>}>
    <Feedback error={op.error} notice={op.notice} />
    {!config ? <Loading error={remote.error} retry={remote.load} /> : <><Feedback error={remote.error} />{!config.staff.length ? <Empty><Users size={26} className="mb-3" aria-hidden="true" />{loc('ابدأ باختيار حساب الموظف وإعداد أجره.', 'Start by choosing a staff account and their earning rule.')}</Empty> : <div className="fp-stack">{config.staff.map((person) => {
      const rules = config.rules.filter((r) => r.staff_id === person.id);
      return <article className="fp-rule" key={person.id}><div className="fp-rule-heading"><div className="flex items-center gap-3 min-w-0"><span className="fp-avatar" aria-hidden="true">{person.name.slice(0, 1)}</span><div className="min-w-0"><h3>{person.name}</h3><p className="fp-muted">{person.role || person.account_name || loc('موظف', 'Staff')}</p></div></div><Button size="sm" variant="ghost" icon={<Plus size={15} />} onClick={() => setEditor({ staff: person })}>{loc('قاعدة', 'Rule')}</Button></div>
        {!person.user_id && <div className="flex items-center justify-between gap-3"><p className="fp-muted">{loc('اربط حسابه ليشاهد أرباحه ويطلب السحب.', 'Link an account for earnings and withdrawals.')}</p><Button size="sm" onClick={() => { setLinking(person); setLinkAccount(null); op.clear(); }}>{loc('ربط الحساب', 'Link account')}</Button></div>}
        {rules.length === 0 ? <p className="fp-muted">{loc('لم تُضف قاعدة أجور بعد.', 'No earning rule yet.')}</p> : rules.map((rule) => {
          const scope = ruleScope(rule), all = !scope.catalog_ids.length && !scope.product_ids.length;
          return <div key={rule.id} className="fp-detail"><div className="fp-rule-heading"><strong>{describe(rule)}</strong><Button size="sm" variant="ghost" icon={<Pencil size={14} />} onClick={() => setEditor({ rule, staff: person })}>{loc('تعديل', 'Edit')}</Button></div><div className="fp-chips mt-2">{all && <span className="fp-status">{loc('كل المنتجات', 'All products')}</span>}{scope.catalog_ids.map((id) => <span className="fp-status" key={id}>{config.catalogs.find((c) => c.id === id) ? label(config.catalogs.find((c) => c.id === id)) : loc('قسم', 'Category')}</span>)}{scope.product_ids.map((id) => <span className="fp-status" key={id}>{config.scope_products?.find((p) => p.id === id) ? label(config.scope_products.find((p) => p.id === id)) : loc('منتج محدد', 'Selected product')}</span>)}{scope.excluded_product_ids.length > 0 && <span className="fp-status fp-status-rejected">{loc(`باستثناء ${scope.excluded_product_ids.length} منتج`, `${scope.excluded_product_ids.length} product exclusions`)}</span>}{!rule.active && <span className="fp-status">{loc('متوقفة', 'Paused')}</span>}</div><p className="fp-row-meta">{rule.milestone === 'prepared' ? loc('عند إنجاز التجهيز', 'On preparation') : loc('عند التسليم', 'On delivery')}{rule.requires_assignment ? loc(' · يتطلب إسناد العمل', ' · requires assignment') : ''}</p></div>;
        })}
      </article>;
    })}</div>}</>}
  </Surface>{editor && config && <RuleBuilder config={config} initial={editor} onClose={() => setEditor(null)} onSaved={refresh} />}
    <Dialog open={!!linking} onClose={() => setLinking(null)} title={loc('ربط حساب الموظف', 'Link staff account')} busy={op.busy}><AccountPicker value={linkAccount} onChange={setLinkAccount} /><Feedback error={op.error} /><footer className="fp-footer"><Button variant="ghost" disabled={op.busy} onClick={() => setLinking(null)}>{loc('رجوع', 'Back')}</Button><Button variant="primary" loading={op.busy} disabled={!linkAccount} onClick={() => op.run(async () => { if (!linking || !linkAccount) return; await api.patch(`${PEOPLE}/staff/${encodeURIComponent(linking.id)}`, { user_id: linkAccount.id }); setLinking(null); await refresh(); }, loc('تم ربط الحساب.', 'Account linked.'))}>{loc('ربط الحساب', 'Link account')}</Button></footer></Dialog>
  </div>;
}

function RuleBuilder({ config, initial, onClose, onSaved }: { config: Config; initial: { rule?: Rule; staff?: Staff }; onClose: () => void; onSaved: () => Promise<void> }) {
  const { loc } = useLanguage(), op = useMutation();
  const existing = initial.rule;
  const [step, setStep] = useState(existing ? 2 : 0), [staffId, setStaffId] = useState(initial.staff?.id ?? ''), [account, setAccount] = useState<Account | null>(null), [role, setRole] = useState(initial.staff?.role ?? '');
  const originalScope = existing ? ruleScope(existing) : emptyScope();
  const [scope, setScope] = useState<Scope>(originalScope), [mode, setMode] = useState(originalScope.catalog_ids.length ? 'categories' : originalScope.product_ids.length ? 'products' : 'all');
  const [products, setProducts] = useState<Named[]>(config.scope_products ?? []);
  const [basis, setBasis] = useState(existing?.basis ?? 'unit'), [amount, setAmount] = useState<number | null>(existing ? existing.amount / (existing.basis.endsWith('percent') ? 100 : 1) : null), [milestone, setMilestone] = useState(existing?.milestone ?? 'delivered'), [assignment, setAssignment] = useState(!!existing?.requires_assignment), [active, setActive] = useState(existing ? !!existing.active : true), [cap, setCap] = useState<number | null>(existing?.cap_iqd ?? null), [name, setName] = useState(existing?.name ?? '');
  const [quantity, setQuantity] = useState<number | null>(1), [sampleProfit, setSampleProfit] = useState<number | null>(100000);
  const isPercent = basis.endsWith('percent'), chosenStaff = config.staff.find((s) => s.id === staffId);
  const accountName = chosenStaff?.name || account?.name || account?.email || '';
  const canNext = step === 0 ? !!(staffId || account) : step === 1 ? mode === 'all' || (mode === 'categories' ? scope.catalog_ids.length > 0 : scope.product_ids.length > 0) : amount != null && amount > 0 && (!isPercent || amount <= 100);
  const calculation = amount == null ? 0 : basis === 'unit' ? amount * (quantity ?? 0) : basis === 'order' ? amount : Math.round((sampleProfit ?? 0) * amount / 100);
  const toggle = (key: keyof Scope, id: string) => setScope((s) => ({ ...s, [key]: s[key].includes(id) ? s[key].filter((x) => x !== id) : [...s[key], id] }));
  const chooseMode = (next: string) => { setMode(next); setScope((s) => ({ ...s, catalog_ids: next === 'categories' ? s.catalog_ids : [], product_ids: next === 'products' ? s.product_ids : [] })); };
  const addProduct = (key: 'product_ids' | 'excluded_product_ids', id: string, p: Named | null) => {
    if (!id || !p) return;
    setProducts((old) => [...old.filter((x) => x.id !== id), p]);
    setScope((s) => ({ ...s, [key]: s[key].includes(id) ? s[key] : [...s[key], id] }));
  };
  const save = () => op.run(async () => {
    if (amount == null || amount <= 0 || (!staffId && !account)) return;
    let id = staffId;
    if (!id && account) {
      const known = config.staff.find((s) => s.user_id === account.id);
      if (known) id = known.id;
      else { const r = await api.post<{ staff: Staff }>(`${PEOPLE}/staff`, { user_id: account.id, role }); id = r.staff.id; }
      setStaffId(id);
    }
    const payload = { ...existing, staff_id: id, name: name || undefined, basis, amount: isPercent ? Math.round(amount * 100) : amount, scope, milestone, requires_assignment: assignment ? 1 : 0, active, cap_iqd: cap, target_type: 'all', target_id: '' };
    if (existing) await api.put(`/api/admin/finance-operations/rules/${encodeURIComponent(existing.id)}`, payload);
    else await api.post('/api/admin/finance-operations/rules', payload);
    await onSaved(); onClose();
  });
  const productList = (key: 'product_ids' | 'excluded_product_ids') => <div className="fp-stack"><div className="fp-chips">{scope[key].map((id) => <button key={id} type="button" className={`fp-chip ${key === 'excluded_product_ids' ? 'fp-chip-excluded' : 'fp-chip-selected'}`} onClick={() => toggle(key, id)} aria-label={loc(`إزالة ${label(products.find((p) => p.id === id) ?? { id })}`, `Remove ${label(products.find((p) => p.id === id) ?? { id })}`)}><span>{label(products.find((p) => p.id === id) ?? { id })}</span><X size={13} aria-hidden="true" /></button>)}</div><ProductPicker value="" keepOpen excludeComposition={false} ariaLabel={key === 'product_ids' ? loc('ابحث عن منتج مشمول', 'Search eligible products') : loc('ابحث عن منتج مستثنى', 'Search excluded products')} onChange={(id, p) => addProduct(key, id, p)} /></div>;
  return <Dialog open onClose={onClose} busy={op.busy} dirty title={existing ? loc('تعديل قاعدة الأجر', 'Edit earning rule') : loc('إعداد الأجر', 'Set up earnings')}>
    <ol className="fp-steps">{[loc('الحساب', 'Account'), loc('المشمول', 'Scope'), loc('الأجر', 'Pay'), loc('المراجعة', 'Review')].map((text, i) => <li key={i} aria-current={step === i ? 'step' : undefined} data-done={step > i}>{i + 1}. {text}</li>)}</ol>
    <Feedback error={op.error} />
    {step === 0 && <div className="fp-stack">{config.staff.length > 0 && <Field label={loc('موظف مسجل', 'Existing staff')}><Select value={staffId} onChange={(e) => { setStaffId(e.target.value); setAccount(null); }}><option value="">{loc('اختيار حساب جديد', 'Choose a new account')}</option>{config.staff.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</Select></Field>}{!staffId && <><AccountPicker value={account} onChange={setAccount} /><details className="fp-detail"><summary>{loc('إضافة المسمى الوظيفي', 'Add job title')}</summary><Field label={loc('المسمى الوظيفي', 'Job title')} optional><Input value={role} onChange={(e) => setRole(e.target.value)} placeholder={loc('مثال: تجهيز الطلبات', 'e.g. Order preparation')} /></Field></details></>}</div>}
    {step === 1 && <div className="fp-stack"><div className="fp-chips">{[['all', loc('كل المنتجات', 'All products')], ['categories', loc('أقسام معينة', 'Categories')], ['products', loc('منتجات معينة', 'Products')]].map(([id, text]) => <button type="button" className="fp-chip" aria-pressed={mode === id} key={id} onClick={() => chooseMode(id)}>{text}</button>)}</div>{mode === 'categories' && <div className="fp-chips">{config.catalogs.map((c) => <button type="button" key={c.id} className="fp-chip" aria-pressed={scope.catalog_ids.includes(c.id)} onClick={() => toggle('catalog_ids', c.id)}>{scope.catalog_ids.includes(c.id) && <Check size={14} aria-hidden="true" />}{label(c)}</button>)}</div>}{mode === 'products' && productList('product_ids')}<details className="fp-detail" open={scope.excluded_product_ids.length > 0 || undefined}><summary>{loc('استثناء منتجات', 'Exclude products')}{scope.excluded_product_ids.length > 0 ? ` (${scope.excluded_product_ids.length})` : ''}</summary>{productList('excluded_product_ids')}</details><p className="fp-note">{loc('الأقسام تشمل أقسامها الفرعية. المنتج المستثنى لا يولّد أجرًا لهذه القاعدة.', 'Categories include their children. Excluded products do not earn pay under this rule.')}</p></div>}
    {step === 2 && <div className="fp-stack"><Field label={loc('طريقة الحساب', 'Calculation')}><Select value={basis} onChange={(e) => { setBasis(e.target.value); setAmount(null); }}><option value="unit">{loc('مبلغ لكل قطعة', 'Amount per unit')}</option><option value="order">{loc('مبلغ لكل طلب', 'Amount per order')}</option><option value="profit_percent">{loc('نسبة من الربح', 'Percentage of profit')}</option><option value="revenue_percent">{loc('نسبة من البيع', 'Percentage of sales')}</option></Select></Field><Field label={isPercent ? loc('النسبة', 'Percentage') : loc('الأجر', 'Pay')}><NumberInput kind={isPercent ? 'number' : 'money'} value={amount} min={0.01} max={isPercent ? 100 : undefined} unit={isPercent ? '%' : undefined} onValueChange={(n, valid) => setAmount(valid ? n : null)} placeholder={isPercent ? '10' : '5,000'} /></Field><details className="fp-detail"><summary>{loc('خيارات إضافية', 'More options')}</summary><div className="fp-stack"><Field label={loc('الاستحقاق عند', 'Earned when')}><Select value={milestone} onChange={(e) => setMilestone(e.target.value)}><option value="delivered">{loc('تسليم الطلب', 'Order delivery')}</option><option value="prepared">{loc('إنجاز التجهيز', 'Preparation complete')}</option></Select></Field><label className="fp-check"><input type="checkbox" checked={assignment} onChange={(e) => setAssignment(e.target.checked)} />{loc('يتطلب إسناد المهمة لهذا الموظف', 'Requires assigning the task to this employee')}</label><Field label={loc('سقف الأجر', 'Pay cap')} optional><NumberInput kind="money" value={cap} onValueChange={(n, valid) => setCap(valid ? n : null)} /></Field><Field label={loc('اسم القاعدة', 'Rule name')} optional><Input value={name} onChange={(e) => setName(e.target.value)} /></Field><label className="fp-check"><input type="checkbox" checked={active} onChange={(e) => setActive(e.target.checked)} />{loc('القاعدة فعّالة', 'Rule enabled')}</label></div></details></div>}
    {step === 3 && <div className="fp-stack"><div className="fp-account"><span className="fp-avatar" aria-hidden="true">{accountName.slice(0, 1)}</span><div><strong>{accountName}</strong><p>{isPercent ? `${amount}% ${basis === 'profit_percent' ? loc('من الربح', 'of profit') : loc('من البيع', 'of sales')}` : `${amount?.toLocaleString('en-US')} ${loc('د.ع', 'IQD')} ${basis === 'unit' ? loc('لكل قطعة', 'per unit') : loc('لكل طلب', 'per order')}`}</p></div></div><p className="fp-note">{mode === 'all' ? loc('تشمل جميع المنتجات', 'All products included') : mode === 'categories' ? scope.catalog_ids.map((id) => label(config.catalogs.find((c) => c.id === id) ?? { id })).join('، ') : scope.product_ids.map((id) => label(products.find((p) => p.id === id) ?? { id })).join('، ')}{scope.excluded_product_ids.length > 0 && <> · {loc(`باستثناء ${scope.excluded_product_ids.length} منتج`, `${scope.excluded_product_ids.length} exclusions`)}</>}</p><details className="fp-detail"><summary>{loc('تجربة الحساب', 'Try the calculation')}</summary><div className="fp-stack">{basis === 'unit' && <Field label={loc('عدد القطع المشمولة', 'Eligible quantity')}><NumberInput kind="quantity" min={1} value={quantity} onValueChange={(n) => setQuantity(n)} /></Field>}{isPercent && <Field label={basis === 'profit_percent' ? loc('ربح المنتجات المشمولة', 'Eligible product profit') : loc('صافي مبيعات المنتجات المشمولة', 'Eligible net sales')}><NumberInput kind="money" value={sampleProfit} onValueChange={(n) => setSampleProfit(n)} /></Field>}<div className="fp-rule-heading"><span>{loc('الأجر في هذا المثال', 'Pay in this example')}</span><Money value={cap == null ? calculation : Math.min(cap, calculation)} /></div><p className="fp-muted">{loc('هذه معاينة فقط ولا تسجل أي مستحقات.', 'This preview does not create earnings.')}</p></div></details><p className="fp-muted">{loc('تسري القاعدة على العمليات الجديدة. التفاصيل والتعديلات محفوظة تلقائيًا.', 'Applies to new operations. Details and changes are recorded automatically.')}</p></div>}
    <footer className="fp-footer"><Button variant="ghost" disabled={op.busy} onClick={() => step ? setStep(step - 1) : onClose()}>{step ? loc('السابق', 'Back') : loc('إلغاء', 'Cancel')}</Button>{step < 3 ? <Button variant="primary" disabled={!canNext} onClick={() => setStep(step + 1)}>{loc('التالي', 'Continue')}</Button> : <Button variant="primary" loading={op.busy} onClick={save}>{loc('حفظ القاعدة', 'Save rule')}</Button>}</footer>
  </Dialog>;
}
export { PeoplePanel };
