import { useRef, useState } from 'react';
import { Check, Receipt, RefreshCw } from 'lucide-react';
import { NumberInput } from '../ui/NumberInput';
import { api, Button, dateLabel, Dialog, Empty, Feedback, Field, Input, Loading, Money, PEOPLE, StateBadge, Surface, useLanguage, useMutation, useRemote, type PanelProps, type Withdrawal } from './shared';

export default function WithdrawalPanel({ onChanged }: PanelProps = {}) {
  const { loc, lang, dir } = useLanguage();
  const [offset, setOffset] = useState(0);
  const remote = useRemote<{ withdrawals: Withdrawal[] }>(`${PEOPLE}/withdrawals?offset=${offset}`), op = useMutation();
  const [filter, setFilter] = useState('open'), [paying, setPaying] = useState<Withdrawal | null>(null), [amount, setAmount] = useState<number | null>(null), [reference, setReference] = useState(''), [receipt, setReceipt] = useState('');
  const operationId = useRef('');
  const rows = remote.data?.withdrawals.filter((w) => filter === 'all' || ['requested', 'approved', 'part_paid'].includes(w.state)) ?? [];
  const change = (w: Withdrawal, action: string) => op.run(async () => { await api.post(`${PEOPLE}/withdrawals/${encodeURIComponent(w.id)}/${action}`, {}); await remote.load(); onChanged?.(); }, action === 'approve' ? loc('تم اعتماد الطلب للتسديد.', 'Approved for payment.') : loc('رُفض الطلب وأعيد المبلغ إلى صاحبه.', 'Request rejected and funds released.'));
  const startPayment = (w: Withdrawal) => { operationId.current = crypto.randomUUID(); setPaying(w); setAmount(w.amount_iqd - w.paid_iqd); setReference(''); setReceipt(''); op.clear(); };
  const pay = () => op.run(async () => { if (!paying || !amount) return; await api.post(`${PEOPLE}/withdrawals/${encodeURIComponent(paying.id)}/pay`, { operation_id: operationId.current, amount_iqd: amount, reference: reference.trim(), receipt_url: receipt.trim() || undefined }); setPaying(null); await remote.load(); onChanged?.(); }, loc('تم تسجيل التسديد وتحديث رصيد المستحق.', 'Payment recorded and balance updated.'));
  return <div className="ap fp fp-stack" dir={dir}><Surface title={loc('طلبات السحب والتسوية', 'Withdrawals and settlement')} hint={loc('اعتماد الطلب يحجز المبلغ. سجّل التسديد بعد الدفع الفعلي.', 'Approval reserves funds. Record payment after actually paying.')} action={<Button variant="ghost" aria-label={loc('تحديث طلبات السحب', 'Refresh withdrawals')} icon={<RefreshCw size={17} />} loading={remote.loading} onClick={remote.load} />}>
    <Feedback error={op.error || remote.error} notice={op.notice} />
    <div className="fp-chips mb-5">{[['open', loc('بانتظار التسوية', 'Awaiting settlement')], ['all', loc('جميع الطلبات', 'All requests')]].map(([id, name]) => <button type="button" key={id} className="fp-chip" aria-pressed={filter === id} onClick={() => { setFilter(id); setOffset(0); }}>{name}</button>)}</div>
    {!remote.data ? <Loading error={remote.error} retry={remote.load} /> : !rows.length ? <Empty>{loc('لا توجد طلبات في هذه القائمة.', 'No requests in this list.')}</Empty> : <div className="fp-rows">{rows.map((w) => <article key={w.id} className="fp-row"><div className="min-w-0 flex-1"><div className="fp-rule-heading"><div><div className="fp-row-title">{w.user_name || w.email || loc('حساب مستحق', 'Beneficiary')}</div><div className="fp-row-meta">{dateLabel(w.created_at, lang)}</div></div><Money value={w.amount_iqd} /></div><div className="mt-2"><StateBadge state={w.state} />{w.balance_type === 'capital' && <span className="fp-status ms-2">{loc('رأس المال', 'Capital')}</span>}</div>{w.paid_iqd > 0 && <p className="fp-row-meta">{loc('المسدد: ', 'Paid: ')}<Money value={w.paid_iqd} /></p>}{w.reference && <p className="fp-row-meta">{loc('مرجع التسديد: ', 'Reference: ')}<bdi>{w.reference}</bdi></p>}<div className="fp-row-actions">{w.state === 'requested' && <><Button size="sm" variant="primary" icon={<Check size={15} />} loading={op.busy} onClick={() => change(w, 'approve')}>{loc('اعتماد الطلب', 'Approve')}</Button><Button size="sm" variant="ghost" loading={op.busy} onClick={() => change(w, 'reject')}>{loc('رفض وإعادة الرصيد', 'Reject and release')}</Button></>}{['approved', 'part_paid'].includes(w.state) && <><Button size="sm" variant="primary" icon={<Receipt size={15} />} onClick={() => startPayment(w)}>{loc('تسجيل التسديد', 'Record payment')}</Button><Button size="sm" variant="ghost" loading={op.busy} onClick={() => change(w, 'reject')}>{loc('تحرير المبلغ المتبقي', 'Release remaining funds')}</Button></>}</div></div></article>)}</div>}
    {remote.data && (offset > 0 || remote.data.withdrawals.length === 100) && <div className="fp-footer"><Button disabled={offset === 0 || remote.loading} onClick={() => setOffset(Math.max(0, offset - 100))}>{loc('السابق', 'Previous')}</Button><span className="fp-muted">{loc('صفحة', 'Page')} {offset / 100 + 1}</span><Button disabled={remote.loading || remote.data.withdrawals.length < 100} onClick={() => setOffset(offset + 100)}>{loc('التالي', 'Next')}</Button></div>}
  </Surface><Dialog open={!!paying} onClose={() => setPaying(null)} busy={op.busy} title={loc('تسجيل التسديد الفعلي', 'Record actual payment')}><div className="fp-stack"><p className="fp-muted">{paying?.user_name || paying?.email}</p><Field label={loc('المبلغ المسدد', 'Amount paid')}><NumberInput kind="money" value={amount} min={1} max={paying ? paying.amount_iqd - paying.paid_iqd : 0} onValueChange={(n, valid) => setAmount(valid ? n : null)} /></Field><Field label={loc('مرجع التسديد', 'Payment reference')} hint={loc('رقم التحويل أو رقم وصل التسليم النقدي.', 'Transfer number or signed cash receipt number.')}><Input value={reference} onChange={(e) => setReference(e.target.value)} placeholder={loc('مثال: وصل ١٢٤', 'e.g. Receipt 124')} /></Field><details className="fp-detail"><summary>{loc('إرفاق رابط الوصل', 'Attach receipt link')}</summary><Field label={loc('رابط الوصل', 'Receipt URL')} optional><Input ltr type="url" value={receipt} onChange={(e) => setReceipt(e.target.value)} placeholder="https://…" /></Field></details><Feedback error={op.error} /></div><footer className="fp-footer"><Button variant="ghost" disabled={op.busy} onClick={() => setPaying(null)}>{loc('رجوع', 'Back')}</Button><Button variant="primary" loading={op.busy} disabled={!paying || !amount || amount > paying.amount_iqd - paying.paid_iqd || (!reference.trim() && !/^https:\/\//.test(receipt.trim()))} onClick={pay}>{loc('تأكيد التسديد', 'Confirm payment')}</Button></footer></Dialog></div>;
}
export { WithdrawalPanel };
