/**
 * GENERATED by scripts/cairo-advances.mjs from the app's own Cairo faces (the
 * three subsets and the Kurdish patch) in Chromium — do not edit; re-run the
 * script (tests/personalizeFit.test.ts pins the checksum). Smart Fit's only
 * data: fit.ts decodes it on first use.
 *
 *   u      data units per em (values rounded up)
 *   w      the weights the data holds: a lighter weight reads the first,
 *          between two the value is linear (never below the browser)
 *   cap    cap height / em (H, the lowest across weights)
 *   asc, desc, over   ink above / below the baseline and past the advance at
 *          a line's end, em, [Latin, Arabic] (the highest across weights)
 *   gap    the space between two stacked lines, em
 *   stem   the thinnest stroke / em at 300, 400 … 900
 *   lig    lams that form a ligature with a following آ أ إ ا
 *   kern   pair rules [left, right, units per weight]: a glyph whose letter
 *          is in `left` followed by one whose letter is in `right` draws
 *          that much wider — the contextual spacing Arabic pairs have here
 *   cps    the code points with entries (hex ranges); an Arabic letter holds
 *          one entry per form its joining class allows (fit.ts formCount), a
 *          ligature two (isolated, final) after them; any other Latin letter
 *          the rule allows folds to its NFD base
 *   data   per entry, each character's code point − 48 a value 0–63: the
 *          value at w[0] in two characters (high, low), then one per next
 *          weight: its rise in steps of 3 units, + 16 (rounded up, so a value
 *          is never below the measured one)
 * CAIRO_SUM is FNV-1a 32 of `${cps}|${lig}|${JSON of kern}|${data}`.
 */
export interface CairoTable {
  u: number;
  w: readonly number[];
  cap: number;
  asc: readonly [number, number];
  desc: readonly [number, number];
  over: readonly [number, number];
  gap: number;
  stem: readonly number[];
  lig: string;
  kern: ReadonlyArray<readonly [string, string, readonly number[]]>;
  cps: string;
  data: string;
}

export const CAIRO: CairoTable = {
  u: 500,
  w: [400, 900],
  cap: 0.678,
  asc: [0.938, 1.032],
  desc: [0.266, 0.485],
  over: [0.076, 0.063],
  gap: 0.08,
  stem: [0.042, 0.063, 0.067, 0.069, 0.086, 0.093, 0.101],
  lig: '\u0644',
  kern: [['\u0631\u0632\u0698', '\u064a\u067e', [40, 27]], ['\u06ce', '\u0693\u0695\u06b5\u06c6\u06ce', [68, 68]]],
  cps: '20-21,26-27,2b,2d-2e,30-39,3f,41-5a,61-7a,c6,d0,d8,de-df,e6,ed,f0,f8,fe,10f-111,126-127,131-133,138-139,13d-142,149-14b,152-153,165-167,17f,61f,621-63a,640-64a,660-669,67e,686,693,695,698,6a4,6a9,6af,6b5,6be,6c6,6cc,6ce,6d5,6f0-6f9,2019',
  data: '1_@1mE5MB1_F4I?3R81]G4I?4I?4I?4I?4I?4I?4I?4I?4I?4I?3RC4ZE4e?4A?54A4F@4:@4eA5D>1mE2AD4ME3aB6UB5DA5<A4YC5<A4dA4?D48@54@4VB6lC4NC4GF4=D3kF49E3JD4:E3mE2_C4<E4>E1_G1_G3aH1eE6SC4>E49D48E48E2^C3YC2aB4:E3bG5nC3SI3bG3TE6gA55B5<A4\\B4PM6GA25R4E>49D49E4jR55B4:E5I>4>E1_R6;S4E@4>J3aA3lB2RT56J2nI3bA2P@5JU5DA4>E7D<6bA3KI4:?2bB2;@3RC4@J27M2DL27M2DL4AK4QL27M2DL70P26M2CO6jN27M2DL6<N26M2CO6IS4UL4QL6<N26\\2Cc6IS6<N26]2Cc6IS4SI4FG4^F4jH4SI4FG4^F4jH4SI4FG4^F4jH3cD4<E3cD4<E24Q2FR24Q2FR9NT6NW6^X9`V9NT6NW6^X9`V9DG6JH6[H9TH9DG6JH6[H9TH5nM5eM5gO6?N5nM5eM5gO6?N4DF4[=4nJ4lI4DF4[=4nJ4lI1m@85E4`G50H8AF6aN4`G50H70O68R4iJ5:K6IS5>J2:L2JM5NJ4iK51F5BF5:L5>J26M2CO5NJ4UL6?C5;H4QL4AK4QL70P26M2CO6jN70P26\\2Cc6jN1nO2KM48F5BU3\\>5DH3aL4hI4hI44L6<N26\\2CY6IS4SI4FG4^F4jH2^E33C2^E33C24Q2FR85E4`G50H8AF68W4iJ5:K6JX68W5BO5RP6JX53F2BD2O@5AC6:G6?C6JG6JH3QE3PB70P26\\2Cc6jN5SD2NC2f@56C3\\E46C1nO2KM48F5BU5<T4AV3_D4hI4hI44L1]G52N5@O52N5@O52N5@O52N5@O',
};

export const CAIRO_SUM = 0xc9ddd0cb;
