/**
 * LEVO Studio sign-in handoff (MAIN worker side) — STUDIO_PLAN decision 3.
 *
 * The Studio runs on its own host (studio.levonis-iq.com) where the
 * host-scoped `levonis_session` cookie never arrives, and widening that
 * cookie to `Domain=.levonis-iq.com` is forbidden (community subdomains
 * exist). Instead the flow is a single-use server-to-server code exchange:
 *
 *   1. The Studio host redirects the browser here:
 *        GET /api/studio/handoff/start?dest=<studio origin>&state=<nonce>
 *      (the SPA may equivalently POST /api/studio/handoff and follow the
 *      returned redirect_url). `state` was generated by the STUDIO worker
 *      and stored in a host-scoped cookie there — the callback verifies it,
 *      which is what makes the GET navigation entry safe against login-CSRF.
 *   2. With a live levonis_session, a 32-byte single-use code is minted
 *      (stored SHA-256-hashed, bound to user + destination, TTL 60s) and
 *      the browser is 302'd to `<dest>/auth/callback?code=…&state=…`.
 *      `dest` must exactly match an origin in STUDIO_ALLOWED_DESTINATIONS.
 *   3. The Studio worker redeems the code SERVER-TO-SERVER:
 *        POST /api/studio/handoff/redeem  (Authorization: Bearer <shared secret>)
 *      Consumption is atomic and single-use; replays and expired codes get
 *      one uniform BAD_CODE error. The response carries the minimum
 *      identity only: { user_id, display_name, locale } — no email, no
 *      phone, no KYC, no wallet (mandate §3).
 *   4. POST /api/studio/handoff/introspect lets the Studio's sensitive APIs
 *      check whether the user still has ANY live main-site session, so
 *      main-site logout/invalidation reaches Studio access (mandate §3).
 *
 * Conventions: session comes from the global loadSessionUser middleware,
 * CSRF from the global originCheck (state-changing requests), rate limiting
 * via lib/ratelimit, sensitive mutations audited via lib/audit. Raw codes
 * and the shared secret are never logged and never stored.
 *
 * Registered in worker/index.ts as:  app.route('/api/studio', studioRoutes);
 */
import { Hono } from 'hono';
import type { Context } from 'hono';
import type { AppContext } from '../lib/types';
import { localeToApi } from '../lib/types';
import { badRequest, forbidden, unauthorized, unavailable, str } from '../lib/http';
import { randomToken, sha256Hex, timingSafeEqual } from '../lib/crypto';
import { rateLimit } from '../lib/ratelimit';
import { audit } from '../lib/audit';

export const studioRoutes = new Hono<AppContext>();

/**
 * Deploy-time additions for this route. NOT yet part of lib/types.ts Env
 * (that file is owned by the orchestrator this round) — both stay optional
 * and the endpoints report honest 503s until they are configured:
 *   STUDIO_HANDOFF_SECRET       shared secret presented by the Studio worker
 *                               (wrangler secret; set per environment).
 *   STUDIO_ALLOWED_DESTINATIONS comma-separated exact origins allowed as
 *                               handoff destinations, e.g.
 *                               "https://studio.levonis-iq.com".
 */
interface StudioHandoffEnv {
  STUDIO_HANDOFF_SECRET?: string;
  STUDIO_ALLOWED_DESTINATIONS?: string;
}

const HANDOFF_TTL_SECONDS = 60;
/** b64url of 32 random bytes is 43 chars; both nonces share the charset. */
const NONCE_RE = /^[A-Za-z0-9_-]{20,128}$/;
/** One uniform message for every redeem failure — no oracle for attackers. */
const BAD_CODE_MSG = 'This sign-in code is invalid or has expired';

const enc = new TextEncoder();

function extras(c: Context<AppContext>): StudioHandoffEnv {
  return c.env as AppContext['Bindings'] & StudioHandoffEnv;
}

function allowedDestinations(c: Context<AppContext>): string[] {
  return (extras(c).STUDIO_ALLOWED_DESTINATIONS || '')
    .split(',')
    .map((s) => s.trim().replace(/\/+$/, ''))
    .filter(Boolean);
}

/** Validates ?dest= against the exact-origin allowlist. */
function requireDest(c: Context<AppContext>, raw: unknown): string {
  const allowed = allowedDestinations(c);
  if (allowed.length === 0) {
    throw unavailable(
      'LEVO Studio sign-in is not configured yet (STUDIO_ALLOWED_DESTINATIONS is unset)',
      'STUDIO_NOT_CONFIGURED'
    );
  }
  const value = str(raw, 'dest', { min: 1, max: 300 });
  let origin: string;
  try {
    origin = new URL(value).origin;
  } catch {
    throw badRequest('dest must be a valid origin', 'BAD_DEST');
  }
  // Exact origin match only — no prefixes, no wildcards (mandate §3).
  if (origin === 'null' || !allowed.includes(origin)) {
    throw forbidden('This destination is not allowed');
  }
  return origin;
}

function requireState(raw: unknown): string {
  const value = str(raw, 'state', { min: 20, max: 128 });
  if (!NONCE_RE.test(value)) throw badRequest('state has an invalid format', 'BAD_STATE');
  return value;
}

/** Constant-time shared-secret check for the server-to-server endpoints. */
async function requireStudioSecret(c: Context<AppContext>): Promise<void> {
  const secret = (extras(c).STUDIO_HANDOFF_SECRET || '').trim();
  if (!secret) {
    throw unavailable(
      'LEVO Studio sign-in is not configured yet (STUDIO_HANDOFF_SECRET is unset)',
      'STUDIO_NOT_CONFIGURED'
    );
  }
  const header = c.req.header('Authorization') || '';
  const presented = header.startsWith('Bearer ') ? header.slice(7).trim() : '';
  // Hashing both sides first makes the comparison length-independent.
  const a = enc.encode(await sha256Hex(presented));
  const b = enc.encode(await sha256Hex(secret));
  if (!presented || !timingSafeEqual(a, b)) {
    throw unauthorized('Invalid service credentials');
  }
}

/**
 * Mints a single-use handoff code for the signed-in user and returns the
 * full callback URL on the Studio host. Only the SHA-256 digest is stored.
 */
async function mintHandoffUrl(c: Context<AppContext>, dest: string, state: string): Promise<string> {
  const user = c.get('user')!;
  const code = randomToken(32);
  const codeHash = await sha256Hex(code);
  const now = Date.now();
  const expiresAt = new Date(now + HANDOFF_TTL_SECONDS * 1000).toISOString();
  await c.env.DB.prepare(
    'INSERT INTO studio_handoff_codes (code_hash, user_id, dest, state, expires_at) VALUES (?, ?, ?, ?, ?)'
  )
    .bind(codeHash, user.id, dest, state, expiresAt)
    .run();
  // Opportunistic cleanup: codes are 60s-lived, so anything an hour old is
  // dead weight whether consumed or abandoned.
  await c.env.DB.prepare('DELETE FROM studio_handoff_codes WHERE expires_at < ?')
    .bind(new Date(now - 3_600_000).toISOString())
    .run();
  await audit(c.env.DB, user.id, 'studio.handoff_minted', user.id, { dest });
  return `${dest}/auth/callback?code=${code}&state=${encodeURIComponent(state)}`;
}

/**
 * Origin for links back into the main site (login resume). Mirrors
 * routes/auth.ts trustedOrigin: APP_ORIGIN in deployed environments, the
 * request origin only as a local-dev fallback.
 */
function trustedOrigin(c: Context<AppContext>): string {
  const configured = (c.env.APP_ORIGIN || '').trim().replace(/\/+$/, '');
  if (configured) return configured;
  return new URL(c.req.url).origin;
}

/**
 * Browser navigation entry (top-level GET from the Studio host). Session
 * cookies are SameSite=Lax, so this navigation carries them. Minting on a
 * GET is safe here because the code only ever lands on an allowlisted
 * destination AND the Studio callback rejects any response whose `state`
 * does not match the nonce in its own host-scoped cookie — a forged
 * cross-site GET cannot know the victim's Studio state cookie.
 */
studioRoutes.get('/handoff/start', async (c) => {
  await rateLimit(c, 'studio-handoff', 30, 300);
  const dest = requireDest(c, c.req.query('dest'));
  const state = requireState(c.req.query('state'));
  c.header('Cache-Control', 'no-store');

  if (!c.get('user')) {
    // Not signed in on the main site: send to the main login and come back
    // here afterwards (?next= is sanitized to a same-origin relative path
    // by the SPA). The raw code is never minted for an anonymous visitor.
    const resume = `/api/studio/handoff/start?dest=${encodeURIComponent(dest)}&state=${encodeURIComponent(state)}`;
    return c.redirect(`${trustedOrigin(c)}/auth?next=${encodeURIComponent(resume)}`, 302);
  }

  const url = await mintHandoffUrl(c, dest, state);
  return c.redirect(url, 302);
});

/**
 * SPA/fetch entry — the JSON twin of /handoff/start for a signed-in page
 * that wants to open the Studio (global originCheck covers CSRF). Returns
 * the callback URL for the caller to navigate to; never a Set-Cookie.
 */
studioRoutes.post('/handoff', async (c) => {
  await rateLimit(c, 'studio-handoff', 30, 300);
  if (!c.get('user')) throw unauthorized();
  const body = await c.req.json().catch(() => ({} as Record<string, unknown>));
  const dest = requireDest(c, body.dest);
  const state = requireState(body.state);
  c.header('Cache-Control', 'no-store');
  const redirectUrl = await mintHandoffUrl(c, dest, state);
  return c.json({ success: true, redirect_url: redirectUrl, expires_in: HANDOFF_TTL_SECONDS });
});

/**
 * Server-to-server redemption by the Studio worker (never the browser).
 * Atomic single-use: the conditional UPDATE consumes the code exactly once;
 * expired/replayed/wrong-destination codes all fail with one uniform error.
 */
studioRoutes.post('/handoff/redeem', async (c) => {
  await requireStudioSecret(c);
  // Bearer-gated already; generous backstop bucket (worker egress IPs are
  // shared, so a tight IP bucket would throttle legitimate sign-ins).
  await rateLimit(c, 'studio-redeem', 600, 60);
  const body = await c.req.json().catch(() => ({} as Record<string, unknown>));
  const code = str(body.code, 'code', { min: 20, max: 128 });
  const dest = str(body.dest, 'dest', { min: 1, max: 300 });
  if (!NONCE_RE.test(code)) throw badRequest(BAD_CODE_MSG, 'BAD_CODE');
  c.header('Cache-Control', 'no-store');

  const codeHash = await sha256Hex(code);
  const nowIso = new Date().toISOString();
  // Atomic consume-and-fetch: exactly one concurrent redeem can win.
  const row = await c.env.DB.prepare(
    `UPDATE studio_handoff_codes SET consumed_at = ?1
      WHERE code_hash = ?2 AND consumed_at IS NULL AND expires_at > ?1 AND dest = ?3
      RETURNING user_id`
  )
    .bind(nowIso, codeHash, dest.replace(/\/+$/, ''))
    .first<{ user_id: string }>();
  if (!row) throw badRequest(BAD_CODE_MSG, 'BAD_CODE');

  const user = await c.env.DB.prepare('SELECT id, name, username, locale FROM users WHERE id = ?')
    .bind(row.user_id)
    .first<{ id: string; name: string | null; username: string | null; locale: string }>();
  if (!user) throw badRequest(BAD_CODE_MSG, 'BAD_CODE');

  await audit(c.env.DB, user.id, 'studio.handoff_redeemed', user.id, { dest });
  // Minimum identity only (mandate §3): no email, no phone, no roles, no
  // wallet/KYC — the Studio stores this as an opaque owner identity.
  return c.json({
    success: true,
    user_id: user.id,
    display_name: (user.name || '').trim() || user.username || 'User',
    locale: localeToApi(user.locale),
  });
});

/**
 * Server-to-server liveness check: does this user still have ANY live
 * main-site session? Lets Studio's sensitive APIs honor main-site logout /
 * session invalidation (mandate §3) without ever seeing the session token.
 */
studioRoutes.post('/handoff/introspect', async (c) => {
  await requireStudioSecret(c);
  await rateLimit(c, 'studio-introspect', 600, 60);
  const body = await c.req.json().catch(() => ({} as Record<string, unknown>));
  const userId = str(body.user_id, 'user_id', { min: 1, max: 64 });
  c.header('Cache-Control', 'no-store');
  const live = await c.env.DB.prepare(
    'SELECT s.id FROM sessions s JOIN users u ON u.id = s.user_id WHERE s.user_id = ? AND s.expires_at > ? LIMIT 1'
  )
    .bind(userId, new Date().toISOString())
    .first();
  return c.json({ success: true, active: !!live });
});
