/**
 * THE MEMBERS CONSOLE'S OWN WORDS, IN ALL THREE LANGUAGES.
 *
 * Moved here whole out of AdminMemberships.tsx when the member detail became a
 * window (src/components/adminMemberships/MemberDetailModal.tsx): the modal and
 * the table that opens it both read them, and a second copy in either file
 * would drift — one screen would say «الأرقام المالية محجوبة» while the other
 * still said nothing at all.
 *
 * THE THREE LANGUAGES ARE THREE LANGUAGES, NOT TWO AND A DIRECTION. Every
 * string below exists in `ar`, `en` AND `ckb`, and every reader of this table
 * picks by LANGUAGE (`STRINGS[lang]`, or `loc(ar, en, ckb)` in a component
 * that has no `S` to hand). The idiom this repository keeps having to remove —
 * `dir === 'rtl' ? ar : en` — serves ARABIC to every Kurdish admin and calls
 * it a translation, because Sorani is also written right to left. It is
 * invisible to an Arabic-reading reviewer, which is exactly why it survives.
 */

export const STRINGS = {
  ar: {
    tabMembers: 'الأعضاء',
    tabQueue: 'قائمة الدعم',
    searchPlaceholder: 'بحث بالبريد/الاسم/اسم المستخدم...',
    fTier: 'الفئة',
    fStatus: 'حالة الاشتراك',
    fKyc: 'حالة الهوية',
    fRestriction: 'القيود',
    fExpiry: 'ينتهي خلال',
    all: 'الكل',
    days: 'يوم',
    colMember: 'العضو',
    colTier: 'الفئة',
    colState: 'الاشتراك',
    colExpiry: 'الانتهاء',
    colKyc: 'الهوية',
    colRestr: 'قيود',
    colAddr: 'عنوان معتمد',
    yes: 'نعم',
    no: 'لا',
    none: 'لا يوجد',
    loading: 'جارٍ التحميل...',
    empty: 'لا نتائج',
    loadError: 'تعذر التحميل',
    retry: 'إعادة المحاولة',
    detailTitle: 'تفاصيل العضو',
    secSubscription: 'الاشتراك (الدفع والمدة)',
    secIdentity: 'حالة الهوية (KYC)',
    secBenefits: 'سياق أهلية المزايا',
    secAddresses: 'العنوان المعتمد',
    secDebt: 'الديون (الشراء الآن والدفع لاحقًا)',
    secRestrictions: 'قضايا القيود',
    bnplStatus: 'BNPL فعّال حصريًا لأعضاء PRO المستوفين. سجل الدين غير قابل للتعديل؛ إدارة السقف والحالة مدققة أدناه.',
    eligible: 'مؤهل الآن',
    ineligible: 'غير مؤهل',
    available: 'المتاح',
    approveBnpl: 'اعتماد / تحديث السقف',
    suspendBnpl: 'تعليق BNPL',
    limitPlaceholder: 'السقف بالدينار',
    bnplSaved: 'تم تحديث حساب BNPL',
    outstanding: 'الرصيد المستحق',
    creditLimit: 'السقف',
    accountState: 'حالة الحساب',
    noLedger: 'لا توجد حركات',
    kycNone: 'لا توجد قضايا هوية',
    kycNote: 'تُعرض الحالات فقط — أدلة الهوية المشفّرة تُفتح حصريًا من واجهة مراجعة KYC المخصصة.',
    benefitActive: 'مزايا سارية',
    benefitGated: 'مزايا مقيّدة حاليًا',
    benefitNoneGated: 'لا قيود فعالة على المزايا',
    benefitNote:
      'القيود تقيّد احتساب المزايا فقط — لا تحذف طلبات أو محفظة أو نقاطًا ولا تمنع الضمان أو الدعم. اختيار عنوان بديل حالة لكل طلب وليس عقوبة.',
    gatingScopeNote:
      'التقييد نافذ عبر طبقة الاستحقاقات المركزية في الدفع والشحن والمجتمع والمتجر والدعم.',
    addrNone: 'لا يوجد عنوان معتمد',
    subsNone: 'لا اشتراكات',
    openCase: 'فتح قضية قيد',
    caseType: 'نوع القضية',
    ct_dropshipping_suspected: 'اشتباه دروبشيبينغ',
    ct_repeated_refusal: 'رفض استلام متكرر',
    ct_abuse: 'إساءة استخدام',
    ct_debt: 'دين غير مسدد',
    evidence: 'الأدلة (نص)',
    reason: 'السبب',
    decision: 'القرار',
    d_pause: 'إيقاف مؤقت',
    d_revoke: 'سحب حتى القرار',
    flags: 'المزايا المقيّدة',
    submitCase: 'فتح القضية',
    creating: 'جارٍ الحفظ...',
    resume: 'استئناف المزايا (حل القضية)',
    resumeReason: 'سبب الاستئناف:',
    active: 'فعالة',
    resolved: 'محلولة',
    openedAt: 'فُتحت',
    resolvedAt: 'حُلّت',
    caseNone: 'لا قضايا',
    required: 'هذا الحقل مطلوب',
    selectFlag: 'اختر ميزة واحدة على الأقل',
    close: 'إغلاق',
    openMember: 'فتح ملف العضو',
    memberIdLabel: 'معرّف الحساب',
    statTickets: 'تذاكر الدعم',
    statGated: 'مزايا مقيّدة',
    joined: 'عضو منذ',
    ledgerTitle: 'حركات الدين',
    bnplControls: 'إدارة السقف (مدقّقة)',
    // §11 — the sentence that appears INSTEAD of a figure, never over it.
    moneyLocked: 'محجوب',
    moneyHidden:
      'الأرقام المالية (السقف والدين والمبالغ المدفوعة) للمالك أو للأدمن المالي فقط. ما يظهر هنا هو ما أرسله الخادم لهذا الحساب — لا يُخفى شيء في المتصفح.',
    // queue
    queueTitle: 'قائمة تذاكر الدعم (أولوية PRO ثم الأقدمية — العمر ظاهر دائمًا)',
    qState: 'الحالة',
    unresolved: 'غير المحلولة',
    colTicket: 'التذكرة',
    colCustomer: 'العميل',
    colPriority: 'الأولوية',
    colAge: 'العمر',
    colMsgs: 'رسائل',
    proBadge: 'PRO',
    ordinary: 'عادي',
    stateOpen: 'مفتوحة',
    stateWaitingCustomer: 'بانتظار العميل',
    stateWaitingStaff: 'بانتظار الفريق',
    stateResolved: 'محلولة',
    replyPlaceholder: 'رد الفريق...',
    reply: 'إرسال الرد',
    moveTo: 'نقل إلى...',
    customer: 'العميل',
    staffLabel: 'الفريق',
    ticketsEmpty: 'لا تذاكر',
  },
  en: {
    tabMembers: 'Members',
    tabQueue: 'Support queue',
    searchPlaceholder: 'Search email/name/username...',
    fTier: 'Tier',
    fStatus: 'Membership',
    fKyc: 'KYC',
    fRestriction: 'Restrictions',
    fExpiry: 'Expires within',
    all: 'All',
    days: 'days',
    colMember: 'Member',
    colTier: 'Tier',
    colState: 'Membership',
    colExpiry: 'Expires',
    colKyc: 'KYC',
    colRestr: 'Restr.',
    colAddr: 'Appr. address',
    yes: 'Yes',
    no: 'No',
    none: 'None',
    loading: 'Loading...',
    empty: 'No results',
    loadError: 'Failed to load',
    retry: 'Retry',
    detailTitle: 'Member detail',
    secSubscription: 'Subscription (payment & term)',
    secIdentity: 'Identity status (KYC)',
    secBenefits: 'Benefit eligibility context',
    secAddresses: 'Approved address',
    secDebt: 'Debt (Buy Now Pay Later)',
    secRestrictions: 'Restriction cases',
    bnplStatus: 'BNPL is active exclusively for eligible PRO members. Debt entries are immutable; audited limit/state controls are below.',
    eligible: 'Eligible now',
    ineligible: 'Not eligible',
    available: 'Available',
    approveBnpl: 'Approve / update limit',
    suspendBnpl: 'Suspend BNPL',
    limitPlaceholder: 'Credit limit (IQD)',
    bnplSaved: 'BNPL account updated',
    outstanding: 'Outstanding',
    creditLimit: 'Limit',
    accountState: 'Account state',
    noLedger: 'No ledger entries',
    kycNone: 'No identity cases',
    kycNote: 'States only — encrypted identity evidence opens exclusively in the dedicated KYC review surface.',
    benefitActive: 'Active benefits basis',
    benefitGated: 'Currently gated benefits',
    benefitNoneGated: 'No active benefit restrictions',
    benefitNote:
      'Restrictions gate benefit computation ONLY — they never delete orders, wallet or points, and never block warranty or support access. Choosing an alternate address is a per-order condition, not a sanction.',
    gatingScopeNote:
      'Gating is enforced through the canonical entitlement layer across checkout, shipping, Community, stores and support.',
    addrNone: 'No approved address',
    subsNone: 'No memberships',
    openCase: 'Open restriction case',
    caseType: 'Case type',
    ct_dropshipping_suspected: 'Suspected dropshipping',
    ct_repeated_refusal: 'Repeated delivery refusal',
    ct_abuse: 'Abuse',
    ct_debt: 'Unpaid debt',
    evidence: 'Evidence (text)',
    reason: 'Reason',
    decision: 'Decision',
    d_pause: 'Pause (temporary)',
    d_revoke: 'Revoke until resolved',
    flags: 'Gated benefits',
    submitCase: 'Open case',
    creating: 'Saving...',
    resume: 'Resume benefits (resolve case)',
    resumeReason: 'Resume reason:',
    active: 'Active',
    resolved: 'Resolved',
    openedAt: 'Opened',
    resolvedAt: 'Resolved',
    caseNone: 'No cases',
    required: 'This field is required',
    selectFlag: 'Select at least one benefit',
    close: 'Close',
    openMember: 'Open member profile',
    memberIdLabel: 'Account id',
    statTickets: 'Support tickets',
    statGated: 'Gated benefits',
    joined: 'Member since',
    ledgerTitle: 'Debt entries',
    bnplControls: 'Credit limit (audited)',
    moneyLocked: 'Hidden',
    moneyHidden:
      'Money (credit limit, debt, amounts paid) is for the owner or a financial admin. What is shown here is what the server sent this account — nothing is hidden in the browser.',
    queueTitle: 'Support ticket queue (PRO priority then age — age always visible)',
    qState: 'State',
    unresolved: 'Unresolved',
    colTicket: 'Ticket',
    colCustomer: 'Customer',
    colPriority: 'Priority',
    colAge: 'Age',
    colMsgs: 'Msgs',
    proBadge: 'PRO',
    ordinary: 'Ordinary',
    stateOpen: 'Open',
    stateWaitingCustomer: 'Waiting customer',
    stateWaitingStaff: 'Waiting staff',
    stateResolved: 'Resolved',
    replyPlaceholder: 'Staff reply...',
    reply: 'Send reply',
    moveTo: 'Move to...',
    customer: 'Customer',
    staffLabel: 'Staff',
    ticketsEmpty: 'No tickets',
  },
  ckb: {
    tabMembers: 'ئەندامان',
    tabQueue: 'ڕیزی پشتگیری',
    searchPlaceholder: 'گەڕان بە ئیمەیڵ/ناو...',
    fTier: 'پلە',
    fStatus: 'ئەندامێتی',
    fKyc: 'KYC',
    fRestriction: 'سنووردارکردن',
    fExpiry: 'کۆتایی دێت لە ماوەی',
    all: 'هەموو',
    days: 'ڕۆژ',
    colMember: 'ئەندام',
    colTier: 'پلە',
    colState: 'ئەندامێتی',
    colExpiry: 'کۆتایی',
    colKyc: 'KYC',
    colRestr: 'سنوور',
    colAddr: 'ناونیشانی پەسەند',
    yes: 'بەڵێ',
    no: 'نەخێر',
    none: 'نییە',
    loading: 'بارکردن...',
    empty: 'هیچ ئەنجامێک نییە',
    loadError: 'بارکردن سەرکەوتوو نەبوو',
    retry: 'هەوڵدانەوە',
    detailTitle: 'وردەکاری ئەندام',
    secSubscription: 'ئەندامێتی (پارەدان و ماوە)',
    secIdentity: 'دۆخی ناسنامە (KYC)',
    secBenefits: 'سیاقی شایستەیی سوودەکان',
    secAddresses: 'ناونیشانی پەسەندکراو',
    secDebt: 'قەرز (BNPL)',
    secRestrictions: 'کەیسەکانی سنووردارکردن',
    bnplStatus: 'BNPL تەنها بۆ ئەندامی PRO ی گونجاو چالاکە. تۆماری قەرز ناگۆڕدرێت؛ سنوور و دۆخ لە خوارەوە بە پشکنینەوە بەڕێوەدەبرێت.',
    eligible: 'ئێستا گونجاوە',
    ineligible: 'گونجاو نییە',
    available: 'بەردەست',
    approveBnpl: 'پەسەندکردن / نوێکردنەوەی سنوور',
    suspendBnpl: 'ڕاگرتنی BNPL',
    limitPlaceholder: 'سنووری قەرز (IQD)',
    bnplSaved: 'هەژماری BNPL نوێکرایەوە',
    outstanding: 'ماوەی قەرز',
    creditLimit: 'سنوور',
    accountState: 'دۆخی هەژمار',
    noLedger: 'هیچ تۆمارێک نییە',
    kycNone: 'هیچ کەیسێکی ناسنامە نییە',
    kycNote: 'تەنها دۆخەکان — بەڵگە شفرکراوەکانی ناسنامە تەنها لە ڕووکاری پێداچوونەوەی KYC دەکرێنەوە.',
    benefitActive: 'بنەمای سوودە چالاکەکان',
    benefitGated: 'سوودە سنووردارکراوەکان',
    benefitNoneGated: 'هیچ سنوورێکی چالاک نییە لەسەر سوودەکان',
    benefitNote:
      'سنووردارکردنەکان تەنها ژماردنی سوودەکان دەگرنەوە — هەرگیز داواکاری، جزدان یان خاڵ ناسڕنەوە و گەرەنتی و پشتگیری ناگیرێت. هەڵبژاردنی ناونیشانی جیاواز مەرجی هەر داواکارییەکە، نەک سزا.',
    gatingScopeNote:
      'سنووردارکردن لە ڕێگەی توێژی ناوەندی سوودەکان لە پارەدان و گەیاندن و کۆمەڵگە و فرۆشگا و پشتگیری جێبەجێ دەکرێت.',
    addrNone: 'ناونیشانی پەسەندکراو نییە',
    subsNone: 'هیچ ئەندامێتییەک نییە',
    openCase: 'کردنەوەی کەیسی سنووردارکردن',
    caseType: 'جۆری کەیس',
    ct_dropshipping_suspected: 'گومانی دڕۆپشیپینگ',
    ct_repeated_refusal: 'ڕەتکردنەوەی دووبارەی وەرگرتن',
    ct_abuse: 'بەکارهێنانی خراپ',
    ct_debt: 'قەرزی نەدراوە',
    evidence: 'بەڵگە (دەق)',
    reason: 'هۆکار',
    decision: 'بڕیار',
    d_pause: 'ڕاگرتنی کاتی',
    d_revoke: 'سەندنەوە تا چارەسەر',
    flags: 'سوودە سنووردارکراوەکان',
    submitCase: 'کردنەوەی کەیس',
    creating: 'پاشەکەوتکردن...',
    resume: 'گەڕاندنەوەی سوودەکان (چارەسەری کەیس)',
    resumeReason: 'هۆکاری گەڕاندنەوە:',
    active: 'چالاک',
    resolved: 'چارەسەرکراوە',
    openedAt: 'کرایەوە',
    resolvedAt: 'چارەسەرکرا',
    caseNone: 'هیچ کەیسێک نییە',
    required: 'ئەم خانەیە پێویستە',
    selectFlag: 'لانیکەم یەک سوود هەڵبژێرە',
    close: 'داخستن',
    openMember: 'کردنەوەی پرۆفایلی ئەندام',
    memberIdLabel: 'ناسنامەی هەژمار',
    statTickets: 'تیکێتی پشتگیری',
    statGated: 'سوودی سنووردارکراو',
    joined: 'ئەندام لە',
    ledgerTitle: 'جووڵەکانی قەرز',
    bnplControls: 'سنووری قەرز (پشکنراو)',
    moneyLocked: 'شاراوە',
    moneyHidden:
      'ژمارە داراییەکان (سنوور، قەرز، پارەی دراو) تەنها بۆ خاوەن یان ئەدمینی دارایی. ئەوەی لێرە دەردەکەوێت ئەوەیە کە ڕاژە بۆ ئەم هەژمارە ناردوویەتی — هیچ شتێک لە وێبگەڕدا نەشاردراوەتەوە.',
    queueTitle: 'ڕیزی تیکێتی پشتگیری (پێشینەیی PRO پاشان تەمەن — تەمەن هەمیشە دیارە)',
    qState: 'دۆخ',
    unresolved: 'چارەسەرنەکراوەکان',
    colTicket: 'تیکێت',
    colCustomer: 'کڕیار',
    colPriority: 'پێشینەیی',
    colAge: 'تەمەن',
    colMsgs: 'پەیام',
    proBadge: 'PRO',
    ordinary: 'ئاسایی',
    stateOpen: 'کراوەیە',
    stateWaitingCustomer: 'چاوەڕوانی کڕیار',
    stateWaitingStaff: 'چاوەڕوانی تیم',
    stateResolved: 'چارەسەرکراوە',
    replyPlaceholder: 'وەڵامی تیم...',
    reply: 'ناردنی وەڵام',
    moveTo: 'گواستنەوە بۆ...',
    customer: 'کڕیار',
    staffLabel: 'تیم',
    ticketsEmpty: 'هیچ تیکێتێک نییە',
  },
};

export type S = (typeof STRINGS)['en'];

export const BENEFIT_LABELS: Record<string, { ar: string; en: string; ckb: string }> = {
  proPricing: { ar: 'أسعار PRO', en: 'PRO prices', ckb: 'نرخەکانی PRO' },
  freeDelivery: { ar: 'التوصيل المجاني', en: 'Free delivery', ckb: 'گەیاندنی بێبەرامبەر' },
  noPreorderCommission: { ar: 'إعفاء عمولة الطلب المسبق', en: 'Preorder commission waiver', ckb: 'لێبوردنی کۆمیسیۆنی پێش-داواکاری' },
  priorityService: { ar: 'أولوية الخدمة والدعم', en: 'Priority service/support', ckb: 'پێشینەیی خزمەتگوزاری/پشتگیری' },
  proExclusive: { ar: 'عروض PRO الحصرية', en: 'PRO-exclusive offers', ckb: 'ئۆفەرە تایبەتەکانی PRO' },
  merchantProfile: { ar: 'ملف التاجر', en: 'Merchant profile', ckb: 'پرۆفایلی بازرگان' },
  exclusiveSections: { ar: 'الأقسام الحصرية', en: 'Exclusive sections', ckb: 'بەشە تایبەتەکان' },
  verifiedMerchant: { ar: 'شارة التاجر PRO', en: 'PRO merchant badge', ckb: 'نیشانەی بازرگانی PRO' },
  proMerchantBadge: { ar: 'شارة التاجر PRO', en: 'PRO merchant badge', ckb: 'نیشانەی بازرگانی PRO' },
  exclusiveCoupons: { ar: 'كوبونات الأعضاء', en: 'Member coupons', ckb: 'کۆپۆنی ئەندامان' },
};

export const CASE_TYPES = ['dropshipping_suspected', 'repeated_refusal', 'abuse', 'debt'] as const;

export function benefitLabel(flag: string, lang: 'ar' | 'en' | 'ckb'): string {
  const l = BENEFIT_LABELS[flag];
  if (!l) return flag;
  return lang === 'en' ? l.en : lang === 'ckb' ? l.ckb : l.ar;
}

/**
 * A stored instant as a bare YYYY-MM-DD, for a column that must stay narrow.
 *
 * NO DAY ARITHMETIC HAPPENS HERE, and the ISO slice is deliberate rather than
 * lazy: `toISOString` is UTC, and Baghdad is UTC+3, so for the first three
 * hours of every Baghdad day this prints YESTERDAY. It is kept because it is
 * what the table already showed and because nothing decides anything from it —
 * but the moment a screen needs "expired today", it asks the server, which has
 * worker/lib/baghdadTime.ts. Anything else silently misses a whole day's
 * memberships every night.
 */
export function shortDate(iso: string | null): string {
  if (!iso) return '—';
  const ms = Date.parse(iso);
  if (!Number.isFinite(ms)) return '—';
  return new Date(ms).toISOString().slice(0, 10);
}
