/**
 * Remove ONE object — the private duplicate of the public logo — and
 * nothing else, ever, and only once the public copy is proven.
 * Generated by .github/workflows/media-stray-private-logo-remove.yml.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { isAnonymousPublicMediaKey } from '../worker/lib/mediaStorage';

function required(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is not set`);
  return value;
}

const PRIVATE_BUCKET = required('PRIVATE_BUCKET');
const PUBLIC_BUCKET = required('PUBLIC_BUCKET');
const ENDPOINT = required('R2_ENDPOINT');
const DRY_RUN = process.env.DRY_RUN === 'true';

/**
 * THE ONLY KEY THIS SCRIPT MAY DELETE, and the size its surviving
 * twin must have. Literals, not inputs: an operator chooses the
 * buckets and whether to run, never the key.
 */
const KEY = 'UiUx/Logo/Logo.webp';
const EXPECTED_BYTES = 107218;

function aws(args: string[], expectJson = true): any {
  const out = execFileSync(
    'aws',
    ['s3api', args[0], '--endpoint-url', ENDPOINT, '--output', 'json', ...args.slice(1)],
    { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }
  );
  if (!expectJson) return null;
  const text = out.trim();
  return text ? JSON.parse(text) : null;
}

function awsOrNull(args: string[]): any {
  try { return aws(args); } catch { return null; }
}

const scratch = mkdtempSync(join(tmpdir(), 'straylogo-'));
function sha256(bucket: string, tag: string): string {
  const file = join(scratch, tag);
  aws(['get-object', '--bucket', bucket, '--key', KEY, file]);
  return createHash('sha256').update(readFileSync(file)).digest('hex');
}

const refusals: string[] = [];
function check(name: string, held: boolean, value: string): void {
  console.log('  ' + (held ? 'ok  ' : 'FAIL') + '  ' + name + ' : ' + value);
  if (!held) refusals.push(name);
}

console.log('key            : ' + JSON.stringify(KEY));
console.log('delete from    : ' + PRIVATE_BUCKET);
console.log('must survive in: ' + PUBLIC_BUCKET);
console.log('mode           : ' + (DRY_RUN ? 'DRY RUN — proves everything, deletes nothing' : 'DELETE'));
console.log('');

// The buckets are distinct, and the delete does not name the public one.
check('private and public are different buckets', PRIVATE_BUCKET !== PUBLIC_BUCKET, PRIVATE_BUCKET + ' vs ' + PUBLIC_BUCKET);

// This key is PUBLIC by the Worker's own rule, which is why the
// private copy is dead weight: for a public key `mediaBucket()`
// resolves to R2_PUBLIC and no request ever opens the private one.
check('the Worker classifies this key as public', isAnonymousPublicMediaKey(KEY) === true, String(isAnonymousPublicMediaKey(KEY)));

// PROOF 1 + 2 — the survivor exists, at this exact key, at this size.
const publicHead = awsOrNull(['head-object', '--bucket', PUBLIC_BUCKET, '--key', KEY]);
check('public copy exists', publicHead !== null, publicHead ? 'present' : 'ABSENT');
const publicBytes = publicHead ? Number(publicHead.ContentLength) : -1;
check('public copy size is exactly ' + EXPECTED_BYTES, publicBytes === EXPECTED_BYTES, String(publicBytes));

// The private object itself. Absent is not a failure: re-running must
// be a no-op, because the object this job removes stays removed.
const privateHead = awsOrNull(['head-object', '--bucket', PRIVATE_BUCKET, '--key', KEY]);
if (!privateHead) {
  console.log('');
  console.log('STRAY PRIVATE LOGO BEFORE  : absent');
  console.log('STRAY PRIVATE LOGO DELETED : 0 (an earlier run already removed it)');
  console.log('PUBLIC LOGO INTACT         : ' + (publicBytes === EXPECTED_BYTES ? 'yes' : 'NO'));
  if (refusals.length > 0) { console.error('::error::' + refusals.join('; ')); process.exit(1); }
  process.exit(0);
}
console.log('  --  private copy present   : ' + Number(privateHead.ContentLength) + ' B');

// PROOF 4 — it is a DUPLICATE, byte for byte. Same size is not
// enough: two different 107218-byte files would pass that. If the
// bytes differ this is not the stray copy, it is something unique,
// and deleting it would destroy the only instance of whatever it is.
const publicDigest = publicHead ? sha256(PUBLIC_BUCKET, 'public') : '';
const privateDigest = sha256(PRIVATE_BUCKET, 'private');
console.log('  --  public  sha256         : ' + publicDigest);
console.log('  --  private sha256         : ' + privateDigest);
check('the private object is byte-identical to the public one',
  publicDigest !== '' && publicDigest === privateDigest,
  publicDigest === privateDigest ? 'identical' : 'DIFFERENT — this is not a duplicate');

if (refusals.length > 0) {
  console.error('');
  console.error('::error::refusing to delete anything: ' + refusals.join('; '));
  process.exit(1);
}

if (DRY_RUN) {
  console.log('');
  console.log('DRY RUN — every check passed and no delete-object call was made');
  process.exit(0);
}

// THE DELETE. One object, in the private bucket, by its exact key.
aws(['delete-object', '--bucket', PRIVATE_BUCKET, '--key', KEY], false);
console.log('');
console.log('DeleteObject: single object, --bucket ' + PRIVATE_BUCKET + ' --key ' + JSON.stringify(KEY));

// AFTERWARDS: the duplicate is gone and the survivor is untouched.
const goneHead = awsOrNull(['head-object', '--bucket', PRIVATE_BUCKET, '--key', KEY]);
const survivorHead = awsOrNull(['head-object', '--bucket', PUBLIC_BUCKET, '--key', KEY]);
const survivorBytes = survivorHead ? Number(survivorHead.ContentLength) : -1;
console.log('');
console.log('STRAY PRIVATE LOGO BEFORE  : present (' + Number(privateHead.ContentLength) + ' B)');
console.log('STRAY PRIVATE LOGO DELETED : 1');
console.log('STRAY PRIVATE LOGO EXISTS  : ' + (goneHead ? 'YES — IT DID NOT GO' : 'no'));
console.log('PUBLIC LOGO EXISTS         : ' + (survivorHead ? 'yes' : 'NO'));
console.log('PUBLIC LOGO BYTES          : ' + survivorBytes);
console.log('OTHER OBJECTS DELETED      : 0');

if (goneHead) { console.error('::error::the private duplicate is still present'); process.exit(1); }
if (survivorBytes !== EXPECTED_BYTES) {
  console.error('::error::the PUBLIC logo is not intact after the delete — this is the failure this job exists to prevent');
  process.exit(1);
}
