/**
 * Legacy R2 media move — copy + verify (MODE=copy), or verify + prune
 * (MODE=prune). Generated by .github/workflows/media-bucket-move.yml
 * and never committed.
 *
 * Which bucket an object belongs in is decided by `planLegacyMediaKey`,
 * this repository's single split rule, imported below.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { planLegacyMediaKey } from '../worker/lib/mediaMigration';
import { isSafeMediaKey } from '../worker/lib/mediaStorage';

function required(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is not set`);
  return value;
}

const MODE = process.env.MODE === 'prune' ? 'prune' : 'copy';
const SOURCE = required('SOURCE_BUCKET');
const PUBLIC_BUCKET = required('PUBLIC_BUCKET');
const PRIVATE_BUCKET = required('PRIVATE_BUCKET');
const ENDPOINT = required('R2_ENDPOINT');
const MANIFEST = required('MANIFEST');

/**
 * One `aws s3api` call. Arguments are passed as an array — nothing here
 * is ever assembled into a shell string, so a key containing a quote or
 * a space cannot become a command.
 */
function aws(args: string[], expectJson = true): any {
  const [operation, ...rest] = args;
  const out = execFileSync(
    'aws',
    ['s3api', operation, '--endpoint-url', ENDPOINT, '--output', 'json', ...rest],
    { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 }
  );
  if (!expectJson) return null;
  const text = out.trim();
  return text ? JSON.parse(text) : null;
}

/** An Error's name and message, bounded, for a log line. */
function describeError(error: unknown): string {
  if (error instanceof Error) return (error.name + ': ' + error.message).slice(0, 300);
  return String(error).slice(0, 300);
}

function awsOrNull(args: string[]): any {
  try {
    return aws(args);
  } catch {
    // head-object on an absent key exits non-zero. That is an answer,
    // not a failure, and it is the answer this script asks for most.
    return null;
  }
}

interface SourceObject { key: string; size: number; etag: string }

/**
 * Every object in the bucket, paged to the very end. `--no-paginate`
 * turns OFF the CLI's own merging so the cursor is explicit and this
 * loop is the only thing deciding when the listing is complete — a
 * silently truncated listing is a silently incomplete migration.
 */
function listAll(bucket: string): SourceObject[] {
  const found: SourceObject[] = [];
  let token: string | null = null;
  do {
    const args = ['list-objects-v2', '--bucket', bucket, '--no-paginate', '--max-keys', '1000'];
    if (token) args.push('--continuation-token', token);
    const page = aws(args) ?? {};
    for (const item of page.Contents ?? []) {
      found.push({ key: String(item.Key), size: Number(item.Size), etag: String(item.ETag ?? '') });
    }
    token = page.IsTruncated ? String(page.NextContinuationToken) : null;
  } while (token);
  return found;
}

const scratch = mkdtempSync(join(tmpdir(), 'r2move-'));
function sha256(bucket: string, key: string, tag: string): string {
  const file = join(scratch, tag + '-' + createHash('sha1').update(key).digest('hex'));
  aws(['get-object', '--bucket', bucket, '--key', key, file]);
  return createHash('sha256').update(readFileSync(file)).digest('hex');
}

/** An ETag is the content MD5 only when the object is single-part. */
function simpleEtag(etag: string): string | null {
  const clean = etag.replace(/"/g, '');
  return clean && !clean.includes('-') ? clean : null;
}

interface Proof { ok: boolean; method: string; detail: string }

/**
 * A copy is "done" only when the destination is PROVEN to hold the same
 * bytes. Size always; ETag when both sides are single-part, because then
 * it is the MD5 of the content. When either side is multipart the ETags
 * are not comparable at all, so both objects are downloaded and SHA-256
 * compared — slower, and the only honest answer.
 */
function verify(destBucket: string, source: SourceObject): Proof {
  const head = awsOrNull(['head-object', '--bucket', destBucket, '--key', source.key]);
  if (!head) return { ok: false, method: 'missing', detail: 'destination has no such object' };
  if (Number(head.ContentLength) !== source.size) {
    return { ok: false, method: 'size', detail: 'dest ' + head.ContentLength + ' B vs source ' + source.size + ' B' };
  }
  const a = simpleEtag(source.etag);
  const b = simpleEtag(String(head.ETag ?? ''));
  if (a && b) {
    return a === b
      ? { ok: true, method: 'etag', detail: a }
      : { ok: false, method: 'etag', detail: a + ' != ' + b };
  }
  const sa = sha256(SOURCE, source.key, 'src');
  const sb = sha256(destBucket, source.key, 'dst');
  return sa === sb
    ? { ok: true, method: 'sha256', detail: sa }
    : { ok: false, method: 'sha256', detail: sa + ' != ' + sb };
}

interface Row {
  key: string;
  visibility: string;
  /** The media DOMAIN the key's prefix resolves to — products, chat,
   *  receipts, reviews… The report is unreadable without it. */
  domain: string;
  destination: string;
  /** The key WRITTEN at the destination. `buildMediaKey` does not
   *  encode visibility into a path, so a copy keeps its key and this
   *  equals `key` — but the prune gate compares it instead of
   *  assuming it, because "the key does not change" is precisely the
   *  assumption that would delete the wrong source if it ever broke. */
  destinationKey: string;
  bytes: number;
  /** The verdict itself. `outcome` is a label for humans; reading the
   *  verdict back out of that label would be a second rule to keep
   *  in sync with the first, so the row carries it directly. */
  verified: boolean;
  outcome: string;
  method: string;
  detail: string;
}

const rows: Row[] = [];
const blocked: Row[] = [];

/**
 * A THROW MUST NOT TAKE THE RECORD WITH IT.
 *
 * The prune loop deletes irreversibly, one object at a time. Without
 * this, an exception on object 10 — a throttled delete, a 503 on the
 * get-object inside a SHA-256 comparison — would exit node before the
 * manifest was written and before anything was printed. The step that
 * uploads `media-prune-manifest` is `if: always()`, so it would have
 * uploaded the file still sitting on disk: job 1's COPY manifest,
 * saying mode "copy", verified_all true, nothing deleted. The only
 * forensic record of a half-finished destruction would have been a
 * document asserting that nothing happened.
 *
 * So the work is caught, the report below always runs on whatever was
 * accumulated, and the failure is re-raised at the very end.
 */
let fatal: string | null = null;

try {
if (MODE === 'copy') {
  const objects = listAll(SOURCE);
  const total = objects.reduce((n, o) => n + o.size, 0);
  console.log(SOURCE + ': ' + objects.length + ' object(s), ' + total + ' B');
  for (const object of objects) {
    // An unsafe key is one the Worker's own `isSafeMediaKey` refuses to
    // serve from ANY bucket. Copying it would create a second
    // unreachable copy and let the run call that progress.
    if (!isSafeMediaKey(object.key)) {
      blocked.push({
        key: object.key, visibility: '-', domain: '-', destination: '-', destinationKey: '-',
        bytes: object.size, verified: false, outcome: 'BLOCKED', method: 'unsafe-key',
        detail: 'the Worker will not serve this key from any bucket; rename or move it by hand',
      });
      continue;
    }
    // THE SPLIT RULE. Imported, not reimplemented. `referenced` is true
    // because THIS job copies everything: whether an object is still
    // referenced decides whether it may eventually be deleted, not
    // where it lives, and nothing is deleted here.
    const plan = planLegacyMediaKey(object.key, true);
    const destination = plan.visibility === 'public' ? PUBLIC_BUCKET : PRIVATE_BUCKET;

    // Re-runnable: an object already in place is verified, not re-copied.
    const existing = awsOrNull(['head-object', '--bucket', destination, '--key', object.key]);
    let action = 'already-present';
    if (!existing || Number(existing.ContentLength) !== object.size) {
      // Server-side copy: the bytes never traverse this runner.
      const encoded = object.key.split('/').map(encodeURIComponent).join('/');
      aws(['copy-object', '--bucket', destination, '--key', object.key,
           '--copy-source', SOURCE + '/' + encoded, '--metadata-directive', 'COPY']);
      action = 'copied';
    }
    const proof = verify(destination, object);
    rows.push({
      key: object.key, visibility: plan.visibility, domain: plan.domain, destination,
      destinationKey: object.key, bytes: object.size,
      verified: proof.ok, outcome: proof.ok ? 'VERIFIED (' + action + ')' : 'FAILED',
      method: proof.method, detail: proof.detail,
    });
    console.log((proof.ok ? 'ok   ' : 'FAIL ') + plan.visibility.padEnd(7) + ' ' +
      destination + '  ' + object.key + '  [' + action + '/' + proof.method + ']');
  }
} else {
  // PRUNE. The manifest proves job 1 verified these keys in this run.
  // This re-proves it NOW, object by object, and deletes each source
  // only after that object's own destination has just answered for it.
  const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8'));

  // WHOLE-MANIFEST GATES. One bad row is not a reason to delete the
  // other seventeen, so these refuse the entire run.
  const manifestFailed = (manifest.rows as Row[]).filter((r) => r.outcome === 'FAILED').length;
  const manifestBlocked = (manifest.blocked ?? []).length;
  console.log('manifest BLOCKED: ' + manifestBlocked + '   manifest FAILED: ' + manifestFailed);
  if (!manifest.verified_all || manifestBlocked > 0 || manifestFailed > 0) {
    throw new Error('the copy manifest is not a clean pass — refusing to delete anything');
  }
  // The delete targets SOURCE by name. If SOURCE were ever also a
  // destination, this loop would delete the copies it just proved.
  if (SOURCE === PUBLIC_BUCKET || SOURCE === PRIVATE_BUCKET) {
    throw new Error('the source bucket is also a destination — refusing to delete anything');
  }

  const sources = new Map<string, SourceObject>(
    listAll(SOURCE).map((o): [string, SourceObject] => [o.key, o])
  );

  /**
   * THE PER-OBJECT GATE, one named check at a time.
   *
   * Everything below is checked BEFORE the delete for THIS object,
   * and every check prints whether it held — so a reader can see the
   * reason each source was allowed to go, rather than trusting that
   * a loop somewhere did the right thing. Any single failure keeps
   * that object's source and moves on; it never widens.
   */
  function pruneGate(row: Row, source: SourceObject): string | null {
    const checks: Array<[string, boolean, string]> = [
      ['manifest row verified=true', row.verified === true, String(row.verified)],
      ['source key matches the manifest', row.key === source.key, row.key],
      ['destination is an authorised bucket',
        row.destination === PUBLIC_BUCKET || row.destination === PRIVATE_BUCKET, row.destination],
      ['destination is not the source bucket', row.destination !== SOURCE, row.destination],
      ['destination key equals the manifest destination key',
        row.destinationKey === row.key, String(row.destinationKey)],
    ];
    for (const [name, held, value] of checks) {
      console.log('    ' + (held ? 'ok  ' : 'FAIL') + '  ' + name + ' : ' + value);
      if (!held) return name;
    }
    return null;
  }

  for (const row of manifest.rows as Row[]) {
    console.log('---- ' + row.key);
    const source = sources.get(row.key);
    if (!source) {
      // Already pruned by an earlier run. Re-running is a no-op, not an error.
      console.log('    skip  not in the legacy bucket — an earlier run already pruned it');
      rows.push({ ...row, verified: true, outcome: 'ALREADY-GONE', method: 're-list', detail: 'not in the legacy bucket' });
      continue;
    }
    const refused = pruneGate(row, source);
    if (refused) {
      console.log('    ::error::KEPT — ' + refused);
      blocked.push({ ...row, verified: false, outcome: 'KEPT', method: 'gate', detail: refused });
      continue;
    }
    // Existence + size + ETag (or SHA-256 when either side is
    // multipart), taken against the destination RIGHT NOW.
    const proof = verify(row.destination, source);
    console.log('    ' + (proof.ok ? 'ok  ' : 'FAIL') + '  destination re-verified by ' + proof.method + ' : ' + proof.detail);
    if (!proof.ok) {
      blocked.push({ ...row, verified: false, outcome: 'KEPT', method: proof.method, detail: proof.detail });
      continue;
    }
    // ONE object, from the LEGACY bucket, by its exact key.
    aws(['delete-object', '--bucket', SOURCE, '--key', row.key], false);
    rows.push({ ...row, verified: true, outcome: 'SOURCE-DELETED', method: proof.method, detail: proof.detail });
    console.log('    pruned ' + row.key + ' from ' + SOURCE + ' (copy in ' + row.destination + ' proved by ' + proof.method + ')');
  }

  // AFTERWARDS: the legacy bucket must hold none of the manifest's
  // keys, and every destination object must still be there. Asking
  // again, from scratch, is the only answer worth reporting.
  const stillInSource = listAll(SOURCE).filter((o) => (manifest.rows as Row[]).some((r) => r.key === o.key));
  console.log('');
  console.log('LEGACY SOURCE COPIES REMAINING FROM THE MANIFEST: ' + stillInSource.length);
  for (const leftover of stillInSource) console.log('  still present: ' + leftover.key + ' (' + leftover.size + ' B)');
  let missingPublic = 0;
  let missingPrivate = 0;
  for (const row of manifest.rows as Row[]) {
    const head = awsOrNull(['head-object', '--bucket', row.destination, '--key', row.destinationKey]);
    if (head && Number(head.ContentLength) === row.bytes) continue;
    if (row.visibility === 'public') missingPublic++;
    else missingPrivate++;
    console.log('  ::error::DESTINATION GONE OR CHANGED: ' + row.destination + '/' + row.destinationKey);
  }
  console.log('PUBLIC DESTINATION OBJECTS MISSING : ' + missingPublic);
  console.log('PRIVATE DESTINATION OBJECTS MISSING: ' + missingPrivate);
  if (missingPublic > 0 || missingPrivate > 0) {
    throw new Error('a destination object is missing after the prune — the copies are what survive, and one did not');
  }
}
} catch (error) {
  fatal = describeError(error);
  console.error('');
  console.error('::error::RUN STOPPED: ' + fatal);
  console.error('The report below covers everything that happened BEFORE this point.');
}

const failures = rows.filter((r) => r.outcome === 'FAILED').length;
// COUNTED, not assumed. `LEGACY DELETED` used to be the literal 0 —
// true of every copy run and of no prune run, including the one that
// deletes all eighteen exactly as intended.
const deleted = rows.filter((r) => r.outcome === 'SOURCE-DELETED').length;
const verifiedAll = !fatal && failures === 0 && blocked.length === 0;
writeFileSync(MANIFEST, JSON.stringify({
  mode: MODE, source: SOURCE, public_bucket: PUBLIC_BUCKET, private_bucket: PRIVATE_BUCKET,
  generated_at: new Date().toISOString(), verified_all: verifiedAll, rows, blocked,
}, null, 2));

const summaryPath = process.env.GITHUB_STEP_SUMMARY;
if (summaryPath) {
  const lines = [
    '## ' + (MODE === 'copy' ? 'Copy + verify' : 'Prune verified sources'), '',
    'Source `' + SOURCE + '` -> `' + PUBLIC_BUCKET + '` / `' + PRIVATE_BUCKET + '`', '',
    '| key | visibility | destination | bytes | outcome | proof |',
    '|---|---|---|---|---|---|',
  ];
  for (const r of [...rows, ...blocked]) {
    lines.push('| `' + r.key + '` | ' + r.visibility + ' | ' + r.destination + ' | ' +
      r.bytes + ' | ' + r.outcome + ' | ' + r.method + ': ' + r.detail + ' |');
  }
  // A prune that deleted seventeen objects and kept one has NOT
  // "refused deletion", and saying so to someone holding no other
  // copy is the worst sentence this file could print.
  lines.push('', verifiedAll
    ? (MODE === 'copy'
        ? '**' + rows.length + ' object(s) byte-verified at the destination. Nothing was deleted by this job.**'
        : '**' + deleted + ' legacy source object(s) deleted after re-verification. Every destination copy re-checked and present.**')
    : (MODE === 'copy'
        ? '**' + failures + ' failed, ' + blocked.length + ' blocked. Nothing was deleted; deletion is refused.**'
        : '**RUN DID NOT COMPLETE CLEANLY. ' + deleted + ' source object(s) WERE ALREADY DELETED, ' +
          blocked.length + ' kept. Read the per-object list below before assuming anything.**'));
  writeFileSync(summaryPath, lines.join('\n') + '\n', { flag: 'a' });
}

// ------------------------------------------------- THE FULL REPORT
//
// Printed to the CONSOLE, every run, pass or fail. The step summary
// is a web page; a migration's per-object result has to be readable
// where the run is read, or "18 of 22" is the only fact that travels.
const all = [...rows, ...blocked];
console.log('\n===== PER-OBJECT RESULT =====');
for (const r of all) {
  console.log(
    [
      // In prune the outcome IS the news — SOURCE-DELETED must never
      // be flattened into a cheerful "OK".
      MODE === 'prune' ? r.outcome : r.verified ? 'OK     ' : r.outcome === 'BLOCKED' ? 'BLOCKED' : r.outcome,
      'src=' + r.key,
      'domain=' + r.domain,
      'class=' + r.visibility,
      'dest=' + r.destination,
      'destKey=' + (r.destination === '-' ? '-' : r.key),
      'bytes=' + r.bytes,
      'proof=' + r.method + (r.detail ? ':' + r.detail : ''),
    ].join('  ')
  );
}
const pub = rows.filter((r) => r.visibility === 'public' && r.verified);
const priv = rows.filter((r) => r.visibility === 'private' && r.verified);
console.log('\n===== SUMMARY =====');
console.log('TOTAL LEGACY OBJECTS: ' + all.length);
console.log('PUBLIC VERIFIED: ' + pub.length);
console.log('PRIVATE VERIFIED: ' + priv.length);
console.log('BLOCKED: ' + blocked.length);
console.log('FAILED: ' + failures);
console.log('LEGACY DELETED: ' + deleted);
console.log('\nPUBLIC OBJECT LIST:');
for (const r of pub) console.log('  ' + r.key + '  (' + r.bytes + ' B, ' + r.method + ')');
console.log('PRIVATE OBJECT LIST:');
for (const r of priv) console.log('  ' + r.key + '  (' + r.bytes + ' B, ' + r.method + ')');
console.log('BLOCKED OBJECT LIST + EXACT REASON:');
for (const r of blocked) console.log('  ' + r.key + '  -> ' + r.method + ': ' + r.detail);
if (blocked.length === 0) console.log('  (none)');

if (!verifiedAll) {
  console.error('\n' + failures + ' object(s) failed verification, ' + blocked.length + ' blocked.');
  if (MODE === 'prune' && deleted > 0) {
    console.error(deleted + ' SOURCE OBJECT(S) WERE DELETED BEFORE THIS RUN STOPPED. They are listed above as SOURCE-DELETED.');
  }
  // NAME THEM, IN THE LOG. These rows lived only in the step summary,
  // so a run that refused to delete could not tell anyone WHICH four
  // objects to fix without opening a web page and scrolling a table.
  // A refusal you cannot act on is only half a safety feature.
  for (const r of rows.filter((x) => x.outcome === 'FAILED')) {
    console.error('  FAILED  ' + r.key + '  (' + r.method + ': ' + r.detail + ')');
  }
  for (const r of blocked) {
    console.error('  BLOCKED ' + r.key + '  (' + r.method + ': ' + r.detail + ')');
  }
  if (MODE === 'copy') {
    console.error('Nothing has been deleted. Fix or hand-move those objects, then re-run —');
    console.error('objects already verified are skipped, so a re-run is cheap and safe.');
  } else {
    console.error('A re-run will skip what is already gone and retry only what was kept.');
  }
  if (fatal) console.error('The run stopped early: ' + fatal);
  process.exit(1);
}
