/**
 * Remove four zero-byte folder markers, and nothing else, ever.
 * Generated by .github/workflows/media-folder-markers-remove.yml.
 */
import { execFileSync } from 'node:child_process';
import { isSafeMediaKey } from '../worker/lib/mediaStorage';

function required(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is not set`);
  return value;
}

const BUCKET = required('SOURCE_BUCKET');
const ENDPOINT = required('R2_ENDPOINT');
const DRY_RUN = process.env.DRY_RUN === 'true';

/**
 * THE ONLY KEYS THIS SCRIPT MAY DELETE.
 *
 * A literal, not an input. An operator can choose the bucket and
 * whether to run at all; they cannot choose the keys, so no typo and
 * no crafted input can widen this to a prefix. Every candidate is
 * compared against this array with ===.
 */
const MARKERS = [
  'UiUx/',
  'UiUx/Animation/',
  'UiUx/Icons/',
  'UiUx/Logo/',
] as const;

function aws(args: string[], expectJson = true): any {
  const out = execFileSync(
    'aws',
    ['s3api', args[0], '--endpoint-url', ENDPOINT, '--output', 'json', ...args.slice(1)],
    { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }
  );
  if (!expectJson) return null;
  const text = out.trim();
  return text ? JSON.parse(text) : null;
}

function awsOrNull(args: string[]): any {
  try { return aws(args); } catch { return null; }
}

interface Child { key: string; size: number }

/** Every object whose key starts with this prefix, to the last page. */
function listUnder(prefix: string): Child[] {
  const found: Child[] = [];
  let token: string | null = null;
  do {
    const args = ['list-objects-v2', '--bucket', BUCKET, '--prefix', prefix,
                  '--no-paginate', '--max-keys', '1000'];
    if (token) args.push('--continuation-token', token);
    const page = aws(args) ?? {};
    for (const item of page.Contents ?? []) {
      found.push({ key: String(item.Key), size: Number(item.Size) });
    }
    token = page.IsTruncated ? String(page.NextContinuationToken) : null;
  } while (token);
  return found;
}

/**
 * Is this key a folder marker, by the repository's own rules rather
 * than by how it looks to a human? All three must hold.
 */
function markerShape(key: string): { ok: boolean; reasons: string[] } {
  const reasons: string[] = [];
  const endsInSlash = key.endsWith('/');
  const hasEmptySegment = key.split('/').includes('');
  const refused = !isSafeMediaKey(key);
  reasons.push(`ends with "/": ${endsInSlash}`);
  reasons.push(`has an empty path segment: ${hasEmptySegment}`);
  reasons.push(`isSafeMediaKey refuses it: ${refused}`);
  return { ok: endsInSlash && hasEmptySegment && refused, reasons };
}

let deleted = 0;
let skipped = 0;
const failures: string[] = [];

console.log(`bucket: ${BUCKET}`);
console.log(`mode:   ${DRY_RUN ? 'DRY RUN — proves everything, deletes nothing' : 'DELETE'}`);
console.log('');

for (const marker of MARKERS) {
  console.log(`================ ${JSON.stringify(marker)}`);

  // PROOF 1 — the key is one of the four literals, compared exactly.
  const listed = MARKERS.filter((m) => m === marker);
  if (listed.length !== 1) {
    failures.push(`${marker}: not in the literal allow-list`);
    continue;
  }
  console.log(`  [1] exact key match      : in the allow-list, and ${JSON.stringify(marker)} === itself`);

  // PROOF 2 — it exists and holds zero bytes.
  const head = awsOrNull(['head-object', '--bucket', BUCKET, '--key', marker]);
  if (!head) {
    // Already gone. Re-running must be a no-op, not an error.
    console.log('  [2] head-object          : absent — already removed by an earlier run, skipping');
    skipped++;
    continue;
  }
  const size = Number(head.ContentLength);
  console.log(`  [2] Content-Length       : ${size}`);
  if (size !== 0) {
    failures.push(`${marker}: ContentLength is ${size}, not 0 — this is not a marker, refusing`);
    console.log('  ::error:: NOT ZERO BYTES — refusing to delete this key');
    continue;
  }

  // PROOF 3 — it is shaped like a marker by this repository's rules.
  const shape = markerShape(marker);
  for (const reason of shape.reasons) console.log(`  [3] ${reason}`);
  if (!shape.ok) {
    failures.push(`${marker}: does not have folder-marker shape — refusing`);
    console.log('  ::error:: NOT A FOLDER MARKER — refusing to delete this key');
    continue;
  }

  // PROOF 4 — write down everything under this prefix FIRST. These are
  // the objects the delete must not touch, and naming them before the
  // delete is what makes the check afterwards mean anything.
  const before = listUnder(marker).filter((c) => c.key !== marker);
  console.log(`  [4] objects UNDER this prefix that must survive: ${before.length}`);
  for (const child of before) console.log(`        keep: ${child.key}  (${child.size} B)`);

  if (DRY_RUN) {
    console.log('  [5] DRY RUN — no delete-object call was made');
    skipped++;
    continue;
  }

  // THE DELETE. One object, named in full, by its exact key.
  // `delete-object` is the singular call: it takes exactly one --key
  // and has no prefix form at all. It cannot reach a child even in
  // principle, because in S3 a prefix is not a container.
  aws(['delete-object', '--bucket', BUCKET, '--key', marker], false);
  console.log(`  [-] DeleteObject         : single object, --key ${JSON.stringify(marker)}`);

  // PROOF 5 — the marker is gone and every child is still there.
  const gone = awsOrNull(['head-object', '--bucket', BUCKET, '--key', marker]);
  if (gone) {
    failures.push(`${marker}: still present after the delete`);
    continue;
  }
  const after = new Map(listUnder(marker).map((c): [string, number] => [c.key, c.size]));
  const lost = before.filter((c) => after.get(c.key) !== c.size);
  if (lost.length > 0) {
    // Nothing in the S3 API makes this reachable, which is exactly
    // why it is worth asserting: if it ever fires, the assumption
    // this whole workflow rests on was wrong.
    for (const child of lost) {
      failures.push(`${marker}: COLLATERAL DAMAGE — ${child.key} changed or disappeared`);
      console.log(`  ::error:: ${child.key} did not survive the delete`);
    }
    continue;
  }
  console.log(`  [5] marker gone, ${before.length} child object(s) intact`);
  deleted++;
}

console.log('');
console.log('===== SUMMARY =====');
console.log(`MARKERS DELETED: ${deleted}`);
console.log(`MARKERS SKIPPED: ${skipped}`);
console.log(`REFUSED/FAILED : ${failures.length}`);
console.log('DATA OBJECTS DELETED: 0');

// Whatever happened above, say what the bucket holds now.
const remaining = listUnder('UiUx/');
console.log('');
console.log('EVERYTHING STILL UNDER UiUx/ :');
for (const item of remaining) console.log(`  ${item.key}  (${item.size} B)`);
if (remaining.length === 0) console.log('  (nothing)');

if (failures.length > 0) {
  console.error('');
  for (const failure of failures) console.error(`  REFUSED  ${failure}`);
  process.exit(1);
}
