/**
 * MakerWorld preflight (slice S7 — mandate §9 step 1).
 *
 * Pure, dependency-free project checks that run BEFORE the 3MF project file is
 * prepared: build-volume bounds, plates, materials/extruders, paint and
 * profile limitations. Every limitation reported here comes from the gap table
 * (docs/STUDIO_GAPS.md) or from reading the installed three-slicer 0.2.2 build
 * — nothing is invented and nothing marked partial/absent there is presented
 * as supported.
 *
 * This module intentionally has ZERO imports so Node tests can load it in
 * isolation (tests/slice-fixtures.test.mjs transpiles it the same way
 * tests/arrange.test.mjs loads plate-packing.ts).
 *
 * The preflight is advisory where the engine has the authoritative check
 * (over-bed detection at slice time stays the engine's job); it is blocking
 * only for conditions that make preparing a MakerWorld project pointless:
 * no objects, or an object that cannot fit the selected printer's volume in
 * any in-plane orientation.
 */

// ---------------------------------------------------------------------------
// Declared engine limits
// ---------------------------------------------------------------------------

/**
 * The installed engine's real plate limit. Kept as a local constant so this
 * module stays import-free; tests assert it equals plate-packing.PLATE_CAP and
 * the "max 9" advertised by the installed three-slicer build.
 */
export const ENGINE_PLATE_CAP = 9;

// ---------------------------------------------------------------------------
// Input
// ---------------------------------------------------------------------------

export interface PreflightObjectInput {
  id: number;
  name: string;
  /** 1-based extruder/filament assignment, matching the engine's object list. */
  extruder: number;
  visible: boolean;
  /**
   * World-space bed footprint and height in millimetres (after transforms),
   * e.g. derived from the S4 adapter's sceneSnapshot + snapshotFootprint.
   * Omitted dimensions make the object "unmeasured": it is skipped by the
   * bounds check and counted in `unmeasuredObjectCount` instead of being
   * silently assumed to fit.
   */
  widthMm?: number;
  depthMm?: number;
  heightMm?: number;
}

export interface PreflightProfileInput {
  id: string;
  model: string;
  shortName: string;
  nozzle: number;
  bedWidthMm: number;
  bedDepthMm: number;
  bedHeightMm: number;
}

export interface PreflightInput {
  objects: readonly PreflightObjectInput[];
  plateCount: number;
  profile: PreflightProfileInput;
  /**
   * From profile-loader (S4): true only when machine, process AND filament
   * presets all loaded from the engine. False means generic fallback settings
   * are in play — the prepared file then carries settings that are NOT the
   * advertised verified profile, and the summary must say so.
   */
  profileVerified: boolean;
  /** Requested preset names that were missing from the engine build, if any. */
  missingPresets?: readonly string[];
  /** Filament/extruder display colors currently configured (1-based order). */
  extruderColors?: readonly string[];
  /**
   * True when the project is known to carry support-paint data; undefined when
   * the shell cannot tell. Used only for the multi-plate paint limitation
   * warning (gap table §3: multi-plate projects persist imported paint only).
   */
  supportPaintPresent?: boolean;
}

// ---------------------------------------------------------------------------
// Findings
// ---------------------------------------------------------------------------

export type PreflightSeverity = "blocker" | "warning" | "info";

export type PreflightCode =
  /** Nothing to prepare. */
  | "no-objects"
  /** An object cannot fit the printer volume in any in-plane orientation. */
  | "object-exceeds-bed"
  /** Some objects had no measurable dimensions; bounds were not checked for them. */
  | "objects-unmeasured"
  /** Hidden objects are still written into the saved 3MF project. */
  | "objects-hidden"
  /** Engine presets missing — generic fallback settings are embedded, not the verified profile. */
  | "preset-fallback"
  /**
   * More than one extruder is assigned. The assignment is written into the
   * 3MF (Metadata/model_settings.config) and feeds the engine's slice request,
   * but its presence in final sliced G-code is not verified in this build —
   * the remaining MMU limits stay declared (gap table §3).
   */
  | "multi-extruder-unverified"
  /** Bambu-style facet color painting is not available in this engine build (gap table §3). */
  | "surface-paint-unavailable"
  /** Multi-plate projects persist imported support paint only (gap table §3). */
  | "paint-multi-plate-limit"
  /** The engine's 3MF save embeds no thumbnail; MakerWorld will ask for images at upload. */
  | "thumbnail-not-embedded"
  /**
   * MakerWorld's print-profile check rejects files not generated by Bambu
   * Studio (gap table §8) — the prepared file uploads as a model/project, not
   * as a print profile.
   */
  | "print-profile-not-accepted"
  /** The project is at the engine's declared plate limit. */
  | "plate-cap";

export interface PreflightFinding {
  code: PreflightCode;
  severity: PreflightSeverity;
  /** Objects the finding refers to, ascending; omitted for project-level findings. */
  objectIds?: number[];
  /** Small, serializable detail payload for message templating. */
  data?: Record<string, string | number>;
}

// ---------------------------------------------------------------------------
// Transfers summary (mandate §9 step 3: what transfers, what may not)
// ---------------------------------------------------------------------------

export type TransferKey =
  | "geometry"
  | "plates"
  | "transforms"
  | "extruder-assignment"
  | "support-paint"
  | "global-settings"
  | "surface-colors"
  | "thumbnail"
  | "print-profile"
  | "slice-info";

export type TransferStatus = "transfers" | "partial" | "not-transferred";

export interface TransferItem {
  key: TransferKey;
  status: TransferStatus;
}

export interface PreflightReport {
  /** True when no blocker was found (warnings and infos do not block). */
  ok: boolean;
  findings: PreflightFinding[];
  /** Honest "what will transfer / what may not be supported" summary. */
  transfers: TransferItem[];
  /** Distinct extruders used by visible objects, ascending. */
  usedExtruders: number[];
  checkedObjectCount: number;
  unmeasuredObjectCount: number;
  hiddenObjectCount: number;
  plateCount: number;
}

// ---------------------------------------------------------------------------
// Checks
// ---------------------------------------------------------------------------

const SEVERITY_RANK: Record<PreflightSeverity, number> = {
  blocker: 0,
  warning: 1,
  info: 2,
};

function isFiniteDim(value: number | undefined): value is number {
  return typeof value === "number" && Number.isFinite(value) && value > 0;
}

/**
 * True when a footprint of `width` × `depth` fits a `bedWidth` × `bedDepth`
 * bed in at least one in-plane orientation (the user may rotate 90° on the
 * bed without changing the print). Height has no alternative orientation.
 */
export function footprintFitsBed(
  width: number,
  depth: number,
  bedWidth: number,
  bedDepth: number,
): boolean {
  return (width <= bedWidth && depth <= bedDepth) || (width <= bedDepth && depth <= bedWidth);
}

/**
 * Runs the full preflight. Deterministic: identical input yields an identical
 * report (findings sorted by severity, then code, then first object id).
 */
export function runPreflight(input: PreflightInput): PreflightReport {
  const findings: PreflightFinding[] = [];
  const { profile } = input;

  const oversizedIds: number[] = [];
  const unmeasuredIds: number[] = [];
  const hiddenIds: number[] = [];
  const usedExtruderSet = new Set<number>();

  for (const object of input.objects) {
    if (object.visible === false) hiddenIds.push(object.id);
    else usedExtruderSet.add(Math.max(1, Math.floor(object.extruder) || 1));

    const measured = isFiniteDim(object.widthMm) && isFiniteDim(object.depthMm) && isFiniteDim(object.heightMm);
    if (!measured) {
      unmeasuredIds.push(object.id);
      continue;
    }
    const fitsFootprint = footprintFitsBed(
      object.widthMm as number,
      object.depthMm as number,
      profile.bedWidthMm,
      profile.bedDepthMm,
    );
    const fitsHeight = (object.heightMm as number) <= profile.bedHeightMm;
    if (!fitsFootprint || !fitsHeight) oversizedIds.push(object.id);
  }

  if (input.objects.length === 0) {
    findings.push({ code: "no-objects", severity: "blocker" });
  }

  if (oversizedIds.length) {
    findings.push({
      code: "object-exceeds-bed",
      severity: "blocker",
      objectIds: [...oversizedIds].sort((a, b) => a - b),
      data: {
        printer: profile.model,
        bed: `${profile.bedWidthMm}×${profile.bedDepthMm}×${profile.bedHeightMm}`,
      },
    });
  }

  if (unmeasuredIds.length) {
    findings.push({
      code: "objects-unmeasured",
      severity: "warning",
      objectIds: [...unmeasuredIds].sort((a, b) => a - b),
    });
  }

  if (hiddenIds.length) {
    findings.push({
      code: "objects-hidden",
      severity: "warning",
      objectIds: [...hiddenIds].sort((a, b) => a - b),
    });
  }

  if (!input.profileVerified) {
    findings.push({
      code: "preset-fallback",
      severity: "warning",
      data: { missing: (input.missingPresets ?? []).join(", ") },
    });
  }

  const usedExtruders = [...usedExtruderSet].sort((a, b) => a - b);
  if (usedExtruders.length > 1) {
    findings.push({
      code: "multi-extruder-unverified",
      severity: "info",
      data: { extruders: usedExtruders.join(", ") },
    });
  }

  // Declared engine/format limitations — always surfaced so the step-3 summary
  // never over-promises (gap table §3 and §8).
  findings.push({ code: "surface-paint-unavailable", severity: "info" });
  findings.push({ code: "thumbnail-not-embedded", severity: "info" });
  findings.push({ code: "print-profile-not-accepted", severity: "info" });

  if (input.supportPaintPresent && input.plateCount > 1) {
    findings.push({ code: "paint-multi-plate-limit", severity: "warning" });
  }

  if (input.plateCount >= ENGINE_PLATE_CAP) {
    findings.push({ code: "plate-cap", severity: "info", data: { cap: ENGINE_PLATE_CAP } });
  }

  findings.sort((a, b) => (
    SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity]
    || a.code.localeCompare(b.code)
    || (a.objectIds?.[0] ?? 0) - (b.objectIds?.[0] ?? 0)
  ));

  const ok = !findings.some((finding) => finding.severity === "blocker");

  return {
    ok,
    findings,
    transfers: buildTransferSummary({
      profileVerified: input.profileVerified,
      multiExtruder: usedExtruders.length > 1,
      supportPaintPresent: input.supportPaintPresent,
      plateCount: input.plateCount,
    }),
    usedExtruders,
    checkedObjectCount: input.objects.length - unmeasuredIds.length,
    unmeasuredObjectCount: unmeasuredIds.length,
    hiddenObjectCount: hiddenIds.length,
    plateCount: input.plateCount,
  };
}

interface TransferContext {
  profileVerified: boolean;
  multiExtruder: boolean;
  supportPaintPresent?: boolean;
  plateCount: number;
}

/**
 * The honest transfer matrix for the engine's saved 3MF, grounded in the
 * installed three-slicer 0.2.2 save writer (read statically: geometry +
 * plates + per-object `extruder` metadata in Metadata/model_settings.config,
 * settings JSON in Metadata/project_settings.config; no thumbnail, no
 * slice_info.config) and in the gap table:
 *
 * - "transfers": written by the engine save path and reopenable.
 * - "partial": written, but with a declared limitation the UI must show.
 * - "not-transferred": not present in the file or not accepted by MakerWorld.
 */
export function buildTransferSummary(context: TransferContext): TransferItem[] {
  return [
    { key: "geometry", status: "transfers" },
    { key: "plates", status: "transfers" },
    { key: "transforms", status: "transfers" },
    {
      key: "global-settings",
      // Fallback settings are still written, but they are not the advertised
      // verified profile — partial, never silently "transfers".
      status: context.profileVerified ? "transfers" : "partial",
    },
    {
      key: "extruder-assignment",
      // Written into the 3MF and fed to the slice request; presence in final
      // G-code is unverified in this build (remaining MMU limit) — partial.
      status: "partial",
    },
    {
      key: "support-paint",
      // Persisted, with the documented multi-plate limitation.
      status: "partial",
    },
    { key: "surface-colors", status: "not-transferred" },
    { key: "thumbnail", status: "not-transferred" },
    { key: "print-profile", status: "not-transferred" },
    { key: "slice-info", status: "not-transferred" },
  ];
}
