/**
 * THE PROJECTS' WORDS — Arabic, English and Sorani, every key in all three.
 *
 * The owner's rule for the community ecosystem: «لا تترك Arabic placeholder في
 * ckb» — a new string is a real key with a real Sorani sentence, not the
 * Arabic standing in. Counted nouns follow src/components/community/hub/copy.ts.
 */
import { useLanguage } from '../../../LanguageContext';
import type { PostKind, PostState, PostVisibility } from './api';

const STRINGS = {
  ar: {
    projects: 'المشاريع',
    project: 'مشروع',
    newProject: 'مشروع جديد',
    shareWhatYouPrinted: 'شارك ما طبعته',
    editProject: 'تعديل المشروع',
    kinds: { project: 'مشروع', post: 'منشور', tutorial: 'شرح', timelapse: 'تايم لابس', before_after: 'قبل وبعد' } as Record<PostKind, string>,
    states: { draft: 'مسودة', published: 'منشور', archived: 'مؤرشف' } as Record<PostState, string>,
    visibility: { public: 'عام', unlisted: 'بالرابط فقط', private: 'خاص' } as Record<PostVisibility, string>,
    visibilityHint: { public: 'يظهر في المجتمع وصفحتك.', unlisted: 'يراه من يملك الرابط فقط.', private: 'أنت فقط.' } as Record<PostVisibility, string>,
    // the facts
    printer: 'الطابعة',
    material: 'الخامة',
    color: 'اللون',
    printTime: 'زمن الطباعة',
    size: 'الحجم',
    settings: 'إعدادات الطباعة',
    layerHeight: 'ارتفاع الطبقة',
    layer: 'الطبقة',
    infill: 'الملء',
    nozzle: 'الفوهة',
    supports: 'دعامات',
    withSupports: 'مع دعامات',
    noSupports: 'بدون دعامات',
    tags: 'وسوم',
    tagsHint: 'حتى 10 وسوم، افصل بينها بفاصلة.',
    // the doors
    fromWorkshop: 'من ورشة',
    buyThisPiece: 'اشترِ هذه القطعة',
    printOneLikeIt: 'اطلب طباعة مثلها',
    buyTheMaterial: 'اشترِ الخامة المستخدمة',
    seeThePrinter: 'اعرف الطابعة',
    // the composer
    pictures: 'الصور',
    title: 'العنوان',
    titlePh: 'مثال: تنين مفصلي بلونين',
    body: 'القصة',
    bodyPh: 'كيف طبعته؟ ما الذي نجح وما الذي أعدته؟ نصائح لمن يطبعه بعدك.',
    kind: 'النوع',
    printerPh: 'اسم الطابعة، أو اختر من الكتالوج',
    materialPh: 'PLA، PETG، راتنج…',
    colorPh: 'أسود، أبيض، متعدد…',
    minutes: 'دقيقة',
    hours: 'ساعة',
    mm: 'مم',
    linkToStore: 'اربطه بمتجرك',
    linkToStoreHint: 'يظهر متجرك على المشروع وبابٌ إلى المنتج الذي صار منه.',
    linkedProduct: 'المنتج في متجرك',
    noProduct: 'بدون منتج',
    fromCatalogue: 'من الكتالوج',
    typeName: 'اكتب الاسم',
    searchCatalogue: 'ابحث في الكتالوج',
    saveDraft: 'احفظ مسودة',
    publish: 'انشر',
    saveChanges: 'احفظ التعديلات',
    publishing: 'جارٍ النشر…',
    saving: 'جارٍ الحفظ…',
    published: 'نُشر مشروعك',
    saved: 'حُفظت المسودة',
    creatorPageOn: 'بنشر أول مشروع تُفتح صفحتك العامة /u/‏{username} — يمكنك إغلاقها من إعدادات الملف.',
    // banners
    draftBanner: 'مسودة — لا يراها أحد غيرك.',
    consentPending: 'بانتظار موافقة الزبون على عرض قطعته.',
    consentDeclined: 'رفض الزبون عرض قطعته. انشر بدون ربطه بطلبه، أو اتركه خاصًا.',
    hiddenBanner: 'أخفت Levonis هذا المشروع.',
    reason: 'السبب',
    archivedBanner: 'مؤرشف — لا يظهر في المجتمع.',
    // consent (the customer)
    askedTitle: 'ورشة تريد عرض قطعتك',
    askedBody: 'هذه القطعة طُبعت لك. هل توافق أن تظهر في معرض أعمال الورشة؟',
    allow: 'أوافق',
    decline: 'لا أوافق',
    youAllowed: 'وافقت على عرض قطعتك.',
    youDeclined: 'رفضت عرض قطعتك.',
    // actions
    edit: 'تعديل',
    archive: 'أرشفة',
    restore: 'إعادة',
    delete: 'حذف',
    share: 'مشاركة',
    linkCopied: 'نُسخ الرابط',
    deleteQ: 'حذف المشروع؟',
    deleteConsequence: 'تُحذف صوره ولا يمكن استرجاعه.',
    archiveQ: 'أرشفة المشروع؟',
    archiveConsequence: 'يختفي من المجتمع ويبقى لك؛ يمكنك إعادته متى شئت.',
    // lists
    noProjectsYet: 'لا مشاريع بعد',
    noProjectsHint: 'أول من يشارك ما طبعه يُفتتح به هذا القسم.',
    yourFirstProject: 'شارك أول مشروع لك',
    myProjects: 'مشاريعي',
    myProjectsEmpty: 'ما تطبعه يستحق أن يُرى.',
    trending: 'رائج هذا الأسبوع',
    latest: 'أحدث المشاريع',
    seeAll: 'الكل',
    likes: 'إعجاب',
    // creator
    creator: 'صانع',
    projectsCount: 'مشاريع',
    completedJobs: 'طلبات منجزة',
    memberSince: 'عضو منذ',
    about: 'نبذة',
    prints: 'يطبع بـ',
    materialsUsed: 'الخامات',
    website: 'الموقع',
    editProfile: 'تعديل الملف',
    verifiedMerchant: 'تاجر موثّق',
    theirStore: 'متجره',
    creatorNotFound: 'لا صفحة بهذا الاسم',
    creatorNotFoundHint: 'قد يكون الحساب خاصًا أو الاسم مكتوبًا خطأ.',
    // profile settings
    creatorPage: 'صفحتي العامة',
    creatorPageDesc: 'صفحة /u/‏{username} تعرض مشاريعك ونبذتك وروابطك لكل زائر.',
    creatorPageOff: 'مغلقة — لا يراها أحد.',
    printersYouUse: 'طابعاتك',
    printersHint: 'افصل بين الأسماء بفاصلة.',
    materialsYouUse: 'خاماتك',
    // the files (§9.4)
    files: 'الملفات',
    modelFile: 'ملف المجسم (اختياري)',
    modelFileHint: 'حتى 3 ملفات — STL أو 3MF أو OBJ أو PDF. الملفات الكبيرة تُرفع على أجزاء وتُستأنف إن انقطع الاتصال.',
    addFile: 'أضف ملفًا',
    fileName: 'اسم الملف',
    downloadable: 'قابل للتنزيل',
    downloadableHint: 'يستطيع أي عضو مسجّل تنزيل الملف الأصلي.',
    filesLimit: 'الحد 3 ملفات للمشروع الواحد.',
    fileKindRefused: 'اختر ملف مجسم (STL أو 3MF أو OBJ أو STEP) أو مستند PDF.',
    fileKinds: { model: 'مجسم', document: 'مستند' } as Record<'model' | 'document', string>,
    view3d: 'عرض ثلاثي الأبعاد',
    download: 'تنزيل',
    signInToDownload: 'سجّل الدخول لتنزيل هذا الملف.',
    notDownloadable: 'لم يُتح صاحب المشروع تنزيل هذا الملف.',
    noPreview: 'لا معاينة ثلاثية الأبعاد لهذا الملف.',
    removeFile: 'إزالة الملف',
    opening: 'جارٍ الفتح…',
    viewerFailed: 'تعذّر فتح المعاينة.',
    takePhoto: 'التقط صورة',
    uploadingFiles: 'ملفات قيد الرفع',
  },
  en: {
    projects: 'Projects',
    project: 'Project',
    newProject: 'New project',
    shareWhatYouPrinted: 'Share what you printed',
    editProject: 'Edit project',
    kinds: { project: 'Project', post: 'Post', tutorial: 'Tutorial', timelapse: 'Timelapse', before_after: 'Before & after' } as Record<PostKind, string>,
    states: { draft: 'Draft', published: 'Published', archived: 'Archived' } as Record<PostState, string>,
    visibility: { public: 'Public', unlisted: 'Link only', private: 'Private' } as Record<PostVisibility, string>,
    visibilityHint: { public: 'In the community and on your page.', unlisted: 'Only people with the link.', private: 'Only you.' } as Record<PostVisibility, string>,
    printer: 'Printer',
    material: 'Material',
    color: 'Colour',
    printTime: 'Print time',
    size: 'Size',
    settings: 'Print settings',
    layerHeight: 'Layer height',
    layer: 'Layer',
    infill: 'Infill',
    nozzle: 'Nozzle',
    supports: 'Supports',
    withSupports: 'With supports',
    noSupports: 'No supports',
    tags: 'Tags',
    tagsHint: 'Up to 10, separated by commas.',
    fromWorkshop: 'From the workshop',
    buyThisPiece: 'Buy this piece',
    printOneLikeIt: 'Get one printed',
    buyTheMaterial: 'Buy the material used',
    seeThePrinter: 'See the printer',
    pictures: 'Pictures',
    title: 'Title',
    titlePh: 'e.g. Two-colour articulated dragon',
    body: 'The story',
    bodyPh: 'How did you print it? What worked, what did you redo? Tips for whoever prints it next.',
    kind: 'Kind',
    printerPh: 'Printer name, or pick from the catalogue',
    materialPh: 'PLA, PETG, resin…',
    colorPh: 'Black, white, multicolour…',
    minutes: 'min',
    hours: 'h',
    mm: 'mm',
    linkToStore: 'Link it to your store',
    linkToStoreHint: 'Your store appears on the project, with a door to the product it became.',
    linkedProduct: 'The product in your store',
    noProduct: 'No product',
    fromCatalogue: 'From the catalogue',
    typeName: 'Type a name',
    searchCatalogue: 'Search the catalogue',
    saveDraft: 'Save draft',
    publish: 'Publish',
    saveChanges: 'Save changes',
    publishing: 'Publishing…',
    saving: 'Saving…',
    published: 'Your project is published',
    saved: 'Draft saved',
    creatorPageOn: 'Publishing your first project opens your public page /u/{username} — you can close it in profile settings.',
    draftBanner: 'Draft — nobody but you can see it.',
    consentPending: 'Waiting for the customer to allow showing their part.',
    consentDeclined: 'The customer declined. Publish without linking their job, or keep it private.',
    hiddenBanner: 'Levonis hid this project.',
    reason: 'Reason',
    archivedBanner: 'Archived — not shown in the community.',
    askedTitle: 'A workshop wants to show your part',
    askedBody: 'This part was printed for you. May it appear in the workshop’s portfolio?',
    allow: 'Allow',
    decline: 'Decline',
    youAllowed: 'You allowed showing your part.',
    youDeclined: 'You declined showing your part.',
    edit: 'Edit',
    archive: 'Archive',
    restore: 'Restore',
    delete: 'Delete',
    share: 'Share',
    linkCopied: 'Link copied',
    deleteQ: 'Delete this project?',
    deleteConsequence: 'Its pictures are deleted and it cannot be recovered.',
    archiveQ: 'Archive this project?',
    archiveConsequence: 'It leaves the community but stays yours; restore it any time.',
    noProjectsYet: 'No projects yet',
    noProjectsHint: 'The first person to share a print opens this section.',
    yourFirstProject: 'Share your first project',
    myProjects: 'My projects',
    myProjectsEmpty: 'What you print deserves to be seen.',
    trending: 'Trending this week',
    latest: 'Latest projects',
    seeAll: 'All',
    likes: 'likes',
    creator: 'Maker',
    projectsCount: 'projects',
    completedJobs: 'completed jobs',
    memberSince: 'Member since',
    about: 'About',
    prints: 'Prints with',
    materialsUsed: 'Materials',
    website: 'Website',
    editProfile: 'Edit profile',
    verifiedMerchant: 'Verified merchant',
    theirStore: 'Their store',
    creatorNotFound: 'No page by that name',
    creatorNotFoundHint: 'The account may be private, or the name misspelt.',
    creatorPage: 'My public page',
    creatorPageDesc: 'The page /u/{username} shows your projects, bio and links to every visitor.',
    creatorPageOff: 'Closed — nobody can see it.',
    printersYouUse: 'Your printers',
    printersHint: 'Separate names with commas.',
    materialsYouUse: 'Your materials',
    // the files (§9.4)
    files: 'Files',
    modelFile: 'Model file (optional)',
    modelFileHint: 'Up to 3 files — STL, 3MF, OBJ or PDF. Large files upload in parts and resume if the connection drops.',
    addFile: 'Add a file',
    fileName: 'File name',
    downloadable: 'Downloadable',
    downloadableHint: 'Any signed-in member may download the original.',
    filesLimit: 'A project holds up to 3 files.',
    fileKindRefused: 'Choose a model file (STL, 3MF, OBJ, STEP) or a PDF document.',
    fileKinds: { model: 'Model', document: 'Document' } as Record<'model' | 'document', string>,
    view3d: 'View in 3D',
    download: 'Download',
    signInToDownload: 'Sign in to download this file.',
    notDownloadable: 'The maker has not made this file downloadable.',
    noPreview: 'This file has no 3D preview.',
    removeFile: 'Remove the file',
    opening: 'Opening…',
    viewerFailed: 'Could not open the preview.',
    takePhoto: 'Take a photo',
    uploadingFiles: 'Files uploading',
  },
  ckb: {
    projects: 'پڕۆژەکان',
    project: 'پڕۆژە',
    newProject: 'پڕۆژەی نوێ',
    shareWhatYouPrinted: 'ئەوەی چاپت کردووە هاوبەشی بکە',
    editProject: 'دەستکاری پڕۆژە',
    kinds: { project: 'پڕۆژە', post: 'پۆست', tutorial: 'فێرکاری', timelapse: 'تایم‌لاپس', before_after: 'پێش و پاش' } as Record<PostKind, string>,
    states: { draft: 'ڕەشنووس', published: 'بڵاوکراوە', archived: 'ئەرشیفکراو' } as Record<PostState, string>,
    visibility: { public: 'گشتی', unlisted: 'تەنها بە لینک', private: 'تایبەت' } as Record<PostVisibility, string>,
    visibilityHint: { public: 'لە کۆمەڵگە و پەڕەکەتدا دەردەکەوێت.', unlisted: 'تەنها ئەوانەی لینکەکەیان هەیە دەیبینن.', private: 'تەنها تۆ.' } as Record<PostVisibility, string>,
    printer: 'چاپکەر',
    material: 'کەرەستە',
    color: 'ڕەنگ',
    printTime: 'کاتی چاپ',
    size: 'قەبارە',
    settings: 'ڕێکخستنەکانی چاپ',
    layerHeight: 'بەرزی چین',
    layer: 'چین',
    infill: 'پڕکردنەوە',
    nozzle: 'نۆزڵ',
    supports: 'پاڵپشت',
    withSupports: 'بە پاڵپشت',
    noSupports: 'بێ پاڵپشت',
    tags: 'تاگەکان',
    tagsHint: 'تا ١٠ تاگ، بە کۆما لێکیان جیا بکەرەوە.',
    fromWorkshop: 'لە وۆرکشۆپی',
    buyThisPiece: 'ئەم پارچەیە بکڕە',
    printOneLikeIt: 'داوای چاپکردنی وەک ئەمە بکە',
    buyTheMaterial: 'کەرەستە بەکارهاتووەکە بکڕە',
    seeThePrinter: 'چاپکەرەکە بناسە',
    pictures: 'وێنەکان',
    title: 'ناونیشان',
    titlePh: 'نموونە: ئەژدیهای جومگەدار بە دوو ڕەنگ',
    body: 'چیرۆکەکە',
    bodyPh: 'چۆن چاپت کرد؟ چی سەرکەوتوو بوو و چیت دووبارە کردەوە؟ ئامۆژگاری بۆ ئەوەی دوای تۆ چاپی دەکات.',
    kind: 'جۆر',
    printerPh: 'ناوی چاپکەر، یان لە کەتەلۆگ هەڵبژێرە',
    materialPh: 'PLA، PETG، ڕەزین…',
    colorPh: 'ڕەش، سپی، فرەڕەنگ…',
    minutes: 'خولەک',
    hours: 'کاتژمێر',
    mm: 'مم',
    linkToStore: 'بە فرۆشگاکەتەوە ببەستەوە',
    linkToStoreHint: 'فرۆشگاکەت لەسەر پڕۆژەکە دەردەکەوێت، لەگەڵ دەرگایەک بۆ ئەو بەرهەمەی لێی دروست بووە.',
    linkedProduct: 'بەرهەمەکە لە فرۆشگاکەت',
    noProduct: 'بێ بەرهەم',
    fromCatalogue: 'لە کەتەلۆگ',
    typeName: 'ناوێک بنووسە',
    searchCatalogue: 'لە کەتەلۆگ بگەڕێ',
    saveDraft: 'ڕەشنووس پاشەکەوت بکە',
    publish: 'بڵاوی بکەرەوە',
    saveChanges: 'گۆڕانکارییەکان پاشەکەوت بکە',
    publishing: 'بڵاودەکرێتەوە…',
    saving: 'پاشەکەوت دەکرێت…',
    published: 'پڕۆژەکەت بڵاوکرایەوە',
    saved: 'ڕەشنووسەکە پاشەکەوت کرا',
    creatorPageOn: 'بە بڵاوکردنەوەی یەکەم پڕۆژە پەڕە گشتییەکەت /u/{username} دەکرێتەوە — دەتوانیت لە ڕێکخستنەکانی پڕۆفایل دایبخەیت.',
    draftBanner: 'ڕەشنووس — کەس جگە لە تۆ نایبینێت.',
    consentPending: 'چاوەڕێی ڕەزامەندی کڕیارە بۆ پیشاندانی پارچەکەی.',
    consentDeclined: 'کڕیارەکە ڕەزامەند نەبوو. بەبێ بەستنەوە بە کارەکەی بڵاوی بکەرەوە، یان بە تایبەتی بیهێڵەرەوە.',
    hiddenBanner: 'Levonis ئەم پڕۆژەیەی شاردووەتەوە.',
    reason: 'هۆکار',
    archivedBanner: 'ئەرشیفکراوە — لە کۆمەڵگەدا دەرناکەوێت.',
    askedTitle: 'وۆرکشۆپێک دەیەوێت پارچەکەت پیشان بدات',
    askedBody: 'ئەم پارچەیە بۆ تۆ چاپ کراوە. ڕازیت لە پۆرتفۆلیۆی وۆرکشۆپەکە دەربکەوێت؟',
    allow: 'ڕازیم',
    decline: 'ڕازی نیم',
    youAllowed: 'ڕەزامەندیت دا پارچەکەت پیشان بدرێت.',
    youDeclined: 'ڕەزامەند نەبوویت پارچەکەت پیشان بدرێت.',
    edit: 'دەستکاری',
    archive: 'ئەرشیفکردن',
    restore: 'گەڕاندنەوە',
    delete: 'سڕینەوە',
    share: 'هاوبەشکردن',
    linkCopied: 'لینکەکە کۆپی کرا',
    deleteQ: 'پڕۆژەکە بسڕدرێتەوە؟',
    deleteConsequence: 'وێنەکانی دەسڕدرێنەوە و ناگەڕێندرێتەوە.',
    archiveQ: 'پڕۆژەکە ئەرشیف بکرێت؟',
    archiveConsequence: 'لە کۆمەڵگە دەردەچێت بەڵام هی تۆ دەمێنێتەوە؛ هەر کاتێک بتەوێت بیگەڕێنەرەوە.',
    noProjectsYet: 'هێشتا هیچ پڕۆژەیەک نییە',
    noProjectsHint: 'یەکەم کەس کە چاپێک هاوبەش بکات ئەم بەشە دەکاتەوە.',
    yourFirstProject: 'یەکەم پڕۆژەت هاوبەش بکە',
    myProjects: 'پڕۆژەکانم',
    myProjectsEmpty: 'ئەوەی چاپی دەکەیت شایانی بینینە.',
    trending: 'باوی ئەم هەفتەیە',
    latest: 'نوێترین پڕۆژەکان',
    seeAll: 'هەموو',
    likes: 'لایک',
    creator: 'دروستکەر',
    projectsCount: 'پڕۆژە',
    completedJobs: 'کاری تەواوکراو',
    memberSince: 'ئەندام لە',
    about: 'دەربارە',
    prints: 'چاپ دەکات بە',
    materialsUsed: 'کەرەستەکان',
    website: 'ماڵپەڕ',
    editProfile: 'دەستکاری پڕۆفایل',
    verifiedMerchant: 'بازرگانی پشتڕاستکراو',
    theirStore: 'فرۆشگاکەی',
    creatorNotFound: 'هیچ پەڕەیەک بەم ناوە نییە',
    creatorNotFoundHint: 'لەوانەیە هەژمارەکە تایبەت بێت، یان ناوەکە هەڵە نووسرابێت.',
    creatorPage: 'پەڕە گشتییەکەم',
    creatorPageDesc: 'پەڕەی /u/{username} پڕۆژەکان و ژیاننامە و لینکەکانت بۆ هەموو سەردانکەرێک پیشان دەدات.',
    creatorPageOff: 'داخراوە — کەس نایبینێت.',
    printersYouUse: 'چاپکەرەکانت',
    printersHint: 'ناوەکان بە کۆما جیا بکەرەوە.',
    materialsYouUse: 'کەرەستەکانت',
    // the files (§9.4)
    files: 'فایلەکان',
    modelFile: 'فایلی مۆدێل (ئارەزوومەندانە)',
    modelFileHint: 'تا ٣ فایل — STL یان 3MF یان OBJ یان PDF. فایلە گەورەکان بە بەش باردەکرێن و ئەگەر هێڵەکە بپچڕێت بەردەوام دەبنەوە.',
    addFile: 'فایلێک زیاد بکە',
    fileName: 'ناوی فایل',
    downloadable: 'دەکرێت دابگیرێت',
    downloadableHint: 'هەر ئەندامێکی چووەتە ژوورەوە دەتوانێت فایلە ڕەسەنەکە دابگرێت.',
    filesLimit: 'پڕۆژەیەک تا ٣ فایل هەڵدەگرێت.',
    fileKindRefused: 'فایلێکی مۆدێل (STL یان 3MF یان OBJ یان STEP) یان بەڵگەنامەیەکی PDF هەڵبژێرە.',
    fileKinds: { model: 'مۆدێل', document: 'بەڵگەنامە' } as Record<'model' | 'document', string>,
    view3d: 'بینینی سێ ڕەهەندی',
    download: 'داگرتن',
    signInToDownload: 'بۆ داگرتنی ئەم فایلە بچۆ ژوورەوە.',
    notDownloadable: 'خاوەنی پڕۆژەکە ڕێگەی نەداوە ئەم فایلە دابگیرێت.',
    noPreview: 'ئەم فایلە پێشبینینی سێ ڕەهەندی نییە.',
    removeFile: 'لابردنی فایلەکە',
    opening: 'دەکرێتەوە…',
    viewerFailed: 'نەتوانرا پێشبینینەکە بکرێتەوە.',
    takePhoto: 'وێنەیەک بگرە',
    uploadingFiles: 'فایلەکان باردەکرێن',
  },
} as const;

export type ProjectStrings = (typeof STRINGS)['ar'];

export function useProjectStrings(): ProjectStrings {
  const { lang } = useLanguage();
  return (lang === 'en' ? STRINGS.en : lang === 'ckb' ? STRINGS.ckb : STRINGS.ar) as ProjectStrings;
}

/** «6 س 20 د» / «6h 20m» — a print time from minutes. */
export function printTimeLabel(minutes: number, s: ProjectStrings): string {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  if (h === 0) return `${m} ${s.minutes}`;
  if (m === 0) return `${h} ${s.hours}`;
  return `${h} ${s.hours} ${m} ${s.minutes}`;
}

/** «220 × 60 × 40 مم» from whichever axes were given. */
export function dimensionsLabel(d: Partial<Record<'x_mm' | 'y_mm' | 'z_mm', number>>, s: ProjectStrings): string {
  const parts = [d.x_mm, d.y_mm, d.z_mm].filter((v): v is number => typeof v === 'number' && v > 0);
  return parts.length ? `${parts.map((v) => Math.round(v * 10) / 10).join(' × ')} ${s.mm}` : '';
}
