/**
 * «الهدايا» in the admin panel — every word in Arabic, English and Sorani
 * (docs/GIFTS_QUICK_BUY.md §1.3). A key missing from a language is a compile
 * error, so the three cannot drift apart.
 */
import type { GiftStatus, GrantReason } from './types';

export type AdminLang = 'ar' | 'en' | 'ckb';
export const adminLang = (lang: string): AdminLang => (lang === 'en' || lang === 'ckb' ? lang : 'ar');

const ar = {
  title: 'الهدايا',
  subtitle: 'خمسة مستويات من منتجات المتجر الحقيقية، ومنح الهدايا للزبائن ومتابعتها حتى التسليم.',
  tabLevels: 'المستويات',
  tabGrants: 'الهدايا الممنوحة',
  grantGift: 'منح هدية',
  refresh: 'تحديث',
  loading: 'جارٍ التحميل…',
  loadFailed: 'تعذّر التحميل.',
  retry: 'إعادة المحاولة',
  save: 'حفظ',
  saving: 'جارٍ الحفظ…',
  saved: 'تم الحفظ.',
  cancel: 'إلغاء',
  close: 'إغلاق',
  back: 'رجوع',
  edit: 'تعديل',
  remove: 'إزالة',
  active: 'مفعّل',
  inactive: 'موقوف',

  level: 'المستوى',
  levelN: 'المستوى {n}',
  levelName: 'اسم المستوى',
  levelDescription: 'الوصف',
  levelActive: 'المستوى متاح للمنح',
  levelOff: 'موقوف — لا يُمنح يدويًا',
  langAr: 'العربية',
  langEn: 'English',
  langCkb: 'کوردی',
  items: 'منتجات المستوى',
  itemsHint: 'كل منتج هنا بديل: يختار الزبون واحدًا منها. المخزون الحقيقي للمتجر هو الذي يقرر، ولا يُحجز شيء قبل الطلب.',
  noItems: 'لا منتجات في هذا المستوى بعد. أضف منتجًا من المتجر.',
  addItem: 'إضافة منتج',
  editItem: 'تعديل المنتج',
  legacyItems: 'صناديق النظام السابق (للقراءة فقط)',
  available: 'متاح',
  unavailable: 'غير متاح الآن',
  removeItemConfirm: 'إيقاف هذا المنتج في المستوى؟ الهدايا التي اختارته تحتفظ باختيارها.',
  whyOUT_OF_STOCK: 'نفد المخزون',
  whyPREORDER_CAPACITY_EXHAUSTED: 'امتلأت حصة الطلب المسبق',
  whyGIFT_SALE_TYPE_UNAVAILABLE: 'نوع البيع غير متاح لهذا الموديل',
  whyGIFT_PRODUCT_INACTIVE: 'المنتج غير منشور',
  whyGIFT_PRODUCT_NOT_FOUND: 'المنتج محذوف',
  whyGIFT_SELECTION_INVALID: 'الموديل أو اللون لم يعد صالحًا',
  whyGIFT_COMPOSITION_UNSUPPORTED: 'أصبح المنتج حزمة',
  whyGIFT_TRANSPORT_REQUIRED: 'لا يوجد طريق شحن',

  product: 'المنتج',
  pickProduct: 'ابحث عن منتج في المتجر',
  saleType: 'نوع البيع',
  saleDirect: 'بيع مباشر',
  salePreorder: 'طلب مسبق',
  route: 'طريق الشحن',
  routeAir: 'جوي',
  routeSea: 'بحري',
  routeLand: 'بري',
  model: 'الموديل / الخيار',
  chooseValue: 'اختر',
  color: 'اللون',
  noColor: 'بدون لون',
  qty: 'الكمية',
  value: 'القيمة',
  stock: 'المتوفر',
  optionsLoading: 'جارٍ تحميل خيارات المنتج…',
  notGiftable: 'هذا المنتج لا يمكن أن يكون هدية (مسودة أو حزمة).',

  grantsEmpty: 'لا هدايا تطابق هذا البحث.',
  filterStatus: 'الحالة',
  filterLevel: 'المستوى',
  filterReason: 'السبب',
  filterAll: 'الكل',
  search: 'ابحث بالاسم أو البريد أو الهاتف أو رقم الطلب',
  loadMore: 'عرض المزيد',
  customer: 'الزبون',
  grantedAt: 'تاريخ المنح',
  grantedBy: 'منحها',
  system: 'النظام',

  statusGRANTED: 'بانتظار الاختيار',
  statusREADY_TO_REDEEM: 'جاهزة للاسترداد',
  statusREDEEMED: 'تم الاسترداد',
  statusADDED_TO_ORDER: 'في السلة',
  statusORDERED: 'تم الطلب',
  statusFULFILLED: 'تم التسليم',
  statusCANCELLED: 'ملغاة',
  statusLEGACY: 'صندوق سابق',

  reasonreview: 'تقييم',
  reasonreward: 'مكافأة',
  reasoncompensation: 'تعويض',
  reasonadmin_gift: 'هدية من الإدارة',
  reasonlegacy: 'النظام السابق',

  modeLevel: 'يختار الزبون من منتجات المستوى',
  modeItem: 'منتج محدد من المستوى',
  modeProduct: 'أي منتج من المتجر',
  sheetTitle: 'منح هدية',
  findCustomer: 'ابحث عن الزبون',
  customerHint: 'الاسم أو البريد أو اسم المستخدم أو الهاتف',
  noCustomers: 'لا يوجد زبون بهذا البحث.',
  change: 'تغيير',
  chooseLevel: 'المستوى',
  how: 'طريقة المنح',
  chooseItem: 'اختر منتج المستوى',
  reason: 'السبب',
  note: 'ملاحظة داخلية',
  noteHint: 'للإدارة فقط — لا تظهر للزبون أبدًا.',
  grantAction: 'منح الهدية',
  granting: 'جارٍ المنح…',
  granted: 'تم منح الهدية، ووصل الزبونَ إشعار.',
  levelEmptyWarn: 'هذا المستوى بلا منتجات: لن يجد الزبون ما يختاره. أضف منتجًا أو امنح منتجًا محددًا.',
  levelOffWarn: 'هذا المستوى موقوف.',

  detail: 'تفاصيل الهدية',
  chosenProduct: 'المنتج',
  notChosen: 'لم يختر الزبون بعد.',
  order: 'الطلب',
  openOrder: 'فتح الطلب',
  timeline: 'السجل',
  editNote: 'الملاحظة والسبب',
  cancelGift: 'إلغاء الهدية',
  cancelReason: 'سبب الإلغاء (داخلي)',
  cancelConsequence: 'تُلغى الهدية ويُزال سطرها من سلة الزبون إن كان فيها. لا يمكن التراجع.',
  cancelled: 'أُلغيت الهدية.',
  convert: 'تحويل إلى النظام الجديد',
  convertHint: 'يصبح الصندوق السابق هدية مستوى يختار الزبون منتجها ويطلبها عبر السلة.',
  converted: 'تم التحويل، ووصل الزبونَ إشعار.',
  fulfill: 'تم التسليم (صندوق سابق)',
  fulfilled: 'سُجّل التسليم.',
  orderedCancelHint: 'هذه الهدية في طلب: ألغِ الطلب لتعود إلى الزبون.',
  cancelledBy: 'أُلغيت بواسطة',

  actiongift_grant: 'مُنحت',
  actiongift_choose: 'اختار الزبون منتجًا',
  actiongift_redeem: 'استردّها الزبون',
  actiongift_order: 'طُلبت',
  actiongift_order_cancelled: 'أُلغي الطلب — عادت للزبون',
  actiongift_delivered: 'سُلّمت',
  actiongift_undelivered: 'تراجع عن التسليم',
  actiongift_cancel: 'أُلغيت',
  actiongift_note: 'عُدّلت الملاحظة أو السبب',
  actiongift_convert: 'حُوّلت إلى النظام الجديد',
  actiongift_fulfill: 'سُلّمت (صندوق سابق)',
};

export type AdminStringKey = keyof typeof ar;

const en: Record<AdminStringKey, string> = {
  title: 'Gifts',
  subtitle: 'Five levels of real store products, gifts granted to customers, and their journey to delivery.',
  tabLevels: 'Levels',
  tabGrants: 'Granted gifts',
  grantGift: 'Grant a gift',
  refresh: 'Refresh',
  loading: 'Loading…',
  loadFailed: 'Could not load.',
  retry: 'Retry',
  save: 'Save',
  saving: 'Saving…',
  saved: 'Saved.',
  cancel: 'Cancel',
  close: 'Close',
  back: 'Back',
  edit: 'Edit',
  remove: 'Remove',
  active: 'Active',
  inactive: 'Off',

  level: 'Level',
  levelN: 'Level {n}',
  levelName: 'Level name',
  levelDescription: 'Description',
  levelActive: 'Level open for grants',
  levelOff: 'Off — not granted by hand',
  langAr: 'العربية',
  langEn: 'English',
  langCkb: 'کوردی',
  items: 'Products in this level',
  itemsHint: 'Each product here is an alternative: the customer picks one. Real store stock decides, and nothing is reserved before the order.',
  noItems: 'No products in this level yet. Add one from the store.',
  addItem: 'Add product',
  editItem: 'Edit product',
  legacyItems: 'Previous-system boxes (read only)',
  available: 'Available',
  unavailable: 'Not available now',
  removeItemConfirm: 'Stop offering this product in the level? Gifts that already chose it keep their choice.',
  whyOUT_OF_STOCK: 'Out of stock',
  whyPREORDER_CAPACITY_EXHAUSTED: 'Pre-order quota full',
  whyGIFT_SALE_TYPE_UNAVAILABLE: 'Sale type not offered for this model',
  whyGIFT_PRODUCT_INACTIVE: 'Product not published',
  whyGIFT_PRODUCT_NOT_FOUND: 'Product deleted',
  whyGIFT_SELECTION_INVALID: 'Model or colour no longer valid',
  whyGIFT_COMPOSITION_UNSUPPORTED: 'The product became a bundle',
  whyGIFT_TRANSPORT_REQUIRED: 'No freight route',

  product: 'Product',
  pickProduct: 'Search a store product',
  saleType: 'Sale type',
  saleDirect: 'Direct sale',
  salePreorder: 'Pre-order',
  route: 'Freight route',
  routeAir: 'Air',
  routeSea: 'Sea',
  routeLand: 'Land',
  model: 'Model / option',
  chooseValue: 'Choose',
  color: 'Colour',
  noColor: 'No colour',
  qty: 'Quantity',
  value: 'Value',
  stock: 'In stock',
  optionsLoading: 'Loading the product’s options…',
  notGiftable: 'This product cannot be a gift (draft or bundle).',

  grantsEmpty: 'No gifts match this search.',
  filterStatus: 'Status',
  filterLevel: 'Level',
  filterReason: 'Reason',
  filterAll: 'All',
  search: 'Search by name, e-mail, phone or order number',
  loadMore: 'Load more',
  customer: 'Customer',
  grantedAt: 'Granted',
  grantedBy: 'Granted by',
  system: 'System',

  statusGRANTED: 'Awaiting choice',
  statusREADY_TO_REDEEM: 'Ready to redeem',
  statusREDEEMED: 'Redeemed',
  statusADDED_TO_ORDER: 'In cart',
  statusORDERED: 'Ordered',
  statusFULFILLED: 'Delivered',
  statusCANCELLED: 'Cancelled',
  statusLEGACY: 'Previous box',

  reasonreview: 'Review',
  reasonreward: 'Reward',
  reasoncompensation: 'Compensation',
  reasonadmin_gift: 'Gift from the team',
  reasonlegacy: 'Previous system',

  modeLevel: 'The customer picks from the level',
  modeItem: 'A specific level product',
  modeProduct: 'Any store product',
  sheetTitle: 'Grant a gift',
  findCustomer: 'Find the customer',
  customerHint: 'Name, e-mail, username or phone',
  noCustomers: 'No customer matches.',
  change: 'Change',
  chooseLevel: 'Level',
  how: 'How',
  chooseItem: 'Choose the level product',
  reason: 'Reason',
  note: 'Internal note',
  noteHint: 'For the team only — never shown to the customer.',
  grantAction: 'Grant gift',
  granting: 'Granting…',
  granted: 'Gift granted; the customer was notified.',
  levelEmptyWarn: 'This level has no products: the customer would have nothing to choose. Add one, or grant a specific product.',
  levelOffWarn: 'This level is switched off.',

  detail: 'Gift details',
  chosenProduct: 'Product',
  notChosen: 'The customer has not chosen yet.',
  order: 'Order',
  openOrder: 'Open order',
  timeline: 'Timeline',
  editNote: 'Note and reason',
  cancelGift: 'Cancel gift',
  cancelReason: 'Cancellation reason (internal)',
  cancelConsequence: 'The gift is cancelled and its line leaves the customer’s cart if it is there. This cannot be undone.',
  cancelled: 'Gift cancelled.',
  convert: 'Convert to the new system',
  convertHint: 'The previous box becomes a level gift: the customer chooses its product and orders it through the cart.',
  converted: 'Converted; the customer was notified.',
  fulfill: 'Mark delivered (previous box)',
  fulfilled: 'Delivery recorded.',
  orderedCancelHint: 'This gift is in an order: cancel the order to return it to the customer.',
  cancelledBy: 'Cancelled by',

  actiongift_grant: 'Granted',
  actiongift_choose: 'Customer chose a product',
  actiongift_redeem: 'Customer redeemed it',
  actiongift_order: 'Ordered',
  actiongift_order_cancelled: 'Order cancelled — returned to the customer',
  actiongift_delivered: 'Delivered',
  actiongift_undelivered: 'Delivery undone',
  actiongift_cancel: 'Cancelled',
  actiongift_note: 'Note or reason edited',
  actiongift_convert: 'Converted to the new system',
  actiongift_fulfill: 'Delivered (previous box)',
};

const ckb: Record<AdminStringKey, string> = {
  title: 'دیارییەکان',
  subtitle: 'پێنج ئاست لە بەرهەمی ڕاستەقینەی فرۆشگا، بەخشینی دیاری بە کڕیاران و بەدواداچوونیان تا گەیاندن.',
  tabLevels: 'ئاستەکان',
  tabGrants: 'دیارییە بەخشراوەکان',
  grantGift: 'بەخشینی دیاری',
  refresh: 'نوێکردنەوە',
  loading: 'باردەکرێت…',
  loadFailed: 'بار نەبوو.',
  retry: 'هەوڵدانەوە',
  save: 'پاشەکەوت',
  saving: 'پاشەکەوت دەکرێت…',
  saved: 'پاشەکەوت کرا.',
  cancel: 'پاشگەزبوونەوە',
  close: 'داخستن',
  back: 'گەڕانەوە',
  edit: 'دەستکاری',
  remove: 'لابردن',
  active: 'چالاک',
  inactive: 'وەستێنراو',

  level: 'ئاست',
  levelN: 'ئاستی {n}',
  levelName: 'ناوی ئاست',
  levelDescription: 'وەسف',
  levelActive: 'ئاستەکە بۆ بەخشین کراوەیە',
  levelOff: 'وەستێنراوە — بە دەست نابەخشرێت',
  langAr: 'العربية',
  langEn: 'English',
  langCkb: 'کوردی',
  items: 'بەرهەمەکانی ئەم ئاستە',
  itemsHint: 'هەر بەرهەمێک لێرە بژاردەیەکە: کڕیار یەکێکیان هەڵدەبژێرێت. کۆگای ڕاستەقینەی فرۆشگا بڕیار دەدات، و پێش داواکاری هیچ ناگیرێت.',
  noItems: 'هێشتا هیچ بەرهەمێک لەم ئاستەدا نییە. بەرهەمێک لە فرۆشگاوە زیاد بکە.',
  addItem: 'زیادکردنی بەرهەم',
  editItem: 'دەستکاریی بەرهەم',
  legacyItems: 'سندوقەکانی سیستەمی پێشوو (تەنها خوێندنەوە)',
  available: 'بەردەستە',
  unavailable: 'ئێستا بەردەست نییە',
  removeItemConfirm: 'ئەم بەرهەمە لەم ئاستەدا ڕابگیرێت؟ ئەو دیارییانەی هەڵیانبژاردووە هەڵبژاردنەکەیان دەمێنێت.',
  whyOUT_OF_STOCK: 'کۆگا تەواو بووە',
  whyPREORDER_CAPACITY_EXHAUSTED: 'بەشی داواکاریی پێشوەختە پڕ بووە',
  whyGIFT_SALE_TYPE_UNAVAILABLE: 'جۆری فرۆشتن بۆ ئەم مۆدێلە بەردەست نییە',
  whyGIFT_PRODUCT_INACTIVE: 'بەرهەمەکە بڵاونەکراوەتەوە',
  whyGIFT_PRODUCT_NOT_FOUND: 'بەرهەمەکە سڕاوەتەوە',
  whyGIFT_SELECTION_INVALID: 'مۆدێل یان ڕەنگ چیتر دروست نییە',
  whyGIFT_COMPOSITION_UNSUPPORTED: 'بەرهەمەکە بووە بە کۆمەڵە',
  whyGIFT_TRANSPORT_REQUIRED: 'هیچ ڕێگایەکی بارکردن نییە',

  product: 'بەرهەم',
  pickProduct: 'بەدوای بەرهەمێکی فرۆشگادا بگەڕێ',
  saleType: 'جۆری فرۆشتن',
  saleDirect: 'فرۆشتنی ڕاستەوخۆ',
  salePreorder: 'داواکاریی پێشوەختە',
  route: 'ڕێگای بارکردن',
  routeAir: 'ئاسمانی',
  routeSea: 'دەریایی',
  routeLand: 'وشکانی',
  model: 'مۆدێل / هەڵبژاردە',
  chooseValue: 'هەڵبژێرە',
  color: 'ڕەنگ',
  noColor: 'بێ ڕەنگ',
  qty: 'بڕ',
  value: 'بەها',
  stock: 'بەردەست',
  optionsLoading: 'هەڵبژاردەکانی بەرهەمەکە باردەکرێن…',
  notGiftable: 'ئەم بەرهەمە ناتوانێت ببێتە دیاری (ڕەشنووس یان کۆمەڵە).',

  grantsEmpty: 'هیچ دیارییەک لەگەڵ ئەم گەڕانەدا ناگونجێت.',
  filterStatus: 'دۆخ',
  filterLevel: 'ئاست',
  filterReason: 'هۆکار',
  filterAll: 'هەموو',
  search: 'گەڕان بە ناو، ئیمەیڵ، مۆبایل یان ژمارەی داواکاری',
  loadMore: 'زیاتر پیشان بدە',
  customer: 'کڕیار',
  grantedAt: 'بەرواری بەخشین',
  grantedBy: 'بەخشەر',
  system: 'سیستەم',

  statusGRANTED: 'چاوەڕێی هەڵبژاردن',
  statusREADY_TO_REDEEM: 'ئامادەی وەرگرتنەوە',
  statusREDEEMED: 'وەرگیرایەوە',
  statusADDED_TO_ORDER: 'لە سەبەتەدایە',
  statusORDERED: 'داواکرا',
  statusFULFILLED: 'گەیەنرا',
  statusCANCELLED: 'هەڵوەشێنراوە',
  statusLEGACY: 'سندوقی پێشوو',

  reasonreview: 'هەڵسەنگاندن',
  reasonreward: 'خەڵات',
  reasoncompensation: 'قەرەبوو',
  reasonadmin_gift: 'دیاری لە بەڕێوەبەرایەتییەوە',
  reasonlegacy: 'سیستەمی پێشوو',

  modeLevel: 'کڕیار لە بەرهەمەکانی ئاستەکە هەڵدەبژێرێت',
  modeItem: 'بەرهەمێکی دیاریکراوی ئاستەکە',
  modeProduct: 'هەر بەرهەمێکی فرۆشگا',
  sheetTitle: 'بەخشینی دیاری',
  findCustomer: 'کڕیارەکە بدۆزەرەوە',
  customerHint: 'ناو، ئیمەیڵ، ناوی بەکارهێنەر یان مۆبایل',
  noCustomers: 'هیچ کڕیارێک نەدۆزرایەوە.',
  change: 'گۆڕین',
  chooseLevel: 'ئاست',
  how: 'شێوازی بەخشین',
  chooseItem: 'بەرهەمی ئاستەکە هەڵبژێرە',
  reason: 'هۆکار',
  note: 'تێبینیی ناوخۆیی',
  noteHint: 'تەنها بۆ بەڕێوەبەرایەتی — هەرگیز بە کڕیار پیشان نادرێت.',
  grantAction: 'بەخشینی دیاری',
  granting: 'دەبەخشرێت…',
  granted: 'دیارییەکە بەخشرا و ئاگادارکردنەوە گەیشتە کڕیار.',
  levelEmptyWarn: 'ئەم ئاستە هیچ بەرهەمێکی نییە: کڕیار هیچی بۆ هەڵبژاردن نابێت. بەرهەمێک زیاد بکە یان بەرهەمێکی دیاریکراو ببەخشە.',
  levelOffWarn: 'ئەم ئاستە وەستێنراوە.',

  detail: 'وردەکاریی دیاری',
  chosenProduct: 'بەرهەم',
  notChosen: 'کڕیار هێشتا هەڵینەبژاردووە.',
  order: 'داواکاری',
  openOrder: 'کردنەوەی داواکاری',
  timeline: 'تۆمار',
  editNote: 'تێبینی و هۆکار',
  cancelGift: 'هەڵوەشاندنەوەی دیاری',
  cancelReason: 'هۆکاری هەڵوەشاندنەوە (ناوخۆیی)',
  cancelConsequence: 'دیارییەکە هەڵدەوەشێتەوە و هێڵەکەی لە سەبەتەی کڕیار لادەبرێت ئەگەر تێیدا بێت. ناتوانرێت بگەڕێنرێتەوە.',
  cancelled: 'دیارییەکە هەڵوەشێنرایەوە.',
  convert: 'گواستنەوە بۆ سیستەمی نوێ',
  convertHint: 'سندوقە پێشووەکە دەبێتە دیاریی ئاست: کڕیار بەرهەمەکەی هەڵدەبژێرێت و لە ڕێگەی سەبەتەوە داوای دەکات.',
  converted: 'گوازرایەوە و ئاگادارکردنەوە گەیشتە کڕیار.',
  fulfill: 'گەیەنرا (سندوقی پێشوو)',
  fulfilled: 'گەیاندن تۆمار کرا.',
  orderedCancelHint: 'ئەم دیارییە لە داواکارییەکدایە: داواکارییەکە هەڵبوەشێنەرەوە تا بگەڕێتەوە بۆ کڕیار.',
  cancelledBy: 'هەڵوەشێنرایەوە لەلایەن',

  actiongift_grant: 'بەخشرا',
  actiongift_choose: 'کڕیار بەرهەمێکی هەڵبژارد',
  actiongift_redeem: 'کڕیار وەریگرتەوە',
  actiongift_order: 'داواکرا',
  actiongift_order_cancelled: 'داواکاری هەڵوەشایەوە — گەڕایەوە بۆ کڕیار',
  actiongift_delivered: 'گەیەنرا',
  actiongift_undelivered: 'گەیاندن گەڕێنرایەوە',
  actiongift_cancel: 'هەڵوەشێنرایەوە',
  actiongift_note: 'تێبینی یان هۆکار دەستکاری کرا',
  actiongift_convert: 'گوازرایەوە بۆ سیستەمی نوێ',
  actiongift_fulfill: 'گەیەنرا (سندوقی پێشوو)',
};

export const ADMIN_GIFT_STRINGS: Readonly<Record<AdminLang, Readonly<Record<AdminStringKey, string>>>> = { ar, en, ckb };

export function adminText(lang: AdminLang, key: AdminStringKey, vars?: Record<string, string | number>): string {
  const raw = ADMIN_GIFT_STRINGS[lang][key] ?? ADMIN_GIFT_STRINGS.ar[key];
  if (!vars) return raw;
  return raw.replace(/\{(\w+)\}/g, (whole, name: string) => (name in vars ? String(vars[name]) : whole));
}

export const statusKey = (s: GiftStatus) => `status${s}` as AdminStringKey;
/** Why the store cannot sell a gift's product today, in words; an unknown code reads as itself. */
export function whyText(lang: AdminLang, code: string | null): string {
  if (!code) return '';
  return ADMIN_GIFT_STRINGS[lang][`why${code}` as AdminStringKey] ?? code;
}
export const reasonKey = (r: GrantReason | 'legacy') => `reason${r}` as AdminStringKey;
/** `gift.order_cancelled` → `actiongift_order_cancelled`; an unknown action reads as itself. */
export function actionLabel(lang: AdminLang, action: string): string {
  const key = `action${action.replace(/\./g, '_')}` as AdminStringKey;
  return ADMIN_GIFT_STRINGS[lang][key] ?? action;
}
